dev-support/Jenkinsfile_GitHub, dev-support/hbase-personality.sh
The output of the error prone check is not stable, sometimes we miss several warnings, and sometimes the order of the warnings are changed. Remove it for now. Can add back later after we fix all these problems. Or another solution is to add it back as a separated check in pre commit and add it to the filter list, so it will only generate a -0 instead of -1.
=> HBASE-22174 Remove error prone from our precommit javac check

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRestartCluster.java
Remove the the non-null assertion, use a waitFor to wait until it is not null instead.
Increase the waiting time to make the test more stable.
=> HBASE-22153 Fix the flaky TestRestartCluster

hbase-server/src/test/java/org/apache/hadoop/hbase/TestSplitMerge.java
Add a `UTIL.waitUntilNoRegionsInTransition();`  before merging to make sure that the split regions are all online.
=> HBASE-22188 Make TestSplitMerge more stable

hbase-server/src/main/resources/hbase-webapps/regionserver/region.jsp
Moved the remaining usage of `StoreFile.getModificationTimeStamp` to `StoreFile.getModificationTimestamp`.
=> HBASE-22189 Removed remaining usage of StoreFile.getModificationTimeStamp

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/RegionSplitter.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaWithReplicas.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestReplicasClient.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSeparateClientZKCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/BaseTestHBaseFsck.java
Moved the remaining usages of the deprecated `ClusterConnection.clearRegionCache()` to `ClusterConnection. clearRegionLocationCache()`.
=> HBASE-22187 Removed remaining usages of ClusterConnection.clearRegionCache

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/util/Monkeys.java, hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/ScannerResource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/AssignRegionHandler.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/UnassignRegionHandler.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/CombinedAsyncWriter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessChecker.java
This PR is used to replace [PR#91](https://github.com/apache/hbase/pull/91). The modification only involves spelling errors in the words in the comments, and does not affect the program function. [PR#91](https://github.com/apache/hbase/pull/91) will be closed and the modified content will not be merged into the master branch.
=> HBASE-21257 misspelled words.[occured -> occurred]

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestHbck.java
fix flakey test which is easily failed due to unfinished assign region procedure .
=> HBASE-22234 Fix flaky TestHbck#testRecoverSplitAfterMetaUpdated

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Result.java
Removed the deprecated method - isPartial() from Result.
Fixes: [HBASE-22243](https://issues.apache.org/jira/browse/HBASE-22243)
=> HBASE-22243 Removed deprecated method in Result

hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotDescriptionUtils.java
Moved the remaining usages of the deprecated `SnapshotDescriptionUtils.SNAPSHOT_TIMEOUT_MILLIS_KEY` to `SnapshotDescriptionUtils.MASTER_SNAPSHOT_TIMEOUT_MILLIS`.
=> HBASE-22186 Removed remaining usages of SnapshotDescriptionUtils.SNAPSHOT_TIMEOUT_MILLIS_KEY

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSource.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationGlobalSourceSource.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSourceImpl.java
Removed the deprecated field- SOURCE_SHIPPED_KBS from MetricsReplicationSourceSource class and the required dependencies.
Fixes: [HBASE-22246](https://issues.apache.org/jira/browse/HBASE-22246)
=> HBASE-22246 Removed deprecated field from MetricsReplicationSourceSource

hbase-client/src/main/java/org/apache/hadoop/hbase/replication/ReplicationLoadSink.java
Removed deprecated methods in ReplicationLoadSink.
Fixes: [HBASE-22260](https://issues.apache.org/jira/browse/HBASE-22260)
=> HBASE-22260 Removed deprecated method in ReplicationLoadSink

hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestCoprocessorClassLoader.java
TestCoprocessorClassLoader.testCleanupOldJars fails when run by itself.
This can be fixed by calling CoprocessorClassLoader.getClassLoader, which initializes the jar file needed by testCleanupOldJars.
Link to issue: [HBASE-21467](https://issues.apache.org/jira/browse/HBASE-21467)
=> HBASE-21467 Fix flaky test TestCoprocessorClassLoader.testCleanupOldJars

hbase-client/src/main/java/org/apache/hadoop/hbase/client/PreemptiveFastFailInterceptor.java, hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
in PreemptiveFastFailInterceptor, the failureMapCleanupIntervalMilliSec and fastFailClearingTimeMilliSec are used to clean repeatedFailuresMap, but the HConstants.HBASE_CLIENT_FAST_FAIL_CLEANUP_MS_DURATION_MS seem to config fastFailClearingTimeMilliSec, and fastFailClearingTimeMilliSec has no config value. so in occasionallyCleanupFailureInformation function the else if branch will be always true.
=> fix PreemptiveFastFailInterceptor clean repeatedFailuresMap issue

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RpcRetryingCallerWithReadReplicas.java
This PR refines the client logging message on `RpcRetryingCallerWithReadReplicas.getRegionLocations` for easier debugging.
* Add row and table name into the logging message of `RpcRetryingCallerWithReadReplicas.getRegionLocations` when failed to get region location or the location got is null.
This change could be verified by existing tests.
- Dependencies (does it add or upgrade a dependency): (no)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
- The runtime code path (performance sensitive): (no)
- Anything that affects deployment or recovery: AssignmentManager, WAL system, ZooKeeper: (no)
- File system relative (HDFS/S3): (no)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)
=> HBASE-22283 Print row and table information when failed to get region location

src/main/asciidoc/_chapters/architecture.adoc
Corrected the default value as 1. Also updated the deprecated HColumnDescriptor class and added ColumnFamilyDescriptorBuilder in the documentation.
Fixes: [HBASE-22299](https://issues.apache.org/jira/browse/HBASE-22299)
=> HBASE-22299 Documentation has incorrect default number of versions

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALKeyImpl.java
Removed deprecated methods in ReplicationLoadSink.
Fixes: [HBASE-22294](https://issues.apache.org/jira/browse/HBASE-22294)
=> HBASE-22294 Removed deprecated method from WALKeyImpl

hbase-resource-bundle/src/main/resources/supplemental-models.xml, hbase-shaded/hbase-shaded-client-byo-hadoop/pom.xml, hbase-shaded/hbase-shaded-mapreduce/pom.xml, hbase-shaded/pom.xml
This includes two general fixes that will be needed by all branch-2 releases
* HBASE-22312 when built against hadoop 3 our hbase-shaded-mapreduce module incorrectly includes the mapreduce client's transitive dependencies
* HBASE-22314 when built against hadoop 3 our hbase-shaded-client-byo-hadoop module incorrectly includes the hadoop client's transitive dependencies
and also two fixes that will only be needed for upcoming minor releases, since they fix problems that depend on which version(s) of Hadoop 3 end up getting released and built against. These are both modified versions of patches provided by other contributors.
* HBASE-22109 Update hbase shaded client for new transitive dependencies of guava after hadoop update
* HBASE-22087 Update LICENSE/shading for the dependencies from the …
=> Related jiras that update our handling of Hadoop transitive dependencies

hbase-server/src/test/java/org/apache/hadoop/hbase/client/ScanPerNextResultScanner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerHeartbeatMessages.java
Introduced a `ScanPerNextResultScanner` to simulate the `ResultScanner` in the old time.
=> HBASE-22036 Rewrite TestScannerHeartbeatMessages

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncNonMetaRegionLocator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestRegionLocator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/RegionReplicaTestHelper.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncAdminWithRegionReplicas.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncMetaRegionLocator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableUseMetaReplicas.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestConnectionImplementation.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaWithReplicas.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestZKAsyncRegistry.java
Also done some cleanups on `TestMetaWithReplicas`. Planed to reuse the test but finally give up, but I think the cleanup is still needed. Introduced a `TestAsyncTableUseMetaReplicas` instead.
=> HBASE-22317 Support reading from meta replicas

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdminBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdminBuilderBase.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdminRequestRetryingCaller.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBatchRpcRetryingCaller.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncClientScanner.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionConfiguration.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncMasterRequestRpcRetryingCaller.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRpcRetryingCaller.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRpcRetryingCallerFactory.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncScanSingleRegionRpcRetryingCaller.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncServerRequestRpcRetryingCaller.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncSingleRequestRpcRetryingCaller.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableBuilderBase.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncClientPauseForCallQueueTooBig.java
Still have some problems on implementing UTs, will update the patch soon. And maybe we could change the config name? I think a more general reason to use a larger pause is that the region server is overloaded, CallQueueTooBigException is only one possible result of a overloaded region server. So maybe we could change the config and also the new methods in TableBuilder and AdminBuilder to something like pauseWhenOverloaded? What do you think @carp84 . Thanks.
=> HBASE-22322 Use special pause for CallQueueTooBigException

hbase-shell/src/main/ruby/.rubocop.yml
Changed configuration and analyzed code with rubocop on some files and it works.
=> HBASE-20851 Change rubocop config for max line length of 100

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/throttle/PressureAwareCompactionThroughputController.java
address issue mentioned on https://issues.apache.org/jira/browse/HBASE-21777
=> HBASE-21777 Only log compaction pressure throughput when changed or traced

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreScanner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreScannerClosure.java
Allows either updateReaders() or close() to happen at the same time. The JIRA reporter has tested the fix provided.
=> HBASE-22072 High read/write intensive regions may cause long crash

hbase-shell/src/main/ruby/.rubocop.yml
Changed configuration and analyzed the code and the change in configuration works.
=> HBASE-22358 Change rubocop configuration for method length

dev-support/hbase-vote.sh
also simplify the download path depth with `--cut-dirs 4`, and those downloaded files will be under `${HBASE_RC_VERSION}` e.g. `${OUTPUT_DIR}/hbase-1.4.10RC0`
=> HBASE-22429 hbase-vote download step requires URL to end with '/'

src/main/asciidoc/_chapters/appendix_hbase_incompatibilities.adoc
Changes made and warnings are gone.
=> HBASE-22226 Incorrect level for headings in asciidoc

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManifest.java
HBase-backup module's class "org.apache.hadoop.hbase.backup.impl.BackupManifest" FSDataInputStream is not close.
=> [HBASE-22476] FSDataInputStream is not closed.

hbase-client/src/main/java/org/apache/hadoop/hbase/RegionLoad.java, hbase-client/src/main/java/org/apache/hadoop/hbase/RegionMetrics.java, hbase-client/src/main/java/org/apache/hadoop/hbase/RegionMetricsBuilder.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapper.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSourceImpl.java, hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionSourceImpl.java, hbase-protocol-shaded/src/main/protobuf/ClusterStatus.proto, hbase-protocol/src/main/protobuf/ClusterStatus.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperStub.java
Expose the reference count over a region's store file readers as a metric in region metrics and also as a new field in RegionLoad. This will make visible the reader reference count over all stores in the region to both metrics capture and anything that consumes ClusterStatus, like the shell's status command and the master UI.
Coprocessors that wrap scanners might leak them, which will leak readers. We log when this happens but in order to notice the increasing trend of reference counts you have to scrape log output. It would be better if this information is also available as a metric.
=> HBASE-22459 Expose store reader reference count

hbase-server/src/main/java/org/apache/hadoop/hbase/master/TableNamespaceManager.java
Start ZKNamespaceManager as first step in TableNamespaceManager initialization
=> HBASE-22451 TestLoadIncrementalHFiles and TestSecureLoadIncrementalHFiles are flaky

hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaRetriever.java, hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaAdmin.java
Admin#getQuota get nothing if exceedThrottleQuota is set, because exceedThrottleQuota is a special row key in quota table and can not be parsed to a QuotaSettings.
=> HBASE-22513 Admin#getQuota does not work correctly if exceedThrottleQuota is set

hbase-rsgroup/pom.xml, pom.xml
These dependencies are not required for HBase communicating with Hadoop.
nimbusds is used in JWTRedirectAuthenticationHandler which was added by HADOOP-11717. It's server side functionality, although if we ever wanted to incorporate this functionality into our infoserver stack we'd want to un-exclude.
The okhttp dependency comes from HDFS-8155, support for OAuth2 credentials with WebHDFS. When bundled with HBase no WebHDFS options or access methods are utilized. 
Also remove duplicate exclusions from _hbase-rsgroups_ module. The exclusions in the parent _hbase_ module already apply. I do see htrace exclusions even in leaf modules so put that one there. No compelling reason to do so other than sake of consistency with other leaf POMs. Future followup could include tidying the POMs. Not in …
=> HBASE-22519 New Hadoop 2.8 dependencies fail shaded invariants check

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreChunkPool.java
Add a new counter `gotChunkCount` for calculating reuse ratio.
Correct `createdChunkCount` initial count.
Set `logStats` INFO level, every 5 minutes which is not very chatty, and it is useful information.
=> HBASE-22540 [Memstore] Correct counters in MemStoreChunkPool

hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml, hbase-checkstyle/src/main/resources/hbase/checkstyle.xml, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapred/MultiTableSnapshotInputFormat.java
Fixed the warnings javadoc warnings for MultiTableSnapshotInputFormat.java file.
=> HBASE-22481: Javadoc Warnings reference not found

pom.xml
The `surefire.version` property is inherited from ASF parent pom with version 2.22.0.
[SUREFIRE-1614](https://issues.apache.org/jira/browse/SUREFIRE-1614) is included in 2.22.2 release which fixes an issue with corrupted outputs which could help us for fixing the issue described in [HBASE-22470](https://issues.apache.org/jira/browse/HBASE-22470).
=> HBASE-22554 Upgrade to surefire 2.22.2

hbase-common/src/main/java/org/apache/hadoop/hbase/io/ByteBuffAllocator.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/ExclusiveMemHFileBlock.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlockBuilder.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/LruBlockCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/SharedMemHFileBlock.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/TinyLfuBlockCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/TestHeapSize.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/CacheTestUtils.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestChecksum.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlock.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileDataBlockEncoder.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileScannerImplReferenceCount.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestLruBlockCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCacheRefCnt.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestRAMCache.java
…se the heap block won't need refCnt and save into prevBlocks list before shipping
=> HBASE-22491 Separate the heap HFileBlock and offheap HFileBlock because the heap block won't need refCnt and save into prevBlocks list before shipping

hbase-common/src/test/java/org/apache/hadoop/hbase/HBaseCommonTestingUtility.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplit.java
HBASE-22565: Fixed Javadoc Warnings: @see cannot be used in inline documentation
=> HBASE-22565 Javadoc Warnings: @see cannot be used in inline documentation

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
CompactionChecker and PeriodicMemStoreFlusher
=> HBASE-22596 [Chore] Separate the execution period between 

hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/FileLink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/TakeSnapshotHandler.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/PermissionStorage.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/SnapshotScannerHDFSAclController.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/SnapshotScannerHDFSAclHelper.java, hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestSnapshotScannerHDFSAclController.java
To make hbase granted user have the access to scan table snapshots, use HDFS ACLs to set user 'access r-x' or 'default r-x' ACLs over hfiles.
The basic implementation is:
1. For public directories such as 'data' and 'archive', set other users' permission to '--x' to make everyone have the permission to access the directory.
2. For namespace or table directories such as 'data/ns/table', 'archive/data/ns/table' and '.hbase-snapshot/snapshotName', set user 'r-x' acl and default 'r-x' acl when grant, revoke, snapshot.
The feature is configurable because it's implemented in a master coprocessor.
=> HBASE-21995 Add a coprocessor to set HDFS ACL for hbase granted user

hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/RowIndexCodecV1.java
DataOutputStream is not closed after used.
=> HBASE-22611 Close the DataOutputStream object

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
Multi RPC can be a mix of gets and mutations. The responseTooXXX logging for Multi ops should characterize the operations within the request so we have some clue about whether read or write dispatch was involved.
=> HBASE-22616 responseTooXXX logging for Multi should characterize the component ops

hbase-server/src/main/java/org/apache/hadoop/hbase/backup/HFileArchiver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/HFileLink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterFileSystem.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/DeleteTableProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/migration/NamespaceUpgrade.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionFileSystem.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SplitTransactionImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/RestoreSnapshotHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/HFileArchiveUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java, hbase-server/src/test/java/org/apache/hadoop/hbase/backup/TestHFileArchiving.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/TestHFileLink.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestDistributedLogSplitting.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionMergeTransaction.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSplitTransaction.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplit.java
HBASE-22617 Recovered WAL directories not getting cleaned up (Duo Zhang)
=> HBASE-22627 Port HBASE-22617 (Recovered WAL directories not getting cleaned up) to branch-1

hbase-common/src/main/resources/hbase-default.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DefaultMemStore.java, src/main/asciidoc/_chapters/offheap_read_write.adoc
The document is just a copy from https://issues.apache.org/jira/browse/HBASE-20460,  Will check all those config keys based on our HBase2.x & master. Thanks.
=> HBASE-20060 Add details of off heap memstore into book.

hbase-annotations/src/test/java/org/apache/hadoop/hbase/testclassification/FilterTests.java, hbase-annotations/src/test/java/org/apache/hadoop/hbase/testclassification/IOTests.java, hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml, hbase-client/src/main/java/org/apache/hadoop/hbase/client/MetricsConnection.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/WeakObjectPool.java, hbase-common/src/test/java/org/apache/hadoop/hbase/HBaseClassTestRuleChecker.java, hbase-endpoint/src/test/java/org/apache/hadoop/hbase/coprocessor/ProtobufCoprocessorService.java, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/MultiTableSnapshotInputFormat.java, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/MultiTableSnapshotInputFormatImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/package-info.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/ZKDataMigrator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestCase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/HConnectionTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestIncrementsFromClientSide.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestWarmupRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMemStoreChunkPool.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/HBaseZKTestingUtility.java
Fixed Javadoc Warnings: @link reference not found
=> HBASE-22572 Javadoc Warnings: @link reference not found

hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestMetaTableMetrics.java
the problem was seen only on branch 2.0 and 2.1, but it should be unrelated to the minor version of the branches and the same fix can be applied on all 2.x branches
fixes / changes:
- wait until all the metrics appear on JMX (previously we were only waiting for the bean to appear, I think this was the cause behind fleakyness)
- testing all the jmx attributes for all metrics / operations
- rename the test (test -> testMetaTableMetricsInJmx)
=> HBASE-22637 fix flaky test in TestMetaTableMetrics

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide3.java
This is the `branch-2` backport of master patch: https://github.com/apache/hbase/commit/7878389669740c7da3689d56c7906881b834e0bf
=> HBASE-13798 TestFromClientSide* don't close the Table (branch-2)

pom.xml
License check fails after build with errorProne profile activated. The hbase-error-prone module is added to the root pom only when the profile is active so running RAT check does not consider hbase-error-prone/target as a build directory.
=> HBASE-22654 apache-rat complains on branch-1

src/site/xdoc/index.xml
there are 5 checks failing on https://whimsy.apache.org/site/project/hbase so I added the following information to the main page on the website:
- image and link about current Apache events
- link to HBase license
- link to apache sponsors
- link to security and vulnerability information
- legal text about trademarks
[link to the screenshot in jira](https://issues.apache.org/jira/secure/attachment/12973180/HBASE-20405.png)
I don't know if we can test this with Whimsy before merging to the master branch, so potentially it will require more tries... 
UPDATE: [link to the new screenshot in jira](https://issues.apache.org/jira/secure/attachment/12973640/HBASE-20405-v2.png)
=> HBASE-20405 Update website to meet foundation recommendations

hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestStrings.java
I've analysed your codebase and noticed that `org.apache.hadoop.hbase.util.Strings` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
=> Add unit tests for org.apache.hadoop.hbase.util.Strings

src/site/site.xml
after the previous MR, it looks the [whimsy tool](https://whimsy.apache.org/site/project/hbase) still failed in two cases. In this commit we try to fix these issues, based on the [zookeeper](zookeeper.apach.org) website and the [apache policy description](https://www.apache.org/foundation/marks/pmcs#websites)
It looks the [whimsy tool](https://whimsy.apache.org/site/project/hbase) is checking the first occurrence of the links on the website, so we have to also change the links in the menubars.
=> HBASE-20405 fix License and Thanks links on website

hbase-server/src/main/java/org/apache/hadoop/hbase/coordination/ZkSplitLogWorkerCoordination.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSplitLogWorker.java
The regionserver side distributed split coordination logic only allows a regionserver to grab one task one at a time. Nearby javadoc says "This policy puts an upper-limit on the number of simultaneous log splitting that could be happening in a cluster." That upper limit will be the number of currently live regionservers. However, a regionserver can handle more than one task at once and in fact the max number of concurrent split tasks it can accept is configurable.
=> HBASE-22686 ZkSplitLogWorkerCoordination doesn't allow a regionserver to pick up all of the split work it is capable of

hbase-client/src/main/java/org/apache/hadoop/hbase/client/SimpleRequestController.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapred/TestTableInputFormat.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableInputFormat.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/VersionInfoUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/locking/EntityLock.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreLABImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotInfo.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestServerSideScanMetricsFromClientSide.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestOpenTableInCoprocessor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/RandomKeyValueUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionPlacement.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStore.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStoreFile.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMobStoreScanner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/MultiThreadedAction.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/test/LoadTestDataGenerator.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MiniZooKeeperCluster.java
Javadoc Warnings related to @return tag
=> HBASE-22571 Javadoc Warnings related to @return tag

hbase-common/src/main/java/org/apache/hadoop/hbase/PrivateCellUtil.java, hbase-common/src/test/java/org/apache/hadoop/hbase/util/ClassLoaderTestHelper.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/metrics/impl/HBaseMetrics2HadoopMetricsAdapter.java, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java, hbase-server/src/main/java/org/apache/hadoop/hbase/HealthChecker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/errorhandling/ForeignExceptionDispatcher.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputSaslHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/namespace/NamespaceStateManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StripeStoreFileManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/SyncFuture.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestActiveMasterManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestCatalogJanitorInMemoryStates.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionPlacement.java, hbase-server/src/test/java/org/apache/hadoop/hbase/procedure/TestZKProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/EncodedSeekPerformanceTest.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/ProcessBasedLocalHBaseCluster.java
Fixed javadoc warnings related to @param tag.
=> HBASE-22586 Javadoc Warnings related to @param tag

hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MiniZooKeeperCluster.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAclReset.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKClusterId.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKLeaderManager.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java
- final arguments for Constructor with args
- try with resources
- removal of redundant null check
- avoid possible NPE due to KeeperException
=> HBASE-22638 : Zookeeper Utility enhancements

NOTICE.txt, hbase-shaded/hbase-shaded-check-invariants/src/test/resources/ensure-jars-have-correct-contents.sh, hbase-shaded/hbase-shaded-testing-util-tester/pom.xml, hbase-shaded/hbase-shaded-testing-util-tester/src/test/java/org/apache/hbase/shaded/TestShadedHBaseTestingUtility.java, hbase-shaded/hbase-shaded-testing-util/pom.xml, hbase-shaded/hbase-shaded-testing-util/src/main/resources/org/apache/hadoop/hbase/shaded/org/mortbay/jetty/webapp/webdefault.xml, hbase-shaded/pom.xml
Added new artifact hbase-shaded-testing-util. It wraps a whole hbase-server
with its testing dependencies. Users should use only the following dependency
in pom:
<dependency>
<groupId>org.apache.hbase</groupId>
<artifactId>hbase-shaded-testing-util</artifactId>
<version>${hbase.version}</version>
<scope>test</scope>
</dependency>
=> HBASE-15666 shaded dependencies for hbase-testing-util

hbase-common/src/main/resources/hbase-default.xml, src/main/asciidoc/_chapters/configuration.adoc, src/main/asciidoc/_chapters/hbase-default.adoc, src/main/asciidoc/_chapters/schema_design.adoc
- more details in the [HBASE-22700](https://issues.apache.org/jira/browse/HBASE-22700)
=> HBASE-22700:incorrect timeout in recommended ZooKeeper configuration

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/SnapshotDescription.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/snapshot/ClientSnapshotDescriptionUtils.java, hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-common/src/main/resources/hbase-default.xml, hbase-protocol-shaded/src/main/protobuf/Snapshot.proto, hbase-protocol/src/main/protobuf/HBase.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/SnapshotCleanerChore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotDescriptionUtils.java, hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotInfo.java, hbase-server/src/main/resources/hbase-webapps/master/snapshot.jsp, hbase-server/src/main/resources/hbase-webapps/master/snapshotsStats.jsp, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSnapshotFromClient.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSnapshotTemporaryDirectory.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestSnapshotCleanerChore.java, hbase-shell/src/main/ruby/hbase/admin.rb, src/main/asciidoc/_chapters/hbase-default.adoc, src/main/asciidoc/_chapters/ops_mgt.adoc
- Associate TTL in sec with Snapshot argument. e.g. snapshot 'table', 'snapshot', {TTL => 20} 
- If not specified, default TTL to be taken for Snapshot. Specified here: HConstants.DEFAULT_SNAPSHOT_TTL
- If Snapshot is never meant to get expired, specify negative value for TTL. snapshot 'table', 'snapshot', {TTL => -2}
=> HBASE-22648 : Introducing Snapshot TTL

hbase-common/src/main/java/org/apache/hadoop/hbase/CellUtil.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestHFileOutputFormat2.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/OpenRegionHandler.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreScanner.java
Removed warnings coming due to @link tag.
=> HBASE-22603 Javadoc Warnings related to @link tag

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide.java
- Refactored `testNull()` into multiple,
- Added suppress warning for `testVersionLimits()` - cannot split,
- Added suppress warning for `testDeletesWithReverseScan()` - cannot split
=> HBASE-22382 Refactor tests in TestFromClientSide

hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/backup/example/HFileArchiveManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/backup/example/LongTermArchivingHFileCleaner.java, hbase-server/src/main/java/org/apache/hadoop/hbase/backup/example/TableHFileArchiveTracker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/backup/example/ZKTableArchiveClient.java, hbase-server/src/test/java/org/apache/hadoop/hbase/backup/example/TestZooKeeperTableArchiveClient.java
Clean up from #145 without moving the files.
=> HBASE-22594 Clean up for backup examples

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java
TraceScope for reclaimMemStoreMemory to be wrapped around by try-with-resources so that any Exception in reclaimMemStoreMemory() does not leave scope opened
=> HBASE-22132 : Backport HBASE-22115 to branch-1

hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/FsDelegationToken.java, hbase-server/src/test/java/org/apache/hadoop/hbase/security/token/TestFsDelegationToken.java
Issue: https://issues.apache.org/jira/browse/HBASE-22313
=> HBASE-22313 Add method to FsDelegation token to accept token kind

hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestByteRangeUtils.java, hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestClasses.java
I've analysed your codebase and noticed that `org.apache.hadoop.hbase.util.ByteRangeUtils` and `Classes` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
=> HBASE-22677 Add unit tests for org.apache.hadoop.hbase.util.ByteRangeUtils and Classes

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java
@petersomogyi Sorry, I missed one more thing: added the user's remote address to the message.
=> HBASE-22759. Added remote address to grant/revoke audit log messages

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
Add audit logger to grant() and revoke() methods of `MasterRpcServices`.
`master` version
=> HBASE-22759 Add user info to AUDITLOG events when doing grant/revoke (master)

hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/BaseRegionObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALKey.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/SimpleRegionObserver.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestRegionObserverInterface.java
This is the branch-1 backport of PR #390 , for HBASE-22623. Since it's a slightly non-trivial backport, opening up a separate PR for ease of review / chance for HBase Robot to pass judgement.
=> HBASE-22623 - Add RegionObserver coprocessor hook for preWALAppend

hbase-client/src/main/java/org/apache/hadoop/hbase/client/BufferedMutatorParams.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/SimpleRequestController.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/Table.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/coprocessor/Batch.java, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStateNode.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFilesTool.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestFlushSnapshotFromClient.java, pom.xml
Removed all javadoc warnings and now there is no javadoc warning anymore
=> HBASE-22725 Remove all remaining javadoc warnings

hbase-assembly/pom.xml
tarball build with assembly:single command fails with user id(mac) or group id(ubuntu) too big error:
```
$ mvn clean install package assembly:single -DskipTests
....
....
....
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (default-cli) on project hbase-assembly: Execution default-cli of goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single failed: user id 'xxxxxxxx' is too big ( > 2097151 ). -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] …
```
=> HBASE-22838 : assembly plugin should use posix

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
We already track region close activity with a MonitoredTask. Enable the status journal and dump it at DEBUG log level so if for some reasons region closes are taking a long time we have a timestamped journal of the activity and how long each step took.
=> HBASE-22828 Log a region close journal

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/BoundedGroupingStrategy.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/NamespaceGroupingStrategy.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/RegionGroupingProvider.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSplitTransaction.java
[JIRA link](https://issues.apache.org/jira/browse/HBASE-22774)
=> HBASE-22774 [WAL] RegionGroupingStrategy loses its function after split

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/executor/EventType.java, hbase-server/src/main/java/org/apache/hadoop/hbase/executor/ExecutorType.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/executor/TestExecutorService.java
=> HBASE-22810 Initialize an separate ThreadPoolExecutor for taking/restoring snapshot

src/main/asciidoc/_chapters/architecture.adoc
JIRA: https://issues.apache.org/jira/browse/HBASE-22873
=> HBASE-22873: Fixed typo in block caching docs

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
HMaster crashes at org/apache/hadoop/hbase/regionserver/HRegionServer.java:1044
**A private static nested class can not be instantiated via reflection.**
**code snippet**
```
try {
abortTimeoutTask =
Class.forName(conf.get(ABORT_TIMEOUT_TASK, SystemExitWhenAbortTimeout.class.getName()))
.asSubclass(TimerTask.class).getDeclaredConstructor().newInstance();
} catch (Exception e) {
LOG.warn("Initialize abort timeout task failed", e);
}
```
**log in product environtment**
```
2019-08-16 18:01:40,737 [WARN ] HRegionServer:1046 Initialize abort timeout task failed
java.lang.IllegalAccessException: Class org.apache.hadoop.hbase.regionserver.HRegionServer can not access a member of class org.apache.hadoop.hbase.regionss
erver.HRegionServer$SystemExitWhenAbortTimeout with modifiers "private"
at …
```
=> HBASE-22870 reflection fails to access a private nested class

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java
@apurtell  This is the patch for master branch. please review.
Cherry-picking master commit applies cleanly to branch-2.
=> [HBASE-22601] Misconfigured addition of peers leads to cluster shutdown.

hbase-mapreduce/pom.xml, hbase-server/pom.xml, hbase-shaded/hbase-shaded-client-byo-hadoop/pom.xml, hbase-shaded/hbase-shaded-mapreduce/pom.xml, hbase-shaded/hbase-shaded-testing-util-tester/pom.xml, hbase-shaded/hbase-shaded-testing-util/pom.xml, pom.xml
Partly forwardport from [HBASE-22728](https://issues.apache.org/jira/browse/HBASE-22728) to master and branch-2
=> HBASE-22863 : Cleanup transitive Jackson1 vulnerable dependencies(forward-port HBASE-22728)

hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/CleanerChore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/DirScanPool.java
…threads in our cluster with thousands table
=> HBASE-22867 The ForkJoinPool in CleanerChore will spawn thousands of threads in our cluster with thousands table

dev-support/Jenkinsfile
HBase, a Hadoop related project, must use the Hadoop label please.
This build, and others are starving the 'ubuntu' label which other projects need to use.
=> HBASE-22913 Use Hadoop label for nightly builds

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
During HMaster failover, if RegionServer send space quota report to HMaster and MasterQuotaManager is not yet initialized then NPE will occur.
https://github.com/apache/hbase/blob/767bb1511285ae67dae15e8a2aab62c38244c797/hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java#L2229
=> HBASE-22904 NPE occurs when RS send space quota usage report during HMaster init

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStateStore.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestSplitMerge.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAdmin1.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionAdminApi2.java
store and return the merge parent regions in ascending order
remove left over check for exactly two merged regions
add unit test
=> HBASE-22941 merge operation returns parent regions in random order

src/main/asciidoc/_chapters/ops_mgt.adoc
Refguide has "HBase Backup" section and a chapter named "Backup and Restore"; neither refers to the other. Added a link in HBase Backup section to refer to Backup and Restore
=> HBASE-20688

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableRecordReaderImpl.java
Updating the counter in multiple exception scenario.
=> HBASE-22928 ScanMetrics counter update may not happen in case of exception in TableRecordReaderImpl

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java, hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
Amending-Author: Duo Zhang <zhangduo@apache.org>
=> HBASE-22729 Start RSGroupInfoManager as default

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/CompactSplit.java
Appended the counter in the thread name.
=> HBASE-22930 Set unique name to longCompactions/shortCompactions threads

hbase-shaded/hbase-shaded-testing-util/pom.xml, hbase-shaded/pom.xml
* Relocation rule "net" has been changed to "net." because "netty"
applies to that rule.
* Added jackson dependencies for WebHdfs.
=> HBASE-23007 UnsatisfiedLinkError when using hbase-shaded packages under linux

src/site/xdoc/downloads.xml
Noticed this while working on some automation. We're https everywhere else in this page, just not this link.
=> Downloads page archive link should be https

hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/RestoreSnapshotHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotManifest.java
HBASE-22899 logging improvements for snapshot operations w/large manifests
=> HBASE-22899 logging improvements for snapshot operations w/large manifests

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSyncUpToolWithBulkLoadedData.java
Bulkload from different hdfs failed when space quotas are turned on.
=> HBASE-22939 SpaceQuotas- Bulkload from different hdfs failed when space quotas are turned on.

dev-support/docker/Dockerfile
because branches-1 use an older Ubuntu we need to include a work around for a bug in the linking of the shellcheck executable.
=> HBASE-23023 upgrade shellcheck used in dockerfile

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/FileIOEngine.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/PersistentIOEngine.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestFileIOEngine.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
[HBASE 22890](https://issues.apache.org/jira/browse/HBASE-22890?filter=-2)
=> HBASE-22890 Verify the files when RegionServer is starting and BucketCache is in file mode

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/FileIOEngine.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/PersistentIOEngine.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
[HBASE-22890](https://issues.apache.org/jira/browse/HBASE-22890)
=> HBASE-22890 Verify the file integrity in persistent IOEngine

hbase-client/src/main/java/org/apache/hadoop/hbase/security/token/ClientTokenUtil.java, hbase-client/src/test/java/org/apache/hadoop/hbase/security/token/TestClientTokenUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SecureBulkLoadManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/TokenProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/TokenUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/security/token/TestDelegationTokenWithEncryption.java, hbase-server/src/test/java/org/apache/hadoop/hbase/security/token/TestGenerateDelegationToken.java
…tTokenUtil, and move ClientTokenUtil to hbase-client
This is a backport of https://github.com/apache/hbase/pull/361 to 2.x
The following changes were made to the diff from that PR: 
* There is no obtainToken(AsyncConnection) on TokenUtil, so removed that variant from ClientTokenUtil.
* Made obtainToken(Connection) public, as it is used in SecureBulkLoadManager.
=> Hbase-22027

hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java, hbase-protocol-shaded/src/main/protobuf/Client.proto, hbase-protocol-shaded/src/main/protobuf/WAL.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/client/AsyncClusterConnection.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/AsyncClusterConnectionImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SecureBulkLoadManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HFileReplicator.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFilesTool.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkLoadReplication.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationBase.java
=> HBASE-22380 break circle replication when doing bulkload

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/CompactSplit.java
ThreadFactoryBuilder internally has the its own counter, but to have the counter in the thread name we need to define the format in setNameFormat(),
new ThreadFactoryBuilder().setNameFormat(n + "-longCompactions-%d")
=> HBASE-22930 Set unique name to longCompactions/shortCompactions/split threads

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableQueryMeter.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableLatenciesImpl.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableQueryMeterImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerTableMetrics.java
[HBASE-22975](https://issues.apache.org/jira/browse/HBASE-22975)
=> HBASE-22975 Add read and write QPS metrics at server level and table level

pom.xml
Jackson security issues：
A Polymorphic Typing issue was discovered in FasterXML jackson-databind before 2.9.10. It is related to com.zaxxer.hikari.HikariDataSource. This is a different vulnerability than CVE-2019-14540.
https://nvd.nist.gov/vuln/detail/CVE-2019-16335
A Polymorphic Typing issue was discovered in FasterXML jackson-databind before 2.9.10. It is related to com.zaxxer.hikari.HikariConfig.
https://nvd.nist.gov/vuln/detail/CVE-2019-14540
=> HBASE-23075 Upgrade jackson version

hbase-client/src/main/java/org/apache/hadoop/hbase/ClusterMetrics.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ClusterMetricsBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionStatesCount.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-protocol-shaded/src/main/protobuf/ClusterStatus.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestClientClusterMetrics.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
Jira: https://issues.apache.org/jira/browse/HBASE-22903
=> HBASE-22903 : Table to RegionStatesCount metrics - Use for broken alter_status command

dev-support/create-release/README.txt, dev-support/create-release/do-release-docker.sh, dev-support/create-release/do-release.sh, dev-support/create-release/release-build.sh, dev-support/create-release/release-tag.sh, dev-support/create-release/release-util.sh, dev-support/create-release/vote.tmpl
Make the scripts generic. Set PROJECT environment variable
and away you go; e.g. set it to hbase-operator-tools or to
hbase-thirdparty.
This commit includes a bunch of bugfixes and miscellaneous
that came of trying to use the scripts making RCs.
=> HBASE-23092 Make the RM tooling in dev-tools/create-release generic

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
Fixes a typo and adds table name to the logging context when
StochasticLoadBalancer is configured "per table". Added some
test coverage with per-table balancer enabled and manually
verified the logs to make sure the table name is formatted
correctly.
=> HBASE-23116: Fix a couple of load balancer logging nits.

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
This commit adds table name to the logging context when
StochasticLoadBalancer is configured "per table".
=> HBASE-23116 LoadBalancer should log table name when balancing per table

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileInfo.java, hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotManifestV2.java, hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestSnapshotStoreFileSize.java
We found this performance issue when taking a snapshot on large MOB table where MOB compaction is disabled more than 3 months, is due to MOB data loss issue HBASE-22075.
=> HBASE-23095 Reuse FileStatus in StoreFileInfo

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestHFileOutputFormat2.java
Issue detail: https://issues.apache.org/jira/browse/HBASE-22887
- writer roll only if wl.written is too long and previousRow is not equal.
- delete bool rollRequested because different writter roll  independently, so they don't need to  communicate.
Signed-off-by: langdamao <lang--lang--lang@163.com>
=> HBASE-22887 Fix HFileOutputFormat2 writer roll

hbase-server/src/main/java/org/apache/hadoop/hbase/mapreduce/TableMapReduceUtil.java
Add the hbase-thirdparty jar to base job dependencies.
=> HBASE-23139 MapReduce jobs lauched from convenience distribution are nonfunctional

hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
```
hbase(main):001:0>  drop_all("t.*")
ERROR: undefined local variable or method `admin' for #<Hbase::Admin:0x3a3b10f4>
Did you mean?  @adminFor usage try 'help "drop_all"'
```
=> HBASE-23138 Drop_all table by regex fail

hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
The deprecated method Admin#mergeRegions is removed in HBase 3.0 but we need to update new API in admin script.
=> HBASE-23123 Merge_region fails from shell

hbase-protocol-shaded/src/main/protobuf/BucketCacheEntry.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketProtoUtils.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/FileIOEngine.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/FileMmapIOEngine.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/PersistentIOEngine.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
[HBASE-23017](https://issues.apache.org/jira/browse/HBASE-23017)
=> HBASE-23017 Verify the file integrity in persistent IOEngine

hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
Compact_rs command will call Admin#compactRegionServer(ServerName, boolean) but this is deprecated method and removed as part of HBASE-22002.
=> HBASE-23144 Compact_rs throw wrong number of arguments

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ExecutorStatusChore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/executor/ExecutorService.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestExecutorStatusChore.java
=> HBASE-23083 Collect Executor status info periodically and report to metric system

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionAdminApi.java, hbase-shell/src/main/ruby/shell/commands/compaction_switch.rb
Compaction_switch is used to stop running compaction on regionservers. This switch works good by using "compaction_switch true/false" but rather I want to stop compaction only for particular regionserver. In that case, the switch doesn't work because serverName that we want to stop is not added into CompletableFuture\<List\<ServerName\>\>. So we always get empty Future list by using RS name.
https://github.com/apache/hbase/blob/master/hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java#L3156
=> HBASE-23152 Compaction_switch does not work by RegionServer name

hbase-shell/src/main/ruby/shell/commands/list_deadservers.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
No of rows should be equivalent to no of dead region servers but mistakenly included current system time in it.
=> HBASE-23154 list_deadservers return incorrect no of rows

hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutput.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/CallRunner.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerCall.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestCallRunner.java
If FanOutOneBlockAsyncDFSOutput#endBlock throw Exception before call "buf.release();", this buf has not chance to release.
In CallRunner if the call skipped or Dropping timed out call, the call do not call cleanup.
=> HBASE-22370 ByteBuf LEAK ERROR

hbase-shell/src/main/ruby/shell/commands/delete_all_snapshot.rb, hbase-shell/src/main/ruby/shell/commands/delete_table_snapshots.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
Delete_all_snapshot.rb is using deprecated method SnapshotDescription#getTable but this method is already removed in 3.0.x.
=> HBASE-23176 delete_all_snapshot does not work with regex

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncProcess.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/BufferedMutatorImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionConfiguration.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionManager.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
https://issues.apache.org/jira/browse/HBASE-23185
=> HBASE-23185 Fix high cpu usage because getTable()#put() gets config value every time

hbase-client/src/main/java/org/apache/hadoop/hbase/RegionMetrics.java, hbase-client/src/main/java/org/apache/hadoop/hbase/RegionMetricsBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ServerMetricsBuilder.java, hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-common/src/main/resources/hbase-default.xml, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapper.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSourceImpl.java, hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionSourceImpl.java, hbase-protocol-shaded/src/main/protobuf/ClusterStatus.proto, hbase-protocol/src/main/protobuf/ClusterStatus.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionsRecoveryChore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ReopenTableRegionsProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionsRecoveryChore.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperStub.java, src/main/asciidoc/_chapters/hbase-default.adoc, src/main/asciidoc/_chapters/ops_mgt.adoc
Jira: https://issues.apache.org/jira/browse/HBASE-22460
=> HBASE-22460 : Reopen regions with very high Store Ref Counts

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/HeterogeneousRegionCountCostFunction.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCostRules.java
Based on the work in HBASE-22618, users can now load custom costFunctions inside the main balancer used by HBase. As an example, we like like to add upstream an optional cost function called HeterogeneousRegionCountCostFunction that will deal with our issue: how to balance regions according to the capacity of a RS instead of using the RegionCountSkewCostFunction that is trying to avoid skew.
A rule file is loaded from HDFS before balancing. It contains lines of rules. A rule is composed of a regexp for hostname, and a limit. For example, we could have:
rs[0-9] 200
rs1[0-9] 50
RegionServers with hostname matching the first rules will have a limit of 200, and the others 50. If there's no match, a default is set.
Thanks to the rule, we have two informations: the max number of regions for …
=> HBASE-23073 Add an optional costFunction to balance regions according to a capacity rule

hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/TokenUtil.java
Jira: https://issues.apache.org/jira/browse/HBASE-23194
=> HBASE-23194 : Remove unused methods from TokenUtil

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceFactory.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregateSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserSource.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceFactoryImpl.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregateSourceImpl.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserSourceImpl.java, hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsUserSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MetaTableMetrics.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregate.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregateFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregateImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/LossyCounting.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsTableLatencies.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsUserAggregate.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestLossyCounting.java
HBASE-15519 Add per-user metrics with lossy counting
Introducing property hbase.regionserver.user.metrics.enabled(Default:true)
to disable user metrics in case it accounts for any performance issues
=> HBASE-23210 Backport HBASE-15519 (Add per-user metrics) to branch-1

hbase-server/src/main/resources/hbase-webapps/master/table.jsp
if quota is enabled, then we fetch table and namespace quota info. It is not necessary both table and namespace will have a quota set.  Sometimes, users only have table level quota or namespace level quota or both un-set.  So we must add Quota "null" check before getting Throttle info(Limit, Type, TimeUnit, Scope). 
```Table Attributes
org.apache.hadoop.hbase.generated.master.table_jsp._jspService(table_jsp.java:385)org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)javax.servlet.http.HttpServlet.service(HttpServlet.java:790)org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:840)org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1780)org.apache.hadoop.hbase.http.lib.StaticUserWebFilter$StaticUserFilter.doFilter(StaticUserWebFilt …
```
=> HBASE-23199 Error populating Table-Attribute fields

hbase-client/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStates.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRegionSplit.java
When split, the parent region set to SPLIT in memory, but the meta do not, so in some circumstances will bring back the parent region.
=> HBASE-23187 Update parent region state to SPLIT in meta

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogReader.java
If no new active writes in WAL edit, then WALEntryStream#hasNext -> ReaderBase -> ProtobufLogReader#readNext will reach end of file. It would be a good idea for changing the log level from INFO to DEBUG.
=> HBASE-23191 EOFE log spam

hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/store/wal/WALProcedureStore.java
This PR contains following changes,
1. Delete the file when header write fails
2. If corrupted file deletion fails then increase the flushLogId, so that WAL rolling will be successful on next attempt
3. Modified the log message to print the correct log file ID.
Tried to mock this scenario, but couldn't as Mockito doesn't support static method or final class mocking.
=> HBASE-22917 Proc-WAL roll fails saying someone else has already created log

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java
When multiple ServerNames having same hostname and port, the Cluster build wrong with regionPerServerIndex.
=> HBASE-22739 ArrayIndexOutOfBoundsException when balance

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceInterface.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/ReplicationSourceDummy.java
Add metrics when replication startup
=> HBASE-23231 ReplicationSource do not update metrics after refresh

hbase-common/src/main/java/org/apache/hadoop/hbase/CellUtil.java, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/WALPlayer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/LogRoller.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSWALEntry.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/SequenceIdAccounting.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/WALUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALActionListener.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/DisabledWALProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/LogRecoveredEditsOutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALEdit.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkLoad.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestFailedAppendAndSync.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRecoveredEdits.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestWALLockup.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestFSWAL.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestWALReplay.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncFSWAL.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/FaultyFSLog.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplit.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/WALPerformanceEvaluation.java
Removes the closeRegion flag added by HBASE-23181 and instead
relies on reading meta WALEdit content. Modified how qualifier is
written when the meta WALEdit is for a RegionEventDescriptor
so the 'type' is added to the qualifer so can figure type
w/o having to deserialize protobuf value content: e.g.
HBASE::REGION_EVENT::REGION_CLOSE
Added doc on WALEdit and tried to formalize the 'meta' WALEdit
type and how it works. Needs complete redo in part as suggested
by HBASE-8457. Meantime, some doc and cleanup.
Also changed the LogRoller constructor to remove redundant param.
Because of constructor change, need to change also
TestFailedAppendAndSync, TestWALLockup, TestAsyncFSWAL &
WALPerformanceEvaluation.java
=> HBASE-23221 Polish the WAL interface after HBASE-23181

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncProcess.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/BufferedMutatorImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionConfiguration.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionManager.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/HConnectionTestingUtility.java
https://builds.apache.org/job/HBase Nightly/job/branch-1/1114//testReport/junit/org.apache.hadoop.hbase.master/TestCatalogJanitor/health_checks___yetus_jdk8_hadoop2_checks___testCleanParent/
=> HBASE-23185 Fix high cpu usage because getTable()#put() gets config value every time [Take2]

hbase-server/src/test/java/org/apache/hadoop/hbase/executor/TestExecutorService.java
[INFO] Running org.apache.hadoop.hbase.executor.TestExecutorService
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.347 s <<< FAILURE! - in org.apache.hadoop.hbase.executor.TestExecutorService
[ERROR] testSnapshotHandlers(org.apache.hadoop.hbase.executor.TestExecutorService)  Time elapsed: 0.086 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
at org.apache.hadoop.hbase.executor.TestExecutorService.testSnapshotHandlers(TestExecutorService.java:247)
=> HBASE-23241 TestExecutorService sometimes fail

hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/store/ProcedureStoreTracker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
Pre-flight check should allow that there may be no WALs to split.
=> HBASE-23247 [hbck2] Schedule SCPs for 'Unknown Servers'

hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsUserSourceImpl.java
The self comparison check in TestMetricsUserSourceImpl triggers error-prone and is of little value, remove it.
=> HBASE-23246 Fix error prone warning in TestMetricsUserSourceImpl

hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/CleanerChore.java
Changed log.debug present inside private void initCleanerChain() to log.info as per the description mentioned in ticket.
=> HBASE-23250 Log message about CleanerChore delegate initialization should be at INFO

hbase-it/src/test/java/org/apache/hadoop/hbase/HBaseClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/AddCPULoadAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/CommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/CorruptDataFilesAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/CorruptPackagesCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DelayPackagesCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DeleteDataFilesAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DuplicatePackagesCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/FillDiskCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/LosePackagesCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/ReorderPackagesCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/SudoCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/TCCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/DataIssuesMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/DistributedIssuesMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/MonkeyConstants.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/MonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerAndDependenciesKillingMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerKillingMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/SlowDeterministicMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/StressAssignmentManagerMonkeyFactory.java
Add monkey actions:
- manipulate network packages with tc (reorder, loose,...)
- add CPU load
- fill the disk
- corrupt or delete regionserver data files
Create monkey factories for the new actions
Extend HBaseClusterManager to allow sudo calls
Fix a copy/paste issue wih monkey constants in some factories
=> HBASE-23085: Network and Data related Actions

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapred/HRegionPartitioner.java, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HRegionPartitioner.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestHRegionPartitioner.java
Partitioner class HRegionPartitioner in a HBase MapReduce job has a method getPartition(). In getPartition(), there is a scenario where we have check for less number of reducers than region. This scenario seems incorrect because for a rowKey present in last region(let us say nth region) , getPartition() should return value (n-1). But it is not returning n-1 for the last region as it is falling in the case where number of reducers < number of regions and returning some random value. 
So if a client uses this class as a partitioner class in HBase MapReduce jobs, this method incorrectly partitions the regions because rowKeys present in the last regions does not fall to the last region.
https://github.com/apache/hbase/blob/fbd5b5e32753104f88600b0f4c803ab5659bce64/hbase-mapreduce/src/main/java/ …
=> HBASE-22980 HRegionPartioner getPartition() method incorrectly partitions the regions of the table.

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/RSStatusTmpl.jamon, hbase-server/src/main/java/org/apache/hadoop/hbase/Server.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/LeaseManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregateImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSDumpServlet.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SplitRequest.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SplitWALCallable.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MockRegionServerServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterStatusServlet.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCleanupCompactedFileAfterFailover.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestPerColumnFamilyFlush.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestPriorityRpc.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRSStatusServlet.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerAbortTimeout.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerMetrics.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerNoMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSecureBulkLoadManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSplitWalDataLoss.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/SerialReplicationTestBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceManager.java
* Clean up a bunch of private variable leakage into other classes. Reduces visibility as much as possible, providing getters where access remains necessary or making use of getters that already exist. There remains an insidious relationship between `HRegionServer` and `RSRpcServices`.
* Rename `fs` to `dataFs`, `rootDir` as `dataRootDir` so as to distinguish from the new `walFs`, `walRootDir` (and make it easier to spot bugs).
* Cleanup or delete a bunch of lack-luster javadoc comments.
* Delete a handful of methods that are unused according to static analysis.
* Reduces the warning count as reported by IntelliJ from 100 to 7.
=> HBASE-23230 Enforce member visibility in HRegionServer

src/main/asciidoc/_chapters/developer.adoc
I assume the Hadoop project moved their wiki around a bit.
=> HBASE-23272 Fix link in Developer guide to "code review checklist"

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
If no online regionservers then master UI can't be opened. This issue occurs when using RSGroupAdminEndpoint coprocessor(RSGrouping).  The master home page tries to load rsgroup info from "hbase:rsgroup" table but currently no regionservers up and running.
=> HBASE-23262 Cannot load Master UI

hbase-server/src/main/java/org/apache/hadoop/hbase/master/CachedClusterId.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestCachedClusterId.java
This patch implements a simple cache that all the masters
can lookup to serve cluster ID to clients. Active HMaster
is still responsible for creating it but all the masters
will read it from fs to serve clients.
RPCs exposing it will come in a separate patch as a part of
HBASE-18095.
=> HBASE-23257: Track clusterID in stand by masters

hbase-it/src/test/java/org/apache/hadoop/hbase/DistributedHBaseCluster.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/Action.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/GracefulRollingRestartRsAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActionBaseAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RollingBatchSuspendResumeRsAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/MonkeyConstants.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerAndDependenciesKillingMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerKillingMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/SlowDeterministicMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/StressAssignmentManagerMonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MiniHBaseCluster.java
HBASE-22982: region server suspend/resume and graceful rolling restart actions (#592)
* Add chaos monkey action for suspend/resume region servers
* Add chaos monkey action for graceful rolling restart
* Add these to relevant chaos monkeys
This is just a backport of a commit already on hbase/master.
=> HBASE-22982: region server suspend/resume and graceful rolling restart actions

hbase-assembly/src/main/assembly/components.xml
* Package the test jar from hbase-zookeeper into lib/
=> HBASE-23318 LoadTestTool doesn't start

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/LocalHBaseCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestHBaseTestingUtility.java
This patch adds the plumbing needed to start the mini cluster with
a pre-determined set of master ports. This is required for HBASE-18095
because the internal client 'Connection's from region servers need
to know the master RPC end points in their configuration even before
the mini cluster starts.
Following patches on HBASE-18095 will use this plumbing for unit tests.
=> HBASE-23259: Ability to start minicluster with pre-determined master ports

hbase-server/src/main/java/org/apache/hadoop/hbase/master/ActiveMasterManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestActiveMasterManager.java
Currently we just track whether an active master exists.
It helps to also track the address of the active master in
all the masters to help serve the client RPC requests to
know which master is active.
=> HBASE-23275: Track active master's address in ActiveMasterManager

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/LocalHBaseCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestHBaseTestingUtility.java
All the clients need to know the master RPC end points while using master
based registry for creating cluster connections. This patch amends the
test cluster utility to populate these configs in the base configuration
object used to spin up the cluster.
The config key added here ("hbase.master.addrs") is used in the subsequent
patches for HBASE-18095.
=> HBASE-23259: Populate master address end points in cluster/rs configs

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RSGroupListTmpl.jamon
In /master-status, rsgoup average load keep two decimals.
=> HBASE-23325 [UI]rsgoup average load keep two decimals

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-replication/src/main/java/org/apache/hadoop/hbase/replication/ReplicationUtils.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/AsyncRegionServerAdmin.java, hbase-server/src/main/java/org/apache/hadoop/hbase/protobuf/ReplicationProtbufUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/ReplicationEndpoint.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HBaseInterClusterReplicationEndpoint.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceShipper.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/SyncReplicationTestBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEndpoint.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestSerialReplicationEndpoint.java
ReplicationSourceShipper#shipEdits may take a while if bulkload replication enabled, since we should copy HFile from the source cluster, so i think there is a need to make the timeout value configurable.
=> HBASE-23293 [REPLICATION] make ship edits timeout configurable

hbase-shell/src/main/ruby/shell/commands/clear_deadservers.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
HBASE-15849 simplified the format of command total runtime but clear_deadservers caller has not modified so it prints current timestamp instead of no of rows. 
```
hbase(main):015:0>  clear_deadservers 'kpalanisamy-apache302.openstacklocal,16020'
SERVERNAME
kpalanisamy-apache302.openstacklocal,16020,16020
1574585488 row(s)
Took 0.0145 seconds
```
=> HBASE-23336 [CLI] Incorrect row(s) count 'clear_deadservers'

src/site/xdoc/downloads.xml
I don't think mirrors have finished updating yet, but these changes should be correct once they do.
=> HBASE-23323 Update downloads page for Apaceh HBase 1.4.12.

hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestBase.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/FillDiskCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/MonkeyConstants.java
Instead of using the default properties when checking for monkey
properties, now we use the ones already extended with command line
params.
Change FillDiskCommandAction to try to stop the remote process if the
command failed with an exception.
=> HBASE-23352: Allow chaos monkeys to access cmd line params, and improve FillDiskCommandAction

dev-support/create-release/release-build.sh, pom.xml
- switch to nexus-staging-maven-plugin for asf-release
- refactor release-build to use mvn deploy and its output.
- cleaned up some tabs in the root pom
first commit corresponds to a rebase of v1 from jira.
=> HBASE-23337 Release scripts should rely on maven for deploy.

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALPrettyPrinter.java
Currently the log entries do not include the table name and the
user cannot filter by a table. This patch adds both.
Tested manually on a local WAL file.
=> HBASE-23362: [WalPrettyPrinter] print/filter by table name.

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java
2019-12-04 15:11:25,868 INFO [MemStoreFlusher.2] regionserver.MemStoreFlusher: Flush of region table_100B_10,user4346,1575440696268.a159ed24ac2b198c9cd5434f3bfe2ab6. due to global heap pressure. Flush type=ABOVE_ONHEAP_LOWER_MARKTotal Memstore Heap size=5.6 GTotal Memstore Off-Heap size=0, Region memstore size=229.8 M
Change the log to be more human-readable and friendly.
=> HBASE-23365 Minor change MemStoreFlusher's log

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RSGroupListTmpl.jamon
We somehow missed limiting decimal points in the total average load.
It is related to https://issues.apache.org/jira/browse/HBASE-23325
=> HBASE-23361 Limit two decimals in total average load

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RetriesExhaustedException.java
Signed-off-by: Lijin Bin <binlijin@apache.org>
=> HBASE-23373 Log `RetriesExhaustedException` context with full time precision (#903)

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheConfig.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestCacheOnWrite.java
the new config is not dependent on the prefetch block option. Just that we can use it as a toggle config. So once cache on compaction is enabled, the blocks are cached.
The threshold level change will do in another subtask. (https://issues.apache.org/jira/browse/HBASE-23350)
Creating a new PR because the previous one was created against master on my local repo. The same patch with updated test fix.
=> HBASE-23066 Allow cache on write during compactions when prefetching is

hbase-it/src/test/java/org/apache/hadoop/hbase/test/IntegrationTestBigLinkedList.java
We have this nice description in the java doc on ITBLL but it's
unformatted and thus illegible. Add some formatting so that it can be
read by humans.
=> HBASE-23552 Format Javadocs on ITBLL

hbase-shell/src/main/ruby/shell/commands/set_quota.rb
To remove a quota by throttle_type,
``` 
hbase> help "set_quota"
...
hbase> set_quota TYPE => THROTTLE, THROTTLE_TYPE => WRITE, USER => 'u1', LIMIT => NONE
....
```
but the actual command should be, 
```
hbase> set_quota TYPE => THROTTLE, THROTTLE_TYPE => WRITE_NUMBER, USER => 'u1', LIMIT => NONE
```
=> HBASE-23360 [CLI] Fix help command 'set_quota'

hbase-client/src/main/java/org/apache/hadoop/hbase/HRegionInfo.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionInfo.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAdmin2.java, hbase-shell/src/main/ruby/shell.rb, hbase-shell/src/main/ruby/shell/commands/regioninfo.rb
Adds shell command regioninfo:
hbase(main):001:0>  regioninfo '0e6aa5c19ae2b2627649dc7708ce27d0'
{ENCODED => 0e6aa5c19ae2b2627649dc7708ce27d0, NAME => 'TestTable,,1575941375972.0e6aa5c19ae2b2627649dc7708ce27d0.', STARTKEY => '', ENDKEY => '00000000000000000000299441'}
Took 0.4737 seconds
=> HBASE-23554 Encoded regionname to regionname utility

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/CorruptPacketsCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DelayPacketsCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DuplicatePacketsCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/LosePacketsCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/ReorderPacketsCommandAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/DistributedIssuesMonkeyFactory.java
There is a terminology problem in some of the network issue related chaos monkey actions. The universally understood technical term for network packet is packet, not "package".
=> HBASE-23566: Fix package/packet terminology problem in chaos monkeys

dev-support/Jenkinsfile_GitHub
the PR tester Jenkinsfile_GitHub has its own set of commands for gathering information about the build environment it runs in. Instead it should rely on the dev-support/gather_machine_environment.sh that gets used by nightly
=> HBASE-22920 github pr testing job should use dev-support script

hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-protocol-shaded/src/main/protobuf/Master.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestClientMetaServiceRPCs.java
This patch implements the RPCs needed for the meta information
lookup during connection init. New tests added to cover the RPC
code paths. HBASE-23305 builds on this to implement the client
side logic.
Fixed a bunch of checkstyle nits around the places the patch
touches.
=> HBASE-23304: RPCs needed for client meta information lookup

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
Make sure commited files belong to the correct column family when
creating a FlushDescriptor.
=> HBASE-23589: FlushDescriptor contains non-matching family/output combinations

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReaderThread.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
https://issues.apache.org/jira/browse/HBASE-23205
https://github.com/apache/hbase/pull/749#issuecomment-565963199
>No luck with the pre-commit. I tried a rebase, but still the job fails while starting. Ain't sure if it's something specific to the PR commits. @JeongDaeKim , would u mind squash these commits on one of you local branches, then open a new PR for branch-1 with this? Please ping me once you open the new PR.
=> HBASE-23205 Correctly update the position of WALs currently being replicated (2)

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkLoadReplication.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestNamespaceReplicationWithBulkLoadedData.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationBase.java
If one of the peers in a cluster is configured with NAMESPACE level, its hfile-refs(zk) will be backlogged.
We have three tables in the cluster and table name is
ns1:test
default:table1
default:bulkload
and this Cluster have three peers
{code:java}
add_peer 's1', CLUSTER_KEY => "cluster1:2181:/hbase"
add_peer 's2', CLUSTER_KEY => "cluster2:2181:/hbase", TABLE_CFS => \{ "table1" => [] }
add_peer 's3', CLUSTER_KEY => "cluster3:2182:/hbase-prod", NAMESPACES => ["ns1"]
{code}
ns1's hfile-refs backlogged when we bulk load files to the default:bulkload
 
=> HBASE-23098 [bulkload] If one of the peers in a cluster is configured with NAMESPACE level, its hfile-refs(zk) will be backlogged

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
[HBASE-23585](https://issues.apache.org/jira/browse/HBASE-23585)
=> HBASE-23585 MetricsRegionServerWrapperImpl.getL1CacheHitCount always returns 200

hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/BlockingRpcConnection.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/Call.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/IPCUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/RpcConnection.java, hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestFutureUtils.java
=> HBASE-23333 Include Call.toShortString() in sendCall exceptions

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncMetaRegionLocator.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableRegionLocatorImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionFactory.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionRegistryFactory.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/DoNothingConnectionRegistry.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncAdminRpcPriority.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncMetaRegionLocatorFailFast.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableRpcPriority.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestConnectionRegistryLeak.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/AsyncClusterConnectionImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/ClusterConnectionFactory.java, hbase-server/src/test/java/org/apache/hadoop/hbase/backup/example/TestZooKeeperTableArchiveClient.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestRegionLocator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/DummyConnectionRegistry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/RegionReplicaTestHelper.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncAdminWithRegionReplicas.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncMetaRegionLocator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncNonMetaRegionLocator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncNonMetaRegionLocatorConcurrenyLimit.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionLocator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncSingleRequestRpcRetryingCaller.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableUseMetaReplicas.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaRegionLocationCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestZKConnectionRegistry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntrySinkFilter.java
This patch is a simple refactor that renames a bunch of classes
to add more context to the readers. The code is littered with
the usage of word "registry" but it is not clear what the registry
is all about. This patch renames a bunch of classes to make it
more self explanatory.
=> HBASE-23604: Clarify AsyncRegistry usage in the code.

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReaderThread.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
https://issues.apache.org/jira/browse/HBASE-23205
related PR : #944
=> HBASE-23205 Correctly update the position of WALs currently being replicated

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RegionReplicaReplicationEndpoint.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/OutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestOutputSinkWriter.java
clear exception after logged
try to restart writer threads if needed
=> HBASE-23601: OutputSink.WriterThread exception gets stuck and repeated indefinietly

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
No need to create and close a new registry on demand. Audited other
usages of getRegistry() and the code looks fine.
=> HBASE-23648: Re-use underlying connection registry in RawAsyncHBaseAdmin

pom.xml
This reverts commit 248d80b0fe02b91b2ed5faa229c0572d83a729dd.
=> Revert "HBASE-23664 Upgrade JUnit to 4.13 (#1010)"

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MetaFixer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMetaFixer.java
The current process for an operator, after fixing holes in meta, is to manually disable and enable the whole table. Let's try to avoid bringing the whole table offline if we can. Have the master attempt to queue up assignment procedures for any new regions it creates.
=> HBASE-23383 [hbck2] `fixHoles` should queue assignment procedures for any regions its fixing

hbase-client/src/main/java/org/apache/hadoop/hbase/client/MasterRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/exceptions/MasterRegistryFetchException.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/BlockingRpcClient.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/HedgedRpcChannel.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcClient.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/RpcClient.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestConnectionRegistryLeak.java, hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/PrettyPrinter.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestTableName.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/JVMClusterUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/DummyConnectionRegistry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSideWithCoprocessor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMasterRegistry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestScannersFromClientSide.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/AbstractTestIPC.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestProtobufRpcServiceImpl.java
Implements a master based registry for clients.
- Supports hedged RPCs (fan out configured via configs).
- Parameterized existing client tests to run with multiple
registry combinations.
- Added unit-test coverage for the new registry implenenation.
=> HBASE-23305: Master based registry implementation

hbase-assembly/pom.xml, hbase-client/pom.xml, hbase-common/pom.xml, hbase-examples/pom.xml, hbase-external-blockcache/pom.xml, hbase-hadoop-compat/pom.xml, hbase-hadoop2-compat/pom.xml, hbase-hbtop/pom.xml, hbase-it/pom.xml, hbase-metrics-api/pom.xml, hbase-metrics/pom.xml, hbase-prefix-tree/pom.xml, hbase-procedure/pom.xml, hbase-protocol/pom.xml, hbase-rest/pom.xml, hbase-rsgroup/pom.xml, hbase-server/pom.xml, hbase-thrift/pom.xml, pom.xml
=> HBASE-23675 Move to Apache parent POM version 22

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HBaseInterClusterReplicationEndpoint.java
Defines create methods for Connection and ReplicationSinkManager instances.
=> HBASE-23683 Make HBaseInterClusterReplicationEndpoint more extensible

hbase-client/src/main/java/org/apache/hadoop/hbase/RegionLocations.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java, hbase-server/pom.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/master/webapp/MetaBrowser.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/webapp/RegionReplicaInfo.java, hbase-server/src/main/resources/hbase-webapps/master/table.jsp, hbase-server/src/test/java/org/apache/hadoop/hbase/ClearUserNamespacesAndTablesRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ConnectionRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/hamcrest/BytesMatchers.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/webapp/TestMetaBrowser.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/webapp/TestMetaBrowserNoCluster.java, pom.xml
Adds a display of the content of 'hbase:meta' to the Master's
table.jsp, when that table is selected. Supports basic pagination,
filtering, &c.
=> HBASE-23653 Expose content of meta table in web ui

hbase-client/src/main/java/org/apache/hadoop/hbase/RegionLocations.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java, hbase-server/pom.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/master/webapp/MetaBrowser.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/webapp/RegionReplicaInfo.java, hbase-server/src/main/resources/hbase-webapps/master/table.jsp, hbase-server/src/test/java/org/apache/hadoop/hbase/ClearUserNamespacesAndTablesRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ConnectionRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/hamcrest/BytesMatchers.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/webapp/TestMetaBrowser.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/webapp/TestMetaBrowserNoCluster.java, pom.xml
Adds a display of the content of 'hbase:meta' to the Master's
table.jsp, when that table is selected. Supports basic pagination,
filtering, &c.
Backport of #1020
=> Backport HBASE-23653 Expose content of meta table in web ui

hbase-checkstyle/src/main/resources/hbase/checkstyle.xml, pom.xml
Bump checkstyle version to 8.28, maven-checkstyle-plugin to 3.1.0.
As per HBASE-23242 and the updated checkstyle docs[1], the LineLength
check should be placed under an instance of Checker.
[1] https://checkstyle.sourceforge.io/config_sizes.html#LineLength
=> HBASE-23700 Upgrade checkstyle and plugin versions

hbase-checkstyle/src/main/resources/hbase/checkstyle.xml, pom.xml
Bump checkstyle version to 8.28, maven-checkstyle-plugin to 3.1.0.
As per HBASE-23242 and the updated checkstyle docs[1], the LineLength
check should be placed under an instance of Checker.
[1] https://checkstyle.sourceforge.io/config_sizes.html#LineLength
Co-authored-by: Bharath Vissapragada <bharathv@apache.org>
=> HBASE-23700 Upgrade checkstyle and plugin versions (#1056)

hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml, hbase-common/src/main/java/org/apache/hadoop/hbase/CellComparator.java, hbase-common/src/main/java/org/apache/hadoop/hbase/net/Address.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/SpanReceiverHost.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteRangeUtils.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/ConcatenatedLists.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/Order.java
=> HBASE-23622 Reduced the number of Checkstyle violations in hbase-common

hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml, hbase-common/src/main/java/org/apache/hadoop/hbase/net/Address.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteRangeUtils.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java
Based on the feedback from Sean on #1034.
=> HBASE-23686 Revert binary incompatible change in ByteRangeUtils and removed reflections in CommonFSUtils

hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/HBaseRESTTestingUtility.java, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/PerformanceEvaluation.java, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/RowResourceBase.java, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestMultiRowResource.java, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestScannersWithFilters.java
=> HBASE-23646 Resolved remaining Checkstyle violations in tests of hbase-rest

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSource.java
https://issues.apache.org/jira/browse/HBASE-23254
=> HBASE-23254 Release replication buffer quota correctly, when batch includes bulk loaded hfiles

hbase-client/src/main/java/org/apache/hadoop/hbase/security/provider/SaslClientAuthenticationProviders.java, hbase-client/src/test/java/org/apache/hadoop/hbase/security/provider/TestSaslClientAuthenticationProviders.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/webapp/MetaBrowser.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/provider/SaslServerAuthenticationProviders.java
=> HBASE-23347 Allow custom authentication methods for RPCs; addendum

hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml, hbase-common/src/test/java/org/apache/hadoop/hbase/TestKeyValue.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestTimeout.java, hbase-common/src/test/java/org/apache/hadoop/hbase/Waiter.java, hbase-common/src/test/java/org/apache/hadoop/hbase/types/TestCopyOnWriteMaps.java
=> HBASE-23645 Fixed remaining Checkstyle violations in hbase-common tests

pom.xml
caffeine: 2.6.2 => 2.8.1
commons-codec: 1.10 => 1.13
commons-io: 2.5 => 2.6
disrupter: 3.3.6 => 3.4.2
httpclient: 4.5.3 => 4.5.11
httpcore: 4.4.6 => 4.4.13
jackson: 2.9.10 => 2.10.1
jackson.databind: 2.9.10.1 => 2.10.1
jetty: 9.3.27.v20190418 => 9.3.28.v20191105
jruby: 9.1.17.0 => 9.2.9.0
protobuf.plugin: 0.5.0 => 0.6.1
zookeeper: 3.4.10 => 3.4.14
slf4j: 1.7.25 => 1.7.30
rat: 0.12 => 0.13
asciidoctor: 1.5.5 => 1.5.8.1
asciidoctor.pdf: 1.5.0-alpha.15 => 1.5.0-rc.2
error-prone: 2.3.3 => 2.3.4
=> HBASE-23069 periodic dependency bump for Sep 2019

hbase-common/src/test/java/org/apache/hadoop/hbase/ClassFinder.java, hbase-common/src/test/java/org/apache/hadoop/hbase/HBaseCommonTestingUtility.java, hbase-common/src/test/java/org/apache/hadoop/hbase/ResourceChecker.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestCellUtil.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestClassFinder.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestHBaseConfiguration.java, hbase-common/src/test/java/org/apache/hadoop/hbase/codec/TestCellCodecWithTags.java, hbase-common/src/test/java/org/apache/hadoop/hbase/codec/TestKeyValueCodecWithTags.java, hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/TestEncryption.java, hbase-common/src/test/java/org/apache/hadoop/hbase/util/RedundantKVGenerator.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
=> HBASE-23621 Reduced the number of Checkstyle violations in tests of hbase-common

hbase-common/src/test/java/org/apache/hadoop/hbase/HBaseClassTestRule.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestHBaseClassTestRule.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
There were a couple of issues.
- There was a leak of a file descriptor for hbck lock file. This
was contributing to all the "ConnectionRefused" stack traces since
it was trying to renew lease for an already expired mini dfs cluster.
This issue was there for a while, just that we noticed it now.
- After upgrade to JUnit 4.13, it looks like the behavior for test
timeouts has changed. Earlier the timeout seems to have applied for
each parameterized run, but now it looks like it is applied across
all the runs.
This patch fixes both the issues.
=> HBASE-23731: De-flake TestFromClientSide

hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionReplayEvents.java
New, smaller try as in #477. Not removing everything at once this time.
=> HBASE-23738 Removed deprecated createLocalHRegion from HBaseTestingUtility

hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/zookeeper/ZNodePaths.java, hbase-protocol-shaded/src/main/protobuf/Master.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/ActiveMasterManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/CachedClusterId.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MetaRegionLocationCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestCachedClusterId.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaRegionLocationCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestActiveMasterManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestClientMetaServiceRPCs.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestCloseAnOpeningRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestClusterRestartFailover.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionsRecoveryConfigManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestShutdownBackupMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestOpenRegionProcedureBackoff.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestOpenRegionProcedureHang.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRegionAssignedToMultipleRegionServers.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestReportOnlineRegionsRace.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestReportRegionStateTransitionFromDeadServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestReportRegionStateTransitionRetry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestSCPGetRegionsRace.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestWakeUpUnexpectedProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/protobuf/TestProtobufUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerReportForDuty.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationProcedureRetry.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MetaTableLocator.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
This patch implements the RPCs needed for the meta information
lookup during connection init. New tests added to cover the RPC
code paths. HBASE-23305 builds on this to implement the client
side logic.
Fixed a bunch of checkstyle nits around the places the patch
touches.
=> HBASE-23304: RPCs needed for client meta information lookup (apache#904)

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSideWithCoprocessor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestSnapshotScannerHDFSAclController.java, hbase-server/src/test/java/org/apache/hadoop/hbase/security/provider/TestCustomSaslAuthenticationProvider.java
TestFromClientSideWithCoprocessor: Initialization bug causing parameterized
runs to fail.
TestCustomSaslAuthenticationProvider: Test config had to be fixed because
it was written pre-master registry implementation.
=> HBASE-23752: Fix remaining test failures from nightly runs

dev-support/hbase-personality.sh
I saw this over on
https://builds.apache.org/view/H-L/view/HBase/job/HBase%20Nightly/job/branch-2/2447/console. Looks
like we need to bump the memory allocation for maven. I wonder if this
is the underlying cause of HBASE-22470.
```
6:38:47  ============================================================================
16:38:47  ============================================================================
16:38:47                                Finished build.
16:38:47  ============================================================================
16:38:47  ============================================================================
16:38:47
16:38:47
Post stage
[Pipeline] stash
16:38:48  Warning: overwriting stash 'hadoop2-result'
16:38:48  Stashed 1 file(s)
[Pipeline] junit
16:38:48 …
```
=> HBASE-23793 Increase maven heap allocation to 4G in Yetus personality

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshotNoCluster.java
1. Survive flakey rerunning by converting the static BeforeClass stuff
into instance-level Before.
2. Break the test method into two, one for running over each of the
snapshot manifest versions.
=> HBASE-23792 [Flakey Test] TestExportSnapshotNoCluster.testSnapshotWithRefsExportFileSystemState

dev-support/hbase-personality.sh, pom.xml, src/main/asciidoc/_chapters/developer.adoc
Set the fork count for first and second parts to be 0.75C. Add a bit of
doc too on this as well as some qualification on our test categories.
=> HBASE-23779 Up the default fork count; make count relative to CPU count

hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestDeadServerMetricRegionChore.java
(cherry picked from commit 24823ecfc9ddc9bbb473657d2ccf73cbd971ee2b)
=> HBASE-23682 Fix NPE when disable DeadServerMetricRegionChore (#1026)

hbase-client/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionStates.java
https://issues.apache.org/jira/browse/HBASE-23693
=> HBASE-23693 Split failure may cause region hole and data loss when use zk assign

hbase-client/src/main/java/org/apache/hadoop/hbase/client/MasterRegistry.java, hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/DNS.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/DateTieredCompactionPolicy.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/RatioBasedCompactionPolicy.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMasterRegistry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MockHStoreFile.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerHostname.java
Master rpc server end point doesn't always bind to localhost when a
specific end point is configured. It looks up the hostname and
binds to the endpoint to which it resolves. MasterRegistry should
do the same when building the default server end point to talk to.
=> HBASE-23804: Fix default master addr hostname in master registry

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshotV1NoCluster.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshotV2NoCluster.java
ADDENDUM: Break test in two to see if it makes it more reliable.
=>  HBASE-23816 [Flakey Test] TestExportSnapshotNoCluster.testSnapshotV2WithRefsExportFileSystemState(TestExportSnapshotNoCluster.java:91) Wrong FS!

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionFileSystem.java
In CommonFSUtils's ` invokeSetStoragePolicy(final FileSystem fs, final Path path,
final String storagePolicy)`, we invoke the setStoragePolicy by the following:
```java
m = fs.getClass().getDeclaredMethod("setStoragePolicy",
new Class<?>[] { Path.class, String.class });
...
m.invoke(fs, path, storagePolicy);
```
When the call is initiated by HRegionFileSystem and fs is HFileSystem, `m.invoke(fs, path, storagePolicy)`repeats the same function call `setStoragePolicy(final FileSystem fs, final Path path,
final String storagePolicy)` with underneath file system. 
We can avoid this duplicate calls by checking in advance if the file system for HRegionFileSystem is HFileSystem call the setStoragePolicy with the underneath fs.
=> HBASE-21776: Avoid duplicate calls to setStoragePolicy which shows up in debug Logging

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/main/ruby/shell/commands.rb, hbase-shell/src/main/ruby/shell/commands/merge_region.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
* mergeRegionsAsync with two regions as parameters, to be deprecated since 2.3.0 and removed from 4.0
* merge_region shell command syntax changed (as it goes into minor release & major release i.e. 2.3.0, 3.0.0). It now supports multiple region merge.
=> HBASE-22827 Expose multi-region merge in shell and Admin API

hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStates.java
This is my first PR using github.
If something is wrong. please let me know.
=> HBASE-23561 Look up of Region in Master by encoded region name is O(n)

hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestSnapshotFromMaster.java
Backport HBASE-23658 - Fix flaky TestSnapshotFromMaster
(cherry picked from commit 25654df98b939f077cb8e06f46c9c28705f86b84)
Signed-off-by: Guanghao Zhang <zghaobac@gmail.com>
=> HBASE-23862 Fix flaky TestSnapshotFromMaster in 1.x versions

dev-support/jenkins_precommit_jira_yetus.sh
Two commits which I will squash after review
1. copy-paste the existing script from the [Jenkins job configuration](https://builds.apache.org/view/H-L/view/HBase/job/PreCommit-HBASE-Build/configure)
1. address the shellcheck complaints
Step 3 will be to clean it up to match more closely the GitHub version. Would be great if they could be merged into one script, or at least two scripts with a common library of functions for building the Yetus invocation params list.
=> HBASE-23874 Move Jira-attached file precommit definition from script in Jenkins config to dev-support

.editorconfig, dev-support/Jenkinsfile, dev-support/Jenkinsfile_GitHub, dev-support/docker/Dockerfile, dev-support/hbase-personality.sh, dev-support/hbase_nightly_yetus.sh, dev-support/jenkins_precommit_github_yetus.sh
This PR provides changes necessary to run JDK11 checks during nightlies. It depends on HBASE-23767/#1183.
=> HBASE-23876 Add JDK11 compilation and unit test support to nightly job

dev-support/Dockerfile, dev-support/create-release/hbase-rm/Dockerfile, dev-support/hbase_docker/Dockerfile
With this patch, `find . -iname '*Dockerfile*' -exec hadolint {} +` reports nothing. Let's see what buildbot says.
=> HBASE-23945 Dockerfiles showing hadolint check failures

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/AbstractRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestMergeNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
- consolidate checks made by master on behalf of balancer and
normalizer: deciding if the master is in a healthy state for
running any actions at all (skipRegionManagementAction). Normalizer
now does as balancer did previously.
- both balancer and normalizer make one final check on above
conditions between calculating an action plan and executing the
plan. should make the process more responsive to shutdown
requests.
- change normalizer to only consider acting on a region when it is in
the OPEN state. previously we would normalizer attempt to merge a
region that was already in a MERGING_NEW,MERGING,MERGED state.
- fix some typos in variable names.
=> HBASE-23932 Minor improvements to Region Normalizer

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/AbstractRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestMergeNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
- consolidate checks made by master on behalf of balancer and
normalizer: deciding if the master is in a healthy state for
running any actions at all (skipRegionManagementAction). Normalizer
now does as balancer did previously.
- both balancer and normalizer make one final check on above
conditions between calculating an action plan and executing the
plan. should make the process more responsive to shutdown
requests.
- change normalizer to only consider acting on a region when it is in
the OPEN state. previously we would normalizer attempt to merge a
region that was already in a MERGING_NEW,MERGING,MERGED state.
- fix some typos in variable names.
Signed-off-by: binlijin <binlijin@gmail.com>
=> Back-port "HBASE-23932 Minor improvements to Region Normalizer (#1258)" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStates.java
- `computeIfAbsent` not guaranteed to be applied once atomically. therefore they can have a different value.
- I should acquire a lock before update two maps.
=> HBASE-23561 acquire lock before update regionsMap

dev-support/docker/Dockerfile, dev-support/hbase_docker/Dockerfile
=> Backport "HBASE-23978 Dockerfiles reusing stale apt sources info" to branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaSettings.java
In QuotaSettings，the method of sizeToString reserved integer. But, this is not very accurate.
`hbase(main):001:0> set_quota TYPE => SPACE, TABLE => 't1', LIMIT => '2000G', POLICY => NO_INSERTS
hbase(main):002:0> list_quotas
OWNER                                    QUOTAS                                                                                                              
TABLE => t1                             TYPE => SPACE, TABLE => t1, LIMIT => 1T, VIOLATION_POLICY => NO_INSERTS                                             
1 row(s) in 0.0340 seconds`
after patch：
`hbase(main):001:0> set_quota TYPE => SPACE, TABLE => 't1', LIMIT => '2000G', POLICY => NO_INSERTS
hbase(main):002:0> list_quotas
OWNER                                    QUOTAS …
=> HBASE-23967 Improve the accuracy of the method sizeToString

hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestFutureUtils.java, hbase-hadoop2-compat/pom.xml, hbase-http/src/test/java/org/apache/hadoop/hbase/http/log/TestLogLevel.java, hbase-shaded/hbase-shaded-check-invariants/pom.xml, hbase-shaded/hbase-shaded-with-hadoop-check-invariants/pom.xml, pom.xml
Making progress here. `-Dhadoop.profile=3.0` is required. Current issues include:
- `TestBackupSmallTests` fails due to HADOOP-15775.
- can't build vs. Hadoop 3.3.0-SNAPSHOT due to HBASE-23833.
=> HBASE-23829 Get `-PrunSmallTests` passing on JDK11

hbase-examples/src/test/java/org/apache/hadoop/hbase/coprocessor/example/TestZooKeeperScanPolicyObserver.java, hbase-replication/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStateBasic.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestZKConnectionRegistry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationProcedureRetry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestCanaryTool.java, hbase-shell/src/test/ruby/hbase/replication_admin_test.rb, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MiniZooKeeperCluster.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestReadOnlyZKClient.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKMainServer.java
hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MiniZooKeeperCluster.java
Have client and server use loopback instead of 'localhost'
=> HBASE-23993 Use loopback for zk standalone server in minizkcluster

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactionTool.java
Do not overwrite the hbase-site.xml which is being used by other tests.
=> HBASE-23999 [flakey test] TestTableOutputFormatConnectionExhaust

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminServer.java
HBASE-24019: Correct exception messages for table null and namespace unavailable.
=> HBASE-24019: Correct exception messages for table null and namespace unavailable.

pom.xml
Does what it says on the tin. Bound to `initialize` phase so that it
runs early in lifecycle. Uses `<inherited>false</inherited>` so that
the plugin will run only for the base pom's reactor stage and not for
any children.
=> HBASE-23980 Use enforcer plugin to print JVM info in maven output

pom.xml
Does what it says on the tin. Bound to `initialize` phase so that it
runs early in lifecycle. Uses `<inherited>false</inherited>` so that
the plugin will run only for the base pom's reactor stage and not for
any children.
=> Backport "HBASE-23980 Use enforcer plugin to print JVM info in maven output" to branch-2

pom.xml
Does what it says on the tin. Bound to `initialize` phase so that it
runs early in lifecycle. Uses `<inherited>false</inherited>` so that
the plugin will run only for the base pom's reactor stage and not for
any children.
=> Backport "HBASE-23980 Use enforcer plugin to print JVM info in maven output" to branch-2.3

pom.xml
Does what it says on the tin. Bound to `initialize` phase so that it
runs early in lifecycle. Uses `<inherited>false</inherited>` so that
the plugin will run only for the base pom's reactor stage and not for
any children.
=> Backport "HBASE-23980 Use enforcer plugin to print JVM info in maven output" to branch-1

dev-support/hbase-personality.sh
This implementation is almost surely incorrect. Personality
initialization parses the `--hadoop-profile` argument and sets
`HADOOP_PROFILE`. That value is then used to build an `extras` value
that is passed  along to module initialization. I'm guessing that the
`extras` value need to be honored down in the shadedjars module. I'm
not clear on how to make that work (need to study the interfaces at
play here), so taking the more ham-handed approach of referring to
`HADOOP_PROFILE`. I'm not sure if this will even work, or if it will
only work because the `foo_yetus.sh` scripts happen to use a variable
of the same name.
=> HBASE-24002 shadedjars check does not propagate --hadoop-profile

dev-support/hbase-personality.sh
This implementation is almost surely incorrect. Personality
initialization parses the `--hadoop-profile` argument and sets
`HADOOP_PROFILE`. That value is then used to build an `extras` value
that is passed  along to module initialization. I'm guessing that the
`extras` value need to be honored down in the shadedjars module. I'm
not clear on how to make that work (need to study the interfaces at
play here), so taking the more ham-handed approach of referring to
`HADOOP_PROFILE`. I'm not sure if this will even work, or if it will
only work because the `foo_yetus.sh` scripts happen to use a variable
of the same name.
=> Backport "HBASE-24002 shadedjars check does not propagate --hadoop-profile" to branch-2

dev-support/hbase-personality.sh
This implementation is almost surely incorrect. Personality
initialization parses the `--hadoop-profile` argument and sets
`HADOOP_PROFILE`. That value is then used to build an `extras` value
that is passed  along to module initialization. I'm guessing that the
`extras` value need to be honored down in the shadedjars module. I'm
not clear on how to make that work (need to study the interfaces at
play here), so taking the more ham-handed approach of referring to
`HADOOP_PROFILE`. I'm not sure if this will even work, or if it will
only work because the `foo_yetus.sh` scripts happen to use a variable
of the same name.
=> Backport "HBASE-24002 shadedjars check does not propagate --hadoop-profile" to branch-2.3

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/FSDataInputStreamWrapper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerMetrics.java, src/main/asciidoc/_chapters/schema_design.adoc
Expose file system level read metrics for RegionServer.
If the HBase RS runs on top of HDFS, calculate the aggregation of
ReadStatistics of each HdfsFileInputStream. These metrics include:
(1) total number of bytes read from HDFS.
(2) total number of bytes read from local DataNode.
(3) total number of bytes read locally through short-circuit read.
(4) total number of bytes read locally through zero-copy read.
Because HDFS ReadStatistics is calculated per input stream, it is not
feasible to update the aggregated number in real time. Instead, the
metrics are updated when an input stream is closed.
=> HBASE-8868. add metric to report client shortcircuit reads.

dev-support/adhoc_run_tests/adhoc_run_tests.sh
I think this shouldn't break the associated jenkins job, but...
=> HBASE-24045 Support setting `-Dhadoop.profile` in adhoc_run_tests.sh

dev-support/adhoc_run_tests/adhoc_run_tests.sh
=> Backport "HBASE-24045 Support setting `-Dhadoop.profile` in adhoc_run_tests.sh" to branch-1

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableMapReduceUtil.java
Branch-2.1 did not move to thirdparty GSON in HBASE-20587 so Jackson dependencies need to stay.
=> HBASE-24057 Add modules to mapreduce job classpaths

pom.xml
Minor tweaks required to get passing runs of `-PrunLargeTests`.
* Minimum Hadoop version is 3.2.0 due to [HADOOP-12760](https://issues.apache.org/jira/browse/HADOOP-12760).
* JDK11 looks like it consumes more memory than JDK8, so failures due to OOME see more common here. Bumping heap allocated to surefire forks allows better pass rate.
=> HBASE-24007 Get `-PrunLargeTests` passing on JDK11

pom.xml
Minor tweaks required to get passing runs of `-PrunLargeTests`.
* Minimum Hadoop version is 3.2.0 due to
[HADOOP-12760](https://issues.apache.org/jira/browse/HADOOP-12760).
* JDK11 looks like it consumes more memory than JDK8, so failures due
to OOME see more common here. Bumping heap allocated to surefire
forks allows better pass rate.
=> Backport "HBASE-24007 Get `-PrunLargeTests` passing on JDK11 (#1351)" to branch-2

pom.xml
Minor tweaks required to get passing runs of `-PrunLargeTests`.
* Minimum Hadoop version is 3.2.0 due to
[HADOOP-12760](https://issues.apache.org/jira/browse/HADOOP-12760).
* JDK11 looks like it consumes more memory than JDK8, so failures due
to OOME see more common here. Bumping heap allocated to surefire
forks allows better pass rate.
=> Backport "HBASE-24007 Get `-PrunLargeTests` passing on JDK11 (#1351)" to branch-2.3

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RSProcedureDispatcher.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterShutdown.java
Add check for stopped server at a few more points in Master startup.
Defend against NPE in RSProcedureDispatcher; log and retun instead.
=> HBASE-24052 Add debug+fix to TestMasterShutdown

dev-support/hbase-personality.sh
Without patch, the spotbugs results include warnings for inapplicable
modules:
```
+---------------------------------------------------------------------------
|      |                |            | Compile Tests
+---------------------------------------------------------------------------
|   0  |        mvndep  |   0m 11s   | Maven dependency ordering
|  +1  |    mvninstall  |   2m 47s   | the source passed
|   0  |      spotbugs  |   0m 11s   | branch/hbase-annotations no spotbugs
|      |                |            | output file (spotbugsXml.xml)
|   0  |      spotbugs  |   0m 14s   | branch/hbase-assembly no spotbugs output
|      |                |            | file (spotbugsXml.xml)
|   0  |      spotbugs  |   0m 07s   |
|      |                |            | …
```
=> HBASE-24078 SpotBugs check automatically skip inapplicable modules

dev-support/hbase-personality.sh
* HBASE-20467 Precommit personality should only run checkstyle once if we're going to run it at the root.
* HBASE-24078 SpotBugs check automatically skip inapplicable modules
HBASE-20467 is a good thing to have for PR builds, and is a prerequisite of the checkstyle cleanup performed in HBASE-24078.
=> Backport HBASE-20467 and HBASE-24078 to branch-2

dev-support/hbase-personality.sh
* HBASE-20467 Precommit personality should only run checkstyle once if we're going to run it at the root.
* HBASE-24078 SpotBugs check automatically skip inapplicable modules
HBASE-20467 is a good thing to have for PR builds, and is a prerequisite of the checkstyle cleanup performed in HBASE-24078.
=> Backport HBASE-20467 and HBASE-24078 to branch-2.3

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterWrapper.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/CachedClusterId.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterWrapperImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestCachedClusterId.java
JMXCacheBuster resets the metrics state at various points in time. These
events can potentially race with a master shutdown. When the master is
tearing down, metrics initialization can touch a lot of unsafe state,
for example invalidated FS objects. To avoid this, this patch makes
the getMetrics() a no-op when the master is either stopped or in the
process of shutting down. Additionally, getClusterId() when the server
is shutting down is made a no-op.
Simulating a test for this is a bit tricky but with the patch I don't
locally see the long stacktraces from the jira.
(cherry picked from commit 6f213e9d5a15afcc40b6562ab4898f913cec91eb)
=> HBASE-24075: Fix a race between master shutdown and metrics (re)init

dev-support/Jenkinsfile
Links going back to JIRA look like
```
For more information [see jdk8 (hadoop2) report|https://builds.apache.org/job/HBase%20Nightly/job/branch-2/2574//JDK8_Nightly_Build_Report_(Hadoop2)/]
```
But the actual URL to this report is `https://builds.apache.org/job/HBase%20Nightly/job/branch-2/2574/JDK8_20Nightly_20Build_20Report_20_28Hadoop2_29/`
=> HBASE-24092 Fix links to build reports generated by nightly job

dev-support/Jenkinsfile, dev-support/Jenkinsfile_GitHub
=> Backport "HBASE-24071 [JDK11] Remove `unit` filter from nightly and precommit jobs" to branch-2

dev-support/Jenkinsfile, dev-support/Jenkinsfile_GitHub
=> Backport "HBASE-24071 [JDK11] Remove `unit` filter from nightly and precommit jobs" to branch-2.3

hbase-server/src/main/java/org/apache/hadoop/hbase/io/FSDataInputStreamWrapper.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/TestFSDataInputStreamWrapper.java
If you have an inherited parent class that implements CanUnbuffer instead of directly implementing CanUnbuffer, you cannot get unbuffer.Differences between the old and new methods can be found in UT.
=> HBASE-24051 Allows indirect inheritance to CanUnbuffer

hbase-assembly/src/main/assembly/hadoop-two-compat.xml
Simply cleanup the whitespace and readability of these include, exclude lists before making any subsequent changes. To be squished into the subsequent commit on merge.
After HBASE-23986, running on JDK8/Hadoop2 from the binary tarball
results in
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:149)
at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3062)
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at …
```
=> HBASE-24084 Fix missing jdk8 dependencies in hbase-assembly/hadoop-two-compat

hbase-assembly/src/main/assembly/hadoop-two-compat.xml
After HBASE-23986, running on JDK8/Hadoop2 from the binary tarball
results in
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:149)
at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3062)
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 2 more
```
The missing class is from `com.fasterxml.woodstox:woodstox-core`. This
and `org.codehaus.woodstox:stax2-api` are explicit dependencies of …
=> Backport "HBASE-24084 Fix missing jdk8 dependencies in hbase-assembly/hadoop-two-compat" to branch-2

hbase-assembly/src/main/assembly/hadoop-two-compat.xml
After HBASE-23986, running on JDK8/Hadoop2 from the binary tarball
results in
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:149)
at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:3062)
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 2 more
```
The missing class is from `com.fasterxml.woodstox:woodstox-core`. This
and `org.codehaus.woodstox:stax2-api` are explicit dependencies of …
=> Backport "HBASE-24084 Fix missing jdk8 dependencies in hbase-assembly/hadoop-two-compat" to branch-2.3

src/main/asciidoc/_chapters/getting_started.adoc
Updates documentation according to change in HBASE-24086 / #1408 .
=> HBASE-24106 Update getting started documentation after HBASE-24086

dev-support/HOW_TO_YETUS_LOCAL.md
Jira: https://issues.apache.org/jira/browse/HBASE-24130
=> HBASE-24130 rat plugin complains about having an unlicensed file

hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestSnapshotScannerHDFSAclController.java
There is a gap between snapshot finished and hdfs acl setup, scanSnapshot kicks in between and gets permission error.
=> HBASE-24114 [Flakey Tests] TestSnapshotScannerHDFSAclController

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogReader.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationRuntimeException.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceShipper.java
When remove peer happens, it may interrupt ReplicationSourceShipper thread.
interruptOrAbortWhenFail will throw out a RunTimeException which is not handled
and will abort Region Server. The solution is not to throw out a RunTimeException.
=> HBASE-24120 Flakey Test: TestReplicationAdminWithClusters timeout

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/FSDataInputStreamWrapper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerMetrics.java, src/main/asciidoc/_chapters/schema_design.adoc
Signed-off-by: stack <stack@apache.net>
(cherry picked from commit 4ec19096dfaa4ff5ac1e8504f44d8d0be6e2eb2c)
Conflicts:
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
=> HBASE-8868. add metric to report client shortcircuit reads. (#1334)

hbase-resource-bundle/src/main/resources/supplemental-models.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutput.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputSaslHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/ProtobufDecoder.java
I've tried a few approaches. It turns out the quickest solution to this is with Java Reflection.
(1) Create a ProtobufDecoder that is inspired by io.netty.handler.codec.protobuf.ProtobufDecoder. The original ProtobufDecoder has dependency on protobuf. Use reflection to access the shaded protobuf in HDFS when applicable.
(2) Similarly, create a private class BuilderPayloadSetter that does ByteString.copyFrom() + DataTransferEncryptorMessageProto.Builder.setPayload().
Manually tested with Hadoop 3.1.2 and 3.3.0-SNAPSHOT (on top of HBASE-22103 and HBASE-23998 and set jetty.version=9.4.20)
Please let me know if this is the acceptable approach.
=> HBASE-23833. The relocated hadoop-thirdparty protobuf breaks HBase asyncwal	

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/ServerAndLoad.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java
Based on logs needed when troubleshooting some balancer decisions.
when the log level on `StochasticLoadBalancer` is set to DEBUG messages look like this:
```
2020-04-08 09:57:39,515 DEBUG [Time-limited test] balancer.StochasticLoadBalancer$RegionCountSkewCostFunction(1196): RegionCountSkewCostFunction sees a total of 3 servers and 9 regions.
2020-04-08 09:57:39,527 DEBUG [Time-limited test] balancer.StochasticLoadBalancer(348): We need to load balance cluster; total cost=10005.833333333334, sum multiplier=10602.0; min cost/multiplier which needs balance is 0.05
```
when it is TRACE it looks like:
```
2020-04-08 10:49:48,416 DEBUG [Time-limited test] balancer.StochasticLoadBalancer$RegionCountSkewCostFunction(1196): RegionCountSkewCostFunction sees a total of 3 servers and 9 regions. …
```
=> HBASE-24138 log more details about balancer decisions for StochasticLoadBalancer

hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java
=> Backport "HBASE-24086 Disable output stream capability enforcement when running on LocalFileSystem" to branch-2.2

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
JIRA link: [HBASE-24121](https://issues.apache.org/jira/browse/HBASE-24121)
=> HBASE-24121 [Authorization] ServiceAuthorizationManager isn't dynamically updatable. And it should be

dev-support/hbase-personality.sh, dev-support/hbase_nightly_source-artifact.sh, pom.xml
Pass --threads=2 to mvn when yetus runs so some parallelism
when dependencies allow.
=> HBASE-24150 Allow module tests run in parallel

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java
CME occurred while removing the list item from the same list which is iterated in foreach loop.
Use Iterator instead and delete the list item safely.
=> HBASE-24074 ConcurrentModificationException occured in ReplicationSourceManager while refreshing the peer

dev-support/create-release/release-util.sh
Current code gives me the following; notice default values generated
for `RELEASE_VERSION` and `api_diff_tag`.
```
GIT_BRANCH [branch-2.3]:
Current branch VERSION is 2.3.0-SNAPSHOT.
RELEASE_VERSION [2.3.-1]: 2.3.0
NEXT_VERSION [2.3.0-SNAPSHOT]: 2.3.1-SNAPSHOT
RC_COUNT [0]:
GIT_REF [2.3.0RC0]:
api_diff_tag, [rel/2.2.0)]:
```
With this patch I get
```
GIT_BRANCH [branch-2.3]:
Current branch VERSION is 2.3.0-SNAPSHOT.
RELEASE_VERSION [2.3.0]:
NEXT_VERSION [2.3.1-SNAPSHOT]:
RC_COUNT [0]:
GIT_REF [2.3.0RC0]:
api_diff_tag, [rel/2.2.0]:
```
=> HBASE-24160 create-release fails to process x.y.0 version info correctly

hbase-resource-bundle/src/main/resources/supplemental-models.xml
=> HBASE-23998. Update license for jetty-client. (#1297)

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java, hbase-common/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfo.java, hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto, hbase-protocol-shaded/src/main/protobuf/server/rsgroup/RSGroupAdmin.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/DisabledRSGroupInfoManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminServiceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsAdmin1.java, hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java, hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
JIRA link: https://issues.apache.org/jira/browse/HBASE-24112
=> HBASE-24112 [RSGroup] Support renaming rsgroup

hbase-shell/src/main/ruby/hbase/security.rb, hbase-shell/src/test/ruby/hbase/security_admin_test.rb
=> [HBASE-24176]user_permission '.*' command failed to show all table permissions

hbase-protocol/src/main/java/org/apache/hadoop/hbase/protobuf/generated/RSGroupAdminProtos.java, hbase-protocol/src/main/protobuf/RSGroupAdmin.proto, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdmin.java, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminClient.java, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminServer.java, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManager.java, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java, hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsAdmin1.java, hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsBase.java, hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdminClient.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/BaseMasterAndRegionObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/BaseMasterObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestMasterObserver.java
=> [Back-port branch-1]: HBASE-24112 [RSGroup] Support renaming rsgroup

hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestAddToSerialReplicationPeer.java
Will put up a root cause analysis later.
=> HBASE-24183 [flakey test] replication.TestAddToSerialReplicationPeer

hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java
use the findPort logic even if the BindException is wrapped in an IOException
=> HBASE-24197 TestHttpServer.testBindAddress failure with latest jetty

hbase-server/src/main/java/org/apache/hadoop/hbase/util/RegionMover.java
add replicationId to RegionMover logic
=> HBASE-24186: RegionMover ignores replicationId

hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutput.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputSaslHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/ProtobufDecoder.java
Cherry pick this to branch-2. The cherrypick is clean.
=> HBASE-23833. The relocated hadoop-thirdparty protobuf breaks HBase asyncwal

bin/hbase, bin/hbase-config.sh, conf/hbase-env.sh
Per comments in Jira, be explicit about what collector we
use. Existing code simply hard-codes HBASE_OPTS in
`conf/hbase-env.sh`. We now need to be a little more clever than this,
so moves the definition into `bin/hbase`. Also consolidates logic
around JVM version detection into a reusable function.
This change also changes how we set `HBASE_OPTS`. Before, we would
accept an operator's value, but always append our GC
prescription. After this change, we defer entirely to the operator's
choice, only applying our values when they've not specified their
intentions.
=> HBASE-24143 [JDK11] Switch default garbage collector from CMS

bin/hbase, bin/hbase-config.sh, conf/hbase-env.sh
Per comments in Jira, be explicit about what collector we
use. Existing code simply hard-codes HBASE_OPTS in
`conf/hbase-env.sh`. We now need to be a little more clever than this,
so moves the definition into `bin/hbase`. Also consolidates logic
around JVM version detection into a reusable function.
This change also changes how we set `HBASE_OPTS`. Before, we would
accept an operator's value, but always append our GC
prescription. After this change, we defer entirely to the operator's
choice, only applying our values when they've not specified their
intentions.
=> Backport "HBASE-24143 [JDK11] Switch default garbage collector from CMS" to branch-2

bin/hbase, bin/hbase-config.sh, conf/hbase-env.sh
Per comments in Jira, be explicit about what collector we
use. Existing code simply hard-codes HBASE_OPTS in
`conf/hbase-env.sh`. We now need to be a little more clever than this,
so moves the definition into `bin/hbase`. Also consolidates logic
around JVM version detection into a reusable function.
This change also changes how we set `HBASE_OPTS`. Before, we would
accept an operator's value, but always append our GC
prescription. After this change, we defer entirely to the operator's
choice, only applying our values when they've not specified their
intentions.
=> Backport "HBASE-24143 [JDK11] Switch default garbage collector from CMS" to branch-2.3

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/ZKPermissionWatcher.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java
Create table is slow in large cluster when AccessController is enabled.
=> HBASE-24211: Create table is slow in large cluster when AccessController is enabled.

hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutput.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputSaslHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/ProtobufDecoder.java
…yncwal	 (#1301) (#1535)
* Use Reflection to access shaded Hadoop protobuf classes.
(cherry picked from commit a321e536989083ca3620bf2c53f12c07740bf5b0)
* Update to improve the code:
1. Added license.
2. Added more comments.
3. Wrap byte array instead of copy to make a ByteString.
4. Moved all reflection instantiation to static class loading time.
* Use LiteralByteString to wrap byte array instead of copying it.
(cherry picked from commit 72727ff9be9bc626522247aad9155938656fbfdb)
(cherry picked from commit ae3de38bedf7e0a8b418ce50c05956104b4f8621)
(cherry picked from commit b8b8e0afd494f073f6bdff8471aa53a6764b1257)
=> HBASE-24225 Backport HBASE-23833 to branch-2.2

hbase-resource-bundle/src/main/resources/supplemental-models.xml
Co-authored-by: Wei-Chiu Chuang <weichiu@apache.org>
(cherry picked from commit 5dfd0d8e0403ee3061fc316dc4d99e936063c1a4)
=> HBASE-23998. Update license for jetty-client. (#1297) (#1498)

src/site/xdoc/downloads.xml
This one should be merged at the end of April (see HBASE-24063).
=> HBASE-24171 Removed 2.1.10 from download page

hbase-it/pom.xml, hbase-it/src/test/java/org/apache/hadoop/hbase/MockHttpApiRule.java, hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/TestRESTApiClusterManager.java
Use the correct GSON API for deserializing service responses. Add
simple unit test covering a very limited selection of the overall API
surface area, just enough to ensure deserialization works.
=> Forward-port "HBASE-24274 `RESTApiClusterManager` attempts to deserialize response using serialization API" to branch-2

hbase-it/pom.xml, hbase-it/src/test/java/org/apache/hadoop/hbase/MockHttpApiRule.java, hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/TestRESTApiClusterManager.java
Use the correct GSON API for deserializing service responses. Add
simple unit test covering a very limited selection of the overall API
surface area, just enough to ensure deserialization works.
=> Backport "HBASE-24274 `RESTApiClusterManager` attempts to deserialize response using serialization API" to branch-2.2

hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestBindExceptionHandling.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftHttpServer.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftServer.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftServerCmdLine.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftSpnegoHttpFallbackServer.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftSpnegoHttpServer.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/ThriftServerRunner.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThrift2HttpServer.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThrift2ServerCmdLine.java
Refactor Thrift tests so resilient when launch of ThriftServer runs
into BindException.
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestBindExceptionHandling.java
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftHttpServer.java
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftServerCmdLine.java
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThrift2HttpServer.java
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThrift2ServerCmdLine.java
Refactor to use new ThriftServerRunner and ThriftServerSupplier
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftServer.java
Log list of existing tables on assert.
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/TestThriftSpnegoHttpFallbackServer.j …
=> HBASE-24294 [Flakey Tests] TestThriftHttpServer BindException

hbase-endpoint/src/main/protobuf/ShellExecEndpoint.proto, hbase-it/pom.xml, hbase-it/src/test/java/org/apache/hadoop/hbase/CoprocClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/HBaseClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestingUtility.java, hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/ShellExecEndpointCoprocessor.java, hbase-it/src/test/java/org/apache/hadoop/hbase/TestShellExecEndpointCoprocessor.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/MonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/util/ChaosMonkeyRunner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ClearUserNamespacesAndTablesRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ConnectionRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestAlwaysStandByHMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/webapp/TestMetaBrowser.java
Implements `ClusterManager` that relies on the new `ShellExecCoproc`
for remote shell command execution.
=> HBASE-24260 Add a ClusterManager that issues commands via coprocessor

hbase-endpoint/src/main/protobuf/ShellExecEndpoint.proto, hbase-it/pom.xml, hbase-it/src/test/java/org/apache/hadoop/hbase/CoprocClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/HBaseClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestingUtility.java, hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/ShellExecEndpointCoprocessor.java, hbase-it/src/test/java/org/apache/hadoop/hbase/TestShellExecEndpointCoprocessor.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/MonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/util/ChaosMonkeyRunner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ClearUserNamespacesAndTablesRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ConnectionRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestAlwaysStandByHMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/webapp/TestMetaBrowser.java
Implements `ClusterManager` that relies on the new
`ShellExecEndpointCoprocessor` for remote shell command execution.
=> Forwardport "HBASE-24260 Add a ClusterManager that issues commands via coprocessor" to branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/Coprocessor.java, hbase-it/pom.xml, hbase-it/src/test/java/org/apache/hadoop/hbase/CoprocClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/HBaseClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestingUtility.java, hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/ShellExecEndpointCoprocessor.java, hbase-it/src/test/java/org/apache/hadoop/hbase/TestShellExecEndpointCoprocessor.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/MonkeyFactory.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/util/ChaosMonkeyRunner.java, hbase-protocol-shaded/src/main/protobuf/test/coprocessor/ShellExecEndpoint.proto, hbase-server/src/test/java/org/apache/hadoop/hbase/ClearUserNamespacesAndTablesRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ConnectionRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestAlwaysStandByHMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/webapp/TestMetaBrowser.java
Implements `ClusterManager` that relies on the new
`ShellExecEndpointCoprocessor` for remote shell command execution.
=> Forwardport "HBASE-24260 Add a ClusterManager that issues commands via coprocessor" to master

.asf.yaml
This is an initial version of the yaml config for ASF infra
integration. We might have some hiccups in the beginning but we
can iteratively improve until the old (desired) setup is back
in place.
We will have to do separate commits for other repositories like
hbase-site etc, for now this is for the main hbase source code
repo.
=> HBASE-24261: Initial version of ASF infra integration configuration

pom.xml
(1) HBASE-24170 removed hadoop-2.0 profile and hadoop.guava.version is therefore not used afterwards.
(2) set netty.hadoop.version default to 3.10.5.Final which is set in the default hadoop-3.0 profile.
=> HBASE-24238 Clean up root pom after removing hadoop-2.0 profile

hbase-server/src/main/java/org/apache/hadoop/hbase/mob/DefaultMobStoreCompactor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/CloseChecker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/Compactor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/mob/FaultyMobStoreCompactor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompaction.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestCloseChecker.java
The compaction check that the system is stopped when it reaches hbase.hstore.close.check.interval (size) or hbase.hstore.close.check.time.interval (time)
> https://issues.apache.org/jira/browse/HBASE-23968
=> HBASE-23968 Periodically check whether a system stop is requested in compaction by time.

hbase-archetypes/hbase-shaded-client-project/pom.xml, hbase-client/pom.xml, hbase-endpoint/pom.xml, hbase-examples/pom.xml, hbase-hadoop2-compat/pom.xml, hbase-http/pom.xml, hbase-it/pom.xml, hbase-mapreduce/pom.xml, hbase-rest/pom.xml, hbase-rsgroup/pom.xml, hbase-server/pom.xml, hbase-shaded/hbase-shaded-mapreduce/pom.xml, hbase-shaded/hbase-shaded-testing-util/pom.xml, hbase-shell/pom.xml, hbase-testing-util/pom.xml, hbase-thrift/pom.xml
Exclude transitive includes of jax-rs 1.x and then
explicitly include jax-rs 2.x glassfish impl for REST
context when hadoop3.
=> HBASE-24284 [h3/jdk11] REST server won't start

hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
https://stackoverflow.com/a/28870635 claims nio is more reliable than the old `File` API, so try that instead.
=> HBASE-23976 Use nio for file manipulation in TestVerifyBucketCacheFile

hbase-client/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/GCMultipleMergedRegionsProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMetaFixer.java
It addresses couple issues:
1. Make sure deleteMergeQualifiers() does not delete the row if there is no columns with "merge" keyword.
2. GCMulitpleMergedRegionsProcedure now acquire an exclusive lock on the child region.
=> HBASE-24316 GCMulitpleMergedRegionsProcedure is not idempotent

hbase-client/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/GCMultipleMergedRegionsProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMetaFixer.java
It addresses couple issues:
1. Make sure deleteMergeQualifiers() does not delete the row if there is no columns with "merge" keyword.
2. GCMulitpleMergedRegionsProcedure now acquire an exclusive lock on the child region.
=> Backport: HBASE-24316 GCMulitpleMergedRegionsProcedure is not idempotent (#1660)

hbase-client/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/ZKPermissionWatcher.java
HBASE-24211: [Addendum] Create table is slow in large cluster when AccessController is enabled.
=> HBASE-24211: [Addendum] Create table is slow in large cluster when AccessController is enabled.

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterShutdown.java
```
2020-05-08 07:48:32,831 WARN  [RPCClient-NioEventLoopGroup-6-17] client.AsyncRpcRetryingCaller(171): Get async master stub failed, tries = 15, maxAttempts = 15, timeout = 1200000 ms, time elapsed = 109017 ms
org.apache.hadoop.hbase.exceptions.MasterRegistryFetchException: Exception making rpc to masters [asf904.gq1.ygridcore.net,42533,-1]
at org.apache.hadoop.hbase.client.MasterRegistry.lambda$groupCall$1(MasterRegistry.java:213)
at org.apache.hadoop.hbase.util.FutureUtils.lambda$addListener$0(FutureUtils.java:68)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
at …
```
=> HBASE-24327 : Handle shutdown() if master cannot be contacted

hbase-common/src/main/resources/hbase-default.xml
Updated default value hbase.hstore.compaction.min to null
With this change if user uses old key "hbase.hstore.compactionThreshold", then it will take effect. If user doesn't define any then default value of null, will result in 3 for minFilesToComapct, which is expected.
=> HBASE-23832 Old config hbase.hstore.compactionThreshold is ignored

hbase-common/src/main/java/org/apache/hadoop/hbase/io/ByteBufferPool.java
maxPoolSize should be logged as a plain number.
Raising PR#1483 again for QA run.
=> HBASE-24165 maxPoolSize is logged incorrectly in ByteBufferPool

.gitignore, conf/hbase-site.xml, hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java, src/main/asciidoc/_chapters/getting_started.adoc
Simplify the new user experience shipping a configuration that enables
a fresh checkout or tarball distribution to run in standalone mode
without direct user configuration. This change restores the behavior
we had when running on Hadoop 2.8 and earlier.
Patch for master includes an update to the book. This change will be
omitted when backporting to earlier branches.
=> HBASE-24271 Set values in `conf/hbase-site.xml` that enable running on `LocalFileSystem` out of the box

hbase-client/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java, hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStateStore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/webapp/RegionReplicaInfo.java, hbase-server/src/main/resources/hbase-webapps/master/table.jsp, hbase-server/src/main/resources/hbase-webapps/static/css/hbase.css
https://issues.apache.org/jira/browse/HBASE-23969
The code was based on #1485 The conflict in `table.jsp` between `master` and `branch-2` mainly comes from Java/HTML indentation. So this PR is update following the `branch-2` indentation.
=> HBASE-23969 Meta browser should show all `info` columns

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/Action.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RollingBatchRestartRsAction.java
`RollingBatchRestartRsAction` doesn't handle failure cases when
tracking its list of dead servers. The original author believed that a
failure to restart would result in a retry. However, by removing the
dead server from the failed list, that state is lost, and retry never
occurs. Because this action doesn't ever look back to the current
state of the cluster, relying only on its local state for the current
action invocation, it never realizes the abandoned server is still
dead. Instead, be more careful to only remove the dead server from the
list when the `startRs` invocation claims to have been successful.
=> HBASE-24360 RollingBatchRestartRsAction loses track of dead servers

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/Action.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RollingBatchRestartRsAction.java
`RollingBatchRestartRsAction` doesn't handle failure cases when
tracking its list of dead servers. The original author believed that a
failure to restart would result in a retry. However, by removing the
dead server from the failed list, that state is lost, and retry never
occurs. Because this action doesn't ever look back to the current
state of the cluster, relying only on its local state for the current
action invocation, it never realizes the abandoned server is still
dead. Instead, be more careful to only remove the dead server from the
list when the `startRs` invocation claims to have been successful.
=> forwardport "HBASE-24360 RollingBatchRestartRsAction loses track of dead servers" to branch-2

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/Action.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RollingBatchRestartRsAction.java
`RollingBatchRestartRsAction` doesn't handle failure cases when
tracking its list of dead servers. The original author believed that a
failure to restart would result in a retry. However, by removing the
dead server from the failed list, that state is lost, and retry never
occurs. Because this action doesn't ever look back to the current
state of the cluster, relying only on its local state for the current
action invocation, it never realizes the abandoned server is still
dead. Instead, be more careful to only remove the dead server from the
list when the `startRs` invocation claims to have been successful.
=> Forward-port "HBASE-24360 RollingBatchRestartRsAction loses track of dead servers" to master

hbase-it/src/test/java/org/apache/hadoop/hbase/HBaseClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java
* sometimes API calls return with null/empty response bodies. thus,
wrap all API calls in a retry loop.
* calls that submit work in the form of "commands" now retrieve the
commandId from successful command submission, and track completion
of that command before returning control to calling context.
* model CM's process state and use that model to guide state
transitions more intelligently. this guards against, for example,
the start command failing with an error message like "Role must be
stopped".
* improvements to logging levels, avoid spamming logs with the
side-effects of retries at this and higher contexts.
* include references to API documentation, such as it is.
=> HBASE-24361 Make `RESTApiClusterManager` more resilient

hbase-it/src/test/java/org/apache/hadoop/hbase/HBaseClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java
* sometimes API calls return with null/empty response bodies. thus,
wrap all API calls in a retry loop.
* calls that submit work in the form of "commands" now retrieve the
commandId from successful command submission, and track completion
of that command before returning control to calling context.
* model CM's process state and use that model to guide state
transitions more intelligently. this guards against, for example,
the start command failing with an error message like "Role must be
stopped".
* improvements to logging levels, avoid spamming logs with the
side-effects of retries at this and higher contexts.
* include references to API documentation, such as it is.
=> Forward-port" HBASE-24361 Make `RESTApiClusterManager` more resilient (#1701)" to branch-2

hbase-it/src/test/java/org/apache/hadoop/hbase/HBaseClusterManager.java, hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java
* sometimes API calls return with null/empty response bodies. thus,
wrap all API calls in a retry loop.
* calls that submit work in the form of "commands" now retrieve the
commandId from successful command submission, and track completion
of that command before returning control to calling context.
* model CM's process state and use that model to guide state
transitions more intelligently. this guards against, for example,
the start command failing with an error message like "Role must be
stopped".
* improvements to logging levels, avoid spamming logs with the
side-effects of retries at this and higher contexts.
* include references to API documentation, such as it is.
=> Forward-port "HBASE-24361 Make `RESTApiClusterManager` more resilient (#1701)" to master

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableSnapshotInputFormatImpl.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableSnapshotInputFormat.java
In some scenario , We want to  scan limited rows on each InputSplit for sampling data extraction
=> HBASE-24387 TableSnapshotInputFormatImpl support row limit on each InputSplit

hbase-examples/README.txt, hbase-examples/src/main/cpp/DemoClient.cpp, hbase-examples/src/main/cpp/gen-cpp/Hbase.cpp, hbase-examples/src/main/cpp/gen-cpp/Hbase.h, hbase-examples/src/main/cpp/gen-cpp/Hbase_server.skeleton.cpp
Changed boost::shared_ptr to std::shared_ptr for compatibility with apache thrift v0.13.
=> HBASE-24434 Fix building cpp-example DemoClient

src/main/asciidoc/_chapters/schema_design.adoc
The current wording gives an impression the session timeout range
on the ZK side is forced to be in the range [2 * tickTime, 20 * tickTime].
This range is configurable on the ZK service side using minSessionTimeout
and maxSessionTimeout. Clarified that.
=> HBASE-22700 (addendum): Clarify ZK session timeout doc

conf/log4j.properties
We don't have a section in the book on configuring logging, so I left it as comments in `conf/log4j.properties`.
=> HBASE-24343 Document how to configure the http request log

hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompaction.java
Polling of active compaction count is racy. Tightened the asserts
to be more reliable.
=> HBASE-24479: Deflake TestCompaction#testStopStartCompaction

src/main/asciidoc/_chapters/configuration.adoc, src/main/asciidoc/_chapters/upgrading.adoc
Add a note to the 2.3 upgrade section regarding the ZooKeeper version
bump and include a link off to ZooKeeper's FAQ.
=> HBASE-24488 Update docs re: ZooKeeper compatibility of 2.3.x release

src/main/asciidoc/_chapters/configuration.adoc
Trying to make doc changes is pretty awful, with lines running on for
hundreds of columns. At least for this time, clean up with line breaks
where asciidoc will let us.
=> HBASE-24494 Wrap long lines in `_chapters/configuration.adoc`

dev-support/jenkins_precommit_github_yetus.sh
Looks like we have two different environments with two sets of environment variables. Yetus talks about that target branch as `BRANCH_NAME`, but GitHub + Jenkins refer to it as `CHANGE_TARGET`, so we need to use that one from the shell script that invokes Yetus.
=> HBASE-24280 ADDENDUM branch on CHANGE_TARGET instead of BRANCH_NAME

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/FIFOCompactionPolicy.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestFIFOCompactionPolicy.java
This one surfaced as a flake test but turns out to be a legit bug
in FIFOCompaction code. FifoCompaction does not check if an empty
store file is already being compacted by an in-flight compaction
request and still enqueues. It can potentially race with a running
compaction (as in this test case, see jira for the exact exception).
Fixes the edge case and cleans up the test code a bit.
=> HBASE-21905: [FIFOCompaction] Don't compact already inflight store files

src/main/asciidoc/_chapters/configuration.adoc
* Add a section calling out our categorical lack of support for
non-LTS Java versions.
* Provide clarification as to the meaning of the 'red x' in our
support matrix.
* Transpose the support matrix to have HBase releases along the x-axis
and Java releases along the y-axis, because there are more Java
releases than HBase release categories.
* Update the JDK11 status in the matrix.
* Add a note qualifying our JDK11 support.
=> HBASE-23997 Consider JDK11 in our support matrix

hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAdmin4.java
removed RS entry from zk draining server znode on RS stopped
=> HBASE-24208 Remove RS entry from zk draining servers node after RS been stopped

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/TestPerformanceEvaluation.java
PE options validations were happening while options are getting evaluated. And hence order of options were necessary to make the validations pass. With this patch, moved validations of all such interdependent options to a private method. Added (2) and updated (2) few unit tests to validate the change.
=> HBASE-24340 PerformanceEvaluation options should not mandate any specific order

src/main/asciidoc/_chapters/developer.adoc
Follow-on to [HBASE-23997](https://issues.apache.org/jira/browse/HBASE-23997), #1844.
=> HBASE-24005 Document maven invocation with JDK11

hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/FsDelegationToken.java, hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFilesTool.java, hbase-server/src/test/java/org/apache/hadoop/hbase/security/token/TestFsDelegationToken.java
When doing Bulkload, we find that `FsDelegationToken` will acquire token of NameNode every time for a single file, although, from the comment of `acquireDelegationToken()`, it claims that it is trying to find token in cache firstly, but the newly requested token is never put to cache and thus the cache is still empty for the following request;
In cases there are many files to do the bulk load,  the token request will cause big shock to NameNode.
```
public void acquireDelegationToken(final String tokenKind, final FileSystem fs)
throws IOException {
Objects.requireNonNull(tokenKind, "tokenKind:null");
if (userProvider.isHadoopSecurityEnabled()) {
this.fs = fs;
userToken = userProvider.getCurrent().getToken(tokenKind, fs.getCanonicalServiceName());
if (userToken == null) {
hasForwardedToken …
```
=> HBASE-24403 FsDelegationToken Should Cache Token After Acquired A New One

hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSnapshotWithAcl.java
[https://issues.apache.org/jira/browse/HBASE-24184](url)
The code in AccessController.preListSnapshot:
if (SnapshotDescriptionUtils.isSnapshotOwner(snapshot, user)) {
// list it, if user is the owner of snapshot
AuthResult result = AuthResult.allow("listSnapshot " + snapshot.getName(),
"Snapshot owner check allowed", user, null, null, null);
accessChecker.logResult(result);
}
So i think the logic of setOwner is used for **authorization**, not **authentication**, SnapshotManager should not only setOwner when hbase.security.authentication = kerberos, which cause listSnapshots returns empty when i just use simple acls.
=> Backport HBASE-23896 to branch-1: Snapshot owner cannot delete snapshot when ACL is enabled and Kerberos is not enabled

hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitLogManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestSplitLogManager.java
Add simple backoff where we'll check every 100ms if < 10 WALs to complete else wait up to a minute between checks.
=> HBASE-24545 Add backoff to SCP check on WAL split completion

src/main/asciidoc/_chapters/architecture.adoc
Updated to include changes in HBASE-24265 and some rewording
to make it version agnostic.
=> HBASE-24535: Tweak the master registry docs for branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/security/HBaseSaslRpcClient.java, hbase-client/src/test/java/org/apache/hadoop/hbase/security/TestHBaseSaslRpcClient.java
read input stream even if the authentication is completed
add a test
=> HBASE-24579: Failed SASL authentication does not result in an exception on client side

hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitLogManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitWALManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionRemoteProcedureBase.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionTransitionProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SplitWALProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SplitWALRemoteProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SplitWALCallable.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitLogManager.java
Don't register as a chore on construction if no coordination state
manager instance (there is no instance when procv2 WAL splitter).
hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitWALManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
Edit logs.
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionRemoteProcedureBase.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionTransitionProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SplitWALProcedure.java …
=> HBASE-24574 Procedure V2 - Distributed WAL Splitting => LOGGING

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AbstractRecoveredEditsOutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/BoundedRecoveredEditsOutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/BoundedRecoveredHFilesOutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/OutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/RecoveredEditsOutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java
Sample output:
```
Journal Log: null at 1591291865775
Opening log file hdfs://localhost:64541/user/vjasani/test-data/9cad028f-1b56-2eeb-fec5-c83773b30f41/WALs/testsplitlogfilemultipleregions,16010,1591291865558/wal.dat.0 at 1591291865776
Finishing writing output logs and closing down at 1591291865801
Creating recovered edits writer path=hdfs://localhost:64541/user/vjasani/test-data/9cad028f-1b56-2eeb-fec5-c83773b30f41/data/default/t1/ccc/recovered.edits/0000000000000000002-wal.dat.0.temp at 1591291866091
Creating recovered edits writer path=hdfs://localhost:64541/user/vjasani/test-data/9cad028f-1b56-2eeb-fec5-c83773b30f41/data/default/t1/bbb/recovered.edits/0000000000000000001-wal.dat.0.temp at 1591291866091
3 split writer threads finished at 1591291866118
Closed recovered edits writer …
```
=> HBASE-24380 : Provide WAL splitting journal logging

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/LogRecoveredEditsOutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/OutputSink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java
=> HBASE-24598 : Backport HBASE-24380 (Provide WAL splitting journal logging) (#1860)

dev-support/create-release/release-util.sh
By default, `urllib.quote` will skipp over `/` characters, which are valid for use in passwords.
=> HBASE-24567 Create release should url-encode all characters when building git uri

hbase-client/src/main/java/org/apache/hadoop/hbase/security/HBaseSaslRpcClient.java, hbase-client/src/test/java/org/apache/hadoop/hbase/security/TestHBaseSaslRpcClient.java
branch-2.2 compatible version of #1921
=>  HBASE-24579: Failed SASL authentication does not result in an exception on client side

src/main/asciidoc/_chapters/configuration.adoc
Add a line for hadoop-3.2.x. Values are based on the if-statement in
our personality file,
```
if [[ "${PATCH_BRANCH}" = branch-1* ]]; then
yetus_info "Setting Hadoop 3 versions to test based on branch-1.x rules."
hbase_hadoop3_versions=""
elif [[ "${PATCH_BRANCH}" = branch-2.0 ]] || [[ "${PATCH_BRANCH}" = branch-2.1 ]]; then
yetus_info "Setting Hadoop 3 versions to test based on branch-2.0/branch-2.1 rules"
if [[ "${QUICK_HADOOPCHECK}" == "true" ]]; then
hbase_hadoop3_versions="3.0.3 3.1.2"
else
hbase_hadoop3_versions="3.0.3 3.1.1 3.1.2"
fi
else
yetus_info "Setting Hadoop 3 versions to test based on branch-2.2+/master/feature branch rules"
if [[ "${QUICK_HADOOPCHECK}" == "true" ]]; then
hbase_hadoop3_versions="3.1.2 3.2.1"
else
hbase_hadoop3_versions="3.1.1 3.1.2 3.2.0 3.2.1"
fi
fi
```
=> HBASE-24231 Add hadoop 3.2.x in our support matrix

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterMetaBootstrap.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaWithReplicas.java
This is related to HBASE-21624 .
I created a separate ticket because in the original one a "complete solution for meta replicas" was requested and this is not one. I'm just trying to make master startup more stable by making assigning meta replicas asynchronous and preventing a potential assignment failure from crashing master.
The idea is that starting master with less or even no meta replicas assigned is preferable to not having a running master.
=> HBASE-24562: Stabilize master startup with meta replicas enabled

dev-support/Dockerfile, dev-support/create-release/hbase-rm/Dockerfile, dev-support/docker/Dockerfile, dev-support/hbase_docker/Dockerfile
After a bit of research into [0] and [1], and a bit of experimentation, it seems we can use a partial wild-card expression for these version strings. Let's try this for now. If it works out, we should expand this usage to all the version package numbers, pinning them to their epic:upstream-version components.
[0]: http://manpages.ubuntu.com/manpages/xenial/en/man5/deb-version.5.html
[1]: http://manpages.ubuntu.com/manpages/xenial/man8/apt-get.8.html
=> HBASE-24631 Loosen Dockerfile pinned package versions of the "debian-revision"

hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteBufferUtils.java
Address incompatibility issue raised in 2.3.0RC0 vote thread.
=> Backport "HBASE-22504 Addendum: restore findCommonPrefix" to branch-2.3

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/Threads.java, hbase-server/src/main/java/org/apache/hadoop/hbase/backup/example/HFileArchiveManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/visibility/ZKVisibilityLabelWatcher.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
Writing a test for this is tricky. There is enough coverage for
functional tests. Only concern is performance, but there is enough
logging for it to detect timed out/badly performing sync calls.
=> HBASE-24603: Make Zookeeper sync() call synchronous

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/Threads.java, hbase-server/src/main/java/org/apache/hadoop/hbase/backup/example/HFileArchiveManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/visibility/ZKVisibilityLabelWatcher.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
Writing a test for this is tricky. There is enough coverage for
functional tests. Only concern is performance, but there is enough
logging for it to detect timed out/badly performing sync calls.
Additionally, this patch decouples the ZK event processing into it's
own thread rather than doing it in the EventThread's context. That
avoids deadlocks and stalls of the event thread.
(cherry picked from commit 84e246f9b197bfa4307172db5465214771b78d38)
=> HBASE-24603: Make Zookeeper sync() call synchronous (#1945)

hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/main/ruby/hbase/security.rb, hbase-shell/src/main/ruby/hbase_constants.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
Resolves https://issues.apache.org/jira/browse/HBASE-20819
- Based on an old patch from Ha, Xiaolin (patch is still attached to Jira), updated for the current master branch
- In the hbase-shell module, replace all usages of HTableDescriptor with TableDescriptorBuilder
- Add unit tests for removing nonexistent attributes and configurations in the shell (This was previously untested and touches some of the code changes in this PR)
- Added new overload for TableDescriptorBuilder.removeValue that takes a String argument.
=> HBASE-20819 Use TableDescriptor to replace HTableDescriptor in hbase-shell module

src/main/asciidoc/_chapters/configuration.adoc, src/main/asciidoc/_chapters/offheap_read_write.adoc, src/main/asciidoc/_chapters/upgrading.adoc
Bring back documentation from master branch (37b863bd0b), using
```
$ git checkout master -- src/main/asciidoc/
$ git checkout master -- src/site/asciidoc/
```
And then:
* remove changes from HBASE-23890
This reverts commit 420e38083f13ebf9ca056d2ee2de2192c23801c7.
* delete docs re: sync_replication
* delete docs re: backup
=> Backport "HBASE-24144 Update docs from master (addendum)" to branch-2.3

hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/AsyncFSOutput.java, hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutput.java, hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/WrapperAsyncFSOutput.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncProtobufLogWriter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogWriter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALProvider.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestFailedAppendAndSync.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestWALLockup.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncFSWAL.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncFSWALDurability.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLogDurability.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestLogRolling.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
This PR is different from #1970 as follows, which makes the `AsyncFSWAL.doShutdown` consistent with the master:
1. In `AsyncFSWAL.doShutdown` method, after we invoke `closeWriter()`, we set the `writer` to null
2. At the end of `TestWALEntryStream.testReplicationSourceWALReaderRecovered` :
` -    // Actually this should be true but we haven't handled this yet since for a normal queue the`
` -    // last one is always open... Not a big deal for now.`
` -    assertFalse(batch.isEndOfFile());`
` +    assertTrue(batch.isEndOfFile());`
=> Backport "HBASE-24625 AsyncFSWAL.getLogFileSizeIfBeingWritten does not return the expected synced file length. (#1970)" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterMetaBootstrap.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaWithReplicasBasic.java
- make sure to always clean up excess meta replicas not just when their number get decreased
- make sure NotServingRegionException is handled properly even when wrapped
- add test
=> HBASE-24720: Meta replicas not cleaned when disabled

src/site/xdoc/downloads.xml
I've copied what I found from the 2.2.5 release. I did change the URLs for everything except the tarballs to point to https://downloads.apache.org. I'm not sure if this is "in policy", so holler.
=> HBASE-24566 Add 2.3.0 to the downloads page

hbase-shell/src/main/ruby/shell/commands/balance_switch.rb, hbase-shell/src/main/ruby/shell/commands/balancer.rb, hbase-shell/src/main/ruby/shell/commands/catalogjanitor_enabled.rb, hbase-shell/src/main/ruby/shell/commands/catalogjanitor_switch.rb, hbase-shell/src/main/ruby/shell/commands/cleaner_chore_enabled.rb, hbase-shell/src/main/ruby/shell/commands/cleaner_chore_switch.rb, hbase-shell/src/main/ruby/shell/commands/clear_block_cache.rb, hbase-shell/src/main/ruby/shell/commands/clear_deadservers.rb, hbase-shell/src/main/ruby/shell/commands/disable_exceed_throttle_quota.rb, hbase-shell/src/main/ruby/shell/commands/disable_rpc_throttle.rb, hbase-shell/src/main/ruby/shell/commands/enable_exceed_throttle_quota.rb, hbase-shell/src/main/ruby/shell/commands/enable_rpc_throttle.rb, hbase-shell/src/main/ruby/shell/commands/is_disabled.rb, hbase-shell/src/main/ruby/shell/commands/normalize.rb, hbase-shell/src/main/ruby/shell/commands/normalizer_enabled.rb, hbase-shell/src/main/ruby/shell/commands/normalizer_switch.rb, hbase-shell/src/main/ruby/shell/commands/snapshot_cleanup_switch.rb, hbase-shell/src/main/ruby/shell/commands/splitormerge_enabled.rb, hbase-shell/src/main/ruby/shell/commands/splitormerge_switch.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb, hbase-shell/src/test/ruby/hbase/quotas_test.rb
Resolves https://issues.apache.org/jira/browse/HBASE-24722
- Prior to this commit, there were 13 commands that unintentionally return the
number of lines they print (usually one). This commit ensures that they
return the value documented by the help text, or nil if there is not a simple
logical value to return.
- Fixes 6 hbase-shell commands that return String rather than TrueClass or
FalseClass
- Use double-bang to cast truthy values to TrueClass and FalseClass so that
ruby's to_s can reliably print true or false without using ternary operators
- Updates tests for is_disabled, is_enabled, disable_rpc_throttle,
enable_rpc_throttle, disable_exceed_throttle_quota,
enable_exceed_throttle_quota, clear_deadservers, snapshot_cleanup_switch,
snapshot_cleanup_enabled, and balancer to check return …
=> HBASE-24722 Address hbase-shell commands with unintentional return values

hbase-shell/src/main/ruby/shell/commands/balance_switch.rb, hbase-shell/src/main/ruby/shell/commands/balancer.rb, hbase-shell/src/main/ruby/shell/commands/catalogjanitor_enabled.rb, hbase-shell/src/main/ruby/shell/commands/catalogjanitor_switch.rb, hbase-shell/src/main/ruby/shell/commands/cleaner_chore_enabled.rb, hbase-shell/src/main/ruby/shell/commands/cleaner_chore_switch.rb, hbase-shell/src/main/ruby/shell/commands/clear_block_cache.rb, hbase-shell/src/main/ruby/shell/commands/clear_deadservers.rb, hbase-shell/src/main/ruby/shell/commands/disable_exceed_throttle_quota.rb, hbase-shell/src/main/ruby/shell/commands/disable_rpc_throttle.rb, hbase-shell/src/main/ruby/shell/commands/enable_exceed_throttle_quota.rb, hbase-shell/src/main/ruby/shell/commands/enable_rpc_throttle.rb, hbase-shell/src/main/ruby/shell/commands/is_disabled.rb, hbase-shell/src/main/ruby/shell/commands/normalize.rb, hbase-shell/src/main/ruby/shell/commands/normalizer_enabled.rb, hbase-shell/src/main/ruby/shell/commands/normalizer_switch.rb, hbase-shell/src/main/ruby/shell/commands/snapshot_cleanup_switch.rb, hbase-shell/src/main/ruby/shell/commands/splitormerge_enabled.rb, hbase-shell/src/main/ruby/shell/commands/splitormerge_switch.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb, hbase-shell/src/test/ruby/hbase/quotas_test.rb
- Prior to this commit, there were 13 commands that unintentionally return the
number of lines they print (usually one). This commit ensures that they
return the value documented by the help text, or nil if there is not a simple
logical value to return.
- Fixes 6 hbase-shell commands that return String rather than TrueClass or
FalseClass
- Use double-bang to cast truthy values to TrueClass and FalseClass so that
ruby's to_s can reliably print true or false without using ternary operators
- Updates tests for is_disabled, is_enabled, disable_rpc_throttle,
enable_rpc_throttle, disable_exceed_throttle_quota,
enable_exceed_throttle_quota, clear_deadservers, snapshot_cleanup_switch,
snapshot_cleanup_enabled, and balancer to check return values
- Adds new tests for balance_switch, …
=> HBASE-24722 Update commands with unintentional return values (#2058)

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java
=> Forward-port "HBASE-24658 Update PolicyBasedChaosMonkey to handle uncaught exceptions" to master

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java
=> Backport "HBASE-24658 Update PolicyBasedChaosMonkey to handle uncaught exceptions" to branch-1

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DumpClusterStatusAction.java
Sometimes running chaos monkey, I've found that we lose accounting of
region servers. I've taken to a manual process of checking the
reported list against a known reference. It occurs to me that
ChaosMonkey has a known reference, and it can do this accounting for
me.
=> Forward-port "HBASE-24662 Update DumpClusterStatusAction to notice changes in region server count" to master

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DumpClusterStatusAction.java
Sometimes running chaos monkey, I've found that we lose accounting of
region servers. I've taken to a manual process of checking the
reported list against a known reference. It occurs to me that
ChaosMonkey has a known reference, and it can do this accounting for
me.
=> Forward-port "HBASE-24662 Update DumpClusterStatusAction to notice changes in region server count" to branch-2

src/site/site.xml
2.1 is EOM so the 2.1 Documentation link can be removed.
The content is still available under https://hbase.apache.org/2.1
=> HBASE-24763 Remove 2.1 Documentation direct link from website

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/Replication.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSink.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMultiLogThreshold.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSink.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntrySinkFilter.java
=> HBASE-24757 : ReplicationSink should limit row count in batch mutation based on hbase.rpc.rows.warning.threshold

hbase-shell/src/main/ruby/hbase/taskmonitor.rb
Uncommented the code to handle the SSL scenario.
=> HBASE-24738 [Shell] processlist command fails with ERROR: Unexpected end of file from server when SSL enabled

hbase-server/src/main/java/org/apache/hadoop/hbase/io/FSDataInputStreamWrapper.java
HBASE-24336 is applicable to branch-2.2 also.
=> HBASE-24756 Backport HBASE-24336 "[Metrics] FSDataInputStream's localBytesRead is wrong" to branch-2.2

hbase-shell/src/main/ruby/hbase/table.rb, hbase-shell/src/test/ruby/hbase/table_test.rb
Resolves https://issues.apache.org/jira/browse/HBASE-11676
- In HBase::Table, the instance variable @converters is used to map column
names to converters. This patch fixes how HBase::Table#_get_internal and
HBase::Table#_scan_internal generate the column name key used to access
@converters.
- Refactor parsing of family:qualifier:converter specifications so that the
code is more readable and reusable. As part of this change, I added two
private methods and marked HBase::Table#set_converter as deprecated for
removal in HBase 4.0.0. I doubt people are using this method, but I kept it
for compatibility.
- I added unit tests that cover the bug.
- I manually double-check the example scenario provided in Jira.
=> HBASE-11676 Scan FORMATTER is not applied for columns using non-printable name in shell

hbase-server/src/main/java/org/apache/hadoop/hbase/SplitLogCounters.java
HBASE-24790 Remove unused counter from SplitLogCounters
=> HBASE-24790 Remove unused counter from SplitLogCounters

hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerRemoteProcedure.java
Add outline of how the mechanism works generally.
=> HBASE-24766 Document Remote Procedure Execution

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableOutputFormat.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/ServerRegionReplicaUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncReplicationAdminApiWithClusters.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestReplicaWithCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestClearRegionBlockCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestMasterReplication.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestMultiSlaveReplication.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestPerTableCFReplication.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestGlobalReplicationThrottler.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestRegionReplicaReplicationEndpoint.java
Fixing the connection leaks in hbase due to closing hbase admin without closing connection.
=> HBASE-24788: Fix the connection leaks on getting hbase admin from unclosed connection

hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotManifest.java
We observed this delete call to be a bottleneck for table with lots of
regions. Patch attempts to parrallelize them.
=> HBASE-20226: Parallelize region manifest deletes

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
with just the new test, things fail after spinning until timeout
```
13:40:17 [INFO] -------------------------------------------------------
13:40:17 [INFO]  T E S T S
13:40:17 [INFO] -------------------------------------------------------
13:40:18 [INFO] Running org.apache.hadoop.hbase.regionserver.TestHRegion
13:54:30 [ERROR] Tests run: 104, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 780.658 s <<< FAILURE! - in org.apache.hadoop.hbase.regionserver.TestHRegion
13:54:30 [ERROR] org.apache.hadoop.hbase.regionserver.TestHRegion  Time elapsed: 586.556 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 780 seconds
at org.apache.hadoop.hbase.regionserver.TestHRegion.testBatchMutateWithZeroRowLockWait(TestHRegion.java:6488)
```
warning for those looking to …
=> HBASE-24794 hbase.rowlock.wait.duration should not be <= 0

hbase-client/src/main/java/org/apache/hadoop/hbase/client/CheckAndMutate.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Region.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/SimpleRegionObserver.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestRegionObserverInterface.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java
- Added a new method `checkAndMutate(CheckAndMutate)` to `Region`/`HRegion` and deprecated the old methods `checkAndPut`/`checkAndDelete`/`checkAndRowMutate`
- Added new coprocessor methods `preCheckAndMutate`/`preCheckAndMutateAfterRowLock`/`postCheckAndMutate` to RegionObserver and deprecated the old coprocessor methods `preCheckAndPut`/`preCheckAndPutAfterRowLock`/`postCheckAndPut`/`preCheckAndDelete`/`preCheckAndDeleteAfterRowLock/postCheckAndDelete`
- Added a new metric for `checkAndMutate`
=> HBASE-24680 Refactor the checkAndMutate code on the server side

dev-support/create-release/release-util.sh
first pass at turning a given gpg key name into a key id during release info gathering.
=> HBASE-24572 release scripts should try to use a keyid when refering to GPG keys.

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java
HBASE-24791 Improve HFileOutputFormat2 to avoid always call getTableRelativePath method
=> HBASE-24791 Improve HFileOutputFormat2 to avoid always call getTableRelativePath method

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregateFactory.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestClientClusterMetrics.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsUserAggregate.java
Set hbase.regionserver.user.metrics.enabled default to false; i.e. off.
=> HBASE-24767 Change default to false for HBASE-15519 per-user metrics

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DumpClusterStatusAction.java
Sometimes running chaos monkey, I've found that we lose accounting of
region servers. I've taken to a manual process of checking the
reported list against a known reference. It occurs to me that
ChaosMonkey has a known reference, and it can do this accounting for
me.
=> Backport "HBASE-24662 Update DumpClusterStatusAction to notice changes in region server count" to branch-1

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/SystemTableWALEntryFilter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/WALEntryFilter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AbstractFSWALProvider.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSource.java
Allow specifying base WALEntry filter on construction of
ReplicationSource. Add means of being able to filter WALs by name.
hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java
Add constructor that allows passing a predicate for filtering *in* WALs
and a list of filters for filtering *out* WALEntries. The latter was
hardcoded to filter out system-table WALEntries. The former did not
exist but we'll need it if Replication takes in more than just the
default Provider.
=> HBASE-24817 Allow configuring WALEntry filters on ReplicationSource

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
Currently, added read replica stats for RandomReadTest .
=> HBASE-24824 Add more stats in PE for read replica

hbase-common/src/test/java/org/apache/hadoop/hbase/TableNameTestRule.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/MergeNormalizationPlan.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SplitNormalizationPlan.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
* add `testMergeEmptyRegions` to explicitly cover different interleaving of 0-sized regions.
* fix bug where merging a 0-size region is skipped due to large neighbor.
* remove unused `splitPoint` from `SplitNormalizationPlan`.
* generate `toString`, `hashCode`, and `equals` methods from Apache Commons Lang3 template on `SplitNormalizationPlan` and `MergeNormalizationPlan`.
* simplify test to use equality matching over `*NormalizationPlan` instances as plain pojos.
* test make use of this handy `TableNameTestRule`.
* fix line-length issues in `TestSimpleRegionNormalizer`
=> HBASE-24583 Normalizer can't actually merge empty regions when neighbor is larger than average size

hbase-common/src/test/java/org/apache/hadoop/hbase/TableNameTestRule.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/MergeNormalizationPlan.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SplitNormalizationPlan.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
when neighbor is larger than average size
* add `testMergeEmptyRegions` to explicitly cover different
interleaving of 0-sized regions.
* fix bug where merging a 0-size region is skipped due to large
neighbor.
* remove unused `splitPoint` from `SplitNormalizationPlan`.
* generate `toString`, `hashCode`, and `equals` methods from Apache
Commons Lang3 template on `SplitNormalizationPlan` and
`MergeNormalizationPlan`.
* simplify test to use equality matching over `*NormalizationPlan`
instances as plain pojos.
* test make use of this handy `TableNameTestRule`.
* fix line-length issues in `TestSimpleRegionNormalizer`
Signed-off-by: huaxiangsun <huaxiangsun@apache.org>
Signed-off-by: Aman …
=> Backport "HBASE-24583 Normalizer can't actually merge empty regions..." to branch-2

hbase-common/src/test/java/org/apache/hadoop/hbase/TableNameTestRule.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/MergeNormalizationPlan.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SplitNormalizationPlan.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
when neighbor is larger than average size
* add `testMergeEmptyRegions` to explicitly cover different
interleaving of 0-sized regions.
* fix bug where merging a 0-size region is skipped due to large
neighbor.
* remove unused `splitPoint` from `SplitNormalizationPlan`.
* generate `toString`, `hashCode`, and `equals` methods from Apache
Commons Lang3 template on `SplitNormalizationPlan` and
`MergeNormalizationPlan`.
* simplify test to use equality matching over `*NormalizationPlan`
instances as plain pojos.
* test make use of this handy `TableNameTestRule`.
* fix line-length issues in `TestSimpleRegionNormalizer`
Signed-off-by: huaxiangsun <huaxiangsun@apache.org>
Signed-off-by: Aman …
=> Backport "HBASE-24583 Normalizer can't actually merge empty regions..." to branch-2.3

hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java, hbase-client/src/main/java/org/apache/hadoop/hbase/util/PoolMap.java
since Reusable PoolType has been removed, no need to check allowedPoolTypes
=> HBASE-24872 refactor valueOf PoolType

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/NormalizeTableFilterParams.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java, hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizerOnCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/main/ruby/hbase_constants.rb, hbase-shell/src/main/ruby/shell/commands/normalize.rb, hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
Introduce an additional method to our Admin interface that allow an
operator to selectivly run the normalizer. The IPC protocol supports
general table name select via compound filter.
=> HBASE-24627 Normalize one table at a time

hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/main/ruby/hbase_constants.rb, hbase-shell/src/main/ruby/shell/commands/alter.rb, hbase-shell/src/test/ruby/hbase/admin_test.rb
Resolves https://issues.apache.org/jira/browse/HBASE-24874
- Fix hbase-shell access in JDK 11 for calls to
TableDescriptorBuilder.toCoprocessorDescriptor and
ModifiableTableDescriptor.toStringTableAttributes.
- Allow coprocessors to be specified using a Ruby hash in the hbase-shell alter
command and replace usage in the help text. The previous String overload of
the alter command will continue to work and is still covered by a unit test,
but will no longer be suggested in the alter command help.
=> HBASE-24874 Fix hbase-shell access to ModifiableTableDescriptor methods

bin/hirb.rb, hbase-shell/src/main/ruby/shell.rb, hbase-shell/src/main/ruby/shell/hbase_loader.rb, hbase-shell/src/test/ruby/shell/shell_test.rb, hbase-shell/src/test/ruby/tests_runner.rb
Resolves https://issues.apache.org/jira/browse/HBASE-24806
1. Create exception handler for shell (to hide tracebacks unless debug is on). The handler just replaces exceptions with SystemExit.
2. Get rid of a recently introduced IRB warning (`can't alias help from irb_help`).
3. Create a new module Hbase::Loader that can find ruby scripts using JRuby's loader. This is better than IRB::Loader because it can find anything that can be found directly with `load`, including files inside a Jar. It is necessary so that our shell can _evaluate_ scripts in the $LOAD_PATH/classpath.
4. Update the test runner to catch SystemExits. This will ensure that our unit tests stay potent and cannot fail unnoticed.
- Move exception handler from Shell::Shell#eval_io to new method,
Shell::Shell#exception_handler …
=> HBASE-24806 Small Updates to Functionality of Shell IRB Workspace

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/NormalizeTableFilterParams.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java, hbase-protocol-shaded/src/main/protobuf/Master.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizerOnCluster.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/main/ruby/hbase_constants.rb, hbase-shell/src/main/ruby/shell/commands/normalize.rb, hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
Introduce an additional method to our Admin interface that allow an
operator to selectivly run the normalizer. The IPC protocol supports
general table name select via compound filter.
=> Backport "HBASE-24627 Normalize one table at a time" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStateNode.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestHbck.java
Adds region state check on hbck2 assigns/unassigns. Returns pid of -1
if in inappropriate state with logging explaination which suggests
passing override if operator wants to assign/unassign anyways. Here
is an example of what happens now if hbck2 tries an unassign and
Region already unassigned:
2020-08-19 11:22:06,926 INFO  [RpcServer.default.FPBQ.Fifo.handler=1,queue=0,port=50086] assignment.AssignmentManager(820): Failed {ENCODED => d1112e553991e938b6852f87774c91ee, NAME => 'TestHbck,zzzzz,1597861310769.d1112e553991e938b6852f87774c91ee.', STARTKEY => 'zzzzz', ENDKEY => ''} unassign, override=false; set override to by-pass state checks.
org.apache.hadoop.hbase.client.DoNotRetryRegionException: Unexpected state for state=CLOSED, location=null, table=TestHbck, …
=> HBASE-24885 STUCK RIT by hbck2 assigns

hbase-client/src/main/java/org/apache/hadoop/hbase/client/MasterAddressRefresher.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/MasterRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/MetricsConnection.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestMasterRegistryHedgedReads.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestMetricsConnection.java, hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/ActiveMasterManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMasterAddressRefresher.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMasterRegistry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/AlwaysStandByHMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestActiveMasterManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMasterAddressTracker.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MasterAddressTracker.java
This patch adds the ability to discover newly added masters
dynamically on the master registry side. The trigger for the
re-fetch is either 5mins or any registry RPC failure.
I didn't add the method to ZK registry interface since there
is a design discussion going on in splittable meta doc. We can
add it later if needed.
=> HBASE-24765: Dynamic master discovery

hbase-server/src/test/java/org/apache/hadoop/hbase/TestJMXConnectorServer.java
Two optimization points for TestJMXConnectorServer in this issue:
1. Just run cluster once, not once per test case.
2. Use random free port to run ConnectorServer, avoid specifying a fixed port.
=> HBASE-24913 Refactor TestJMXConnectorServer

hbase-server/src/test/java/org/apache/hadoop/hbase/http/log/TestLogLevel.java
This PR introduces changes to fix the failing `TestLogLevel` unit tests.
Post making this change I looked into the branch-2 tests on ci-hadoop and found that the same test was passing for the same profile ie [JDK 8 + Hadoop 2]. So I delved into the code-base for this test in branch-2 and found that a similar fix had already been done to branch-2 as part of `HBASE-23829`. Here is the link to the PR introducing similar code change in branch-2 - https://github.com/apache/hbase/pull/1296/files#diff-88475ac51af9e041c429e33afc3e8ca0
This PR basically cherrypicks the changes in the TestLogLevel class as introduced in https://github.com/apache/hbase/pull/1296
=> [HBASE-24893] [branch-1] Fix failing TestLogLevel unit test on ci-hadoop

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableRecordReaderImpl.java, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableSnapshotInputFormat.java
Avoid invoke Counter using reflection in SnapshotInputFormat
=> HBASE-24831 Avoid invoke Counter using reflection in SnapshotInputFormat

hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java, hbase-http/src/test/java/org/apache/hadoop/hbase/http/TestHttpCookieFlag.java
Patch adds setHttpOnly(true) and setSecure(true) when creating a new servlet via `HttpServer#addInternalServlet`
=>     HBASE-19352 Port HADOOP-10379: Protect authentication cookies with the HttpOnly and Secure flags

src/main/asciidoc/_chapters/architecture.adoc, src/main/asciidoc/_chapters/other_info.adoc, src/site/asciidoc/metrics.adoc
Fix dead links in HBase book
jira: https://issues.apache.org/jira/browse/HBASE-24980
=> HBASE-24980 Fix dead links in HBase book

hbase-client/src/main/java/org/apache/hadoop/hbase/client/CheckAndMutate.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ResponseConverter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MiniBatchOperationInProgress.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/OperationStatus.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Region.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTable.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableBatch.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestCheckAndMutate.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide3.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestAtomicOperation.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
Summary of the change:
- Add build(Increment) and build(Append) methods to the Builder class of the CheckAndMutate class. After this change, we can perform checkAndIncrement/Append operation as follows:
```
// Build a CheckAndMutate object with a Increment object
CheckAndMutate checkAndMutate = CheckAndMutate.newBuilder(row)
.ifEquals(family, qualifier, value)
.build(increment);
// Perform a CheckAndIncrement operation
CheckAndMutateResult checkAndMutateResult = table.checkAndMutate(checkAndMutate);
// Get whether or not the CheckAndIncrement operation is successful
boolean success = checkAndMutateResult.isSuccess();
// Get the result of the increment operation
Result result = checkAndMutateResult.getResult();
```
- After this change, HRegion.batchMutate() is used for increment/append …
=> HBASE-24602 Add Increment and Append support to CheckAndMutate

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java, src/main/asciidoc/_chapters/performance.adoc
https://issues.apache.org/jira/browse/HBASE-24994
Hedged reads use same thread pool for the original read:
https://github.com/apache/hadoop/blob/0b8464d75227fcee2c6e7f2410377b3d53d3d5f8/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSInputStream.java#L1349-L1357
When the executor is full and rejects the task, it will be executed in current thread, increasing this metric:
https://github.com/apache/hadoop/blob/0b8464d75227fcee2c6e7f2410377b3d53d3d5f8/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSClient.java#L2913-L2918
I want to expose this metric to HBase since it will be useful to estimate the correct  thread pool size (dfs.client.hedged.read.threadpool.size).
=> HBASE-24994 Add hedgedReadOpsInCurThread metric

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALPrettyPrinter.java
Provide flexibility to print only row key from WALPrettyPrinter and filter for multiple tables in the WALPrettyPrinter
=> HBASE-24974: Provide a flexibility to print only row key and filter for multiple tables in the WALPrettyPrinter

hbase-hbtop/src/main/java/org/apache/hadoop/hbase/hbtop/HBTop.java, hbase-hbtop/src/main/java/org/apache/hadoop/hbase/hbtop/screen/AbstractScreenView.java, hbase-hbtop/src/main/java/org/apache/hadoop/hbase/hbtop/screen/Screen.java, hbase-hbtop/src/main/java/org/apache/hadoop/hbase/hbtop/screen/top/TopScreenModel.java, hbase-hbtop/src/main/java/org/apache/hadoop/hbase/hbtop/screen/top/TopScreenPresenter.java, hbase-hbtop/src/main/java/org/apache/hadoop/hbase/hbtop/screen/top/TopScreenView.java, hbase-hbtop/src/main/java/org/apache/hadoop/hbase/hbtop/terminal/impl/batch/BatchTerminal.java, hbase-hbtop/src/main/java/org/apache/hadoop/hbase/hbtop/terminal/impl/batch/BatchTerminalPrinter.java, hbase-hbtop/src/test/java/org/apache/hadoop/hbase/hbtop/screen/top/TestTopScreenModel.java, hbase-hbtop/src/test/java/org/apache/hadoop/hbase/hbtop/screen/top/TestTopScreenPresenter.java
Added the following command line parameters to hbtop:
| Argument | Description | 
|---|---|
| -n,--numberOfIterations <arg> | The number of iterations |
| -O,--outputFieldNames | Print each of the available field names on a separate line, then quit |
| -f,--fields <arg> | Show only the given fields. Specify comma separated fields to show multiple fields |
| -s,--sortField <arg> | The initial sort field. You can prepend a `+' or `-' to the field name to also override the sort direction. A leading `+' will force sorting high to low, whereas a `-' will ensure a low to high ordering |
| -i,--filters <arg> | The initial filters. Specify comma separated filters to set multiple filters |
| -b,--batchMode | Starts hbtop in Batch mode, which could be useful for sending output from hbtop to other …
=> HBASE-24776 [hbtop] Support Batch mode

hbase-client/src/main/java/org/apache/hadoop/hbase/replication/ReplicationPeerConfig.java, hbase-client/src/main/java/org/apache/hadoop/hbase/replication/ReplicationPeersZKImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestMasterReplication.java
JIRA: https://issues.apache.org/jira/browse/HBASE-24764
JIRA Description:
Today, if a user needs to apply some common base peer configs to all the replication peers on the cluster,  the only way is to execute update_peer_config via CLI which requires manual intervention and can be tedious in case of large deployment fleet.
As part of this JIRA, we plan to add the support to have base replication peer configs as part of hbase-site.xml like hbase.replication.peer.base.config="k1=v1;k2=v2.." which can be easily updated and applied as part of a rolling restart. 
Example below:
```
<property> 
<name>hbase.replication.peer.base.configs</name>
<value>hbase.replication.source.custom.walentryfilters=x,y,z;hbase.rpc.protection=abc;hbase.xxx.custom_property=123</value>
</property>
```
This property …
=> Hbase-24764 : Add support of adding base peer configs via hbase-site.xml for all replication peers

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionInfo.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionInfoStaticInitialization.java
Untangle RegionInfo, RegionInfoBuilder, and MutableRegionInfo static
initializations some. Move MutableRegionInfo from inner-class of
RegionInfoBuilder to be (package private) standalone. Undo static
initializing references from RI to RIB.
This PR rebases #2274 and adds a test. Test fails reliably for me without this patch.
=> HBASE-24896 'Stuck' in static initialization creating RegionInfo instance

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaCache.java
This is just the backport of  branch-2 PR. https://github.com/apache/hbase/pull/2322/
There are 2 differences compared to branch-2.
1. LockTimeoutException already exists in branch-1 so reusing that.
2. In TestMetaCache#testUserRegionLockThrowsException, I have set HBASE_CLIENT_RETRIES_NUMBER value to 1 whereas in branch-2, it was set to 0.
In branch-2, they have attempts and retries notion differently. It is calculating numAttempts = numRetries + 1 but in branch-1, numAttempts = numTries.
@bharathv please review branch-1 PR. Thank you !
=> [HBASE-24956] ConnectionManager#locateRegionInMeta waits for user region lock indefinitely.

hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RESTServer.java
When i think i have configurated the secure cluster correctly,  i start the rest server, the log message are:
1.   SLF4J: Class path contains multiple SLF4J bindings.
2.   SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.8.5/share/hadoop/common/lib/slf4j-log4j12- 
1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
3.   SLF4J: Found binding in [jar:file:/usr/local/hbase-2.2.1/lib/client-facing-thirdparty/slf4j-log4j12- 
1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
4.   SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
5.   SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
6.   2020-09-03 02:10:57,995 INFO  [main] RESTServer: ***** STARTING service 'RESTServer' *****
7.   2020-09-03 02:10:57,998 INFO  [main] util.VersionInfo: …
=> HBASE-24976 Printing the swallowed exception 

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
It will just return "Interface" for all services. This is not a bug for AsyncConnectionImpl as we have different maps for ClientService and AdminService, but it is still a bit confusing to developers.
I suggest either we just use empty string and add a comment to say that the service name is not important here, or change to use XXXService.class.getSimpleName() or XXXService.getDescriptor().getName(), so it is less confusing to developers.
=> Should not use XXXService.Interface.class.getSimpleName as stub key prefix in AsyncConnectionImpl

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide.java
https://issues.apache.org/jira/browse/HBASE-25025
=> [Flaky Test][branch-1] TestFromClientSide#testCheckAndDeleteWithCompareOp

hbase-balancer/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java
The comment of `MetaTableAccessor#getScanForTableName` says it is only for internal use but MetaTableAccessor is IA.Private, so it is OK to keep method `getScanForTableName`, which should remove the deprecated annotation for `MetaTableAccessor#getScanForTableName`.
=> HBASE-25120 Remove the deprecated annotation for MetaTableAccessor.getScanForTableName

dev-support/hbase-personality.sh, src/main/asciidoc/_chapters/community.adoc
Following the [announcement](0) to EOL branch-1.3, update the precommit
script to not consider this branch any longer, and refresh mentions of
this branch in the doc.
[0]: https://lists.apache.org/thread.html/r9552e9085aaac2a43f8b26b866d34825a84a9be7f19118ac560d14de%40%3Cuser.hbase.apache.org%3E
=> HBASE-25143 Remove branch-1.3 from precommit and docs

hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java
To be safe, jetty's version number should be blocked.
=> HBASE-24054

dev-support/hbase-personality.sh
Now that Hadoop 3.3.0 is released, let's figure out where it goes in
our testing matrix. Start by adding it to precommit checks.
=> HBASE-25144 Add Hadoop-3.3.0 to precommit check list

src/main/asciidoc/_chapters/hbase_mob.adoc
Added the MOB troubleshooting section for bulk load and WAL split-to-hfile behavior.
=> HBASE-23742 Document that with split-to-hfile data over the MOB threshold will be treated as normal data

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterFailover.java
Change the test to wait for evidence that the active master has seen that the backup master killed by the test has gone away. This is done before proceeding to validate that the dead backup is correctly omitted from the ClusterStatus report.
Also, minor fixup to several assertions, using `assertEquals` instead of `assertTrue(...equals(...))` and correcting expected vs. actual ordering of assertion arguments.
=> HBASE-25156 TestMasterFailover.testSimpleMasterFailover is flaky

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterFailover.java
Change the test to wait for evidence that the active master has seen
that the backup master killed by the test has gone away. This is done
before proceeding to validate that the dead backup is correctly
omitted from the ClusterStatus report.
Also, minor fixup to several assertions, using `assertEquals` instead
of `assertTrue(...equals(...))` and correcting expected vs. actual
ordering of assertion arguments.
=> Backport "HBASE-25156 TestMasterFailover.testSimpleMasterFailover is flaky (#2507)" to branch-2.3

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterFailover.java
Change the test to wait for evidence that the active master has seen
that the backup master killed by the test has gone away. This is done
before proceeding to validate that the dead backup is correctly
omitted from the ClusterStatus report.
Also, minor fixup to several assertions, using `assertEquals` instead
of `assertTrue(...equals(...))` and correcting expected vs. actual
ordering of assertion arguments.
=> Backport "HBASE-25156 TestMasterFailover.testSimpleMasterFailover is flaky (#2507)" to branch-2.2

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterWrapperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/MergeTableRegionsProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/SplitTableRegionProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/MergeNormalizationPlan.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/NormalizationPlan.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/NormalizationTarget.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerChore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorkQueue.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/package-info.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterChoreScheduled.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterMetricsWrapper.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestRegionNormalizerWorkQueue.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestRegionNormalizerWorker.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizerOnCluster.java
Implement a rate limiter for the normalizer. Implemented in terms of
MB/sec of affacted region size (the same metrics used to make
normalization decisions). Uses Guava `RateLimiter` to perform the
resource accounting. `RateLimiter` works by blocking (uninterruptible
😖) the calling thread. Thus, the whole construction of the normalizer
subsystem needed refactoring. See the provided `package-info.java` for
an overview of this new structure.
Introduces a new configuration,
`hbase.normalizer.throughput.max_bytes_per_sec`, for specifying a
limit on the throughput of actions executed by the normalizer. Note
that while this configuration value is in bytes, the minimum honored
valued `1_000_000`. Supports values configured using the
human-readable suffixes honored by `Configuration.getLongBytes`
=> HBASE-24628 Region normalizer now respects a rate limit

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterWrapperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/MergeTableRegionsProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/SplitTableRegionProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/MergeNormalizationPlan.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/NormalizationPlan.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/NormalizationTarget.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerChore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorkQueue.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/package-info.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterChoreScheduled.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterMetricsWrapper.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestRegionNormalizerWorkQueue.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestRegionNormalizerWorker.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizerOnCluster.java
Implement a rate limiter for the normalizer. Implemented in terms of
MB/sec of affacted region size (the same metrics used to make
normalization decisions). Uses Guava `RateLimiter` to perform the
resource accounting. `RateLimiter` works by blocking (uninterruptible
😖) the calling thread. Thus, the whole construction of the normalizer
subsystem needed refactoring. See the provided `package-info.java` for
an overview of this new structure.
Introduces a new configuration,
`hbase.normalizer.throughput.max_bytes_per_sec`, for specifying a
limit on the throughput of actions executed by the normalizer. Note
that while this configuration value is in bytes, the minimum honored
valued `1_000_000`. Supports values configured using the
human-readable suffixes honored by `Configuration.getLongBytes` …
=> Backport "HBASE-24628 Region normalizer now respects a rate limit" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AbstractFSWALProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AsyncFSWALProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/DisabledWALProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/FSHLogProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/RegionGroupingProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/SyncReplicationWALProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALProvider.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestFailedAppendAndSync.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestLogRolling.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/IOTestProvider.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALFactory.java
=> HBASE-25065 WAL archival to be done by a separate thread

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
I think this variable is null for backup masters. `initializeZKBasedSystemTrackers` only called when a master transitions to active. I don't know why it impacts this test though, as an NPE in the backup master thread should cause the thread to halt.
=> HBASE-24628 Region normalizer now respects a rate limit (HMaster chore shutdown NPE ADDENDUM)

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
Add the documentation when
HConstants#REPLICATION_DROP_ON_DELETED_TABLE_KEY was deprecated and when
it is expected to be removed.
=> HBASE-25196 Add deprecation documentation to HConstants

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/FifoRpcSchedulerFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RpcSchedulerFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SimpleRpcSchedulerFactory.java
Remove the deprecated RpcSchedulerFactory#create(Configuration,
PriorityFunction) method from the interface and in all implementing
classes.
=> HBASE-25198 Remove deprecated RpcSchedulerFactory#create

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableLatencies.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableLatenciesImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerTableMetrics.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java
[HBASE-25189](https://issues.apache.org/jira/browse/HBASE-25189)
=> HBASE-25189 [Metrics] Add checkAndPut and checkAndDelete latency metrics at table level

hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/GCMultipleMergedRegionsProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/HBCKServerCrashProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java, hbase-server/src/main/resources/hbase-webapps/master/hbck.jsp
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/GCMultipleMergedRegionsProcedure.java
Edit a log.
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/HBCKServerCrashProcedure.java
Add override of isMatchingRegionLocation. Allow 'null' as a pass in
HBCKSCP.
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java
Add a method for HBCKSCP to override and be less strict filtering
assigns.
hbase-server/src/main/resources/hbase-webapps/master/hbck.jsp
Some doc on what 'Unknown Servers' are.
Co-authored-by: Peter Somogyi <psomogyi@apache.org>
=> HBASE-25221 Backport HBASE-24368 Let HBCKSCP clear 'Unknown Servers', even if RegionStateNode has RegionLocation == null

dev-support/git-jira-release-audit/README.md, dev-support/git-jira-release-audit/git_jira_release_audit.py
Populating the audit database with release tag information from git is
time consuming. Until that's sorted out, give the user a flag for
limiting which branches they want to be reviewed.
=> HBASE-24845 Git/Jira Release Audit: limit branches when building audit db

hbase-common/src/test/java/org/apache/hadoop/hbase/MatcherPredicate.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/MergeNormalizationPlan.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/NormalizationTarget.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizerOnCluster.java
The core change here is to the loop in `SimpleRegionNormalizer#computeMergeNormalizationPlans`. It's a nested loop that walks the table's region chain once, looking for contiguous sequences of regions that meet the criteria for merge. The outer loop tracks the starting point of the next sequence, the inner loop looks for the end of that sequence. A single sequence becomes an instance of `MergeNormalizationPlan`.
Pay mind only to the commit for this JIRA. This PR depends on [HBASE-24628](https://issues.apache.org/jira/browse/HBASE-24628)/#2454 and will need rebased once that one lands.
=> HBASE-24419 Normalizer merge plans should consider more than 2 regions when possible

hbase-common/src/main/java/org/apache/hadoop/hbase/util/UnsafeAccess.java
UnsafeAccess is observed to throw NoSuchMethodErrors running on Java 11. Some of our methods accept 'int' parameters and use them as parameters to Unsafe methods expecting 'long'.  Not an issue on branch-2 and up.
=> HBASE-25227 [branch-1] Fix Java 11 runtime issue in UnsafeAccess

hbase-server/src/main/java/org/apache/hadoop/hbase/util/TableDescriptorChecker.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestHBaseMetaEdit.java
Added a sanity check for meta table before modifying the table schema
=> HBASE-24977 Meta table shouldn't be modified as read only

hbase-server/src/main/java/org/apache/hadoop/hbase/mapreduce/TableInputFormatBase.java, hbase-server/src/main/java/org/apache/hadoop/hbase/mapreduce/TableSplit.java, hbase-server/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableInputFormatScanBase.java
It has been observed that when the table has too many regions, MR jobs consume a lot of memory in the client. This is because we keep the region level information in memory and the memory heavy object is TableSplit because of the Scan object as a part of it.
However, it looks like the TableInputFormat for single table doesn't need to store the scan object in the TableSplit because we do not use it and all the splits are expected to have the exact same scan object. In `TableInputFormat` we use the scan object directly from the MR conf.
=> HBASE-24859: Optimize in-memory representation of HBase map reduce table splits

hbase-common/src/main/java/org/apache/hadoop/hbase/conf/ConfigurationManager.java, hbase-common/src/main/java/org/apache/hadoop/hbase/conf/ConfigurationObserver.java, hbase-common/src/test/java/org/apache/hadoop/hbase/conf/TestConfigurationManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestRegionNormalizerManagerConfigurationObserver.java
Wire up the `ConfigurationObserver` chain for
`RegionNormalizerManager`. The following configuration keys support
hot-reloading:
* hbase.normalizer.throughput.max_bytes_per_sec
* hbase.normalizer.split.enabled
* hbase.normalizer.merge.enabled
* hbase.normalizer.min.region.count
* hbase.normalizer.merge.min_region_age.days
* hbase.normalizer.merge.min_region_size.mb
Note that support for `hbase.normalizer.period` is not provided
here. Support would need to be implemented generally for the `Chore`
subsystem.
Signed-off-by: Aman Poonia <aman.poonia.29@gmail.com>
=> Backport "HBASE-25167 Normalizer support for hot config reloading (#2523)" to branch-2

hbase-http/src/test/java/org/apache/hadoop/hbase/http/ssl/KeyStoreTestUtil.java, hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/Constants.java, hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RESTServer.java, hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/client/Client.java, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestRESTServerSSL.java, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestSslRestServer.java
In this patch I introduced the following new parameters:
hbase.rest.ssl.keystore.type
hbase.rest.ssl.truststore.store
hbase.rest.ssl.truststore.password
hbase.rest.ssl.truststore.type
If any of the new the parameter is not provided, then we are falling-back to the current behaviour (e.g. assuming JKS keystore/truststore types, or no passwords, or no custom trust store file).
I also created a new test case to test the RESTServer with SSL in general and also to test some keystore formats. To be able to write this test I also had to extend the client and keystore utilities we use for testing.
=> HBASE-25267 Add SSL keystore type and truststore related configs for HBase RESTServer

pom.xml
Upgraded asciidoctor-maven-plugin and asciidoctorj-pdf to the latest versions.
Followed the migration guide of [asciidoctor-maven-plugin 2.0.0 migration guide](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/asciidoctor-maven-plugin-2.0.0/docs/v2-migration-guide.adoc).
=> HBASE-25275 Upgrade asciidoctor

dev-support/hbase-personality.sh, src/main/asciidoc/_chapters/configuration.adoc
* Updates the ref guide to add a column to the hadoop table for HBase 1.7
* Updates the yetus personality so that branch-1 uses 2.10.0.
=> HBASE-25083 further HBase 1.y releases should have Hadoop 2.10 as a minimum version.

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerRPCScanMetrics.java
Cherry pick HBASE-25026. @anoopsjohn
=> Cherry pick HBASE-25026

hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/BlockingRpcConnection.java, hbase-client/src/main/java/org/apache/hadoop/hbase/util/PoolMap.java, hbase-client/src/test/java/org/apache/hadoop/hbase/util/PoolMapTestBase.java, hbase-client/src/test/java/org/apache/hadoop/hbase/util/TestRoundRobinPoolMap.java, hbase-client/src/test/java/org/apache/hadoop/hbase/util/TestThreadLocalPoolMap.java
* PoolMap does not discard any elements anymore. If an element is put,
it always stores it. The reason: it stores expensive resources (rpc
connections) which would lead to resource leak if we simple discard it.
RpcClients can reference netty ByteBufs which are reference counted.
Resource cleanup is done by AbstractRpcClient.cleanupIdleConnections().
* Removed concurrency from PoolMap. It is called only from
AbstractRpcClient in synchronized blocks, so it doesn't have to be
thread-safe.
* Max size is a hint for RoundRobinPool. Until maxSize is not reached,
it will force users to create new resources. So it works the same as
before, but it does not prevent putting more elements then maxSize.
* ThreadLocalPool doesn't uses ThreadLocal class anymore. It stores
resources on thread basis, but …
=> HBASE-25307 ThreadLocal pooling leads to NullPointerException

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/CheckAndMutate.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RowMutations.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/Table.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ResponseConverter.java, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/client/RemoteHTable.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MiniBatchOperationInProgress.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Region.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTable.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableBatch.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableNoncedRetry.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestCheckAndMutate.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide3.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide5.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/SimpleRegionObserver.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestRegionObserverInterface.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/RegionAsTable.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntrySinkFilter.java, hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftTable.java
=> HBASE-25242 Add Increment/Append support to RowMutations

hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java
[HBASE-25330](https://issues.apache.org/jira/browse/HBASE-25330)
=> HBASE-25330 RSGroupInfoManagerImpl#moveServers return is not set of servers moved

hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/BlockingRpcConnection.java, hbase-client/src/main/java/org/apache/hadoop/hbase/util/PoolMap.java, hbase-client/src/test/java/org/apache/hadoop/hbase/util/PoolMapTestBase.java, hbase-client/src/test/java/org/apache/hadoop/hbase/util/TestRoundRobinPoolMap.java, hbase-client/src/test/java/org/apache/hadoop/hbase/util/TestThreadLocalPoolMap.java
* PoolMap does not discard any elements anymore. If an element is put,
it always stores it. The reason: it stores expensive resources (rpc
connections) which would lead to resource leak if we simple discard it.
RpcClients can reference netty ByteBufs which are reference counted.
Resource cleanup is done by AbstractRpcClient.cleanupIdleConnections().
* PoolMap does not implement Map interface anymore, so ensuring
thread-safety has become easier. Put method is replaced with getOrCreate().
* ThreadLocalPool doesn't use ThreadLocal class anymore. It stores
resources on thread basis, but it doesn't remove values when a thread
exits. Again, proper cleanup is done by cleanupIdleConnections().
Signed-off-by: Wellington Chevreuil …
=> HBASE-25307 ThreadLocal pooling leads to NullPointerException (#2685)

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableRegionLocator.java
The methods in `AsyncTableRegionLocator` should not throw IOException directly. Current behavior of `getStartEndKeys` basic method couldn't throw `IOException`, therefore it should only modify the method signature with removing the throwing `IOException`.
=> HBASE-24966 The methods in AsyncTableRegionLocator should not throw IOException directly

src/main/asciidoc/_chapters/sync_replication.adoc
Fix spelling error :
from DOWNGRANDE_ACTIVE to DOWNGRADE_ACTIVE
=> HBASE-25366 [Documentation] Fix spelling error in sync_replication.adoc

hbase-server/src/main/java/org/apache/hadoop/hbase/constraint/ConstraintProcessor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/visibility/VisibilityController.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestRegionCoprocessorHost.java
1. Added a check for Object class in RegionCoprocessorHost to avoid wrong initialization of hasCustomPostScannerFilterRow
2. Removed duplication implementation from AccessController, VisibilityController & ConstraintProcessor (which are not required currently)
=> HBASE-25277 postScannerFilterRow impacts Scan performance a lot in HBase 2.x

dev-support/create-release/release-util.sh
Don't install when we call deploy -- makes for doubling of .asc.
Added more to the README while in here and added logging
timestamp so we can tell where we are spending time.
=> HBASE-25376 [create-release] Fix double .asc

dev-support/create-release/README.txt, dev-support/create-release/do-release-docker.sh, dev-support/create-release/release-build.sh, dev-support/create-release/release-util.sh
Added logging of timestamp so we can tell where we are spending time.
Added context to the README copied from head of entrance script.
=> HBASE-25380 [create-release] Add timestamping to log output

hbase-common/pom.xml, hbase-common/src/test/java/org/apache/hadoop/hbase/ClassFinder.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestClassFinder.java
The test `TestClassFinder#testClassFinderDefaultsToOwnPackage` compares two sets from `allClassesFinder.findClasses`. However, the function `allClassesFinder.findClasses` does not return the deterministic order result. From code trace, the root cause is at `ClassFinder.findClassesFromJar` and `ClassFinder.findClassesFromFiles`. They use `HashSet` to store `classes` and `listFiles` to get file array. However, `HashSet` and `listFiles` do not guarantee that order, and the assertion can fail if the order differs. 
The PR uses `LinkedHashSet` and sorts file array to make the order deterministic.
=> HBASE-25370 Fix flaky test TestClassFinder#testClassFinderDefaultsToOwnPackage

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/FixedFileTrailer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestFixedFileTrailer.java
Fallback to MetaCellComparator when "org.apache.hadoop.hbase.CellComparator$MetaCellComparator" or "org.apache.hadoop.hbase.CellComparatorImpl$MetaCellComparator" is set in Hfile trailer
=> HBASE-25378 Legacy comparator in Hfile trailer will fail to load

hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java
[HBASE-25365](https://issues.apache.org/jira/browse/HBASE-25365)
=> HBASE-25365 The log in move_servers_rsgroup is incorrect

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RemoteProcedureResultReporter.java
Added "hbase.rpc.shortoperation.pause.time" for initial pause for reportRegionStateTransition.
=> HBASE-25379 Make retry pause time configurable for regionserver short operation RPC (reportRegionStateTransition/reportProcedureDone)

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
stopServer on RS is slient, which make client  think he/she success shutdown RS. The message to client after fix is:
ERROR RuntimeError: org.apache.hadoop.hbase.security.AccessDeniedException: Insufficient permissions for user 'user1' (global, action=ADMIN)
=> HBASE-25441 : add security check for RSRpcSever

hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableDescriptorBuilder.java, hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/PrettyPrinter.java, hbase-shell/src/main/ruby/hbase/admin.rb
[HBASE-25439](https://issues.apache.org/jira/browse/HBASE-25439)
Add a new unit 'BYTE' to pretty print value of size, such as MAX_FILESIZE, MEMSTORE_FLUSHSIZE
=> HBASE-25439 Add BYTE unit in PrettyPrinter.Unit

hbase-it/src/test/java/org/apache/hadoop/hbase/mapreduce/IntegrationTestImportTsv.java
Currently IntegrationTestImportTsv is generating HFiles under the working directory of the hdfs user executing the tool, before bulkloading it into HBase.
Assuming you encrypt the HBase root directory within HDFS (using HDFS Transparent Encryption), you can bulkload HFiles only if they sit in the same encryption zone in HDFS as the HBase root directory itself.
When IntegrationTestImportTsv is executed against a real distributed cluster and the working directory of the current user (e.g. /user/hbase) is not in the same encryption zone as the HBase root directory (e.g. /hbase/data) then you will get an exception:
```
ERROR org.apache.hadoop.hbase.regionserver.HRegion: There was a partial failure due to IO when attempting to load d : …
```
=> HBASE-25318 Configure where IntegrationTestImportTsv generates HFiles

hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitWALManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestSplitWALManager.java
- If 'hbase.wal.dir' and 'hbase.rootdir' are configured to different filesystem instances, SplitWALRemoteProcedure archived split WAL failed since SplitWALManager using wrong fs instance. SplitWALManager should use WAL corresponding fs instance.
=> HBASE-25445: Use WAL FS instead of master FS in SplitWALManager

dev-support/create-release/release-util.sh
I did the following to test this change.
$ cd dev-support/create-release
$ export YETUS_HOME=~/checkouts/apache-yetus-0.12.0
$ . release-util.sh # source'd the utility file
$ update_releasenotes ~/checkouts/hbase.apache.git 2.3.4 # Called the function that makes the changes to CHANGES.md
=> HBASE-25487 [create-release] changes.md update broken

dev-support/git-jira-release-audit/git_jira_release_audit.py
Profiler shows a lot of time spent in the UPDATE SQL statement. Remove the tight loop and let SQL
do a bulk-update instead.
=> HBASE-25489 improve performance of --parse-release-tags

hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/client/Client.java
HBase Nightly test on branch-2.2 reports warning on InputStream
cleanup while it is used in a try-with-resource block. This commit adds
a SuppressWarnings annotation.
=> HBASE-25499 False-positive findbugs issue on branch-2.2

dev-support/release-vm/.gitignore, dev-support/release-vm/README.md, dev-support/release-vm/Vagrantfile, dev-support/release-vm/provision/focal.sh, dev-support/release-vm/puppet/production/.gitignore, dev-support/release-vm/puppet/production/.librarian/puppet/config, dev-support/release-vm/puppet/production/Puppetfile, dev-support/release-vm/puppet/production/data/nodes/rmvm.yaml, dev-support/release-vm/puppet/production/environment.conf, dev-support/release-vm/puppet/production/hiera.yaml, dev-support/release-vm/puppet/production/manifests/default.pp
This adds a Vagrantfile and supporting automation that creates a virtual machine environment
suitable for running the create-release scriping.
=> HBASE-25375 Provide a VM-based release environment

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestSplitWALManager.java
- zk based wal splitting was deprecated as part of HBASE-24632 and the changes still aren't there in branch-2.3. Hence the assumption of default wal splitting to be procedure-based rather than zk-based doesn't hold for the said branch. The same needs to be considered while setting up the tests in TestSplitWALManager in absence of which the tests were failing in the branch due to NPE. 
- The changes have been tested on branch-2.3 and the test failures are also gone.
=> HBASE-25475: Unset zk based wal splitting explicitly in tests

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
[HBASE-25513](https://issues.apache.org/jira/browse/HBASE-25513)
=> HBASE-25513 When the table is turned on normalize, the first region may not be merged even the size is 0

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
=> Backport "HBASE-25513 When the table is turned on normalize, the first region may not be merged even the size is 0 (#2887)"

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
[HBASE-25482](https://issues.apache.org/jira/browse/HBASE-25482)
If the table is set NormalizerTargetRegionSize, we take NormalizerTargetRegionSize as avgRegionSize and return it. So the totalSizeMb of table is not always calculated.
=> HBASE-25482 Improve SimpleRegionNormalizer#getAverageRegionSizeMb

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/FullTableBackupClient.java
Hbase Backup doesn't make use of bandwidth and worker parameters and hence can't control amount of bandwidth going out of hbase cluster. This bugfix is for controlling the same
=> HBASE-25501 BugFix: Unused backup bandwidth and workers parameter

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/executor/EventType.java, hbase-server/src/main/java/org/apache/hadoop/hbase/executor/ExecutorType.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
Adds "hbase.master.executor.merge.dispatch.threads" and defaults to 2.
Also adds additional logging that includes the number of split plans
and merge plans computed for each normalizer run.
=> HBASE-25528: Dedicated merge dispatch thread pool on master

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/executor/EventType.java, hbase-server/src/main/java/org/apache/hadoop/hbase/executor/ExecutorType.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
Adds "hbase.master.executor.merge.dispatch.threads" and defaults to 2.
Also adds additional logging that includes the number of split plans
and merge plans computed for each normalizer run.
(cherry picked from commit 36b4698cea9485f4d491612342b8c841e1c3db86)
=> HBASE-25528: Dedicated merge dispatch threadpool on master

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ColumnFamilyDescriptorBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestColumnFamilyDescriptorBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableDescriptorBuilder.java, hbase-shell/src/test/ruby/hbase/admin_test.rb
The empty metadata/configuration in Table or CF is meaningless (Please correct me if I'm wrong). So we should remove the metadata/configuration if is set empty string, like set to null.
=> HBASE-25533 The metadata of the table and family should not be an empty string

src/main/asciidoc/_chapters/security.adoc
Add a comment when using Secure HTTP (HTTPS) for the Web UI
=> HBASE-25498 [Documentation] Add a comment when using Secure HTTP (HTTPS) for the Web UI

hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/TransitRegionStateProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRetainAssignmentOnRestart.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRetainAssignmentOnRestartSplitWithoutZk.java
Added "hbase.master.scp.retain.assignment" configuration parameter to contol the retain assignment during SCP.
=> HBASE-24900 Make retain assignment configurable during SCP

hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/PerfTestCompactionPolicies.java
Adds mock for `getRegionInfo` which was missing earlier.
=> HBASE-25546 PerfTestCompactionPolicies is failing because of NPE

hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/PerfTestCompactionPolicies.java
Added HBaseClassTestRule for PerfTestCompactionPolicies
=> HBASE-25546 PerfTestCompactionPolicies is failing because of NPE (addendum)

hbase-server/src/main/java/org/apache/hadoop/hbase/util/RegionMover.java
The key point is that the conf variable has not been initialized before init RackManager.
=> HBASE-25554 NPE when init RegionMover

hbase-common/src/main/java/org/apache/hadoop/hbase/TableName.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestTableName.java
fix bug: string out of bounds when construct illegal tablename error
=> HBASE-25512 May throw StringIndexOutOfBoundsException when construct illegal tablename error

hbase-shell/src/main/ruby/jar-bootstrap.rb
=> HBASE-24772 Use GetoptLong or OptionParser in hbase-shell

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestRegionNormalizerWorker.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
Table can be enabled and disabled merge/split in TableDescriptor, we should judge before calculating the plan.
Part of the configuration can be set by table level. For example, hbase.normalizer.min.region.count can be set by "alter ‘table’, CONFIGURATION=>{'hbase.normalizer.min.region.count' => '5'}". If the table is not set, then use the global configuration which is set in hbase-site.xml.
=> HBASE-25534 Honor TableDescriptor settings earlier in normalization

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorker.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestRegionNormalizerWorker.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
=> Backport "HBASE-25534 Honor TableDescriptor settings earlier in normalization (#2917)" to branch-2.4

dev-support/spotbugs-exclude.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCacheFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/LruAdaptiveBlockCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestLruAdaptiveBlockCache.java
Instead of https://github.com/apache/hbase/pull/1257 (there were some problems with rebase)
=> HBASE-23887 AdaptiveLRU cache

hbase-server/src/main/java/org/apache/hadoop/hbase/executor/ExecutorService.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServicesForStores.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestExecutorStatusChore.java, hbase-server/src/test/java/org/apache/hadoop/hbase/executor/TestExecutorService.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionReplayEvents.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSplitLogWorker.java
Still marked as a WIP because the defaults have not been tuned yet.
All the code is in place, I still need to identify the low priority
thread pools and tune them to release unused threads quickly.
=> HBASE-25547: Thread pools should release unused resources

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java
Currently, when we deque we do not reset the current wal path, and it blows up while opening the next log, the current path still points to previous wal which is not correct.
```java
private boolean openNextLog() throws IOException {
Path nextPath = logQueue.peek();
if (nextPath != null) {
openReader(nextPath); <=== if we blow up here
if (reader != null) {
return true;
}
} else {
// no more files in queue, this could happen for recovered queue, or for a wal group of a sync
// replication peer which has already been transited to DA or S.
setCurrentPath(null);
}
return false;
} 
```
=> HBASE-25541: Setting the path to null when we dequeue the current log

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationGlobalSourceSourceImpl.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RecoveredReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RecoveredReplicationSourceShipper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationLogQueue.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceLogQueue.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceShipper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReader.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/SerialReplicationSourceWALReader.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AbstractFSWALProvider.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceLogQueue.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
https://issues.apache.org/jira/browse/HBASE-25539
=> [HBASE-25539]  Add age of oldest wal metric

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSource.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationGlobalSourceSourceImpl.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RecoveredReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RecoveredReplicationSourceShipper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceLogQueue.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceShipper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReader.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/SerialReplicationSourceWALReader.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AbstractFSWALProvider.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceLogQueue.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
Same as https://github.com/apache/hbase/pull/2945 which was for master branch.
Master patch didn't apply cleanly. Some minor conflicts.
=> [HBASE-25539] Add age of oldest wal metric

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReader.java
=> HBASE-25562 ReplicationSourceWALReader log and handle exception immediately without retrying

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReaderThread.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
Please find the details in jira:
https://issues.apache.org/jira/browse/HBASE-25596
=> HBASE-25596: Fix NPE and avoid permanent unreplicated data due to EOF

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogReader.java
ProtobufLogReader#readNext may be called by code that attempts to advance the reader but does not necessarily expect to succeed, for example WALEntryStream#tryAdvanceEntry. Much of the logging in this method is at TRACE level. Other logging at WARN level will be frequently emitted, as often as a few times per minute, and this will cause false positive assessment from operators that they are experiencing a bug. 
Fix the mixed intent with respect to log levels in readNext. Log at only DEBUG level or below.
=> HBASE-25556 Frequent replication "Encountered a malformed edit" warnings

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerCall.java
ServerCall.java: calling wrapWithSasl() was moved to getResponse(), so
the SASL wrapping is delayed until the reply is sent back to the client.
=> HBASE-25586 Fix HBASE-22492 on branch-2 (SASL GapToken)

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/ReplicationSourceDummyWithNoTermination.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceManagerBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceManagerManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceWithoutReplicationZnodes.java
There was a review comment on the original of HBASE-25583 [here](https://github.com/apache/hbase/pull/2960#discussion_r579384941) for an improvement to call the remove peer workflow as a whole instead of just terminating source.
It makes sense to call the removePeer for no node exception on peer since it will do some aditional cleanup.
@shahrs87 Can you please review it here?
@apurtell @wchevreuil Can you please review it too since you reviewed the original PR for HBASE-25583.
=> HBASE-25583: NoNodeException of the peer should call the remove peer workflow

dev-support/create-release/release-build.sh, dev-support/create-release/vote.tmpl
tested locally by doing a dry run of the hbase-operator-tools repo.
=> HBASE-25580 Release scripts should include in the vote email the git hash that the RC tag points to

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/RSStatusTmpl.jamon, hbase-server/src/main/resources/hbase-webapps/master/table.jsp
HBASE-25402 HBase UI: sorting order by start key or end key is not considering empty start key/end key
=> HBASE-25402 HBase UI: sorting order by start key or end key is not considering empty start key/end key

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/HeterogeneousRegionCountCostFunction.java
This PR fixes the issue mentioned [here](https://issues.apache.org/jira/browse/HBASE-25626).
=> HBASE-25626 Possible Resource Leak in HeterogeneousRegionCountCostFunction

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon, hbase-server/src/main/resources/hbase-webapps/static/js/parser-date-iso8601.min.js, pom.xml
embedded minimized ISO-8601 date Parser v2.18.0
=> HBASE-25367 Sort broken after Change 'State time' in UI

hbase-common/src/main/resources/hbase-default.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactionAfterBulkLoad.java, src/main/asciidoc/_chapters/hbase-default.adoc
when compaction after bulkload is enable,  if bulkload is continuous,  considerable compaction events will be triggered, which increase load, bring about performance impact
=> HBASE-25603 Add switch for compaction after bulkload

hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestCurrentHourProvider.java
Disable this problematic test for now. May be removed after additional
discussion.
=> HBASE-25385 TestCurrentHourProvider fails if the latest timezone changes are not present

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/HeterogeneousRegionCountCostFunction.java
This PR addresses [this](https://issues.apache.org/jira/browse/HBASE-25626?focusedCommentId=17295043&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17295043) comment.
=> HBASE-25626 Possible Resource Leak in HeterogeneousRegionCountCostFunction (branch-2)

hbase-client/src/main/java/org/apache/hadoop/hbase/HTableDescriptor.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptor.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java, hbase-common/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfo.java, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java, hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminServer.java, hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestTableDescriptorWithRSGroup.java
Added setRegionServerGroup API in TableDescriptorBuilder and getRegionServerGroup API in TableDescriptor
Handled impacted RSGroup APIs moveTables, moveServersAndTables and renameRSGroup
If rsgroup is specified in table descriptor then use specified rsgroup otherwise  fallback to existing logic to identify the table's rsgroup.
=> HBASE-25492: Create table with rsgroup

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
[HBASE-25648](https://issues.apache.org/jira/browse/HBASE-25648)
From #2972 there was a change from
`if (!this.regionNormalizerTracker.isNormalizerOn()) {`
to
`if (isNormalizerOn()) {`
(missing `!` it looks like)
and then
```
if (quotaManager.getNamespaceQuotaManager() != null &&
quotaManager.getNamespaceQuotaManager().getState(table.getNamespaceAsString()) != null){
LOG.debug("Skipping normalizing " + table + " since its namespace has quota");
continue;
}
```
changed to
```
final NamespaceAuditor namespaceQuotaManager = quotaManager.getNamespaceQuotaManager();
if(namespaceQuotaManager == null) {
LOG.debug("Skipping normalizing since namespace quota is null");
return false;
}
if (namespaceQuotaManager.getState(table.getNamespaceAsString()) != null) {
LOG.debug("Skipping normalizing " + …
```
=> HBASE-25648 Fix normalizer TestSimpleRegionNormalizerOnCluster branch-1

dev-support/create-release/release-build.sh, dev-support/create-release/vote.tmpl
In the hbase project's RC staging area we use bare version/RC numbers only for the main project. We already have logic for getting the correct directory for copying things into svn, make that logic more visible and use it for the vote template as well.
tested by doing a local dryrun for hbase-thirdparty and examining the RC vote message generated.
=> HBASE-25573 release script generated vote template has incorrect staging area

hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/Constants.java, hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/client/Client.java
Added hbase.rest.client.conn.timeout & hbase.rest.client.socket.timeout configurations
=> HBASE-25374 Make REST Client connection and socket time out configurable

src/main/asciidoc/_chapters/hbase_mob.adoc
This was confusing for me, as I managed to use the wrong configuration. I will check the other branches, as I was working with 2.2 when noticing this. Edit: should be a clean cherry-pick to 2.4, 2.3 and 2.2, same typos there.
=> HBASE-25669 Fix typo of hbase.mob.compaction.chore.period in the docs

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationGlobalSourceSourceImpl.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSourceImpl.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/metrics2/lib/DynamicMetricsRegistry.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSource.java
These metrics keep track of sources getting initialized, and if for any reason source is stuck during initialization, monitoring and alerting can be built on top of that.
=> HBASE-25627: HBase replication should have a metric to represent if the source is stuck getting initialized

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionInfo.java
The RegionInfo class uses  `DataInputStream.read(byte[lengthOfPBMagic])` to read the protobuf magic marker from the beginning of the stream.
The code in RegionInfo assumes that the passed byte buffer will be filled, but the DataInputStream class only guarantees that it will read at most lengthOfPBMagic bytes.
This sometimes causes errors stating that region info file could not be parsed.
The fix is to simply issue multiple read calls until lengthOfPBMagic bytes have been read.
=> HBASE-25674 - RegionInfo.parseFrom(DataInputStream) sometimes fails to read the protobuf magic marker

bin/graceful_stop.sh
This is just a very minor improvement over https://github.com/apache/hbase/pull/2973 (that was actually pushed by @saintstack at https://github.com/apache/hbase/commit/59ec375d679dcbf1701a92d4206ecc676a8fb069).
However, I like the approach to use "localhost" as the argument hostname for the purpose instead of having to pass the fqdn itself, so I would like to add such option (see https://github.com/apache/hbase/pull/3048).
=> HBASE-25594 Make easier to use graceful_stop on localhost mode

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceLogQueue.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
https://issues.apache.org/jira/browse/HBASE-25679?filter=-2
=> HBASE-25679 Size of log queue metric is incorrect

hbase-server/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java, hbase-server/src/test/java/org/apache/hadoop/hbase/mapreduce/TestHFileOutputFormat2.java
https://issues.apache.org/jira/browse/HBASE-25672
https://issues.apache.org/jira/browse/HBASE-25608
Backport #2988 to branch-1
=> HBASE-25672 Backport HBASE-25608 to branch-1

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSource.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationGlobalSourceSource.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSourceImpl.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/metrics2/lib/DynamicMetricsRegistry.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEndpoint.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSource.java
Please refer to jira for the description. 
https://issues.apache.org/jira/browse/HBASE-25627
=> HBASE-25627: [Backport]HBase replication should have a metric to represent if the source is stuck getting initialized

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
The issue is that FileInputStream is created with try-with-resources, so its close() is called right after the try sentence.
FileInputStream is a finalize class, when this object is garbage collected, its close() is called again.
To avoid this double-free resources, add guard against it.
=> HBASE-25691 Test failure: TestVerifyBucketCacheFile.testRetrieveFromFile

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterWrapperImpl.java
When a metrics source is configured in the metrics properties file for a standby master, because the master is not in the active role, getRegionNormalizerManager() returns null and some methods of MetricsMasterWrapperImpl do not properly test for this.
=> HBASE-25693 NPE getting metrics from standby masters (MetricsMasterWrapperImpl.getMergePlanCount)

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DumpClusterStatusAction.java
Trivial fix for
java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1067)
at org.apache.hadoop.hbase.chaos.actions.DumpClusterStatusAction.collectKnownRegionServers(DumpClusterStatusAction.java:67)
at org.apache.hadoop.hbase.chaos.actions.DumpClusterStatusAction.init(DumpClusterStatusAction.java:49)
at org.apache.hadoop.hbase.chaos.policies.PeriodicRandomActionPolicy.init(PeriodicRandomActionPolicy.java:70)
at org.apache.hadoop.hbase.chaos.monkies.PolicyBasedChaosMonkey.start(PolicyBasedChaosMonkey.java:127)
at org.apache.hadoop.hbase.IntegrationTestBase.startMonkey(IntegrationTestBase.java:199)
at org.apache.hadoop.hbase.IntegrationTestBase.setUpMonkey(IntegrationTestBase.java:189)
at …
=> HBASE-25699 [branch-1] UnsupportedOperationException in DumpClusterStatusAction

hbase-client/src/main/java/org/apache/hadoop/hbase/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java, hbase-protocol-shaded/src/main/protobuf/Client.proto, hbase-protocol/src/main/protobuf/MultiRowMutation.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MultiRowMutationEndpoint.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide5.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMalformedCellFromClient.java
=> HBASE-25703 Support conditional update in MultiRowMutationEndpoint

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
Hi:
I have found that in APIs, like execProcedure and execProcedureWithRet, have audit log to record who execute the master service. The log can be like:
LOG.info(master.getClientIdAuditPrefix() + " procedure request for: " + desc.getSignature());`
But it seems that we forget to audit execMasterService. We should add one.
old request is https://github.com/apache/hbase/pull/2937
=> HBASE-25558:Adding audit log for execMasterService

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
[HBASE-25726](https://issues.apache.org/jira/browse/HBASE-25726)
=> HBASE-25726 MoveCostFunction multiplier, default include

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestClientNoCluster.java, hbase-common/src/main/java/org/apache/hadoop/hbase/ServerName.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestServerName.java, hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodeAssignmentHelper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodesManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/favored/StartcodeAgnosticServerName.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/AssignmentVerificationReport.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionPlacementMaintainer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/HBaseFsck.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MetaMockingUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessorNoCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestConnectionImplementation.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestShortCircuitConnection.java, hbase-server/src/test/java/org/apache/hadoop/hbase/favored/TestFavoredNodeAssignmentHelper.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionPlacement.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestFavoredStochasticBalancerPickers.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerAbort.java
=> HBASE-25734 Backport HBASE-24305 to branch-2.4

hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java
Starting ZOOKEEPER-2251, client requests exceeding a timeout can throw
a KeeperException with REQUESTTIMEOUT opcode set. RecoverableZookeeper
doesn't transparently retry in such cases.
=> HBASE-25743: Retry REQUESTTIMEOUT based KeeperExceptions in ZK client.

hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/HBaseRpcController.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/RpcControllerFactory.java
Apache Phoenix has had an unrecognized dependency on RpcControllerFactory and HBaseRpcController. These interfaces are used to override setPriority for appropriate dispatch of requests for Phoenix system or index tables to separate pools. This is a reasonable use of these interfaces but the audience annotations were never updated to reflect this usage. Also seems reasonable to do so as there has been no issue here for four years. (Phoenix commit was made in 2017.)
=> HBASE-25750 Upgrade RpcControllerFactory and HBaseRpcController from Private to LimitedPrivate(COPROC,PHOENIX)

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/package-info.java
=> Backport "HBASE-25744 Change default of `hbase.normalizer.merge.min_region_size.mb` to `0`" to branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcDuplexHandler.java, hbase-common/src/main/java/org/apache/hadoop/hbase/ChoreService.java
Some potential expensive debug-logging calls are partially guarded by `isXXXEnabled()`. Therefore,
- Moving some potential expensive statements into the adjacent `isDebugEnabled` in `NettyRpcDuplexHandler.java`
- Moving the `isTraceEnabled` up to the beginning of `printChoreDetails` and `printChoreServiceDetails` in `ChoreService.java `.
=> HBASE-25762 Improvement for some debug-logging guards

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
Signed-off-by: stack <stack@duboce.net>
Reviewed-by: Viraj Jasani <vjasani@apache.org>
=> Backport "HBASE-25653 Add units and round off region size to 2 digits after decimal (#3046)" to branch-2.3

hbase-http/pom.xml, hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java, hbase-http/src/test/java/org/apache/hadoop/hbase/http/TestHttpServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
Requesting reviews from folks whom I believe have spent time around our InfoService.
=> HBASE-25770 Http InfoServers should honor gzip encoding when requested

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
fix [HBASE-25776](https://issues.apache.org/jira/browse/HBASE-25776)
=> HBASE-25776 Use Class.asSubclass to fix the warning in StochasticLoadBalancer.loadCustomCostFunctions

hbase-http/pom.xml, hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java, hbase-http/src/test/java/org/apache/hadoop/hbase/http/TestHttpServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
=> Backport "HBASE-25770 Http InfoServers should honor gzip encoding when requested (#3159)" to branch-2.4

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
TestAtomicOperation.testMultiRowMutationMultiThreads deadlocks.
There is an easy fix for the test that synchronizes on the CHM instead of the object. We already have a Findbugs exceptions for synchronization on the CHM and get-then-set on it is what we synchronizing for anyway.
This is only relevant for branch-1 because we have to synchronize get-then-set due to Java 7 compatibility. For branch-2 and master we use CHM#computeIfPresent.
=> HBASE-25809 [branch-1] TestAtomicOperation.testMultiRowMutationMultiThreads deadlock

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
From c96b642f15d (HBASE-15265 Implement an asynchronous FSHLog)
- Better formatting; use { } instead of dangling ifs, elses, etc. in RingBufferEventHandler.
From b1269ec57ff (HBASE-19811 Fix findbugs and error-prone warnings in hbase-server (branch-2))
- Change syncFuturesCount in RingBufferEventHandler from 'volatile int' to AtomicInteger.
'volatile' is insufficient for multithreaded access.
From afc1746757f (HBASE-24034 [Flakey Tests] A couple of fixes and cleanups)
- Make a local copy of takeSyncFuture after we get it in SyncRunner#run.
This looks like a workaround for a JIT/compiler bug in some Java versions. (SCARY)
=> HBASE-25808 [branch-1] Backport improvements to FSHLog from branch-2

hbase-mapreduce/pom.xml, hbase-resource-bundle/src/main/resources/META-INF/LICENSE.vm, hbase-server/pom.xml, hbase-shaded/pom.xml
Need to add to allowed-licenses list too....
=> HBASE-25792 Filter out o.a.hadoop.thirdparty building shaded jars

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSDumpServlet.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/encoding/TestChangingEncoding.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/encoding/TestLoadAndSwitchEncodeOnDisk.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactSplitThread.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerOnlineConfigChange.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/throttle/TestCompactionWithThroughputController.java
Minor refactor. Make the `compactSplitThread` member field of `HRegionServer` private, and gate
all access through the getter method.
=> HBASE-25779 HRegionServer#compactSplitThread should be private

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSDumpServlet.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/encoding/TestChangingEncoding.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/encoding/TestLoadAndSwitchEncodeOnDisk.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactSplitThread.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerOnlineConfigChange.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/throttle/TestCompactionWithThroughputController.java
Minor refactor. Make the `compactSplitThread` member field of `HRegionServer` private, and gate all access through the getter method.
Signed-off-by: Yulin Niu <niuyulin@apache.org>
Signed-off-by: Pankaj Kumar <pankajkumar@apache.org>
=> Backport "HBASE-25779 HRegionServer#compactSplitThread should be private" to branch-2

src/main/asciidoc/_chapters/architecture.adoc, src/main/asciidoc/_chapters/hbase_mob.adoc
This PR refers to [https://issues.apache.org/jira/browse/HBASE-25816](url)
While going through the reference guide, I found these small changes that can be made to the documentation of the "Architecture" part of it. Hence I'm filing this Jira to track those changes.
=> HBASE-25816: Improve the documentation of Architecture section of reference guide

hbase-server/src/main/java/org/apache/hadoop/hbase/master/janitor/CatalogJanitor.java
We claim in a WARN level log line to be 
"Playing-it-safe skipping merge/ split gc'ing of regions from hbase:meta while regions-in-transition (RIT)" 
but do not actually skip because of a missing return. 
Playing it safe has proven unnecessary, I would say. Nonetheless here is a patch that adds the missing return, for discussion.
=> HBASE-25840 CatalogJanitor warns about skipping gc of regions during RIT, but does not actually skip

hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStates.java
RegionStates#getAssignmentsForBalancer is used by the HMaster to collect all regions of interest to the balancer for the next chore iteration. We check if a table is in disabled state to exclude regions that will not be of interest (because disabled regions are or will be offline) or are in a state where they shouldn't be mutated (like SPLITTING). 
The current checks are not actually comprehensive. For example, splitting states are considered, but not merging. 
Filter out regions not in OPEN or OPENING state when building the set of interesting regions for the balancer to consider. Only regions open (or opening) on the cluster are of interest to balancing calculations for the current iteration. Regions in all other states can be expected to not be of interest – either offline (OFFLINE, or …
=> HBASE-25836 RegionStates#getAssignmentsForBalancer should only care about OPEN or OPENING regions

hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
A SplitTableRegionProcedure may already be running when a regionserver report is received that includes a split request. The outcome is multiple SplitTableRegionProcedure procedures scheduled for the split request, only one of which can succeed. The others error out.
Do not create a split procedure in response to a region state change report if the region is not open or already splitting.
=> HBASE-25835 Ignore duplicate split requests from regionserver reports

hbase-server/src/main/java/org/apache/hadoop/hbase/master/janitor/CatalogJanitor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/janitor/TestCatalogJanitorInMemoryStates.java
In CatalogJanitor we schedule GCRegionProcedure to clean up both filesystem and in-memory state after a split, and GCMultipleMergedRegionsProcedure to do the same for merges. Both of these procedures clean up in-memory state, but CatalogJanitor also does this redundantly just after scheduling the procedures. The cleanup should be done in only one place. Presumably we are using the procedures to do it in a principled way. This is least a nit, but probably a source of future bugs. Remove the redundancy in CatalogJanitor and fix any follow on issues, like test failures.
=> HBASE-25854 Remove redundant AM in-memory state changes in CatalogJanitor

hbase-server/src/main/java/org/apache/hadoop/hbase/io/Reference.java
` DataInputStream.read(byte[lengthOfPBMagic])`Does not guarantee to read `lengthOfPBMagic` bytes.
Multiple read calls need to be issued.
=> HBASE-25859 Reference class incorrectly parses the protobuf magic marker

hbase-it/src/test/java/org/apache/hadoop/hbase/DistributedHBaseCluster.java, hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestingUtility.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartRsHoldingMetaAction.java, hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/util/ChaosMonkeyRunner.java, hbase-it/src/test/java/org/apache/hadoop/hbase/test/IntegrationTestBigLinkedList.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java
Minor edits to a few log messages.
Explain how the '-c' option works when passed to ChaosMonkeyRunner.
Some added notes on ITBLL.
Fix whacky 'R' and 'Not r' thing in Master (shows when you run ITBLL).
In HRS, report hostname and port when it checks in (was debugging issue
where Master and HRS had different notions of its hostname).
Spare a dirty FNFException on startup if base dir not yet in place.
=> HBASE-25867 Extra doc around ITBLL

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManager.java
Headsup @rda3mon , our policy is that commit summary start with the JIRA ID and the text matches the jira summary. Reverting this so it can be re-applied according to policy.
Reverts apache/hbase#3246
=> Revert "HBASE-25870 while creating manifest, search only for ancestors insteadd of all of…"

dev-support/spotbugs-exclude.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcServer.java
RegionServer failed to start with IllegalThreadStateException due to race condition in AuthenticationTokenSecretManager's start & retrievePassword method
=> HBASE-25875 RegionServer failed to start with IllegalThreadStateException due to race condition in AuthenticationTokenSecretManager

hbase-common/src/main/java/org/apache/hadoop/hbase/HBaseConfiguration.java, hbase-common/src/main/java/org/apache/hadoop/hbase/io/ByteBuffAllocator.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/DNS.java, hbase-common/src/test/java/org/apache/hadoop/hbase/TestHBaseConfiguration.java, hbase-common/src/test/java/org/apache/hadoop/hbase/io/TestByteBuffAllocator.java, hbase-common/src/test/resources/hbase-deprecated-conf.xml, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/WALPlayer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCacheFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, src/main/asciidoc/_chapters/offheap_read_write.adoc
=> Backport "HBASE-25861 Correct the usage of Configuration#addDeprecation (#3249)" to branch-2

hbase-common/src/main/java/org/apache/hadoop/hbase/KeyValue.java, hbase-common/src/main/java/org/apache/hadoop/hbase/io/BoundedDelegatingInputStream.java, hbase-common/src/main/java/org/apache/hadoop/hbase/io/DelegatingInputStream.java, hbase-protocol-shaded/src/main/protobuf/server/region/WAL.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractProtobufLogWriter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/CompressionContext.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogReader.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ReaderBase.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/WALCellCodec.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncWALReplayValueCompression.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestWALCellCodecWithCompression.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestWALReplayValueCompression.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestCompressedWAL.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplitValueCompression.java
WAL storage can be expensive, especially if the cell values represented in the edits are large, consisting of blobs or significant lengths of text. Such WALs might need to be kept around for a fairly long time to satisfy replication constraints on a space limited (or space-contended) filesystem.
We have a custom dictionary compression scheme for cell metadata that is engaged when WAL compression is enabled in site configuration. This is fine for that application, where we can expect the universe of values and their lengths in the custom dictionaries to be constrained. For arbitrary cell values it is better to use one of the available compression codecs, which are suitable for arbitrary albeit compressible data.
**Microbrenchmark Results**
Site configuration used:
<property> …
=> HBASE-25869 WAL value compression

hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftHBaseServiceHandler.java
When opened scanner is not properly closed, it remains scannerMap forever.
To resolve this problem, make scannerMap to Guava Cache so that can be expired on set time.
https://issues.apache.org/jira/browse/HBASE-25817
=> HBASE-25817 Use GuavaCache in thrift server hashmap

hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotFileCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotHFileCleaner.java
More details in [HBASE-25899](https://issues.apache.org/jira/browse/HBASE-25899)
=> HBASE-25899 Improve efficiency of SnapshotHFileCleaner

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DefaultStoreFlushContext.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFlushContext.java
We need this to conduct other tasks related to flush without renames.
=> HBASE-25907 Move StoreFlushContext out of HStore and make it pluggable

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestClusterPortAssignment.java
Disabled port auto assignment when port is in use.
Disabled hdfs cache as restart mini cluster will fail in one jvm if hdfs cache is enabled.
Use exception root case to determine address/port in use with BindException.
=> HBASE-25910 - Fix port assignment test

hbase-common/src/main/java/org/apache/hadoop/hbase/io/compress/Compression.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestCompressionTest.java
Undo asserts that LZ4 and SNAPPY fails if their native libs are NOT
loaded; as of hadoop 3.3.1, LZ4 and SNAPPY can work w/o native libs.
=> HBASE-25940 Update Compression/TestCompressionTest: LZ4, SNAPPY, LZO

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestFSHLogWALEntryStream.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
This bug was exposed by the test from HBASE-25924. Since this wal
implementations close the wal asynchronously, replication can potentially
miss the trailer bytes. (see jira comment for detailed analysis).
While this is not a correctness problem (since trailer does not have any entry data),
it erroneously bumps a metric that is used to track skipped bytes in WAL resulting
in false alarms which is something we should avoid.
=> HBASE-25932: Ensure replication reads the trailer bytes from WAL.

hbase-client/src/main/java/org/apache/hadoop/hbase/CompactionServerMetrics.java, hbase-client/src/main/java/org/apache/hadoop/hbase/CompactionServerMetricsBuilder.java, hbase-protocol-shaded/src/main/protobuf/server/ClusterStatus.proto, hbase-protocol-shaded/src/main/protobuf/server/CompactionServerStatus.proto, hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/CompactionServerListTmpl.jamon, hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/compaction/CompactionOffloadManager.java
the ServerLoad has RegionLoad, ReplicationLoadSource/ReplicationLoadSink metrics, which is nothing to do with Compaction server. So,  introduce CompactionServerLoad, only has compaction related metircs
=> HBASE-25950 add basic compaction server metric

hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/Constants.java, hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftServer.java
Before HBASE-25930, the InfoServer was started first and it set the keystore type in the global keystore manager, which setting propagated to the thrift http server too, based on the InfoServer configuration "ssl.server.keystore.type". In HBASE-25930 the startup order changed, and the thrift http server configuration happens before the InfoServer start, so we lack this accidental configuration change now.
Given that we have independent keystore file path / password parameters already for the thrift http server, the proper solution is to create a new parameter for the keystore type of the thrift http server: hbase.thrift.ssl.keystore.type (defaulting to "jks").
=> HBASE-25987 Make SSL keystore type configurable for HBase ThriftServer

hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java, hbase-http/src/main/java/org/apache/hadoop/hbase/http/InfoServer.java
When starting a jetty http server, one can explicitly exclude certain (unsecure) SSL cipher suites. This can be especially important, when the HBase cluster needs to be compliant with security regulations (e.g. FIPS).
Currently it is possible to set the excluded ciphers for the ThriftServer ("hbase.thrift.ssl.exclude.cipher.suites") or for the RestServer ("hbase.rest.ssl.exclude.cipher.suites"), but one can not configure it for the regular InfoServer started by e.g. the master or region servers.
In this commit I want to introduce a new configuration "ssl.server.exclude.cipher.list" to configure the excluded cipher suites for the http server started by the InfoServer. This parameter has the same name and will work in the same way, as it was already implemented in hadoop (e.g. for …
=> HBASE-25993 Make excluded SSL cipher suites configurable for all Web UIs

hbase-common/src/main/java/org/apache/hadoop/hbase/io/BoundedDelegatingInputStream.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/WALCellCodec.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationCompressedWAL.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationValueCompressedWAL.java
Depending on which compression codec is used, a short read of the compressed bytes can cause catastrophic errors that confuse the WAL reader. This problem can manifest when the reader is actively tailing the WAL for replication. The input stream's available() method sometimes lies so cannot be relied upon. To avoid these issues when WAL value compression is enabled ensure all bytes of the compressed value are read in and thus available before submitting the payload to the decompressor.
Adds new unit tests TestReplicationCompressedWAL and TestReplicationValueCompressedWAL.
Without the WALCellCodec change TestReplicationValueCompressedWAL will fail.
=> HBASE-25994 Active WAL tailing fails when WAL value compression is enabled

hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java
JIRA: [HBASE-26000](https://issues.apache.org/jira/browse/HBASE-26000)
Optimize the display of ZK dump in the master web UI.
=> HBASE-26000 Optimize the display of ZK dump in the master web UI

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/SyncFuture.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestSyncFuture.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestSyncFutureCache.java
Currently uses coarse grained synchronized approach that seems to
create a lot of contention. This patch
- Use a reentrant lock instead of synchronized
- Condition variable based waiting rather than busy wait
- Removed synchronization for unnecessary fields..
=> HBASE-25998: Redo synchronization in SyncFuture

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/SyncFuture.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/SyncFutureCache.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLog.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestSyncFutureCache.java
(cherry picked from commit 5a19bcfa98b3ccd9f7fb1fb933248c808676d91c)
=> HBASE-25984: Avoid premature reuse of sync futures in FSHLog (#3371)

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestPostIncrementAndAppendBeforeWAL.java
https://issues.apache.org/jira/projects/HBASE/issues/HBASE-26001
=> HBASE-26001 When turn on access control, the cell level TTL of Increment and Append operations is invalid

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java, hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestPostMutationBeforeWAL.java
https://issues.apache.org/jira/browse/HBASE-26004
=> HBASE-26004: port HBASE-26001 (cell level tags invisible in atomic operations when access control is on)to branch-1

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
Add access check for switchCompaction
=> HBASE-25877:add access check for compactionSwitch

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRSRpcServices.java
JIRA: [HBASE-25934](https://issues.apache.org/jira/browse/HBASE-25934)
This JIRA [HBASE-25542](https://issues.apache.org/jira/browse/HBASE-25542) has added part of the client information before, we can also add username for RegionScannerHolder.
=> HBASE-25934 Add username for RegionScannerHolder

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSourceImpl.java
Useless check, impl cannot be null (guarded by instanceof)
https://issues.apache.org/jira/browse/HBASE-26035
=> HBASE-26035 Redundant null check in the compareTo function

hbase-common/src/main/java/org/apache/hadoop/hbase/util/ReflectionUtils.java, hbase-common/src/main/java/org/apache/hadoop/hbase/util/Threads.java
HBASE-13710 copied ReflectionUtils utility class from Hadoop, so we no longer need to use reflection to access the Hadoop's one.
=> HBASE-26041 Replace PrintThreadInfoHelper with HBase's own ReflectionUtils.printThreadInfo()

bin/hbase-cleanup.sh
=> HBASE-26030 hbase-cleanup.sh did not clean the wal dir if hbase.wal.dir configured individually

hbase-common/src/main/java/org/apache/hadoop/hbase/util/ReflectionUtils.java, hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestByteBufferUtils.java, hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestBytes.java, hbase-server/src/main/java/org/apache/hadoop/hbase/fs/HFileSystem.java, hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java, hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsKillRS.java
The patch is inspired by powermock: https://github.com/powermock/powermock/pull/1010 to work around the forbidden access to the modifiers field.
=> HBASE-25516 [JDK17] reflective access Field.class.getDeclaredField("modifiers") not supported

hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java, hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFunction.java, hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/DoubleArrayCost.java, hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java, hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/TableSkewCostFunction.java, hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/StochasticBalancerTestBase.java, hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java, hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerBalanceCluster.java, hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java, hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerLargeCluster.java
Re-apply the patch that was merged and reverted for flaky test because of refactoring afterwards.
The flaky tests was actually caused by two bugs: incorrect implementation of TableSkewCostfunction in the old codes and the tests were bent to pass.
There is another bug in the original tableSkew cost function for aggregation of the cost per table:
If we have 10 regions, one per table, evenly distributed on 10 nodes, the cost is scale to 1.0.
The more tables we have, the closer the value will be to 1.0. The cost function becomes useless.
All the balancer tests were set up with large numbers of tables with minimal regions per table. This artificially inflates the total cost and trigger balancer runs. Because of the fix, the default 0.05 minCostNeedBalance will not quite work. As a gap-stopper …
=> HBASE-25739 TableSkewCostFunction need to use aggregated deviation

hbase-common/src/main/java/org/apache/hadoop/hbase/io/ByteBuffAllocator.java, hbase-common/src/main/java/org/apache/hadoop/hbase/io/DeallocateRewriteByteBuffAllocator.java, hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MultiRowMutationEndpoint.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/security/visibility/VisibilityController.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestCheckAndMutateWithByteBuff.java, hbase-server/src/test/java/org/apache/hadoop/hbase/security/visibility/ExpAsStringVisibilityLabelServiceImpl.java
1. Add UT which can reproduce the error, and before HBASE-25187 regionserver JVM crashes.
2. Fix the scanner use in checkAndMutate. 
3. Fix all the use of HRegion.get() except tests. 
4. Make HRegion.get copy cells to heap
=> HBASE-26036 DBB released too early in HRegion.get() and dirty data for some operations

hbase-server/src/main/java/org/apache/hadoop/hbase/LocalHBaseCluster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/JVMClusterUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MiniHBaseCluster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/compactionserver/TestCompactionServer.java
Support create/shutdown compactionserver method in HBaseMinicluster
Fix weakness of TestCompactionServer
=> HBASE-25830 HBaseCluster support CompactionServer for UTs (addendum)

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CombinedBlockCache.java
https://issues.apache.org/jira/browse/HBASE-26083
=> HBASE-26083 L1 miss metric is incorrect when using CombinedBlockCache

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CombinedBlockCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/LruBlockCache.java
https://issues.apache.org/jira/browse/HBASE-26083
=> HBASE-26083 In branch-2 & branch-1 L1 miss metric is always 0 when using CombinedBlockCache

hbase-server/src/main/java/org/apache/hadoop/hbase/compactionserver/CompactionThreadManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java, hbase-server/src/test/java/org/apache/hadoop/hbase/compactionserver/TestCompactionServer.java
On regionserver, when do compact, cleanning TTL expired hfiles is before `store.selectCompaction`. So we need to add this logic on compactionserver
=> HBASE-26043 CompactionServer support compact TTL data

hbase-common/src/main/java/org/apache/hadoop/hbase/io/util/BlockIOUtils.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestBlockIOUtils.java
Use StreamCapabilities.hasCapabilities() to determine if the pread is supported by the input stream. Use reflection to invoke the bytebuffer pread method when it is available (because the ByteBufferPositionedReadable API is not available until Hadoop 3.3). This way, we can maintain backward compatibility for any Hadoop version above 2.9.
Passed a few unit tests building with Hadoop 3.3.1 and 3.1.2. Open this PR to run through the whole precommit test.
=> HBASE-21946 Use ByteBuffer pread instead of byte[] pread in HFileBlock when applicable

bin/hbase
https://issues.apache.org/jira/browse/HBASE-26146
This adds a new env var to the hbase bin, HBASE_HBCK_OPTS. As with other per-command opts, this will get added to HBASE_OPTS last so it will take precedence over previous values.
In order to maintain backwards compatibility with https://issues.apache.org/jira/browse/HBASE-15145, a default value for HBASE_HBCK_OPTS is pulled from AUTH_AS_SERVER_OPTS. 
I've tested this on our internal installation of hbase 1 and 2, with HBASE_HBCK_OPTS set and not set. Let me know if there are other tests I should be adding or running as well. I don't see any tests added in the similar patch provided for HBASE-15145.
=> HBASE-26146: Add support for HBASE_HBCK_OPTS

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/metrics/ExceptionTrackingSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/metrics/ExceptionTrackingSourceImpl.java, hbase-hadoop-compat/src/test/java/org/apache/hadoop/hbase/test/MetricsAssertHelperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/MetricsHBaseServer.java, hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftMetrics.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/ErrorThrowingGetObserver.java
Adds https://github.com/apache/hbase/pull/3544 to master branch
=> HBASE-26154: Adds exception metrics for QuotaExceededException and RpcThrottlingException

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/metrics/ExceptionTrackingSource.java, hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/metrics/ExceptionTrackingSourceImpl.java, hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/test/MetricsAssertHelperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/MetricsHBaseServer.java, hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftMetrics.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/ErrorThrowingGetObserver.java
See https://issues.apache.org/jira/browse/HBASE-26154
Also adds a debug log for unknown exceptions, which we've also found helpful.
=> HBASE-26154: Provide exception metric for quota exceeded and throttling

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
=> HBASE-26166 Fix a minor bug of table list on master ui

dev-support/create-release/do-release-docker.sh, dev-support/create-release/release-util.sh
Allow defining the below on the command-line (previously you
could not):
RC_COUNT
RELEASE_TAG
GPG_KEY
Adds an edit of the usage.
=> HBASE-26153 [create-release] Use cmd-line defined env vars

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/PluggableBlockingQueue.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/PluggableRpcQueueNotFound.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcScheduler.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestPluggableQueueImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSimpleRpcScheduler.java
https://issues.apache.org/jira/browse/HBASE-6908
Can pass in a FQCN to load as the call queue implementation.
Standardized arguments to the constructor are the max queue length, the PriorityFunction, and the Configuration.
`PluggableBlockingQueue` abstract class provided to help guide the correct constructor signature.
Hard fails with `PluggableRpcQueueNotFound` if the class fails to load as a `BlockingQueue<CallRunner>`
Testing added to `TestSimpleRpcScheduler` to verify that it can load a pluggable queue and that it fails when the queue class name is missing, incorrect, or not a `BlockingQueue<CallRunner>`
Upstreaming on behalf of Hubspot, we are interested in defining our own custom RPC queue and don't want to get involved in necessarily upstreaming internal requirements/iterations. I …
=> HBASE-6908: Add pluggable rpc queue implementation

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Get.java, hbase-client/src/main/java/org/apache/hadoop/hbase/protobuf/ProtobufUtil.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-protocol-shaded/src/main/protobuf/Client.proto, hbase-protocol/src/main/protobuf/Client.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestPartialResultsFromClientSide.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
https://issues.apache.org/jira/browse/HBASE-26122
Adds a `Get#setMaxResultSize(long)` method, similar to the one in Scan. The default is -1, meaning not enabled. When a max result size is added to a Get and there are more cells than fit in the specified size, `Result#mayHaveMoreCellsInRow()` will be true. This utilizes ScannerContext on the server side, since Gets are backed by single row scans.
Unlike Scans, no response stitching is implemented. The user must handle the possible true value in `Result#mayHaveMoreCellsInRow()` accordingly. This seems like a fine initial behavior since the default is unlimited, meaning a user would have to opt in to this new functionality with the intent to handle the possible return values.
I've added tests to TestHRegion for the HRegion implementation. …
=> HBASE-26122: Implement an optional maximum size for Gets, after which a partial result is returned

hbase-replication/src/main/java/org/apache/hadoop/hbase/replication/ReplicationQueueInfo.java, hbase-replication/src/main/java/org/apache/hadoop/hbase/replication/ReplicationUtils.java, hbase-replication/src/main/java/org/apache/hadoop/hbase/replication/ZKReplicationQueueStorage.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/replication/ReplicationPeerManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/HReplicationServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/DumpReplicationQueues.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RecoveredReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceInterface.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/hbck/ReplicationChecker.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/ReplicationSourceDummy.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceManagerZkImpl.java
The current `ReplicationQueueInfo` only has `queueId`, which is not enough to distinguish queues in ReplicationServer,  so we need to add the RS holding the queue for `ReplicationQueueInfo`.
=> HBASE-26084 Add owner of replication queue for ReplicationQueueInfo

hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestReplicationHFileCleaner.java
The test `org.apache.hadoop.hbase.master.cleaner.TestReplicationHFileCleaner.testIsFileDeletable` is not idempotent and fail if run twice in the same JVM, because it pollutes some states shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
Running `TestReplicationHFileCleaner.testIsFileDeletable` twice would result in the second run failing due to the following assertion error:
```
java.lang.AssertionError: Cleaner should allow to delete this file as there is no hfile reference node for it in the queue.
```
The root cause is that the a hfile reference is added during the first test run, which doesn't get removed upon test exits. Therefore, in the second test run , …
=> HBASE-25680  Non-idempotent test in TestReplicationHFileCleaner

hbase-server/src/main/java/org/apache/hadoop/hbase/compactionserver/CSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/compactionserver/CompactionThreadManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java, hbase-server/src/test/java/org/apache/hadoop/hbase/compactionserver/TestRegionFavoredNodesWhenCompactOffload.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionFavoredNodes.java
1.If we have favoredNodes for region, We use this policy 
2.If we not have favoredNodes, we add the regionServer request compaction as favoredNodes when do compact on compaction server, to guarantee locality
=> HBASE-26076 Support favoredNodes when do compaction offload

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestHFileOutputFormat2.java
https://issues.apache.org/jira/browse/HBASE-26196
Usecase:
```
TableName tableName = TableName.valueOf("table");
Configuration conf = job.getConfiguration();
// assume cluster B is secure
Configuration clusterB = HBaseConfiguration.createClusterConf(
conf,  "hbase-b-1.example.com,hbase-b-2.example.com,hbase-b-3.example.com:2181:/hbase-b");
clusterB.set(User.HBASE_SECURITY_CONF_KEY, "kerberos");
// configure others too like MASTER_KRB_PRINCIPAL, REGIONSERVER_KRB_PRINCIPAL and so on
// hack. TableMapReduceUtil.initCredentialsForCluster create UserProvider using job's configuration
// Thus if User.HBASE_SECURITY_CONF_KEY is simple, token isn't obtained
conf.set(User.HBASE_SECURITY_CONF_KEY, "kerberos");
TableMapReduceUtil.initCredentialsForCluster(job, clusterB);
// assume cluster A isn't …
```
=> HBASE-26196 Support configuration override for remote cluster of HFileOutputFormat locality sensitive

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java
current export snapshot will be report each ONE MB (1*1024*1024 Bytes),
we can make it can be config
=> HBASE-24842 make export snapshot report size can be config

hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/MonitoredRPCHandlerImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/monitoring/TestTaskMonitor.java
Please see more details at https://issues.apache.org/jira/browse/HBASE-26087
The added UT TestTaskMonitor#testClone will fail without this patch. It simulates the referred offheap ByteBuffer of the param change in the clone MonitoredRPCHandler.
=> HBASE-26087 JVM crash when displaying RPC params by MonitoredRPCHandler

hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-common/pom.xml, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java, hbase-it/src/test/java/org/apache/hadoop/hbase/mttr/IntegrationTestMTTR.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerRpcConnection.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/AbstractTestIPC.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionTracing.java, pom.xml
10/17 commits of HBASE-22120, original commit f6ff519dd0c7fe0e3ae3c175eefee27a26a065a4
=> HBASE-26133 Backport HBASE-25591 "Upgrade opentelemetry to 0.17.1" to branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java, hbase-common/src/main/java/org/apache/hadoop/hbase/AuthUtil.java
In some situations, a caller may know that it is properly managing the
Kerberos ticket to talk to HBase. In these situations, it's possible
that AuthUtil still tries to do renewals, but just fails repeatedly to
do so. Give a configuration flag for such clients to be able to tell
AuthUtil to simply stop trying.
=> HBASE-26212 Expose configuration to enable/disable AuthUtil

hbase-mapreduce/pom.xml, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/replication/VerifyReplication.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/replication/TestVerifyReplicationSecureClusterCredentials.java
https://issues.apache.org/jira/browse/HBASE-26204
Example for execution that this PR wants to fix.
```
hbase VerifyReplication \
-D verifyrep.peer.hbase.regionserver.kerberos.principal=secure-hbase-b/_HOST@EXAMPLE.COM \
-D verifyrep.peer.hbase.master.kerberos.principal=secure-hbase-b/_HOST@EXAMPLE.COM \
... \
secure-hbase-b-1.example.com,secure-hbase-b-2.example.com,secure-hbase-b-3.example.com:2181:/hbase-b \
table
```
=> HBASE-26204 Obtain credential for VerifyReplication with peerQuorumAddress

pom.xml
12/17 commits of HBASE-22120, original commits 8399293e21127df3ffdcb757242e4cb5964c7e99
=> HBASE-26135 Backport HBASE-25616 "Upgrade opentelemetry to 1.0.0" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionScannerImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionTracing.java
13/17 commits of HBASE-22120, original commit 7f90c2201f6a17d2e2d031505c35ae7c2b1ed7ea
=> HBASE-26136 Backport HBASE-25723 "Temporarily remove the trace support for RegionScanner.next" to branch-2

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/BackupMasterStatusTmpl.jamon, hbase-server/src/main/java/org/apache/hadoop/hbase/master/ActiveMasterManager.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestMasterStatusServlet.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MasterAddressTracker.java
Since the backup master status page will remove the MasterAddressTracker, and there is no direct method to obtain ActiveMasterManager (I saw that ActiveMasterManager is a private member of HMaster, and all values in ActiveMasterManager should be returned through HMaster’s public methods). I added some code to make the backup master status page easily retrieve the information it needs.
=> HBASE-26215 The backup master status page should use ActiveMasterManager instead of MasterAddressTracker

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestSeekHints.java
A fix and tests for [[HBASE-26232]](https://issues.apache.org/jira/browse/HBASE-26232)
=> SEEK_NEXT_USING_HINT is ignored on reversed Scans [HBASE-26232]

hbase-client/src/main/java/org/apache/hadoop/hbase/client/BufferedMutatorParams.java
In [HBASE-26103#comment](https://issues.apache.org/jira/browse/HBASE-26103?focusedCommentId=17384541&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17384541), we discussed to remove BufferedMutatorParams#pool and BufferedMutatorParams#getPool methods.
But BufferedMutatorParams#InterfaceAudience is public and `BufferedMutatorParams#pool` and `BufferedMutatorParams#getPool` methods are both public so we can't remove them. We need to deprecate them for 1 version and remove in next.
@saintstack  Please review.
=> HBASE-26103 Deprecate BufferedMutatorParams#pool method

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCacheUtil.java
Our logs have as a fairly common occurrence: 2021-03-05 22:24:31,034 WARN
[StoreFileOpener-foo-1] hfile.BlockCacheUtil: Caching an already cached
block: blah.bub. This is harmless and can happen in rare cases (see HBASE-8547)
Because it is harmless, log at DEBUG level, not WARN.
=> HBASE-25642 Fix or stop warning about already cached block

hbase-mapreduce/pom.xml, hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableMapReduceUtil.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableMapReduceUtil.java
https://issues.apache.org/jira/browse/HBASE-26205
=> HBASE-26205 Use specified cluster conf for UserProvider in TableMRUtil#initCredentialsForCluster

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/ExploringCompactionPolicy.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/StripeCompactionPolicy.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestStripeCompactionPolicy.java
=> HBASE-26229 Limit count and size of L0 files compaction in StripeCompactionPolicy

hbase-client/src/main/java/org/apache/hadoop/hbase/client/BalanceRequest.java
=> HBASE-26240 Set InterfaceAudience to Private for BalanceRequest$Builder

hbase-client/src/main/java/org/apache/hadoop/hbase/client/BalanceRequest.java
=> Backport "HBASE-26240 Set InterfaceAudience to Private for BalanceRequest$Builder (#3663)" to branch-2

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableMapReduceUtil.java
https://issues.apache.org/jira/browse/HBASE-26272
The principal parsing is failing with KerberosName's default rule that relies on the default realm.
It's caused by missing https://github.com/apache/hadoop/commit/be38e530bb23b134758e29c9101f98cf4e1d2c38#diff-4fe7835f2ef9e7512e198edee5ed08b8d0685977efd3434eadfbd612fd4dc768 in branch-2's hadoop librarry
This change affects the difference in behavior.
- In branch-2 (without be38e530bb23b134758e29c9101f98cf4e1d2c38)
- It takes default realm at reset
- KDC and Kerberos config for EXAMPLE.COM is not yet provided at that timing
- (So need to reset again after KDC and Kerberos config are prepared)
- In master (with be38e530bb23b134758e29c9101f98cf4e1d2c38)
- It just set null to default realm at reset
- default realm is taken when getDefaultRealm …
=> HBASE-26272 TestTableMapReduceUtil failure in branch-2

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/ClientSideRegionScanner.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCacheFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CombinedBlockCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/IndexOnlyLruBlockCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/ResizableBlockCache.java, hbase-server/src/main/java/org/apache/hadoop/hbase/io/util/MemorySizeUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestClientSideRegionScanner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestCacheConfig.java
Introduce `hbase.client.scanner.block.cache.size`
and default to 0.1f of over heap size that should
be good enough for caching LEAF_INDEX when a client,
e.g. snapshot scanner, scans the entire HFile
and does not need to seek/reseek to LEAF_INDEX
multiple times.
=> HBASE-26274 Create an option to reintroduce BlockCache to mapreduce job

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionFactory.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HRegionLocator.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/Scan.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestConnectionFactoryTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestConnectionImplementationTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestHTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRegionLocatorTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTracingBase.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
* RPC and IPC tracing supported by HBASE-26125
* WAL tracing supported by HBASE-26131
=> HBASE-26141 Add tracing support for HTable and sync connection on branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
Details Link: [HBASE-24601](https://issues.apache.org/jira/browse/HBASE-24601)
=> HBASE-24601: Change default Hfile storage policy from HOT to NONE for HDFS

hbase-server/src/main/java/org/apache/hadoop/hbase/master/replication/ReplicationPeerManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestNonHBaseReplicationEndpoint.java
Failed to add a peer replicating to non-HBase(like MQ) by implementing custom ReplicationEndpoint,  got exception like this in my UT: 
```
2021-10-29T15:14:47,632 INFO  [RPCClient-NioEventLoopGroup-5-3] client.RawAsyncHBaseAdmin$ReplicationProcedureBiConsumer(2761): Operation: ADD_REPLICATION_PEER, peerId: 1 failed with Invalid cluster key: , should not replicate to itself for HBaseInterClusterReplicationEndpoint2021-10-29T15:14:47,632 INFO  [RPCClient-NioEventLoopGroup-5-3] client.RawAsyncHBaseAdmin$ReplicationProcedureBiConsumer(2761): Operation: ADD_REPLICATION_PEER, peerId: 1 failed with Invalid cluster key: , should not replicate to itself for HBaseInterClusterReplicationEndpoint
org.apache.hadoop.hbase.DoNotRetryIOException: Invalid cluster key: , should not replicate to itself for …
```
=> HBASE-26406 Can not add peer replicating to non-HBase

bin/hbase, conf/hbase-env.sh
Exposes process-specific tracing arguments for most of the commands that we can launch from
`bin/hbase`. In addition to serving as an on/off flag, `HBASE_TRACE_OPTS` acts as the site-wide
configuration setting. Additional variables are provided for each applicable command, giving
operators fine-grain control over which processes participate in the tracing system, and to what
degree.
Signed-off-by: Tak Lon (Stephen) Wu <taklwu@apache.org>
=> Backport "HBASE-26363 OpenTelemetry configuration support for per-process service names" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionFileSystem.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/AssignmentTestingUtil.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRegionSplit.java
A new PR for https://github.com/apache/hbase/pull/2700
=> HBASE-25322 Redundant Reference file in bottom region of split

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java
NPE in HeapMemoryManager$HeapMemoryTunerChore.flushRequested because in MemStoreFlusher.notifyFlushRequest 'type' can be null. Seems like a long standing bug. I guess nobody uses this feature?
=> HBASE-26429 HeapMemoryManager fails memstore flushes with NPE if enabled

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DefaultHeapMemoryTuner.java
The DefaultHeapMemoryTuner chore will explain what it is doing when deciding to make changes, once per chore interval. This is not frequent logging and deserves to be at INFO level as it is making changes of some import. While making the change, also log a line when ignoring the initial periods, so operators are not surprised when nothing happens for a while.
=> HBASE-26430 Increase log level in DefaultHeapMemoryTuner from DEBUG to INFO

hbase-common/src/main/java/org/apache/hadoop/hbase/util/Addressing.java, hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java
https://issues.apache.org/jira/browse/HBASE-26410
=> HBASE-26410 Fix HBase TestCanaryTool for Java17

hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
In an effort to not fail a blocker and walk away, here's something that may also be incorrect, but seems more correct than what we currently have.
=> HBASE-26414 Tracing INSTRUMENTATION_NAME is incorrect

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/CellCounter.java
Add the following stats for a given table:
- Total size of serialized cells of each CF.
- Total size of serialized cells of each qualifier.
- Total size of serialized cells across all rows.
=> HBASE-26446 CellCounter should report serialized cell size counts too

hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegion.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/MasterRegionTestBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/TestMasterRegionWALRecovery.java
We currently cause an error to be thrown by trying to list a
non-existent directory. We see that the master region directory exists
on the filesystem, but forget to make sure that the master region's WAL
directory also exists before we try to list it.
I had to change the TestBase class because `create()` would create a new HTU which ended up creating a new test-directory every time. When we have a new test directory, we always hit bootstrap() instead of open() (which is what had the bug).
=> HBASE-26267 Don't try to recover WALs from a WAL dir which doesn't exist

pom.xml
This is a backport of https://github.com/apache/hbase/commit/5480493f5f7b01b496f54215334543f2a82c6ba7 with a small improvement to use latest openlabtesting:protoc (2.5.0.2) which.
=> HBASE-26470 Use openlabtesting protoc on linux arm64 in HBASE 2.x

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionScanner.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionScannerImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
Tracing is very important in large-scale distributed systems.
The attribute `_operation.attributes.id`  of a scan request can be used as trace id between hbase client and region server.
We should print operation id in region server's log if the scan request is too slow or too big.
It will be very helpful for finding problematic requests.
=> HBASE-26479: Print too slow/big scan's operation_id in region server log

hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
https://issues.apache.org/jira/projects/HBASE/issues/HBASE-26477
=> Backport HBASE-26477 Fix MiniMapReduceCluster failure under Java17 to branch-2

hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionHDFSBlockLocationFinder.java, hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestRegionHDFSBlockLocationFinder.java, hbase-common/src/main/resources/hbase-default.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/io/FileLink.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStoreFile.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/InputStreamBlockDistribution.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java, hbase-server/src/test/java/org/apache/hadoop/hbase/io/TestFileLink.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestInputStreamBlockDistribution.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestFSUtils.java
See https://issues.apache.org/jira/browse/HBASE-26304 for more details.
This is part of my work on porting our internal [LocalityHealer](https://issues.apache.org/jira/browse/HBASE-26250) tool to the hbase project.
HBase data is stored in HDFS Blocks, and HBase tracks the distribution of those blocks' replicas in the HDFSBlockDistribution objects in each StoreFileInfo. The current assumption is that those blocks never move after an HStore is opened, but this is not true. Even without the LocalityHealer, blocks can move if a datanode is decommissioned or someone inadvertently runs the hdfs balancer or mover. But the LocalityHealer is special in that it makes moves with an effort to _improve_ locality for HBase.
Due to the above assumption, HBase cannot take advantage of (or properly …
=> HBASE-26304: Reflect out of band locality improvements in metrics and balancer

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMaster.java
https://issues.apache.org/jira/browse/HBASE-26459
=> HBASE-26459 HMaster should move non-meta region only if meta is ONLINE

hbase-client/src/main/java/org/apache/hadoop/hbase/replication/ReplicationLoadSink.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
https://issues.apache.org/jira/browse/HBASE-26490
=> HBASE-26490 Add builder for class ReplicationLoadSink

hbase-protocol-shaded/src/main/protobuf/server/master/MasterProcedure.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CloneSnapshotProcedure.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RestoreSnapshotProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestCloneSnapshotProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestRestoreSnapshotProcedure.java
https://issues.apache.org/jira/browse/HBASE-26462
=> HBASE-26462 Should persist restoreAcl flag in the procedure state for CloneSnapshotProcedure and RestoreSnapshotProcedure

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRequestFutureImpl.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestClientOperationTimeout.java
This is a new pr instead of #3419.
=> HBASE-26027 The calling of HTable.batch blocked at AsyncRequestFutureImpl.waitUntilDone caused by ArrayStoreException

bin/hbase-config.cmd, bin/hbase-config.sh, pom.xml
https://issues.apache.org/jira/browse/HBASE-26557
=> HBASE-26557 log4j2 has a critical RCE vulnerability

hbase-client/src/main/java/org/apache/hadoop/hbase/filter/FuzzyRowFilter.java, hbase-protocol/src/main/java/org/apache/hadoop/hbase/protobuf/generated/FilterProtos.java, hbase-protocol/src/main/protobuf/Filter.proto, hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFuzzyRowFilter.java, hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFuzzyRowFilterEndToEnd.java
This adds a new proto field to FuzzyRowFilter proto to aid in providing a compatibility path for pre-HBASE-15676 clients.  Users would need to roll this out to their server side first, then roll out to their clients. At which point they are safe to upgrade beyond 1.x.
This brings back support for the old v1 mask from pre-15676. If the new `isMaskV2` field is empty/false, we use the old mask. If present and true, we use the new mask which is used in later versions of hbase.
I updated all of the tests in TestFuzzyRowFilterEndToEnd to test with both the v1 and v2 masks. You'll note that `testAllFixedBits()` (the test added in 15676) matches all rows in the table when using the v1 mask. This is the bug that jira fixed.
=> HBASE-26537: Make HBASE-15676 backwards compatible, using a flag on the proto

dev-support/hbase-personality.sh
Trying this. There's currently no way to test a change to the personality file from a pre-commit
check, so this must be committed to master or a feature branch in order to see its impact.
=> HBASE-26549 hbaseprotoc plugin should initialize maven

hbase-client/pom.xml, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableOperationSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
Follows the guidance outlined in https://github.com/open-telemetry/opentelemetry-specification/blob/3e380e2/specification/trace/semantic_conventions/database.dm
* all table data operations are assumed to be of type CLIENT
* populate `db.name` and `db.operation` attributes
* name table data operation spans as: `db.operation` `db.name`:`db.hbase.table`
note: this implementation deviates from the recommended `db.name`.`db.sql.table` and instead
uses HBase's native String representation of namespace:tablename.
=> HBASE-26472 Adhere to semantic conventions regarding table data operations

hbase-client/pom.xml, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableOperationSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestHTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
Follows the guidance outlined in https://github.com/open-telemetry/opentelemetry-specification/blob/3e380e2/specification/trace/semantic_conventions/database.dm
* all table data operations are assumed to be of type CLIENT
* populate `db.name` and `db.operation` attributes
* name table data operation spans as `db.operation` `db.name`:`db.hbase.table`
note: this implementation deviates from the recommended `db.name`.`db.sql.table` and instead
uses HBase's native String representation of namespace:tablename.
Backport of #3906
=> Backport "HBASE-26472 Adhere to semantic conventions regarding table data operations" to branch-2

hbase-client/pom.xml, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableOperationSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestHTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
Follows the guidance outlined in https://github.com/open-telemetry/opentelemetry-specification/blob/3e380e2/specification/trace/semantic_conventions/database.dm
* all table data operations are assumed to be of type CLIENT
* populate `db.name` and `db.operation` attributes
* name table data operation spans as `db.operation` `db.name`:`db.hbase.table`
note: this implementation deviates from the recommended `db.name`.`db.sql.table` and instead
uses HBase's native String representation of namespace:tablename.
Signed-off-by: Tak Lon (Stephen) Wu <taklwu@apache.org>
=> Backport "HBASE-26472 Adhere to semantic conventions regarding table data operations" to branch-2.5

hbase-protocol-shaded/src/main/protobuf/test/coprocessor/ColumnAggregationNullResponseProtocol.proto, hbase-protocol-shaded/src/main/protobuf/test/coprocessor/ColumnAggregationProtocol.proto, hbase-protocol-shaded/src/main/protobuf/test/coprocessor/ColumnAggregationWithErrorsProtocol.proto, hbase-protocol-shaded/src/main/protobuf/test/coprocessor/IncrementCounterProcessor.proto, hbase-protocol-shaded/src/main/protobuf/test/coprocessor/PingProtocol.proto, hbase-protocol-shaded/src/main/protobuf/test/coprocessor/ShellExecEndpoint.proto, hbase-protocol-shaded/src/main/protobuf/test/ipc/TestProcedure.proto, hbase-protocol-shaded/src/main/protobuf/test/ipc/test.proto, hbase-protocol-shaded/src/main/protobuf/test/ipc/test_rpc_service.proto
This is needed in a couple places in order to test that traces over the IPC layer carry correct
span names, and it's good hygiene anyway.
=> HBASE-26542 Apply a `package` to test protobuf files

hbase-endpoint/src/main/protobuf/ColumnAggregationNullResponseProtocol.proto, hbase-endpoint/src/main/protobuf/ColumnAggregationProtocol.proto, hbase-endpoint/src/main/protobuf/ColumnAggregationWithErrorsProtocol.proto, hbase-endpoint/src/main/protobuf/IncrementCounterProcessor.proto, hbase-endpoint/src/main/protobuf/ShellExecEndpoint.proto, hbase-protocol-shaded/src/main/protobuf/TestProcedure.proto, hbase-protocol-shaded/src/main/protobuf/test.proto, hbase-protocol-shaded/src/main/protobuf/test_rpc_service.proto, hbase-protocol/src/main/protobuf/PingProtocol.proto
This is needed in a couple places in order to test that traces over the IPC layer carry correct
span names, and it's good hygiene anyway.
=> Backport "HBASE-26542 Apply a `package` to test protobuf files" to branch-2

hbase-endpoint/src/main/protobuf/ColumnAggregationNullResponseProtocol.proto, hbase-endpoint/src/main/protobuf/ColumnAggregationProtocol.proto, hbase-endpoint/src/main/protobuf/ColumnAggregationWithErrorsProtocol.proto, hbase-endpoint/src/main/protobuf/IncrementCounterProcessor.proto, hbase-endpoint/src/main/protobuf/ShellExecEndpoint.proto, hbase-protocol-shaded/src/main/protobuf/TestProcedure.proto, hbase-protocol-shaded/src/main/protobuf/test.proto, hbase-protocol-shaded/src/main/protobuf/test_rpc_service.proto, hbase-protocol/src/main/protobuf/PingProtocol.proto
This is needed in a couple places in order to test that traces over the IPC layer carry correct
span names, and it's good hygiene anyway.
=> Backport "HBASE-26542 Apply a `package` to test protobuf files" to branch-2.5

hbase-endpoint/src/main/protobuf/ColumnAggregationNullResponseProtocol.proto, hbase-endpoint/src/main/protobuf/ColumnAggregationProtocol.proto, hbase-endpoint/src/main/protobuf/ColumnAggregationWithErrorsProtocol.proto, hbase-endpoint/src/main/protobuf/IncrementCounterProcessor.proto, hbase-endpoint/src/main/protobuf/ShellExecEndpoint.proto, hbase-protocol-shaded/src/main/protobuf/TestProcedure.proto, hbase-protocol-shaded/src/main/protobuf/test.proto, hbase-protocol-shaded/src/main/protobuf/test_rpc_service.proto, hbase-protocol/src/main/protobuf/PingProtocol.proto
This is needed in a couple places in order to test that traces over the IPC layer carry correct
span names, and it's good hygiene anyway.
=> Backport "HBASE-26542 Apply a `package` to test protobuf files" to branch-2.4

hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestRpcServerSlowConnectionSetup.java
RpcServer identifies the services it hosts by unqualified service name. Thus, use `getName()`
instead of `getFullName()`. See also HBASE-26589.
=> Backport "HBASE-26542 Apply a `package` to test protobuf files (addendum)" to branch-2

hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestRpcServerSlowConnectionSetup.java
RpcServer identifies the services it hosts by unqualified service name. Thus, use `getName()`
instead of `getFullName()`. See also HBASE-26589.
=> Backport "HBASE-26542 Apply a `package` to test protobuf files (addendum)" to branch-2.5

hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestRpcServerSlowConnectionSetup.java
RpcServer identifies the services it hosts by unqualified service name. Thus, use `getName()`
instead of `getFullName()`. See also HBASE-26589.
=> Backport "HBASE-26542 Apply a `package` to test protobuf files (addendum)" to branch-2.4

hbase-server/src/main/java/org/apache/hadoop/hbase/util/compaction/MajorCompactionRequest.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/compaction/MajorCompactionTTLRequest.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/compaction/MajorCompactor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/util/compaction/MajorCompactorTTL.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/compaction/TestMajorCompactionRequest.java, hbase-server/src/test/java/org/apache/hadoop/hbase/util/compaction/TestMajorCompactionTTLRequest.java
MajorCompactor creates excessive connections: once every time MajorCompactionRequest.getConnection is called. Can do better by using the Connection object created in MajorCompactor.
**Testing:**
Ran `mvn -D test="org.apache.hadoop.hbase.util.compaction.TestMajorCompactor" test -pl hbase-server -am`
Before:
```
% grep 'ipc.RpcConnection' hbase-server/target/surefire-reports/org.apache.hadoop.hbase.util.compaction.TestMajorCompactor-output.txt | grep -c 'ClientMeta'
17
```
After:
```
% grep 'ipc.RpcConnection' hbase-server/target/surefire-reports/org.apache.hadoop.hbase.util.compaction.TestMajorCompactor-output.txt | grep -c 'ClientMeta'
2
```
=> HBASE-26598 Fix excessive connections in MajorCompactor

hbase-common/src/main/java/org/apache/hadoop/hbase/util/OrderedBytes.java, hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestOrderedBytes.java
https://issues.apache.org/jira/browse/HBASE-26566
=> HBASE-26566 Optimize encodeNumeric in OrderedBytes

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestImportExport.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/WALActionsListener.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALActionListener.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionServerBulkLoad.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestFSWAL.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLog.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALFactory.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/WALPerformanceEvaluation.java
https://issues.apache.org/jira/browse/HBASE-26564
=> HBASE-26564 Retire the method visitLogEntryBeforeWrite without RegionInfo in WALActionListner

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestCellBasedImportExport2.java, hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestImportExport.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/WALActionsListener.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALActionListener.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionServerBulkLoad.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestWALLockup.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestFSWAL.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLog.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALFactory.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/WALPerformanceEvaluation.java
https://issues.apache.org/jira/browse/HBASE-26564
=> HBASE-26564 Retire the method visitLogEntryBeforeWrite without Region Info in WALActionListner

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/metrics/ExceptionTrackingSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/metrics/ExceptionTrackingSourceImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/MetricsHBaseServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestRpcMetrics.java, hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftMetrics.java, hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift/ErrorThrowingGetObserver.java
`CallDroppedException` can be thrown with `CallRunner.drop()` by queue implementations that decide to drop calls to groom the RPC call backlog. The LifoCoDel queue does this I believe and with Pluggable queue it's possible for 3rd party queue implementations to be using `drop()` for similar reasons. It would be nice for the server to be tracking these exceptions in metrics since otherwise you might have to do some extra lifting on the client side.
https://issues.apache.org/jira/browse/HBASE-26623
=> HBASE-26623 Report CallDroppedException in exception metrics

hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/AsyncFSOutputHelper.java, hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutput.java, hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputHelper.java, hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/monitor/ExcludeDatanodeManager.java, hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/monitor/StreamSlowMonitor.java, hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestExcludeDatanodeManager.java, hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestFanOutOneBlockAsyncDFSOutput.java, hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestLocalAsyncOutput.java, hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestSaslFanOutOneBlockAsyncDFSOutput.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractProtobufLogWriter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncProtobufLogWriter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogWriter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AsyncFSWALProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/FSHLogProvider.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALFactory.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestWALReplay.java, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/master/TestRecoverStandbyProcedure.java, hbase-server/src/test/java/org/apache/hadoop/hbase/wal/IOTestProvider.java
This issue provides the method to detect slow datanodes by checking the packets processing time of each datanode connected by the WAL. When a datanode is considered slow, the datanode will be added to an exclude cache on the regionserver, and every stream created will exclude all the cached slow datanodes in a configured period. 
The exclude logic cooperate with the log rolling logic, will react more sensitively to the lower slow datanodes, whatever there is hardware failure or hotspots. 
On our production cluster with 20% machines with hardware failure, the RS serves stably and can keep a high availability.
Without this feature on the same cluster, there is frequently aborting of RSes, which caused by wal stuck when flushing cache.
=> HBASE-26347 Support detect and exclude slow DNs in fan-out of WAL

hbase-common/src/main/java/org/apache/hadoop/hbase/util/OrderedBytes.java, hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestOrderedBytes.java
https://issues.apache.org/jira/browse/HBASE-26635
=> HBASE-26635 Optimize decodeNumeric in OrderedBytes

hbase-server/src/main/java/org/apache/hadoop/hbase/HBaseServerBase.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMasterCommandLine.java, hbase-server/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZooKeeperACL.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/HQuorumPeer.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAclReset.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAuthentication.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKUtilNoServer.java
This refactor reduces the size and scope of the `ZKUtil` class. The core of this refactor is
moving the `login*` methods from `ZKUtil` into their own class, `ZKAuthentication`. The class
`JaasConfiguration` is also moved along with them.
=> HBASE-26616 Refactor code related to ZooKeeper authentication

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMasterCommandLine.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZooKeeperACL.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/HQuorumPeer.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAclReset.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAuthentication.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKUtilNoServer.java
This refactor reduces the size and scope of the `ZKUtil` class. The core of this refactor is
moving the `login*` methods from `ZKUtil` into their own class, `ZKAuthentication`. The class
`JaasConfiguration` is also moved along with them.
=> Backport "HBASE-26616 Refactor code related to ZooKeeper authentication (#3973)" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMasterCommandLine.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZooKeeperACL.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/HQuorumPeer.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAclReset.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAuthentication.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKUtilNoServer.java
This refactor reduces the size and scope of the `ZKUtil` class. The core of this refactor is
moving the `login*` methods from `ZKUtil` into their own class, `ZKAuthentication`. The class
`JaasConfiguration` is also moved along with them.
=> Backport "HBASE-26616 Refactor code related to ZooKeeper authentication (#3973)" to branch-2.5

hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/TraceTestUtil.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
The HBase-specific attribute `db.hbase.namespace` has been deprecated in favor of the generic
`db.name`. See also https://github.com/open-telemetry/opentelemetry-specification/issues/1760
=> HBASE-26520 Remove use of `db.hbase.namespance` tracing attribute

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMasterCommandLine.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZooKeeperACL.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/HQuorumPeer.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAclReset.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAuthentication.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKUtilNoServer.java
This refactor reduces the size and scope of the `ZKUtil` class. The core of this refactor is
moving the `login*` methods from `ZKUtil` into their own class, `ZKAuthentication`. The class
`JaasConfiguration` is also moved along with them.
=> Backport "HBASE-26616 Refactor code related to ZooKeeper authentication (#3973)" to branch-2.4

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathBalancedQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRWQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRpcHandler.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RWQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcHandler.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcScheduler.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSimpleRpcScheduler.java
https://issues.apache.org/jira/browse/HBASE-26551
=> HBASE-26551 Add FastPath feature to HBase RWQueueRpcExecutor

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AbstractRpcBasedConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRegionLocator.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClusterConnection.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HRegionLocator.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/MasterRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RpcConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/ConnectionSpanBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableOperationSpanBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/DoNothingConnectionRegistry.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionLocatorTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestHTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRegionLocatorTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTracingBase.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/TraceTestUtil.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/RegionServerRegistry.java
Add support for `db.system`, `db.connection_string`, `db.user`.
This is a non-trivial backport of #3952 to branch-2. It's non-trivial because it implements these tracing features on the non-async implementation of HRegionLocator. Please take a look at those changed with a critical reviewer's eye. A diff of the diffs might be useful for reviewers... I don't now if GitHub can produce such a thing.
=> Backport "HBASE-26474 Implement connection-level attributes" to branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AbstractRpcBasedConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRegionLocator.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClusterConnection.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HRegionLocator.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/MasterRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RpcConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/ConnectionSpanBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableOperationSpanBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/DoNothingConnectionRegistry.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionLocatorTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestHTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRegionLocatorTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTracingBase.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/TraceTestUtil.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/client/RegionServerRegistry.java
Add support for `db.system`, `db.connection_string`, `db.user`.
Signed-off-by: Huaxiang Sun <huaxiangsun@apache.org>
Co-authored-by: Josh Elser <josh.elser@gmail.com>
=> Backport "HBASE-26474 Implement connection-level attributes (#4014)" to branch-2.5

hbase-it/src/test/java/org/apache/hadoop/hbase/test/IntegrationTestZKAndFSPermissions.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/DumpReplicationQueues.java, hbase-server/src/main/resources/hbase-webapps/master/zk.jsp, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestNamespaceReplicationWithBulkLoadedData.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MetaTableLocator.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKDump.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestRecoverableZooKeeper.java
The code starting at `ZKUtil.dump(ZKWatcher)` is a small mess – it has cyclic dependencies woven
through itself, `ZKWatcher` and `RecoverableZooKeeper`. It also initializes a static variable in
`ZKUtil` through the factory for `RecoverableZooKeeper` instances. Let's decouple and clean it
up.
=> HBASE-26614 Refactor code related to "dump"ing ZK nodes

hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTracingBase.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/TraceTestUtil.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
The HBase-specific attribute `db.hbase.namespace` has been deprecated in favor of the generic
`db.name`. See also https://github.com/open-telemetry/opentelemetry-specification/issues/1760
Signed-off-by: Tak Lon (Stephen) Wu <taklwu@apache.org>
=> Backport "HBASE-26520 Remove use of `db.hbase.namespance` tracing attribute (#4015)" to branch-2.5

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AbstractRpcBasedConnectionRegistry.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRpcBasedRegistryHedgedReads.java
Addressing additional comments raised in branch-2 backport PR #4014
=> Backport "HBASE-26474 Implement connection-level attributes (addendum)" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMemStoreFlusher.java
=> HBASE-26660 delayed FlushRegionEntry should be removed when we need a non-delayed one

hbase-it/src/test/java/org/apache/hadoop/hbase/test/IntegrationTestZKAndFSPermissions.java, hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/DumpReplicationQueues.java, hbase-server/src/main/resources/hbase-webapps/master/zk.jsp, hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestNamespaceReplicationWithBulkLoadedData.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MetaTableLocator.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKDump.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java, hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java, hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestRecoverableZooKeeper.java
The code starting at `ZKUtil.dump(ZKWatcher)` is a small mess – it has cyclic dependencies woven
through itself, `ZKWatcher` and `RecoverableZooKeeper`. It also initializes a static variable in
`ZKUtil` through the factory for `RecoverableZooKeeper` instances. Let's decouple and clean it
up.
=> Backport "HBASE-26614 Refactor code related to "dump"ing ZK nodes (#3969)" to branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableOperationSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
For batch operations, collect and annotate the associated span with the set of all operations contained in the batch.
This is an HBase-specific extension that I am proposing. The idea here is to provide a single field containing all of the operations contained within an "envelope-type" operation. That field can then be indexed for query, allowing operators to easily find the operations that they seek. This is a project-specific proposal for a solution to the general issue I raised on open-telemetry/opentelemetry-specification#2202.
=> HBASE-26473 Introduce `db.hbase.container_operations` span attribute

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableOperationSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestHTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTracingBase.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
For batch operations, collect and annotate the associated span with the set of all operations
contained in the batch.
=> Backport "HBASE-26473 Introduce `db.hbase.container_operations` span attribute" to branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableOperationSpanBuilder.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestHTableTracing.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTracingBase.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
For batch operations, collect and annotate the associated span with the set of all operations
contained in the batch.
=> Backport "HBASE-26473 Introduce `db.hbase.container_operations` span attribute" to branch-2.5

hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-client/src/test/java/org/apache/hadoop/hbase/shaded/protobuf/TestProtobufUtil.java
Delete properly checked `hasTimestamp`, but I unified it under the new `cellTimestampOrLatest` method. 
Note: I don't think Append is affected by this bug, because it used a version of toMutation which properly passes along timestamp even in old 1.x clients. But both Append/Increment are converted _from_ proto using the same toDelta method, so I added the test case for both.
@apurtell 
I think branch-2 will need a separate PR due to the changes in shaded ProtobufUtils, will get started on that.
=> HBASE-26713 Default to LATEST_TIMESTAMP if no timestamp sent along on Increment/Append

hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java
Ensure table data operations emit one and only one span.
=> HBASE-26472 Adhere to semantic conventions regarding table data operations (addendum)

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
We have encountered two issues with region warmup before the assignment manager gracefully moves a region from one regionserver to another.
The first instance is HBASE-26722. Part of the failure chain is temporary double assignment like conditions where both the source and destination regionservers think they have exclusive rights to storefile management (as they should) but warmup opens a region before it is closed and then both regionservers take compaction related actions. While this can be remediated with more care to this case, it is unclear if warmup affords significant advantage. The motivation of the original commit in 2015 introducing this feature was avoidance of blockcache misses once region ownership transfer was advertised to clients. Depending on use case and additional …
=> HBASE-26726 Allow disable of region warmup before graceful move

hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/ConnectionSpanBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/IpcClientSpanBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java, hbase-server/pom.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/CallRunner.java, hbase-server/src/main/java/org/apache/hadoop/hbase/server/trace/IpcServerSpanBuilder.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/AbstractTestIPC.java, pom.xml
Bring us into basic conformance with https://github.com/open-telemetry/opentelemetry-specification/blob/3e380e249f60c3a5f68746f5e84d10195ba41a79/specification/trace/semantic_conventions/rpc.md
=> HBASE-26521 Name RPC spans as `$package.$service/$method`

LICENSE.txt, NOTICE.txt, hbase-shell/src/main/ruby/irb/hirb.rb
Override eval_input in HIRB to modify exception handling logic.
=> HBASE-26741 Incorrect exception handling in shell

hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/ConnectionSpanBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/IpcClientSpanBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java, hbase-server/pom.xml, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/CallRunner.java, hbase-server/src/main/java/org/apache/hadoop/hbase/server/trace/IpcServerSpanBuilder.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/AbstractTestIPC.java, pom.xml
=> Backport "HBASE-26521 Name RPC spans as `$package.$service/$method` (#4024)" to branch-2.5

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/StripeCompactionPolicy.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestStripeCompactionPolicy.java
This issue solves the similar problem to HBASE-25754. StripeCompactionPolicy doesn't support major compaction, but the expired data in the cold region need to be cleared.
=> HBASE-26434 Compact L0 files for cold regions using StripeCompactionPolicy

hbase-client/src/main/java/org/apache/hadoop/hbase/ClusterMetrics.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ClusterMetricsBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ServerMetrics.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ServerMetricsBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ServerTask.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ServerTaskBuilder.java, hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java, hbase-protocol-shaded/src/main/protobuf/server/ClusterStatus.proto, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/ClusterStatusChore.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestClientClusterMetrics.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionsRecoveryChore.java, hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/main/ruby/shell/commands/status.rb
Expose monitored tasks state in ClusterStatus API via new option in ServerLoad.
Add shell support for interrogating monitored tasks state in ServerLoad.
Here's a prototype running on a branch-2 fork:
=> HBASE-26730 Extend hbase shell 'status' command to support an option 'tasks'

hbase-it/src/test/java/org/apache/hadoop/hbase/mapreduce/IntegrationTestFileBasedSFTBulkLoad.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionFileSystem.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SecureBulkLoadManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkLoad.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkloadBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactionAfterBulkLoad.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSecureBulkLoadManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSecureBulkloadListener.java
move files directly to the store dir when requireWritingToTmpDirFirst is
false
fix failedBulkLoad to work on second call
change existing tests to run without tmp folder too
add tests for SecureBulkLoadListener
=> HBASE-26707: Reduce number of renames during bulkload

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/BalancedQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/QueueBalancer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RWQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RandomQueueBalancer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestRWQueueRpcExecutor.java
Since RandomQueueBalancer is now just the default option of a new config, I thought it might make sense to split it and QueueBalancer out into top-level classes. Let me know if anyone disagrees with the IA/IS chosen here.
This change is covered by tests in TestSimpleRpcScheduler, but I also added an explicit test for the slicing of lists done in RWQueueRpcExecutor.
I want to pass in the actual queues to the balancer factory because some balancers may want to introspect the queues in determining how to balance. For example, a load-based balancer might want to check the size() to determine the least-loaded queue.
=> HBASE-26703 Allow configuration of IPC queue balancer

hbase-shell/src/main/ruby/hbase/admin.rb, hbase-shell/src/main/ruby/shell.rb, hbase-shell/src/main/ruby/shell/commands/change_sft.rb, hbase-shell/src/main/ruby/shell/commands/change_sft_all.rb, hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestChangeSftShell.java, hbase-shell/src/test/ruby/shell/sftchange_shell_test.rb
https://issues.apache.org/jira/browse/HBASE-26673
=> HBASE-26673 Implement a shell command for change SFT implementation

hbase-shaded/pom.xml
I expected there would be more to this, but this ended up working locally without needing to modify our invariants checks. I'm continuing to look into why, but wanted to get the full build started.
=> HBASE-26546: hbase-shaded-client missing required thirdparty classes under hadoop 3.3.1

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Result.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestResult.java
https://issues.apache.org/jira/browse/HBASE-26705
=> HBASE-26705 Backport HBASE-26688 to branch-1

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableResultScanner.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
Minor changes to the internals of async scanning to make code easier to read and trace.
=> HBASE-26765 Minor refactor of async scanning code

hbase-it/src/test/java/org/apache/hadoop/hbase/mapreduce/IntegrationTestFileBasedSFTBulkLoad.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionFileSystem.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SecureBulkLoadManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkLoad.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkloadBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactionAfterBulkLoad.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSecureBulkLoadManager.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSecureBulkloadListener.java
move files directly to the store dir when requireWritingToTmpDirFirst is false
fix failedBulkLoad to work on second call
change existing tests to run without tmp folder too
add tests for SecureBulkLoadListener
=> HBASE-26707: Reduce number of renames during bulkload (#4066)

pom.xml
The upgrade is to get the fix in MENFORCER-336, making beanshell evaluation safe for use with `mvn
-T`. Also upgrade extra-enforcer-rules to 1.5.1, as per experience with HBASE-26664.
=> HBASE-26663 Upgrade Maven Enforcer Plugin

pom.xml
The upgrade is to get the fix in MENFORCER-336, making beanshell evaluation safe for use with `mvn
-T`. Also upgrade extra-enforcer-rules to 1.5.1, as per experience with HBASE-26664.
=> Backport "HBASE-26663 Upgrade Maven Enforcer Plugin" to branch-2

pom.xml
The upgrade is to get the fix in MENFORCER-336, making beanshell evaluation safe for use with `mvn
-T`. Also upgrade extra-enforcer-rules to 1.5.1, as per experience with HBASE-26664.
=> Backport "HBASE-26663 Upgrade Maven Enforcer Plugin" to branch-2.5

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ImmutableScan.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/Scan.java, hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaTableUtil.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestImmutableScan.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestScan.java, hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestScanRowPrefix.java, hbase-shell/src/main/ruby/hbase/table.rb, src/main/asciidoc/_chapters/datamodel.adoc
Issue https://issues.apache.org/jira/browse/HBASE-26762
I found today that with ticket https://issues.apache.org/jira/browse/HBASE-25299 the intended effects of Scan#setRowPrefixFilter were unclear (hence the report of unexpected effects) and instead of just improving the documentation the method was marked as deprecated.
Quote:
@deprecated since 3.0.0. The scan result might be unexpected in some cases.
Yes, if you use this very valuable method incorrectly it will yield incorrect results.
I strongly disagree with this deprecation because it is one of the most used methods of Scan in many of my applications.
I do agree the documentation should more clearly indicate these combinations do not work.
This pull request does only 2 things:
- Remove the deprecation
- Improve the documentation.
=> HBASE-26762: Un-Deprecate and improve documentation for Scan#setRowPrefixFilter

hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java, hbase-http/src/main/java/org/apache/hadoop/hbase/http/SecurityHeadersFilter.java, hbase-http/src/test/java/org/apache/hadoop/hbase/http/TestSSLHttpServer.java, hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RESTServer.java, hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestRESTServerSSL.java
Originally it was implemented with empty default values, but it actually makes sense to automatically enabled them if SSL is turned on. It's still possible to override via config, but the default behaviour is more secure.
=> HBASE-26789 Automatically add default security headers to http/rest if SSL enabled

hbase-server/src/main/java/org/apache/hadoop/hbase/security/HBaseSaslRpcServer.java
=> Backport "HBASE-26776 RpcServer failure to SASL handshake always logs user "unknown" to audit log (#4138)" to branch-2

hbase-server/src/main/java/org/apache/hadoop/hbase/security/HBaseSaslRpcServer.java
=> Backport "HBASE-26776 RpcServer failure to SASL handshake always logs user "unknown" to audit log (#4138)" to branch-2.4

hbase-server/src/main/java/org/apache/hadoop/hbase/security/HBaseSaslRpcServer.java
=> Backport "HBASE-26776 RpcServer failure to SASL handshake always logs user "unknown" to audit log (#4138)" to branch-2.5

hbase-http/src/main/java/org/apache/hadoop/hbase/util/JSONBean.java, hbase-http/src/test/java/org/apache/hadoop/hbase/util/TestJSONBean.java
Enable the balancer cost metrics to be included in the /jmx endpoint. This should be backwards compatible.
=> HBASE-26745: Include balancer cost metrics in jmx endpoint

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
For the `TraceUtil` methods that accept `Callable` and `Runnable` types, make them generic over a
child of `Throwable`. This allows us to consolidate the two method signatures into a single more
flexible definition.
=> HBASE-26764 Implement generic exception support for TraceUtil methods over Callables and Runnables

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionManager.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/MetaScanner.java
I found it really hard to add a test case for this. I think i'd need to modify meta to add a dummy extra CF and then put a bad row in there and validate that it gets ignored by these reads. That should be straightforward, but alters to meta are disallowed in a few places. I could probably add some sort of internal-only config to disable those checks for the purpose of test, or maybe a setter which sets a volatile value? It's hard to access them from the TestingUtility, but maybe doable. Let me know if you'd like me to go through those efforts to test this, but I think it might not be worth it?
=> HBASE-26797 HBase 1.x clients will choke on rep_barrier rows when scanning hbase 2.x meta

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java, hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java, hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java
The test I added verifies the metric, but not the calculation. I looked into adding a more end-to-end test, but it would be a lot of work given where these metrics are counted. Many other metrics don't have any tests at all, so I figured this might be sufficient.
=> HBASE-26731 Add metrics for active and expired scanners

hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/EventMatchers.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/CallRunner.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RPCTInfoGetter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerCall.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerRpcConnection.java, hbase-server/src/main/java/org/apache/hadoop/hbase/server/trace/IpcServerSpanBuilder.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestCallRunner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSimpleRpcScheduler.java
We appear to be generating spans with without a parent context with the name
`RegionScanner.close`.
=> HBASE-26759 Fix trace continuity through CallRunner

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/BalancedQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathBalancedQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRWQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RWQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java
While working on tracing, I see some minor cleanup that can be done in the RpcScheduler and
RpcExecutor classes. The implementations of the `dispatch` methods don't actually throw the
exceptions defined in their signatures, and there's some simplification to be done and checkstyle
warnings to resolve while I'm in there.
=> HBASE-26782 Minor code cleanup in and around RpcExecutor

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HRegionLocator.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java, hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java, hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
For the `TraceUtil` methods that accept `Callable` and `Runnable` types, make them generic over a
child of `Throwable`. This allows us to consolidate the two method signatures into a single more
flexible definition.
=> Backport "HBASE-26764 Implement generic exception support for TraceUtil methods over Callables and Runnables" to branch-2.5

hbase-resource-bundle/src/main/resources/META-INF/LICENSE.vm, hbase-resource-bundle/src/main/resources/supplemental-models.xml
- correct the license name for the Xerial Snappy wrapper.
- correct the license name for the version of GSON brought in with Hadoop 3.3.2+
=> HBASE-26760 LICENSE handling should not allow non-aggregated apache-2.0

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncClientScanner.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncScanSingleRegionRpcRetryingCaller.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableRpcPriority.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestAsyncTableScan.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScan.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanAll.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanner.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRawAsyncTableScan.java
- The change for closeScanner to use HIGH_QOS is a simple one-liner. The rest of this PR is test fixes and incidentals.
- Fixes TestAsyncTableRpcPriority to use a thread for stub calls, because otherwise the interplay of AsyncTableResultScanner onNext and next does not work. Running in a single thread causes the resumer to be instantiated and then nulled out in the same request, which causes further calls to next() to block and calls to close() to not actually call closeScanner. 
- Also fixed the priority assertions to happen on mock instead of on verify. It doesn't work on verify, because mockito seems to keep a reference to the call arguments. Since the AsyncSingleRequestRpcRetryingCaller always resets the same controller object for every request, this means that on verification mockito …
=> HBASE-26784 Use HIGH_QOS for ResultScanner.close requests

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ScannerCallable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/HBaseRpcControllerImpl.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableRpcPriority.java
Fixes a bug in the original implementation in https://github.com/apache/hbase/pull/4163, wherein we attempted to inherit the original controller priority/timeout but accidentally was using the same HBaseRpcController for both reading and writing the fields.
Improves tests to ensure that we are properly inheriting these fields.
=> HBASE-26784 Addendum: Close scanner request should properly inherit original timeout and priority

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/BalancedQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathBalancedQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRWQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RWQueueRpcExecutor.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java
=> Backport "HBASE-26782 Minor code cleanup in and around RpcExecutor" to branch-2

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ReversedScannerCallable.java, hbase-client/src/main/java/org/apache/hadoop/hbase/client/ScannerCallable.java, hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestScannerCallable.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/FromClientSideBase.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaCache.java
I renamed the protected `getRegionLocations` method so that it's clear that it is meant to be used in the prepare method, as mentioned in the new javadoc as well.
I had to handle some complexity in the ReverseScannerCallable due to how it searches for the correct region location. Previously, the default RegionServerCallable.throwable call would not actually clear the cache, because the passed in `getRow()` value would be an empty row key in some cases which doesn't actually match anything in the cache. With my changes now, we keep track of the "locationSearchKey" which is the key used to find the actual region location in prepare. This way `throwable()` will be sure to clear the cache for the location we were reading from.
I've added some tests here:
- A test in TestMetaCache ensures that …
=> HBASE-26783 ScannerCallable doubly clears meta cache on retries

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/throttle/StoreHotnessProtector.java
See discussion in https://issues.apache.org/jira/browse/HBASE-26814
This change applies cleanly to branch-2 as well
=> HBASE-26814 Default StoreHotnessProtector to off, with logs to guide when to turn it on

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java
Implements the minimum change. Will wait for discussion on Jira to determine if additional changes are required.
=> HBASE-26817 Mark RpcExecutor as IA.LimitedPrivate COPROC and PHOENIX

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FifoRpcScheduler.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/MasterFifoRpcScheduler.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcScheduler.java, hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcScheduler.java, hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessor.java, hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncClientPauseForCallQueueTooBig.java, hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/DelegatingRpcScheduler.java
See compatibility discussion from #4173.
FYI @stoty
=> HBASE-26819 Minor code cleanup in and around RpcScheduler

hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java, hbase-http/src/main/java/org/apache/hadoop/hbase/http/InfoServer.java, hbase-http/src/main/java/org/apache/hadoop/hbase/http/gson/ByteArraySerializer.java, hbase-http/src/main/java/org/apache/hadoop/hbase/http/gson/GsonMessageBodyWriter.java, hbase-http/src/main/java/org/apache/hadoop/hbase/http/jersey/ResponseEntityMapper.java, hbase-http/src/main/java/org/apache/hadoop/hbase/http/jersey/SupplierFactoryAdapter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/api_v1/ResourceConfigFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/api_v1/cluster_metrics/model/ClusterMetrics.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/api_v1/cluster_metrics/package-info.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/api_v1/cluster_metrics/resource/ClusterMetricsResource.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/gson/GsonFactory.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/gson/GsonSerializationFeature.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/gson/SizeAsBytesSerializer.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/gson/package-info.java, hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/jersey/MasterFeature.java, hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestApiV1ClusterMetricsResource.java, hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/gson/GsonFactoryTest.java
Publishes a set of JSON endpoints following a RESTful structure, which expose a subset of the
`o.a.h.h.ClusterMetrics` object tree. The URI structure is as follows
/api/v1/admin/cluster_metrics
/api/v1/admin/cluster_metrics/live_servers
/api/v1/admin/cluster_metrics/dead_servers
=> HBASE-25895 Implement a Cluster Metrics JSON endpoint

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/throttle/StoreHotnessProtector.java
See discussion in https://issues.apache.org/jira/browse/HBASE-26814
=> HBASE-26814 Addendum: Fix spotbugs warning and clarify intent

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncProtobufLogWriter.java, hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AbstractWALRoller.java
See the discussion on HBASE-26715
=> HBASE-26715 Blocked on SyncFuture in AsyncProtobufLogWriter#write

dev-support/git-jira-release-audit/requirements.txt
Bumps urllib3 from 1.25.8 to 1.26.5 to resolve two dependabot warnings
- CRLF injection (Moderate) urllib3 (pip) · dev-support/git-jira-release-audit/requirements.txt
- Catastrophic backtracking in URL authority parser when passed URL containing many @ characters (High) urllib3 (pip) · dev-support/git-jira-release-audit/requirements.txt
Bumps cryptography from 2.8 to 3.3.2 to resolve one dependabot warning
- RSA decryption vulnerable to Bleichenbacher timing vulnerability (Moderate) cryptography (pip) · dev-support/git-jira-release-audit/requirements.txt
=> HBASE-26821 Bump dependencies in /dev-support/git-jira-release-audit
