hbase-examples/src/test/java/org/apache/hadoop/hbase/coprocessor/example/TestRefreshHFilesEndpoint.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/regionserver/CompactionTool.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HMobStore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestIOFencing.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSideScanExcpetion.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCacheOnWriteInSchema.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactingMemStore.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactionPolicy.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHMobStore.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStore.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestNotCleanupCompactedFileWhenRegionWarmup.java

Should not archive the compacted store files when region warmup

HBASE-22163 Should not archive the compacted store files when region warmup

---

src/site/xdoc/downloads.xml

HBASE-22220 Release hbase-connectors-1.0.0

---

pom.xml

Raised the version of metrics-core from 3.2.1 to 3.2.6.

HBASE-20494 Updated the version of metrics-core to 3.2.6

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/RestoreTool.java

The method incrementalRestoreTable(...) could be thrown  an NullPointerException and modify method checkAndCreateTable(...)'s doc

[HBASE-22453] A NullPointerException could be thrown

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java

[RPC] set guard against CALL_QUEUE_HANDLER_FACTOR_CONF_KEY

---

hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestMetaTableMetrics.java

This is the same fix of HBASE-22637 on branch-1 that what was already merged on master: https://github.com/apache/hbase/pull/346
fixes / changes:
- wait until all the metrics appear on JMX (previously we were only waiting for the bean to appear, I think this was the cause behind fleakyness)
- testing all the jmx attributes for all metrics / operations
- rename the test (test -> testMetaTableMetricsInJmx)
Note: it looks the hbase-client on hbase 1.4 doesn't really use the get operation to query the meta table information, but is using scan instead. (so for the sake of the test, we now also query the meta table directly to see if the get operation is counted or not) It might be a good idea to extend the MetaMetrics feature with measuring the scan operations as well.

HBASE-22637 fix flaky test in TestMetaTableMetrics

---

src/main/asciidoc/_chapters/architecture.adoc

@anoopsjohn @zyork  please review

HBASE-22628 Document the custom WAL directory (hbase.wal.dir) usage

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupBasedLoadBalancer.java

Changed log level to DEBUG level for "Group not found for table".

HBASE-22702 [Log] 'Group not found for table' is chatty

---

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java

Added caller info to grant / revoke audit log events.
`branch-2.1` version

HBASE-22759 Add user info to AUDITLOG events when doing grant/revoke (2.1)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java
hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java

Creating a PR for branch-2 to run unit tests from branch-2.

[HBASE-22601] Misconfigured addition of peers leads to cluster shutdown.

---

pom.xml

Multiple httpcore and httpclient versions included in binary package (branch-1.3 and branch-1.4)

HBASE-22900

---

hbase-shaded/hbase-shaded-with-hadoop-check-invariants/pom.xml

Use correct version for extra-enforcer-rules

HBASE-22927 Upgrade Mockito version for jdk11 - ADDENDUM

---

src/main/asciidoc/_chapters/community.adoc
src/main/asciidoc/_chapters/configuration.adoc
src/site/site.xml
src/site/xdoc/downloads.xml

* Remove from downloads
* Remove nav menu item
* Remove from compat ref guide
* Remove from list of release managers
Tested by building site locally.

HBASE-22968 Update website for branch-2.0 EOL

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/CompactSplitThread.java

HBASE-22930 Set unique name to longCompactions/shortCompactions threads

---

dev-support/create-release/release-util.sh

The latest version of Apache Yetus is 0.11.0

HBASE-23031 Upgrade Yetus version in RM scripts

---

hbase-shell/src/main/ruby/hbase/quotas.rb
hbase-shell/src/main/ruby/shell/commands/describe_namespace.rb
hbase-shell/src/test/ruby/hbase/admin_test.rb

```
hbase(main):025:0> describe_namespace 'hbase'
DESCRIPTION
{NAME => 'hbase'}
QUOTAS
ERROR: Unknown table hbase:quota!
For usage try 'help "describe_namespace"'
```

HBASE-23140 Remove unknown table error

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RSGroupListTmpl.jamon
hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionServerListTmpl.jamon
hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/RegionListTmpl.jamon
hbase-server/src/main/resources/hbase-webapps/master/rsgroup.jsp
hbase-server/src/main/resources/hbase-webapps/master/table.jsp

The change was conflict with HBASE-22543. Fixed it.

HBASE-23115 Unit change for StoreFileSize and MemStoreSize

---

hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
hbase-protocol-shaded/src/main/protobuf/Client.proto
hbase-protocol-shaded/src/main/protobuf/WAL.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/client/AsyncClusterConnection.java
hbase-server/src/main/java/org/apache/hadoop/hbase/client/AsyncClusterConnectionImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/mob/compactions/PartitionedMobCompactor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SecureBulkLoadManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSink.java
hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFiles.java
hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFilesTool.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/DummyAsyncClusterConnection.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkLoadReplication.java
hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestBulkLoadHFilesSplitRecovery.java

Additional PR to address test issues introduced by having more than one test methods in TestBulkLoadReplication class. This will also amend the previous PR that had been reverted.

HBASE-23136

---

hbase-client/src/main/java/org/apache/hadoop/hbase/protobuf/ProtobufUtil.java
hbase-common/src/main/java/org/apache/hadoop/hbase/ByteBufferKeyValue.java
hbase-common/src/main/java/org/apache/hadoop/hbase/CellUtil.java
hbase-common/src/main/java/org/apache/hadoop/hbase/PrivateCellUtil.java
hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/BufferedDataBlockEncoder.java
hbase-common/src/test/java/org/apache/hadoop/hbase/TestCellUtil.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/util/MapReduceExtendedCell.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestSyncTable.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/CompressionTest.java
hbase-server/src/test/java/org/apache/hadoop/hbase/HFilePerformanceEvaluation.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestTagRewriteCell.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAppendFromClientSide.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestIncrementsFromClientSide.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestResultFromCoprocessor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java
hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlockIndex.java
hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileInlineToRootChunkConversion.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkLoad.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionReplayEvents.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreScanner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSWALEntry.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/ThriftUtilities.java

Remove all deprecated methods of CellUtil
Jira: https://issues.apache.org/jira/browse/HBASE-22679

HBASE-22679 : Revamping CellUtil

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
hbase-server/src/main/resources/hbase-webapps/master/rsgroup.jsp
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAdmin.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java

Rsgroup.jsp call Admin#listTableDescriptors((Pattern)null, true) with Pattern null but implementation RawAsyncHBaseAdmin#listTableDescriptors don't allow null by Precondition.

HBASE-23203 NPE in RSGroup info

---

hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/TokenUtil.java

This reverts commit d7b90b319908113bb90ae871cf4a5843bbf6bbaa.

Revert "HBASE-23194 Remove unused methods from TokenUtil (#737)"

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionsRecoveryChore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionsRecoveryConfigManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionsRecoveryConfigManager.java
src/main/asciidoc/_chapters/configuration.adoc

Jira: https://issues.apache.org/jira/browse/HBASE-23212

HBASE-23212 : Dynamically reload configs for Region Recovery chore

---

hbase-server/src/main/resources/hbase-webapps/master/quotas.jsp

QuotaManager will be started after master initialization. If no online regionservers then master will not be initialized and will throw NPE over accessing Quota page.

HBASE-23263 NPE in Quotas.jsp

---

dev-support/hbase-personality.sh

Testing locally with this version of our yetus personality and #251 for HBASE-22114
* using jdk7 properly ignores the added module
* using jdk8 properly shows the issues present in it according to precommit.

HBASE-23228 Allow for jdk8 specific modules on branch-1 in precommit/nightly testing

---

src/main/asciidoc/_chapters/configuration.adoc

HBASE-23284 Fix Hadoop wiki link in Developer guide to "Distributions and Commercial Support"

---

hbase-client/src/main/java/org/apache/hadoop/hbase/filter/BinaryComponentComparator.java
hbase-client/src/test/java/org/apache/hadoop/hbase/filter/TestComparators.java
hbase-protocol-shaded/src/main/protobuf/Comparator.proto
hbase-protocol/src/main/protobuf/Comparator.proto
hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFiltersWithBinaryComponentComparator.java
src/main/asciidoc/_chapters/architecture.adoc

A new binary component comparator(BinaryComponentComparator) to perform comp
arison of arbitrary length and position

HBASE-22969 A new binary component comparator(BinaryComponentComparator) to perform comparison of arbitrary length and position

---

hbase-server/src/main/resources/hbase-webapps/master/table.jsp

[HBASE-23278](https://issues.apache.org/jira/browse/HBASE-23278)

HBASE-23278 Add a table-level compaction progress display on the UI 

---

hbase-server/src/main/resources/hbase-webapps/master/table.jsp

[HBASE-23278](https://issues.apache.org/jira/browse/HBASE-23278)

HBASE-23278 Add a table-level compaction progress display on the UI (for branch-1)

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/ReorderPackagesCommandAction.java

Fix percentage in String.format

HBASE-23085 Network and Data related Actions; ADDENDUM

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRequestsPerSecondMetric.java

HBASE-23237 Prevent Negative values in metrics requestsPerSecond

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/EncodedDataBlock.java
hbase-common/src/test/java/org/apache/hadoop/hbase/io/encoding/TestEncodedDataBlock.java

Jira: https://issues.apache.org/jira/browse/HBASE-23342

HBASE-23342 : Handle NPE while closing compressingStream

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RetriesExhaustedException.java

Simple improvement from reading logs. Right now we print something like `Thu Dec 05 23:11:14 UTC 2019`. After this patch, we print something like `2019-12-06T00:09:05.744445Z`.

HBASE-23373 Log `RetriesExhaustedException` context with full time precision

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RetriesExhaustedException.java

Signed-off-by: Lijin Bin <binlijin@apache.org>

HBASE-23373 Log `RetriesExhaustedException` context with full time precision (#903)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/HeterogeneousRegionCountCostFunction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCostRules.java

Backport of [HBASE-23073](https://issues.apache.org/jira/browse/HBASE-23073)

HBASE-23073 Add an optional costFunction to balance regions according to a capacity rule

---

hbase-it/src/test/java/org/apache/hadoop/hbase/test/IntegrationTestBigLinkedList.java

We have this nice description in the java doc on ITBLL but it's
unformatted and thus illegible. Add some formatting so that it can be
read by humans.

HBASE-23552 Format Javadocs on ITBLL

---

hbase-http/src/main/java/org/apache/hadoop/hbase/http/ProfileServlet.java
src/main/asciidoc/_chapters/profiler.adoc

 HBASE-23570 Point users to the async-profiler home page if diagrams are coming up blank

---

pom.xml

Backport of #1004 to branch-2.

HBASE-23664 Upgrade JUnit to 4.13

---

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java

HBASE-23045.currentPath may be stitched in a loop in replication source code.

---

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RegionReplicaReplicationEndpoint.java
hbase-server/src/main/java/org/apache/hadoop/hbase/wal/OutputSink.java
hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java
hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestOutputSinkWriter.java

clear exception after logged
try to restart writer threads if needed
adapt code to branch-2

    HBASE-23601  OutputSink.WriterThread exception gets stuck and repeated indefinietly

---

src/main/asciidoc/_chapters/developer.adoc

This works but not sure if it generally good.

HBASE-23690 Checkstyle plugin complains about our checkstyle.xml format

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/webapp/MetaBrowser.java

HBASE-23653 Expose content of meta table in web ui; addendum

---

hbase-common/src/test/java/org/apache/hadoop/hbase/types/TestStruct.java
hbase-common/src/test/java/org/apache/hadoop/hbase/types/TestUnion2.java
hbase-common/src/test/java/org/apache/hadoop/hbase/util/ClassLoaderTestHelper.java
hbase-common/src/test/java/org/apache/hadoop/hbase/util/EnvironmentEdgeManagerTestHelper.java
hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestBytes.java
hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestCoprocessorClassLoader.java
hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestOrderedBytes.java
hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestSimplePositionedMutableByteRange.java
hbase-common/src/test/java/org/apache/hadoop/hbase/util/TimeOffsetEnvironmentEdge.java

HBASE-23626 Reduced number of Checkstyle violations in tests in hbase-common

---

hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/ResultGenerator.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RowResultGenerator.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/client/Response.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/filter/GZIPRequestStream.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/filter/GZIPResponseStream.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/filter/GzipFilter.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/filter/RestCsrfPreventionFilter.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/model/CellSetModel.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/model/StorageClusterStatusModel.java
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/model/TableSchemaModel.java

Backport of #1000 to branch-2.

HBASE-23661 Reduced number of Checkstyle violations in hbase-rest

---

hbase-common/src/main/java/org/apache/hadoop/hbase/CellScanner.java
hbase-common/src/main/java/org/apache/hadoop/hbase/IndividualBytesFieldCell.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/AbstractByteRange.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/AbstractPositionedByteRange.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/AtomicUtils.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/DynamicClassLoader.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/ExceptionUtil.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/Methods.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/Sleeper.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/Strings.java

HBASE-23625 Reduced number of Checkstyle violations in hbase-common

---

src/main/asciidoc/_chapters/architecture.adoc
src/main/asciidoc/_chapters/offheap_read_write.adoc

Signed-off-by: Anoop Sam John <anoopsamjohn@apacher.org>

HBASE-20516 Offheap read-path needs more detail

---

.idea/checkstyle-idea.xml
pom.xml

HBASE-23707 Add IntelliJ check style plugin configuration (#1064)

---

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshotNoCluster.java

1. Survive flakey rerunning by converting the static BeforeClass stuff
into instance-level Before.
2. Break the test method into two, one for running over each of the
snapshot manifest versions.

HBASE-23792 [Flakey Test] TestExportSnapshotNoCluster.testSnapshotWithRefsExportFileSystemState

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Append.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/Delete.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/Increment.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/Mutation.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/Put.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMutationGetCellBuilder.java
src/main/asciidoc/_chapters/datamodel.adoc

- this is still a work in the progress, Plz don't review before removing the WIP tag.
- more details in the [HBASE-20623](https://issues.apache.org/jira/browse/HBASE-20623)

HBASE-20623: [WIP]Introduce the helper method "getCellBuilder()" to Mutation

---

hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MetaTableMetrics.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/LossyCounting.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestLossyCounting.java

Backport HBASE-23802 to branch-1.4

---

hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestSnapshotFromMaster.java

Backport of HBASE-23658 - Fix flaky TestSnapshotFromMaster
(cherry picked from commit e750d2c7af03bfcb85422077cf59ab4b1815cb12)

HBASE-23862 Fix flaky TestSnapshotFromMaster in 1.x versions

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
hbase-shell/src/main/ruby/hbase/admin.rb
hbase-shell/src/main/ruby/shell/commands.rb
hbase-shell/src/main/ruby/shell/commands/merge_region.rb
hbase-shell/src/test/ruby/hbase/admin_test.rb

(cherry picked from commit 4b704346b519fd9c7cb1f0b658e76b259ebd5960)

HBASE-22827 Expose multi-region merge in shell and Admin API

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAdmin1.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionAdminApi2.java

HBASE-22040 - Add mergeRegionsAsync with a List of region names method in AsyncAdmin

HBASE-23878 : Backport HBASE-22040 to branch-2.1

---

hbase-http/src/test/java/org/apache/hadoop/hbase/http/ssl/KeyStoreTestUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/token/SecureTestCluster.java

…nds SecureTestCluster and hbase-server is referred as a jar file.

HBASE-23892 SecureTestCluster should allow its subclasses to pass their Class reference on HBaseKerberosUtils.setSSLConfiguration

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
hbase-shell/src/main/ruby/hbase/admin.rb
hbase-shell/src/main/ruby/shell/commands.rb
hbase-shell/src/main/ruby/shell/commands/merge_region.rb
hbase-shell/src/test/ruby/hbase/admin_test.rb

(cherry picked from commit c4a03c14ecc50604f44cf3b97ffdc40eddda70fd)

HBASE-22827 Expose multi-region merge in shell and Admin API (branch-2.1)

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/Table.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
hbase-protocol-shaded/src/main/protobuf/Client.proto
hbase-protocol/src/main/protobuf/Client.proto
hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/client/RemoteHTable.java
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Region.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestCheckAndMutate.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMalformedCellFromClient.java
hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/SimpleRegionObserver.java
hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestRegionObserverInterface.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/RegionAsTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftTable.java

HBASE-23146 Support CheckAndMutate with multiple conditions

---

dev-support/Dockerfile
dev-support/create-release/hbase-rm/Dockerfile
dev-support/hbase_docker/Dockerfile

Revert "HBASE-23945 Dockerfiles showing hadolint check failures"

---

dev-support/Dockerfile
dev-support/apache_hbase_topology/Dockerfile
dev-support/apache_hbase_topology/README.md
dev-support/apache_hbase_topology/__init__.py
dev-support/apache_hbase_topology/actions.py
dev-support/apache_hbase_topology/configurations.cfg
dev-support/apache_hbase_topology/profile.cfg
dev-support/apache_hbase_topology/ssh/id_rsa
dev-support/apache_hbase_topology/ssh/id_rsa.pub
dev-support/hbase_docker/Dockerfile

Revert "Backport HBASE-23945, HBASE-18418 to branch-2"

---

dev-support/Jenkinsfile
dev-support/Jenkinsfile_GitHub

HBASE-23946 [JDK11] Yetus should vote -0 for known JDK11 issues

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java

Signed-off-by: tedyu <yuzhihong@gmail.com>

Back-port "HBASE-20289 Fix comparator for NormalizationPlan" to branch-2

---

dev-support/Dockerfile
dev-support/create-release/hbase-rm/Dockerfile
dev-support/docker/Dockerfile
dev-support/hbase_docker/Dockerfile
dev-support/hbase_docker/README.md

Trying again. #1244 plus fixes -- all containers build locally for me. Not sure how to test that they all run as expected.

HBASE-23945 Dockerfiles showing hadolint check failures

---

hbase-common/src/main/resources/hbase-default.xml
hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/AbstractRegionNormalizer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/MergeNormalizer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestMergeNormalizer.java

Patch from master applies mostly cleanly.

Back-port "HBASE-22285 A normalizer which merges small size regions with adjacent regions (#978)" to branch-2

---

hbase-server/pom.xml
pom.xml

Clean cherrypick from master branch to branch-2. See: #1179

HBASE-23861. Reconcile Hadoop version.

---

.rubocop.yml

HBASE-23943 Updated Rubocop configuration to current version

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java

Check and delete the incomplete/corrupted recovered hfiles whose length is zero.

HBASE-23633 Find a way to handle the corrupt recovered hfiles

---

hbase-server/src/main/java/org/apache/hadoop/hbase/util/RegionMover.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestRegionMoverWithRSGroupEnable.java

JIRA link: https://issues.apache.org/jira/browse/HBASE-22740

[RSGroup] Forward-port HBASE-22658 to master branch and branch-2.x

---

dev-support/adhoc_run_tests/adhoc_run_tests.sh

Backport "HBASE-24045 Support setting `-Dhadoop.profile` in adhoc_run_tests.sh" to branch-2

---

dev-support/adhoc_run_tests/adhoc_run_tests.sh

Backport "HBASE-24045 Support setting `-Dhadoop.profile` in adhoc_run_tests.sh" to branch-2.3

---

dev-support/adhoc_run_tests/adhoc_run_tests.sh

* Correctly handle the hadoop2 profile.
* Create the output directory if it doesn't exist

HBASE-24045 Support setting `-Dhadoop.profile` in adhoc_run_tests.sh ADDENDUM

---

dev-support/adhoc_run_tests/adhoc_run_tests.sh

* Correctly handle the hadoop2 profile.
* Create the output directory if it doesn't exist

Backport "HBASE-24045 Support setting `-Dhadoop.profile` in adhoc_run_tests.sh ADDENDUM" to branch-2

---

dev-support/adhoc_run_tests/adhoc_run_tests.sh

* Correctly handle the hadoop2 profile.
* Create the output directory if it doesn't exist

Backport "HBASE-24045 Support setting `-Dhadoop.profile` in adhoc_run_tests.sh ADDENDUM" to branch-2.3

---

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionAdminApi.java

Reverts apache/hbase#1378 
Need to add singed-off-by and correct my email address.

Revert "HBASE-24073 [flakey test] client.TestAsyncRegionAdminApi messed up co…"

---

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionAdminApi.java

Backport HBASE-24073 [flakey test] client.TestAsyncRegionAdminApi messed up compaction state. (#1387)

---

dev-support/Jenkinsfile

Backport "HBASE-24092 Fix links to build reports generated by nightly job" to branch-2

---

dev-support/Jenkinsfile

Backport "HBASE-24092 Fix links to build reports generated by nightly job" to branch-2.3

---

hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java

Backport" HBASE-24086 Disable output stream capability enforcement when running on LocalFileSystem" to branch-2

---

hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java

Backport" HBASE-24086 Disable output stream capability enforcement when running on LocalFileSystem" to branch-2.3

---

dev-support/Jenkinsfile
dev-support/hbase_nightly_pseudo-distributed-test.sh
dev-support/hbase_nightly_source-artifact.sh

Backport "HBASE-24049 use hadoop-2.10.0 for "packaging and integration" check" to branch-2

---

dev-support/Jenkinsfile
dev-support/hbase_nightly_pseudo-distributed-test.sh
dev-support/hbase_nightly_source-artifact.sh

Backport "HBASE-24049 use hadoop-2.10.0 for "packaging and integration" check" to branch-2.3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/CloseRegionHandler.java

It is hard to put the root cause analysis in nice format. Attach it as a file.
[rootcause.txt](https://github.com/apache/hbase/files/4424528/rootcause.txt)

HBASE-24105 [Flakey Test] regionserver.TestRegionReplicas

---

dev-support/HOW_TO_YETUS_LOCAL.md

Backport "HBASE-24081 Provide documentation for running Yetus with HBase" to branch-2

---

dev-support/HOW_TO_YETUS_LOCAL.md

Backport "HBASE-24081 Provide documentation for running Yetus with HBase" to branch-1

---

dev-support/HOW_TO_YETUS_LOCAL.md

Backport" HBASE-24130 rat plugin complains about having an unlicensed file (#1445)" to branch-2

---

dev-support/HOW_TO_YETUS_LOCAL.md

Backport "HBASE-24130 rat plugin complains about having an unlicensed file (#1445)" to branch-1

---

hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestSnapshotScannerHDFSAclController.java

[Backport] HBASE-24114 [Flakey Tests] TestSnapshotScannerHDFSAclController (#1433)

---

hbase-resource-bundle/src/main/resources/supplemental-models.xml

HBASE-23998. Update license for jetty-client. (#1297)

---

hbase-protocol-shaded/pom.xml

HBASE-24168 Align the internal.protobuf.version in hbase-protocol-shaded with hbase-thirdparty

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/tool/CanaryStatusTmpl.jamon
hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryStatusServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java
hbase-server/src/main/resources/hbase-webapps/canary/canary.jsp
hbase-server/src/main/resources/hbase-webapps/canary/index.html
hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestCanaryStatusServlet.java

Backport "HBASE-23994: Add WebUI to Canary (#1292)" to branch-2

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/tool/CanaryStatusTmpl.jamon
hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryStatusServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java
hbase-server/src/main/resources/hbase-webapps/canary/canary.jsp
hbase-server/src/main/resources/hbase-webapps/canary/index.html
hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestCanaryStatusServlet.java

Backport "HBASE-23994: Add WebUI to Canary (#1292)" to branch-2.3

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/util/ChaosMonkeyRunner.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/util/Monkeys.java
hbase-it/src/test/java/org/apache/hadoop/hbase/test/IntegrationTestMonkeys.java

JIRA Links: [HBASE-18651](https://issues.apache.org/jira/browse/HBASE-18651)      [HBASE-24193](https://issues.apache.org/jira/browse/HBASE-24193)

HBASE-24193 : BackPort HBASE-18651 to branch-1

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupBasedLoadBalancer.java

Revert "HBASE-24151 The master server aborted for IllegalThreadStateException"

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java

[HBASE-24177] MetricsTable#updateFlushTime is wrong

---

hbase-shell/src/main/ruby/hbase/rsgroup_admin.rb
hbase-shell/src/main/ruby/shell.rb
hbase-shell/src/main/ruby/shell/commands/rename_rsgroup.rb
hbase-shell/src/test/ruby/shell/rsgroup_shell_test.rb

JIRA link: [HBASE-24196](https://issues.apache.org/jira/browse/HBASE-24196)

HBASE-24196 [Shell] Add rename rsgroup command in hbase shell

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java

Balancer should avoid leaving idle region servers

HBASE-24139 : Balancer should avoid leaving idle region servers

---

dev-support/docker/Dockerfile

Revert "HBASE-24229 [Build] Pin rubocop version <= 0.81"

---

bin/hbase-config.sh
conf/hbase-env.sh

Backport "HBASE-24143 [JDK11] Switch default garbage collector from CMS ; Addendum (#1594)" to branch-2

---

bin/hbase-config.sh
conf/hbase-env.sh

Backport "HBASE-24143 [JDK11] Switch default garbage collector from CMS ; Addendum (#1594)" to branch-2.3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputHelper.java

(cherry picked from commit 7b2fe82be3344d526175734d93bef32fbcb0d73f)

HBASE-24236 Backport HBASE-22103 to branch-2.2

---

hbase-it/pom.xml
hbase-it/src/test/java/org/apache/hadoop/hbase/MockHttpApiRule.java
hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java
hbase-it/src/test/java/org/apache/hadoop/hbase/TestRESTApiClusterManager.java

Use the correct GSON API for deserializing service responses. Add
simple unit test covering a very limited selection of the overall API
surface area, just enough to ensure deserialization works.
Assuming this works for you folks, I'll port to appropriate branches.

HBASE-24274 `RESTApiClusterManager` attempts to deserialize response using serialization API

---

hbase-it/pom.xml
hbase-it/src/test/java/org/apache/hadoop/hbase/MockHttpApiRule.java
hbase-it/src/test/java/org/apache/hadoop/hbase/RESTApiClusterManager.java
hbase-it/src/test/java/org/apache/hadoop/hbase/TestRESTApiClusterManager.java

Use the correct GSON API for deserializing service responses. Add
simple unit test covering a very limited selection of the overall API
surface area, just enough to ensure deserialization works.

Forward-port "HBASE-24274 `RESTApiClusterManager` attempts to deserialize response using serialization API" to master

---

hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFilesTool.java
hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestBulkLoadHFiles.java
hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestBulkLoadHFilesByFamily.java

Support bulkLoadHFile by family to avoid long time waiting of bulkLoadHFile because of compacting at server side

HBASE-24221 Support bulkLoadHFile by family

---

hbase-server/src/main/java/org/apache/hadoop/hbase/JMXListener.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestJMXListener.java

Add check that we can make jmx connector in setup. If we can't retry.

HBASE-24331 [Flakey Test] TestJMXListener rmi port clash

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActiveMasterAction.java

HBASE-24295 [Chaos Monkey] abstract logging through the class hierarchy ; ADDENDUM

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActiveMasterAction.java

Backport "HBASE-24295 [Chaos Monkey] abstract logging through the class hierarchy ; ADDENDUM" to branch-2

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActiveMasterAction.java

Backport "HBASE-24295 [Chaos Monkey] abstract logging through the class hierarchy ; ADDENDUM" to branch-2.3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java
hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsBase.java
hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsWithACL.java

JIRA: [HBASE-24345](https://issues.apache.org/jira/browse/HBASE-24345)

HBASE-24345 [ACL] renameRSGroup should require Admin level permission

---

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterShutdown.java

Revert "HBASE-24327 : Handle shutdown() if master cannot be contacted"

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java

HBASE-24355 Fix typos in the HStore#compact annotation

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java
hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManager.java
hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java
hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupUtil.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestDetermineRSGroupInfoForTable.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupMappingScript.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupUtil.java

https://issues.apache.org/jira/browse/HBASE-24135

HBASE-24135 TableStateNotFoundException happends when table creation if rsgroup is enable

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RSGroupListTmpl.jamon
hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionServerListTmpl.jamon
hbase-server/src/main/resources/hbase-webapps/master/rsgroup.jsp

[HBASE-24381](https://issues.apache.org/jira/browse/HBASE-24381)

HBASE-24381 The Size metrics in Master Webui is wrong if the size is 0

---

hbase-client/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java
hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStateStore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/webapp/RegionReplicaInfo.java
hbase-server/src/main/resources/hbase-webapps/master/table.jsp
hbase-server/src/main/resources/hbase-webapps/static/css/hbase.css

Backport "HBASE-23969 Meta browser should show all `info` columns" to branch-2.3

---

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitLogManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestFSUtils.java

https://issues.apache.org/jira/browse/HBASE-24435
Cherry-picked https://github.com/apache/hbase/commit/71ed7033675149956de855b6782e1e22fc908dc8 with just a few adjustments to adapt it to current branch-1.

HBASE-24435 Add hedgedReads and hedgedReadWins count metrics

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RSProcedureDispatcher.java

Add some backoff. Does not break off retrying.

HBASE-22287 inifinite retries on failed server in RSProcedureDispatcher

---

conf/log4j.properties

Backport "HBASE-24343 Document how to configure the http request log" to branch-2

---

conf/log4j.properties

Backport "HBASE-24343 Document how to configure the http request log" to branch-2.3

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsBasics.java

More details about the flakiness in the jira comments.

HBASE-24480: Deflake TestRSGroupsBasics#testClearDeadServers

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HBaseInterClusterReplicationEndpoint.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationDroppedTables.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEditsDroppedWithDeletedTableCFs.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEditsDroppedWithDroppedTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStuckWithDeletedTableCFs.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStuckWithDroppedTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestHBaseInterClusterReplicationEndpointFilterEdits.java

https://issues.apache.org/jira/browse/HBASE-24359

HBASE-24359 Optionally ignore edits for deleted CFs for replication

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBatchRpcRetryingCaller.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/CheckAndMutate.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/MultiServerCallable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/Mutation.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/Table.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ResponseConverter.java
hbase-protocol-shaded/src/main/protobuf/Client.proto
hbase-protocol/src/main/protobuf/Client.proto
hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/client/RemoteHTable.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableBatch.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestCheckAndMutate.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide3.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMalformedCellFromClient.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftTable.java

HBASE-8458 Support for batch version of checkAndMutate()

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java

Signed-off-by Reid Chan <reidchan@apache.org>
(cherry picked from commit 7697d48cd7b636396d5f73be43326a4501a9ea43)

HBASE-22870 reflection fails to access a private nested class

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerAbort.java

(cherry picked from commit 2567d1521875ca39eca4762242ce91a3012e088e)

HBASE-24564: Make RS abort call idempotent.

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreScanner.java

Avoid collecting the metrics for flushes and compactions.

HBASE-24205 - Avoid metric collection for flushes and compactions

---

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSource.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapper.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregate.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSourceImpl.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableAggregateSourceImpl.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableSourceImpl.java
hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperStub.java
hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionSourceImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/KeyValueHeap.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregateImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Store.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperStub.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreScanner.java

HBASE-24205 - Create metric to know the number of reads that happens

---

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSource.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapper.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregate.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSourceImpl.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableAggregateSourceImpl.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableSourceImpl.java
hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperStub.java
hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionSourceImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/KeyValueHeap.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregateImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Store.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperStub.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreScanner.java

HBASE-24205 Create metric to know the number of reads that happens from memstore

---

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java

HBASE-24597 : Backport HBASE-24380 (Provide WAL splitting journal logging) (#1860)

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java

Addendum to fix illegal removal of unused constant w/o
a deprecation cycle.

HBASE-23055 Alter hbase:meta

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-common/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfo.java
hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto
hbase-protocol-shaded/src/main/protobuf/server/rsgroup/RSGroup.proto
hbase-protocol-shaded/src/main/protobuf/server/rsgroup/RSGroupAdmin.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/DisabledRSGroupInfoManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java
hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupConfig.java
hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java
hbase-shell/src/main/ruby/hbase/rsgroup_admin.rb
hbase-shell/src/main/ruby/shell.rb
hbase-shell/src/main/ruby/shell/commands/alter_rsgroup_config.rb
hbase-shell/src/main/ruby/shell/commands/show_rsgroup_config.rb
hbase-shell/src/test/ruby/shell/rsgroup_shell_test.rb
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java

JIRA: https://issues.apache.org/jira/browse/HBASE-24431

HBASE-24431 RSGroupInfo add configuration map to store something extra

---

hbase-assembly/src/main/assembly/client-components.xml

Backport "HBASE-24630 Purge dev javadoc from client bin tarball" to branch-2

---

hbase-assembly/src/main/assembly/client-components.xml

Backport "HBASE-24630 Purge dev javadoc from client bin tarball" to branch-2.3

---

hbase-assembly/src/main/assembly/client-components.xml

Backport "HBASE-24630 Purge dev javadoc from client bin tarball" to branch-2.2

---

hbase-assembly/src/main/assembly/client-components.xml

backport "HBASE-24630 Purge dev javadoc from client bin tarball" to branch-2.1

---

hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteBufferUtils.java

Address incompatibility issue raised in 2.3.0RC0 vote thread.

HBASE-22504 Addendum: restore findCommonPrefix

---

hbase-server/src/main/java/org/apache/hadoop/hbase/tool/LoadIncrementalHFiles.java

Signed-off-by: niuyulin <nyl353@163.com>
Signed-off-by: Wellington Ramos Chevreuil <wchevreuil@apache.org>

Backport "HBASE-24221 addendum to restore public interface on LoadIncrementalHFiles" to branch-2.3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/tool/LoadIncrementalHFiles.java

Signed-off-by: niuyulin <nyl353@163.com>
Signed-off-by: Wellington Ramos Chevreuil <wchevreuil@apache.org>

Backport "HBASE-24221 addendum to restore public interface on LoadIncrementalHFiles" to branch-2.2

---

src/main/asciidoc/_chapters/upgrading.adoc

Here's an exception where we willingly don't follow the guidelines as stated. Let's make that clear.

HBASE-24644 Add a clause to the book noting that sometimes we short-circuit the deprecation cycle

---

src/main/asciidoc/_chapters/configuration.adoc
src/main/asciidoc/_chapters/offheap_read_write.adoc
src/main/asciidoc/_chapters/upgrading.adoc

Bring back documentation from master branch (37b863bd0b), using
```
$ git checkout master -- src/main/asciidoc/
$ git checkout master -- src/site/asciidoc/
```
And then:
* remove changes from HBASE-23890
This reverts commit 420e38083f13ebf9ca056d2ee2de2192c23801c7.
* delete docs re: sync_replication
* delete docs re: backup

HBASE-24144 Update docs from master (addendum)

---

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterNoCluster.java

Forward-port from https://github.com/apache/hbase/commit/91da188d78e15ec3ff699765d5983cc372a85997

HBASE-24712 : Remove flakes from TestMasterNoCluster#testStopDuringStart

---

src/site/site.xml

Add a new 2.3 section to the index page menu.
Companion PR to apache/hbase-site#5.

HBASE-24487 Add 2.3 Documentation to the website

---

dev-support/docker/Dockerfile

Try to use the latest pylint version that supports python2.7.

HBASE-24739 [Build] branch-1's build seems broken because of pylint

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java

In our testing of HBase 1.3 against the current tip of branch-1 we saw a 30% slowdown in scanning scenarios.
We tracked it back to HBASE-17958 and HBASE-19863.
Both add comparisons to one of the tightest HBase has.
The observation is that we do not need to guard against ROWCOL Bloomfilters fake keys if ROWCOL BFs are either not used or not setup for this Store.

HBASE-24742 Improve performance of SKIP vs SEEK logic.

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java

HBASE-24658 Update PolicyBasedChaosMonkey to handle uncaught exceptions

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java

Forward-port "HBASE-24658 Update PolicyBasedChaosMonkey to handle uncaught exceptions" to branch-2

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java

Backport "HBASE-24658 Update PolicyBasedChaosMonkey to handle uncaught exceptions" to branch-2.2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
hbase-common/src/main/resources/hbase-default.xml
hbase-protocol-shaded/src/main/protobuf/server/region/Admin.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServerInterface.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/DisruptorExceptionHandler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/LogEventHandler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/LogHandlerUtils.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/NamedQueuePayload.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/NamedQueueRecorder.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/NamedQueueService.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/RingBufferEnvelope.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/RpcLogDetails.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/SlowLogPersistentService.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/SlowLogQueueService.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/SlowLogTableOpsChore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/impl/SlowLogQueueService.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/request/NamedQueueGetRequest.java
hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/response/NamedQueueGetResponse.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestNamedQueueRecorder.java
hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestSlowLogAccessor.java
hbase-shell/src/test/ruby/hbase/admin_test.rb
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThriftHBaseServiceHandler.java

HBASE-24718 : Generic NamedQueue framework for multiple use-cases (Refactor SlowLog responses)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotManifest.java

We observed this delete call to be a bottleneck for table with lots of
regions. Patch attempts to parallelize them.
(cherry picked from commit f07f30ae24e6d0e9151bb76aebf78928ec9572e3)

HBASE-20226: Parallelize region manifest deletes (#2159)

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/CheckAndMutate.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Region.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/SimpleRegionObserver.java
hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestRegionObserverInterface.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java

HBASE-24680 Refactor the checkAndMutate code on the server side

---

hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java

Backport: HBASE-24824 Add more stats in PE for read replica (#2205)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java

Backport "HBASE-24835 Normalizer should log a successful run at INFO level" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java

Backport "HBASE-24835 Normalizer should log a successful run at INFO level" branch-2.3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RSProcedureDispatcher.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/CompactSplit.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestServerSideScanMetricsFromClientSide.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionAdminApi.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide3.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestScannersFromClientSide.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterShutdown.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRegionMoveAndAbandon.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestSimpleLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaObserverChoreRegionReports.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompaction.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestEndToEndSplitTransaction.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionReplicas.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestAccessController.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestCellACLWithMultipleVersions.java
hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestCanaryTool.java

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide3.java
Be explicit about timestamping to avoid concurrent edit landing
server-side and messing up test expectation.

HBASE-24878 Backport part of HBASE-24079 and HBASE-24034

---

dev-support/create-release/release-build.sh

HBASE-24799 Do not call make_binary_release for hbase-thirdparty in release scripts

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/RegionReplicaFlushHandler.java

HBASE-24897 RegionReplicaFlushHandler should handle NoServerForRegionException to avoid aborting RegionServer

---

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaWithReplicasBasic.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestAssignmentManagerMetrics.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEndpoint.java

HBASE-24906 Enlarge the wait time in TestReplicationEndpoint/TestMetaWithReplicasBasic

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/CurrentHourProvider.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestCurrentHourProvider.java

(cherry picked from commit 14e456c8cb828f24e6525e076daeec97854c3f7f)

HBASE-24898 Addendum to deal with Daylight Saving Time

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/CheckAndMutate.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ResponseConverter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MiniBatchOperationInProgress.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/OperationStatus.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Region.java
hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableBatch.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestCheckAndMutate.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide3.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestAtomicOperation.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java

HBASE-24602 Add Increment and Append support to CheckAndMutate

---

hbase-thrift/src/test/resources/hbase-site.xml

…axthreads' in hbase-thrift module

HBASE-24990 Fix empty value of properties 'hbase.replication.source.maxthreads' in hbase-thrift module

---

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java
src/main/asciidoc/_chapters/performance.adoc

https://issues.apache.org/jira/browse/HBASE-24994
master PR (merged): https://github.com/apache/hbase/pull/2365
branch-1 PR: https://github.com/apache/hbase/pull/2368

HBASE-24994 Add hedgedReadOpsInCurThread metric

---

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALPrettyPrinter.java

@bharathv  This is backport to branch-2

HBASE-24974: Provide a flexibility to print only row key and filter for multiple tables in the WALPrettyPrinter

---

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALPrettyPrinter.java

backport of https://github.com/apache/hbase/pull/2345

HBASE-24974: Provide a flexibility to print only row key and filter for multiple tables in the WALPrettyPrinter 

---

hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide.java

[HBASE-25114](https://issues.apache.org/jira/browse/HBASE-25114)

HBASE-25114 [Flake Test][branch-1] TestFromClientSide#testCacheOnWriteEvictOnClose

---

hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshot.java
hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshotWithTemporaryDirectory.java

[HBASE-25122](https://issues.apache.org/jira/browse/HBASE-25122)

HBASE-25122 [Flake Test][branch-1] TestExportSnapshotWithTemporaryDirectory

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogReader.java

HBASE-24503 : Backport HBASE-24492 Remove infinite loop from ProtobufLogReader#readNext (#1831)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/util/hbck/HFileCorruptionChecker.java

Added some extra logs + missing mob files summary.

HBASE-25146 Add extra logging at info level to HFileCorruptionChecker in order to report progress

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionServerListTmpl.jamon

HBASE-25165 Change 'State time' in UI so sorts

---

hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java
hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsAdmin2.java

HBASE-24025: Improve performance of move_servers_rsgroup  by using async region move API

HBASE-24025: Improve performance of move_servers_rsgroup  by using async region move API

---

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterFailover.java

Change the test to wait for evidence that the active master has seen
that the backup master killed by the test has gone away. This is done
before proceeding to validate that the dead backup is correctly
omitted from the ClusterStatus report.
Also, minor fixup to several assertions, using `assertEquals` instead
of `assertTrue(...equals(...))` and correcting expected vs. actual
ordering of assertion arguments.

Backport "HBASE-25156 TestMasterFailover.testSimpleMasterFailover is flaky (#2507)" to branch-2

---

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterFailover.java

Change the test to wait for evidence that the active master has seen
that the backup master killed by the test has gone away. This is done
before proceeding to validate that the dead backup is correctly
omitted from the ClusterStatus report.
Also, minor fixup to several assertions, using `assertEquals` instead
of `assertTrue(...equals(...))` and correcting expected vs. actual
ordering of assertion arguments.

Backport "HBASE-25156 TestMasterFailover.testSimpleMasterFailover is flaky (#2507)" to branch-1

---

dev-support/flaky-tests/run-flaky-tests.Jenkinsfile

Change the trigger interval from 12h to 4h

HBASE-25162 Make flaky tests run more aggressively

---

dev-support/hbase-personality.sh

Revert the previous commit, apply a new set of rules based on discussion on JIRA.

"HBASE-25144 Add Hadoop-3.3.0 to personality hadoopcheck" try again

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/MetricsHBaseServerWrapperImpl.java

https://issues.apache.org/jira/browse/HBASE-25195

HBASE-25195 [branch-1] getNumOpenConnections is not effective

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStates.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/EnableTableProcedure.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRegionStates.java

Remove the RegionStates.include method as its name is ambiguous.
Add more comments to describe the logic on why we filter region like
this.

HBASE-25207 Revisit the implementation and usage of RegionStates.include

---

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableLatencies.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableLatenciesImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerTableMetrics.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java

https://issues.apache.org/jira/browse/HBASE-25189

HBASE-25189 [Metrics] Add checkAndPut and checkAndDelete latency metrics at table level

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/CatalogJanitor.java
hbase-server/src/main/resources/hbase-webapps/master/hbck.jsp

HBASE-25219 Backport HBASE-24369 Provide more information about merged child regions in Hbck Overlaps section, which cannot be fixed immediately

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptor.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java
hbase-endpoint/src/test/java/org/apache/hadoop/hbase/coprocessor/TestSecureExport.java
hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java
hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/SnapshotScannerHDFSAclController.java
hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/SnapshotWithAclTestBase.java
hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsWithACL.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/SecureTestUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestAccessController.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestAccessController3.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestCellACLWithMultipleVersions.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestCellACLs.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestHDFSAclHelper.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestScanEarlyTermination.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestSnapshotScannerHDFSAclController.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestWithDisabledAuthorization.java
hbase-shell/src/main/ruby/hbase/admin.rb
hbase-shell/src/main/ruby/shell/commands/alter.rb
hbase-shell/src/main/ruby/shell/commands/create.rb
hbase-shell/src/test/ruby/hbase/admin_test.rb

HBASE-25173 Remove owner related methods in TableDescriptor/TableDescriptorBuilder

---

dev-support/Jenkinsfile
dev-support/Jenkinsfile_GitHub
dev-support/jenkins_precommit_jira_yetus.sh

Backport "HBASE-24200 Upgrade to Yetus 0.12.0" to branch-2

---

dev-support/Jenkinsfile
dev-support/Jenkinsfile_GitHub
dev-support/jenkins_precommit_jira_yetus.sh

Backport "HBASE-24200 Upgrade to Yetus 0.12.0" to branch-2.2

---

dev-support/Jenkinsfile
dev-support/Jenkinsfile_GitHub
dev-support/jenkins_precommit_jira_yetus.sh

Backport "HBASE-24200 Upgrade to Yetus 0.12.0" to branch-1

---

dev-support/Jenkinsfile
dev-support/Jenkinsfile_GitHub
dev-support/jenkins_precommit_jira_yetus.sh

Backport "HBASE-24200 Upgrade to Yetus 0.12.0" to branch-1.4

---

dev-support/Jenkinsfile
dev-support/Jenkinsfile_GitHub
dev-support/jenkins_precommit_jira_yetus.sh

Backport "HBASE-24200 Upgrade to Yetus 0.12.0" to branch-2.3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/CompactionConfiguration.java

Backport "HBASE-25090 CompactionConfiguration logs unrealistic store file sizes (#2612)" to branch-1.4

---

src/main/asciidoc/_chapters/upgrading.adoc

https://issues.apache.org/jira/browse/HBASE-25296

HBASE-25296 [Documentation] fix duplicate conf entry about upgrading

---

hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupBasedLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestRSGroupBasedLoadBalancer.java
src/main/asciidoc/_chapters/configuration.adoc

[HBASE-25298](https://issues.apache.org/jira/browse/HBASE-25298)

HBASE-25298 hbase.rsgroup.fallback.enable should support dynamic configuration

---

hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java
hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestCommonFSUtils.java
hbase-server/src/main/java/org/apache/hadoop/hbase/fs/HFileSystem.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java

HBASE-25050 - We initialize Filesystems more than once.

---

src/main/asciidoc/_chapters/ops_mgt.adoc

[HBASE-25355](https://issues.apache.org/jira/browse/HBASE-25355)

HBASE-25355 [Documentation] Fix spelling error

---

pom.xml

Fix typo in ban-jersey section of the enforcer plugin in pom.xml

HBASE-25372 Remove the extra '>' in pom.xml.

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminServer.java

[HBASE-25365](https://issues.apache.org/jira/browse/HBASE-25365)

HBASE-25365 The log in move_servers_rsgroup is incorrect

---

hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/SecureTestUtil.java

Check SecureTestUtil change in branch-1. Due to the bugs do not exist in branch-1, so just test the SecureTestUtil  change.

HBASE-25432 : branch-1 backport (Update SecureTestUtil)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestAccessController.java

@virajjasani it seems that we miss setRegionStateInMeta, fix it and will backport after review!

HBASE-25456:add security check for setRegionStateInMeta

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-common/src/main/resources/hbase-default.xml
hbase-server/src/main/java/org/apache/hadoop/hbase/io/util/MemorySizeUtil.java
src/main/asciidoc/_chapters/hbase-default.adoc

Shenshengli hbase-25450 The parameter "hbase.bucketcache.size" is misdescribed

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderV2.java

This is the reimplementation of HBASE-25287 following the same logic. @apurtell please review

Backport HBASE-25287 to branch-1

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableDescriptorBuilder.java

MEMSTORE_FLUSHSIZE is missing in TableDescriptorBuilder.getUnit

HBASE-25439 Add BYTE unit in PrettyPrinter.Unit (addendum)

---

hbase-client/src/main/java/org/apache/hadoop/hbase/HTableDescriptor.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableDescriptorBuilder.java
hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/PrettyPrinter.java
hbase-shell/src/main/ruby/hbase/admin.rb

backport [HBASE-25439](https://issues.apache.org/jira/browse/HBASE-25439) to branch-2

HBASE-25439 Add BYTE unit in PrettyPrinter.Unit

---

hbase-server/src/main/java/org/apache/hadoop/hbase/util/TableDescriptorChecker.java

[HBASE-25431](https://issues.apache.org/jira/browse/HBASE-25431)

HBASE-25431 MAX_FILESIZE and MEMSTORE_FLUSHSIZE should not be set negative number

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java

Backport "HBASE-25482 Improve SimpleRegionNormalizer#getAverageRegionSizeMb (#2858)" to branch-2.4

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/common/TaskMonitorTmpl.jamon

Should add duration to Completion Time. Make it more readable

HBASE-25550 More readable Competition Time

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ColumnFamilyDescriptorBuilder.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestColumnFamilyDescriptorBuilder.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableDescriptorBuilder.java
hbase-shell/src/main/ruby/hbase/admin.rb

HBASE-25439 added a new unit in PrettyPrint.Unit, the BLOCKSIZE in CF should also support this feature.

HBASE-25519 BLOCKSIZE needs to support pretty print

---

hbase-shell/src/main/ruby/hbase/admin.rb

Eliminate the null value problem of SPLITS_FILE

HBASE-25609 Eliminate the null value problem of SPLITS_FILE

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/janitor/CatalogJanitor.java

This PR fixes the issue mentioned [here](https://issues.apache.org/jira/browse/HBASE-25646).

HBASE-25646 Possible Resource Leak in CatalogJanitor

---

src/main/asciidoc/_chapters/security.adoc

Fix format error in security.adoc

HBASE-25654 [Documentation] Fix format error in security.adoc

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/RoundRobinTableInputFormat.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableMapReduceUtil.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableSplit.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestRoundRobinTableInputFormat.java

Co-authored-by: Huaxiang Sun <huaxiangsun@apache.com>

HBASE-25566 RoundRobinTableInputFormat

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Result.java
hbase-common/src/main/java/org/apache/hadoop/hbase/CellUtil.java
hbase-common/src/main/java/org/apache/hadoop/hbase/PrivateCellUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestResult.java

https://issues.apache.org/jira/browse/HBASE-25622

HBASE-25622 Result#compareResults should compare tags.

---

hbase-client/src/main/java/org/apache/hadoop/hbase/security/provider/GssSaslClientAuthenticationProvider.java
hbase-common/src/main/java/org/apache/hadoop/hbase/security/SecurityConstants.java
hbase-common/src/main/resources/hbase-default.xml
hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestSecureIPC.java

https://issues.apache.org/jira/browse/HBASE-25665

HBASE-25665 Option to use hostname instead of canonical hostname for secure HBase cluster connection

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestHFileOutputFormat2.java

https://issues.apache.org/jira/browse/HBASE-25608

HBASE-25608 Support HFileOutputFormat locality sensitive even destination cluster is different from source cluster

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestHFileOutputFormat2.java

https://issues.apache.org/jira/browse/HBASE-25671
https://issues.apache.org/jira/browse/HBASE-25608
Backport https://github.com/apache/hbase/pull/2988 to branch-2

HBASE-25671 Backport HBASE-25608 to branch-2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBatchRpcRetryingCaller.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncProcess.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableNoncedRetry.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestHTableNoncedRetry.java

HBASE-25678 Support nonce operations for Increment/Append in RowMutations and CheckAndMutate

---

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestActiveMasterManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestHFileCleaner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestHFileLinkCleaner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestLogsCleaner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestReplicationHFileCleaner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/procedure2/store/region/RegionProcedureStorePerformanceEvaluation.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSplitLogWorker.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestWALLockup.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationTrackerZKImpl.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/MockServer.java

Many UTs implementd its own `DummyServer` by `implements Server`, most of the methods of `Server` are useless to them. So I want to simplify these UTs in this PR.

HBASE-25683 Simplify UTs using DummyServer

---

hbase-http/src/main/java/org/apache/hadoop/hbase/http/ProfileServlet.java

Suggestion for 2.3 and 2.4.... just make it so can pass 'output=HTML'.

HBASE-25685 asyncprofiler2.0 no longer supports svg; wants html

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java

The branch-1 backport of [HBASE-25677](https://issues.apache.org/jira/browse/HBASE-25677?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)

HBASE-25677 Server+table counters on each scan #nextRaw invocation becomes a bottleneck when heavy load

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java

Please see some analysis in 
https://issues.apache.org/jira/browse/HBASE-25691?filter=-1

HBASE-25691 Test failure: TestVerifyBucketCacheFile.testRetrieveFromFile

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestClientNoCluster.java
hbase-common/src/main/java/org/apache/hadoop/hbase/ServerName.java
hbase-common/src/test/java/org/apache/hadoop/hbase/TestServerName.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodeAssignmentHelper.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodesManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/StartcodeAgnosticServerName.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/AssignmentVerificationReport.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionPlacementMaintainer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/HBaseFsck.java
hbase-server/src/test/java/org/apache/hadoop/hbase/MetaMockingUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessorNoCluster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestConnectionImplementation.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestShortCircuitConnection.java
hbase-server/src/test/java/org/apache/hadoop/hbase/favored/TestFavoredNodeAssignmentHelper.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionPlacement.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestFavoredStochasticBalancerPickers.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureTestingUtility.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerAbort.java

HBASE-24514 Backport HBASE-24305 to branch-2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestClientNoCluster.java
hbase-common/src/main/java/org/apache/hadoop/hbase/ServerName.java
hbase-common/src/test/java/org/apache/hadoop/hbase/TestServerName.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodeAssignmentHelper.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodesManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/StartcodeAgnosticServerName.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/AssignmentVerificationReport.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionPlacementMaintainer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/HBaseFsck.java
hbase-server/src/test/java/org/apache/hadoop/hbase/MetaMockingUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessorNoCluster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestConnectionImplementation.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestShortCircuitConnection.java
hbase-server/src/test/java/org/apache/hadoop/hbase/favored/TestFavoredNodeAssignmentHelper.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionPlacement.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestFavoredStochasticBalancerPickers.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureTestingUtility.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerAbort.java

HBASE-25737 Backport HBASE-24305 to branch-2.3

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestClientNoCluster.java
hbase-common/src/main/java/org/apache/hadoop/hbase/ServerName.java
hbase-common/src/test/java/org/apache/hadoop/hbase/TestServerName.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodeAssignmentHelper.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodesManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/StartcodeAgnosticServerName.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/AssignmentVerificationReport.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionPlacementMaintainer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/HBaseFsck.java
hbase-server/src/test/java/org/apache/hadoop/hbase/MetaMockingUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessorNoCluster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestConnectionImplementation.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestShortCircuitConnection.java
hbase-server/src/test/java/org/apache/hadoop/hbase/favored/TestFavoredNodeAssignmentHelper.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionPlacement.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestFavoredStochasticBalancerPickers.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureTestingUtility.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerAbort.java

HBASE-25738 Backport HBASE-24305 to branch-2.2

---

pom.xml

Exlude tomcat-embed-core transitive dependency
Remove outdated exclude rule for slf4j

HBASE-25755 Exclude tomcat-embed-core from libthrift

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java

Backport "HBASE-25482 Improve SimpleRegionNormalizer#getAverageRegionSizeMb (#2858)" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java

Backport "HBASE-25482 Improve SimpleRegionNormalizer#getAverageRegionSizeMb (#2858)" to branch-2.3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java

Signed-off-by: stack <stack@duboce.net>
Reviewed-by: Viraj Jasani <vjasani@apache.org>

Backport "HBASE-25653 Add units and round off region size to 2 digits after decimal (#3046)" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java

Signed-off-by: stack <stack@duboce.net>
Reviewed-by: Viraj Jasani <vjasani@apache.org>

Backport "HBASE-25653 Add units and round off region size to 2 digits after decimal (#3046)" to branch-2.4

---

hbase-http/pom.xml
hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java
hbase-http/src/test/java/org/apache/hadoop/hbase/http/TestHttpServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java

Backport "HBASE-25770 Http InfoServers should honor gzip encoding when requested (#3159)" to branch-2

---

hbase-http/pom.xml
hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java
hbase-http/src/test/java/org/apache/hadoop/hbase/http/TestHttpServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java

Backport "HBASE-25770 Http InfoServers should honor gzip encoding when requested (#3159)" to branch-2.3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java

Revert "HBASE-25739 TableSkewCostFunction need to use aggregated deviation"

---

src/site/xdoc/downloads.xml

Correct release date and add EOL notice

HBASE-25780 Add 2.2.7 to download page [addendum]

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/AssignRegionAction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalanceAction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CandidateGenerator.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/HeterogeneousRegionCountCostFunction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/LoadCandidateGenerator.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/LocalityBasedCandidateGenerator.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/MoveRegionAction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaCandidateGenerator.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/SimpleLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/SwapRegionsAction.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestFavoredStochasticBalancerPickers.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplica.java

Signed-off-by: Yulin Niu <niuyulin@apache.org>

HBASE-25793 Move BaseLoadBalancer.Cluster to a separated file (#3185)

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ColumnFamilyDescriptor.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ColumnFamilyDescriptorBuilder.java
hbase-server/src/main/java/org/apache/hadoop/hbase/mob/DefaultMobStoreCompactor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/AbstractMultiOutputCompactor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/Compactor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/DateTieredCompactor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/DefaultCompactor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/StripeCompactor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/TableDescriptorChecker.java
hbase-server/src/test/java/org/apache/hadoop/hbase/mob/FaultyMobStoreCompactor.java
hbase-shell/src/main/ruby/hbase/admin.rb

HBASE-25756 Support alternate compression for major and minor compactions

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterDumpServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/http/RSDumpServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/http/RSStatusServlet.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/http/TestRSStatusServlet.java

Backport "HBASE-25842 move regionserver http-related code into o.a.h.h.regionserver.http" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/MasterDumpServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/MasterRedirectServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/MasterStatusServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/MetaBrowser.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/RegionReplicaInfo.java
hbase-server/src/main/resources/hbase-webapps/master/table.jsp
hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestMasterStatusServlet.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestMetaBrowser.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestMetaBrowserNoCluster.java

Backport "HBASE-25843 move master http-related code into o.a.h.h.master.http" to branch-2

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupBasedLoadBalancer.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/master/balancer/RSGroupableBalancerTestBase.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/master/balancer/TestRSGroupBasedLoadBalancer.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/master/balancer/TestRSGroupBasedLoadBalancerWithStochasticLoadBalancerAsInternal.java
hbase-server/src/main/java/org/apache/hadoop/hbase/favored/FavoredNodeLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/LoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/LoadBalancerFactory.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/MaintenanceLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestSimpleLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java

Signed-off-by: Yulin Niu <niuyulin@apache.org>

HBASE-25851 Make LoadBalancer not extend Configurable interface (#3233)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/mob/DefaultMobStoreCompactor.java

Fix spotbugs warnings on branch-2. cc @Apache9

HBASE-25850 Fix spotbugs warnings on branch-2

---

src/main/asciidoc/_chapters/configuration.adoc

update reference guide for log4j2.xml

HBASE-25862 update reference guide for log4j2.xml

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManager.java

Co-authored-by: Mallikarjun <mallikvarjun@gmail.com>

HBASE-25870 Validate only direct ancestors instead of entire history for a particular backup

---

bin/hbase
bin/hbase_startup.jsh
conf/hbase-env.sh
src/main/asciidoc/_chapters/ops_mgt.adoc

Signed-off-by: Pankaj Kumar <pankajkumar@apache.org>

Backport "HBASE-25841 Add basic jshell support" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java

Backport "HBASE-25513 When the table is turned on normalize, the first region may not be merged even the size is 0" to branch-2

---

bin/hbase

Fixes issue where master fails to start.

HBASE-25841 Add basic jshell support (adendum)

---

hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftServer.java

Add doAs support for Thrift Server

HBASE-25930 Add doAs support for Thrift Server

---

pom.xml

Signed-off-by: Pankaj Kumar <pankajkumar@apache.org>
Signed-off-by: Xiaolin Ha

HBASE-25969 Purge netty-all transitive includes (#3353)

---

hbase-protocol/src/main/protobuf/MultiRowMutation.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MultiRowMutationEndpoint.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide5.java

HBASE-26002 MultiRowMutationEndpoint should return the result of the conditional update

---

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java
hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestPostIncrementAndAppendBeforeWAL.java

https://issues.apache.org/jira/browse/HBASE-26001

HBASE-26001 When turn on access control, the cell level TTL of Increment and Append operations is invalid

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java

https://issues.apache.org/jira/browse/HBASE-26013

HBASE-26013 Get operations readRows metrics becomes zero after HBASE-25677

---

hbase-resource-bundle/src/main/resources/META-INF/NOTICE.vm

Backport "HBASE-25966 Fix typo in NOTICE.vm" to branch-2

---

hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftHBaseServiceHandler.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/generated/IOError.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/ThriftHBaseServiceHandler.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/generated/TIOError.java
hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift/Hbase.thrift
hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift2/hbase.thrift

https://issues.apache.org/jira/browse/HBASE-26025

HBASE-26025 Add a flag to mark if the IOError can be solved by retry in thrift IOError

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupDriver.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRestoreConstants.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/RestoreDriver.java

Move the message to the tool command help.

HBASE-23817 The message "Please make sure that backup is enabled on the cluster." is shown even when the backup feature is enabled

---

hbase-client/src/main/java/org/apache/hadoop/hbase/PleaseRestartMasterException.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSTableDescriptors.java

HBASE-25902 Add missing CFs in meta during HBase 1 to 2 Upgrade

---

hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/ThriftHBaseServiceHandler.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/ThriftUtilities.java

https://issues.apache.org/jira/browse/HBASE-26033

HBASE-26033 complement the admin operations in thrift2 after HBASE-21674

---

hbase-server/src/test/java/org/apache/hadoop/hbase/http/log/TestLogLevel.java

HBASE-26074: Fix testLogLevelByHttps/testLogLevelByHttpsWithSpnego

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerCall.java
hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestFSHLogCorruptionWithMultiPutDueToDanglingByteBuffer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/wal/WALCorruptionWithMultiPutDueToDanglingByteBufferTestBase.java

Creating patch for branch-2, HBASE-24984

HBASE-24984 WAL corruption due to early DBBs re-use when Durability.ASYNC_WAL is used with multi operation	

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CombinedBlockCache.java

https://issues.apache.org/jira/browse/HBASE-26105

HBASE-26105 Rectify the expired TODO comment in CombinedBC.

---

hbase-http/src/main/java/org/apache/hadoop/hbase/http/log/LogLevel.java
hbase-http/src/test/java/org/apache/hadoop/hbase/http/log/TestLogLevel.java

Backports https://github.com/apache/hbase/pull/3549 to branch-2

HBASE-26160: Configurable disallowlist for live editing of loglevels

---

dev-support/hbase-personality.sh

This is a rework of the original commit to enable
Hadoop 3 profile for the HBASE-25853 branch.

HBASE-26176 Correct regex in hbase-personality.sh

---

hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncFSWALDurability.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLogDurability.java
hbase-server/src/test/java/org/apache/hadoop/hbase/wal/FaultyFSLog.java

8/17 commits of HBASE-22120, original commit 2be2c63f0d3917a243b74af9754cbfc805b858d1

HBASE-26131 Backport HBASE-25484 "Add trace support for WAL sync" to branch-2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java
hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/AbstractTestIPC.java

9/17 commits of HBASE-22120, original commit bb8c4967f8ce2c89ebaf1ddc5d8a1bf55f1e20d3

HBASE-26132 Backport HBASE-25535 "Set span kind to CLIENT in AbstractRpcClient" to branch-2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRegionLocator.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionFactory.java

11/17 commits of HBASE-22120, original commit 8d68f8cd1c8613be1b499eaa99f46806b2743294

HBASE-26134 Backport HBASE-25617 "Revisit the span names" to branch-2

---

hbase-server/pom.xml
hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/compactionserver/CSStatusTmpl.jamon
hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/compactionserver/CompactionTasksTmpl.jamon
hbase-server/src/main/java/org/apache/hadoop/hbase/AbstractServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/compactionserver/CSDumpServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/compactionserver/CSStatusServlet.java
hbase-server/src/main/java/org/apache/hadoop/hbase/compactionserver/CompactionTask.java
hbase-server/src/main/java/org/apache/hadoop/hbase/compactionserver/CompactionThreadManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/compactionserver/HCompactionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/main/resources/hbase-webapps/compactionserver/compactionserver.jsp
hbase-server/src/main/resources/hbase-webapps/compactionserver/footer.jsp
hbase-server/src/main/resources/hbase-webapps/compactionserver/header.jsp
hbase-server/src/main/resources/hbase-webapps/compactionserver/index.html

The web UI of compaction server:

HBASE-26044 Add CompactionServer Web UI

---

hbase-balancer/pom.xml
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaGroupingCostFunction.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaHostCostFunction.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaRackCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaRackCostFunction.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaWithRacks.java
hbase-shaded/pom.xml

https://issues.apache.org/jira/browse/HBASE-26178
New patch using Agrona for primitive collections.
Design and Performance evaluation is at https://docs.google.com/document/d/1ovpAdKBEDMCWCMhhqN5MJAV_Urzv-UGhIDRu7scSNR0

HBASE-26178 Improve data structure and algorithm for BalanceClusterState to improve computation speed for large cluster

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Result.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/replication/VerifyReplication.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestResult.java

https://issues.apache.org/jira/browse/HBASE-26238

HBASE-26238 Short message by Result#compareResults for VerifyReplication to avoid OOME

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java

https://issues.apache.org/jira/browse/HBASE-26305

HBASE-26305 Move NavigableSet add operation to writer thread in BucketCache

---

hbase-common/src/main/java/org/apache/hadoop/hbase/CellUtil.java

This is only applicable to all active branch-2 branches.

HBASE-26404 Update javadoc for CellUtil#createCell with tags methods.

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/DoubleArrayCost.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBaseLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestDoubleArrayCost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticBalancerJmxMetrics.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerBalanceCluster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaSameHosts.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaWithRacks.java

HBASE-26311 Balancer gets stuck in cohosted replica distribution

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFunction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/LocalityBasedCostFunction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionCountSkewCostFunction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaGroupingCostFunction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerBalanceCluster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerLargeCluster.java

HBASE-26337 Optimization for weighted random generators

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java

https://issues.apache.org/jira/browse/HBASE-26325

HBASE-26325 Backport the HBASE-26305 to branch-1. Move NavigableSet add operation to writer thread in BucketCache

---

hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtil.java

https://issues.apache.org/jira/browse/HBASE-26477

HBASE-26477 Fix MiniMapReduceCluster failure under Java17

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRegionLocator.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncConnectionTracing.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionLocatorTracing.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTracingBase.java
hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/CallRunner.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/AbstractTestIPC.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionTracing.java

Signed-off-by: Tak Lon (Stephen) Wu <taklwu@apache.org>

Backport "HBASE-26471 Move tracing semantic attributes to their own class" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessChecker.java

JIRA: https://issues.apache.org/jira/browse/HBASE-26517

HBASE-26517 Add auth method information to AccessChecker audit log

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/Encryption.java
hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/TestEncryption.java

https://issues.apache.org/jira/browse/HBASE-26613

HBASE-26613 The logic of the method incrementIV in Encryption class has problem

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/Encryption.java
hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/TestEncryption.java

https://issues.apache.org/jira/browse/HBASE-26619

HBASE-26619 Backport HBASE-26613 to branch-1

---

hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/ThriftHBaseServiceHandler.java
hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThriftHBaseServiceHandler.java

https://issues.apache.org/jira/browse/HBASE-26629

HBASE-26629 Add expiration for long time vacant scanners in Thrift2

---

pom.xml

HBASE-26631 Upgrade junit to 4.13.2

HBASE-26631 Upgrade junit to 4.13.2

---

src/main/asciidoc/_chapters/community.adoc
src/main/asciidoc/_chapters/configuration.adoc
src/main/asciidoc/_chapters/developer.adoc
src/main/asciidoc/_chapters/upgrading.adoc

Amending-Author: Duo Zhang <zhangduo@apache.org>

HBASE-26006 Update ref guide about the 2.4.x release line

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathBalancedQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRWQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRpcHandler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RWQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcHandler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcScheduler.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSimpleRpcScheduler.java

https://issues.apache.org/jira/browse/HBASE-26551

Backport HBASE-26551 Add FastPath feature to HBase RWQueueRpcExecutor to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathBalancedQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRWQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRpcHandler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RWQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcHandler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcScheduler.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSimpleRpcScheduler.java

https://issues.apache.org/jira/browse/HBASE-26551

Backport HBASE-26551 Add FastPath feature to HBase RWQueueRpcExecutor

---

hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java
hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplit.java

https://issues.apache.org/jira/browse/HBASE-26678

Backport HBASE-26579 Set storage policy of recovered edits when wal storage type is configured

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AbstractRpcBasedConnectionRegistry.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRpcBasedRegistryHedgedReads.java

Addressing additional comments raised in branch-2 backport PR #4014

HBASE-26474 Implement connection-level attributes (addendum)

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AbstractRpcBasedConnectionRegistry.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRpcBasedRegistryHedgedReads.java

Addressing additional comments raised in branch-2 backport PR #4014

Backport "HBASE-26474 Implement connection-level attributes (addendum)" to branch-2.5

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Result.java

https://issues.apache.org/jira/browse/HBASE-26688

HBASE-26688 Threads shared EMPTY_RESULT may lead to unexpected client job down.

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestHTableTracing.java

Ensure table data operations emit one and only one span.
This issue applies primarily to branch-2, where I found the bug. There will be a "backport" to master that updates `TestAsyncTableTracing` test.

HBASE-26472 Adhere to semantic conventions regarding table data operations (addendum)

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/ConnectionSpanBuilder.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/IpcClientSpanBuilder.java
hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java
hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
hbase-server/pom.xml
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/CallRunner.java
hbase-server/src/main/java/org/apache/hadoop/hbase/server/trace/IpcServerSpanBuilder.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/AbstractTestIPC.java
pom.xml

Backport "HBASE-26521 Name RPC spans as `$package.$service/$method` (#4024)" to branch-2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Result.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestResult.java

https://issues.apache.org/jira/browse/HBASE-26688

HBASE-26688 Threads shared EMPTY_RESULT may lead to unexpected client job down

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableResultScanner.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java

Backport "HBASE-26765 Minor refactor of async scanning code (#4121)" to branch-2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableResultScanner.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java

Backport "HBASE-26765 Minor refactor of async scanning code (#4121)" to branch-2.5

---

hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/ProtobufDecoder.java
hbase-common/src/main/java/org/apache/hadoop/hbase/KeyValue.java
hbase-endpoint/src/main/java/org/apache/hadoop/hbase/coprocessor/AggregateImplementation.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java
hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/TokenProvider.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestPutDeleteEtcCellIteration.java
hbase-server/src/test/java/org/apache/hadoop/hbase/codec/CodecPerformance.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftHBaseServiceHandler.java
pom.xml

Author:    Mike Drob <mdrob@apache.org>
Co-authored-by: Nick Dimiduk <ndimiduk@apache.org>

Backport "HBASE-26622 Update error-prone to 2.10" to branch-2.5

---

dev-support/Jenkinsfile_GitHub

Backport "HBASE-26788 Disable Checks API callback from test results in PRs" to branch-2.5

---

dev-support/Jenkinsfile_GitHub

Backport "HBASE-26788 Disable Checks API callback from test results in PRs" to branch-2.4

---

dev-support/Jenkinsfile_GitHub

Backport "HBASE-26788 Disable Checks API callback from test results in PRs" to branch-1

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/BalancedQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathBalancedQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FastPathRWQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RWQueueRpcExecutor.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java

Backport "HBASE-26782 Minor code cleanup in and around RpcExecutor" to branch-2.5

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java

Backport "HBASE-26817 Mark RpcExecutor as IA.LimitedPrivate COPROC and PHOENIX" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java

Backport "HBASE-26817 Mark RpcExecutor as IA.LimitedPrivate COPROC and PHOENIX" to branch-2.5

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcExecutor.java

Backport "HBASE-26817 Mark RpcExecutor as IA.LimitedPrivate COPROC and PHOENIX" to branch-2.4

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FifoRpcScheduler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/MasterFifoRpcScheduler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcScheduler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcScheduler.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncClientPauseForCallQueueTooBig.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/DelegatingRpcScheduler.java

Backport "HBASE-26819 Minor code cleanup in and around RpcScheduler" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/FifoRpcScheduler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/MasterFifoRpcScheduler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcScheduler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcScheduler.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableAccessor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncClientPauseForCallQueueTooBig.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/DelegatingRpcScheduler.java

Backport "HBASE-26819 Minor code cleanup in and around RpcScheduler" to branch-2.5

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionCoprocessorRpcChannelImpl.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableOverAsyncTable.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/StringTraceRenderer.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java
hbase-endpoint/pom.xml
hbase-endpoint/src/test/java/org/apache/hadoop/hbase/coprocessor/TestCoprocessorEndpointTracing.java
hbase-server/src/test/java/org/apache/hadoop/hbase/trace/OpenTelemetryClassRule.java
hbase-server/src/test/java/org/apache/hadoop/hbase/trace/OpenTelemetryTestRule.java

Trace table ExecService invocations as table operations. Ensure span relationships for both table
and master invocations.

HBASE-26531 Trace coprocessor exec endpoints

---

hbase-rest/pom.xml

HBASE-26855 Delete unnecessary dependency on jaxb-runtime jar

---

hbase-rest/pom.xml

Backport "HBASE-26855 Delete unnecessary dependency on jaxb-runtime jar" to branch-2

---

hbase-rest/pom.xml

Backport "HBASE-26855 Delete unnecessary dependency on jaxb-runtime jar" to branch-2.5

---

hbase-it/src/test/java/org/apache/hadoop/hbase/TestShellExecEndpointCoprocessor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ConnectionRule.java
hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestApiV1ClusterMetricsResource.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestMetaBrowser.java

Backport "HBASE-26834 Adapt ConnectionRule for both sync and async connections" to branch-2.5

---

hbase-it/src/test/java/org/apache/hadoop/hbase/TestShellExecEndpointCoprocessor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/ConnectionRule.java
hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/webapp/TestMetaBrowser.java

Backport "HBASE-26834 Adapt ConnectionRule for both sync and async connections" to branch-2.4

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/ConstantSizeRegionSplitPolicy.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSource.java

Fix log parameter error and spelling error

HBASE-26924 [Documentation] Fix log parameter error and spelling error

---

pom.xml

Backport "HBASE-26906 Remove duplicate dependency declaration" to branch-2.5

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java

HBase JIRA: [HBASE-26980](https://issues.apache.org/jira/browse/HBASE-26980)

HBASE-26980 Update javadoc of BucketCache.java

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/ConnectionSpanBuilder.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableSpanBuilder.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionLocatorTracing.java
hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncMetaRegionLocator.java

Converts the region locator spans to INTERNAL spans and verifies their presence in test.

HBASE-26648 Improve fidelity of RegionLocator spans

---

hbase-server/src/test/java/org/apache/hadoop/hbase/TestCustomPriorityRpcControllerFactory.java

Simple test to give users peace of mind about the ability for their custom RpcControllerFactory to affect priorities.

HBASE-26886 Add unit test for custom RpcControllerFactory ability to overwrite priorities

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/ConnectionSpanBuilder.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableSpanBuilder.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionLocatorTracing.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRegionLocatorTracing.java
hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncMetaRegionLocator.java

Backport "HBASE-26648 Improve fidelity of RegionLocator spans" to branch-2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/ConnectionSpanBuilder.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/trace/TableSpanBuilder.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionLocatorTracing.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRegionLocatorTracing.java
hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncMetaRegionLocator.java

Backport "HBASE-26648 Improve fidelity of RegionLocator spans" to branch-2.5

---

hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionProcessRowsWithLocks.java

More details please refer to JIRA description: https://issues.apache.org/jira/browse/HBASE-26998

HBASE-26998 TestRegionProcessRowsWithLocks#testProcessExceptionAndRollBack is broken in branch-1

---

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterSource.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterSourceImpl.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterMetricsWrapper.java

JIRA: HBASE-27032.
The draining region servers metric description is incorrect.
Fixed the description and added unit test.

HBASE-27032 The draining region servers metric description is incorrect

---

hbase-server/src/main/java/org/apache/hadoop/hbase/procedure/ZKProcedureUtil.java

https://issues.apache.org/jira/browse/HBASE-27040

HBASE-27040 Optimize the log display of the ZKProcedureUtil.java

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/BufferedDataBlockEncoder.java

Revert "HBASE-26856:BufferedDataBlockEncoder.OnheapDecodedCell value can get corrupted"

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/BufferedDataBlockEncoder.java

…can get corrupted (#4394)"
This reverts commit de9a17e75cc80e7a473f1a4269092a557b1105a0.

Revert "HBASE-26856:BufferedDataBlockEncoder.OnheapDecodedCell value … from branch-2

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/BufferedDataBlockEncoder.java

…can get corrupted (#4394)"
This reverts commit 04956ffe7e35c12b9f6b905692e154a436d56639.

Revert "HBASE-26856:BufferedDataBlockEncoder.OnheapDecodedCell value … branch-2.5

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/BufferedDataBlockEncoder.java

…can get corrupted (#4394)"
This reverts commit 454206b5926dbe6d6231236597b7004fec814f9d.

Revert "HBASE-26856:BufferedDataBlockEncoder.OnheapDecodedCell value … branch-2.4

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotFileCache.java

More details and improve result is at https://issues.apache.org/jira/browse/HBASE-27043

HBASE-27043 Let lock wait timeout to improve performance of SnapshotHFileCleaner

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMaster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerNoMaster.java

https://issues.apache.org/jira/browse/HBASE-26977

HBASE-26977 HMaster's ShutdownHook does not take effect, if tablesOnMaster is false

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/CleanerChore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/DirScanPool.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/HFileCleaner.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/LogCleaner.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterChoreScheduled.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestCleanerClearHFiles.java

Backport to branch-2, HBASE-26342 Support custom paths of independent configuration and pool for hfile cleaner (#4403)

---

hbase-client/src/main/java/org/apache/hadoop/hbase/ClusterMetrics.java
hbase-client/src/main/java/org/apache/hadoop/hbase/ClusterMetricsBuilder.java
hbase-protocol-shaded/src/main/protobuf/server/ClusterStatus.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestClientClusterMetrics.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionsRecoveryChore.java
hbase-shell/src/main/ruby/hbase/admin.rb

JIRA: HBASE-27036.
Displays the number of decommissioned region server for status command.

HBASE-27036 Displays the number of decommissioned region server for status command

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionVisualizerTmpl.jamon

Revert the previous change and replace it with something simpler and entirely client-side.

HBASE-27066 The Region Visualizer display failed

---

hbase-common/src/main/java/org/apache/hadoop/hbase/nio/MultiByteBuff.java

Applied https://issues.apache.org/jira/secure/attachment/13044874/MultiByteBuff.patch from Lijin Bin on JIRA.

HBASE-27097 SimpleRpcServer is broken

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ShortCircuitMasterConnection.java
hbase-protocol-shaded/src/main/protobuf/Master.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegionFlusherAndCompactor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestMasterObserver.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
hbase-shell/src/main/ruby/hbase/admin.rb
hbase-shell/src/main/ruby/shell.rb
hbase-shell/src/main/ruby/shell/commands/flush_master_store.rb
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java

https://issues.apache.org/jira/browse/HBASE-27028

HBASE-27028 Add a shell command for flushing master local region

---

hbase-server/src/main/java/org/apache/hadoop/hbase/protobuf/ReplicationProtobufUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HBaseInterClusterReplicationEndpoint.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/SyncReplicationTestBase.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEndpoint.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicator.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestSerialReplicationEndpoint.java

Revert "HBASE-27062 ThreadPool is unnecessary in HBaseInterClusterReplication…"

---

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HBaseInterClusterReplicationEndpoint.java

Raising PR for branch-2, master branch changes can't be cheryy-picked cleanly.

HBASE-27105 HBaseInterClusterReplicationEndpoint should honor replication adaptive timeout

---

bin/graceful_stop.sh

https://issues.apache.org/jira/browse/HBASE-27275

HBASE-27275 graceful_stop.sh unable to restore the balance state

---

hbase-client/src/main/java/org/apache/hadoop/hbase/ClusterMetrics.java
hbase-client/src/main/java/org/apache/hadoop/hbase/ClusterMetricsBuilder.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
hbase-protocol-shaded/src/main/protobuf/server/ClusterStatus.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestClientClusterMetrics.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRegionsRecoveryChore.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestUnknownServers.java
hbase-shell/src/main/ruby/hbase/admin.rb
hbase-shell/src/main/ruby/shell.rb
hbase-shell/src/main/ruby/shell/commands/list_unknownservers.rb

https://issues.apache.org/jira/browse/HBASE-27104

HBASE-27104 Add a tool command list_unknownservers

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionVisualizerTmpl.jamon

https://issues.apache.org/jira/browse/HBASE-27336

HBASE-27336 The region visualizer shows 'undefined' region server

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/CompactSplit.java

Backport 'HBASE-27152 Under compaction mark may leak (#4725)'  to branch-2

---

src/site/site.xml

Companion PR to apache/hbase-site#8.

HBASE-27351 Add 2.5 Documentation to the website

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/RegionMover.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterUseIp.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerUseIp.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestRegionMoverUseIp.java

https://issues.apache.org/jira/browse/HBASE-27304

HBASE-27304 Support using IP to expose master/rs servers for some special scenarios

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ShortCircuitMasterConnection.java
hbase-protocol-shaded/src/main/protobuf/Master.proto
hbase-protocol-shaded/src/main/protobuf/Replication.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/replication/ReplicationPeerManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSmallTests.java
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java

https://issues.apache.org/jira/browse/HBASE-27448

HBASE-27448 Add an admin method to get replication enabled state

---

hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java

https://issues.apache.org/jira/browse/HBASE-27379

HBASE-27379 fix numOpenConnections metric is one less than the actual

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java

Backport "HBASE-27563 ChaosMonkey sometimes generates invalid boundaries for random item selection" to branch-2

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java

Backport "HBASE-27563 ChaosMonkey sometimes generates invalid boundaries for random item selection" to branch-2.5

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java

Revert "Backport "HBASE-27563 ChaosMonkey sometimes generates invalid boundaries for random item selection" to branch-2.4"

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java

Backport "HBASE-27563 ChaosMonkey sometimes generates invalid boundaries for random item selection" to branch-2.4

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DumpHdfsClusterStatusAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/HdfsActionUtils.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActiveNameNodeAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartRandomDataNodeAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerAndDependenciesKillingMonkeyFactory.java

Backport "HBASE-27567 Introduce ChaosMonkey Action to print HDFS Cluster status" to branch-2

---

hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DumpHdfsClusterStatusAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/HdfsActionUtils.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActiveNameNodeAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartRandomDataNodeAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerAndDependenciesKillingMonkeyFactory.java

Backport "HBASE-27567 Introduce ChaosMonkey Action to print HDFS Cluster status" to branch-2.5

---

hbase-it/src/test/java/org/apache/hadoop/hbase/ClusterManager.java
hbase-it/src/test/java/org/apache/hadoop/hbase/DistributedHBaseCluster.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/Action.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActionBaseAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartRandomJournalNodeAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerAndDependenciesKillingMonkeyFactory.java
hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseCluster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/MiniHBaseCluster.java

Backport "HBASE-27568 ChaosMonkey add support for JournalNodes" to branch-2

---

hbase-it/src/test/java/org/apache/hadoop/hbase/ClusterManager.java
hbase-it/src/test/java/org/apache/hadoop/hbase/DistributedHBaseCluster.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/Action.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActionBaseAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartRandomJournalNodeAction.java
hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerAndDependenciesKillingMonkeyFactory.java
hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseCluster.java
hbase-server/src/test/java/org/apache/hadoop/hbase/MiniHBaseCluster.java

Backport "HBASE-27568 ChaosMonkey add support for JournalNodes" to branch-2.5

---

hbase-protocol-shaded/pom.xml
hbase-shaded/pom.xml

Revert "Backport HBASE-27557 to branch-2"

---

hbase-protocol-shaded/pom.xml
hbase-shaded/pom.xml

Revert "Backport HBASE-27557 to branch-2.5"

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java

The "CREATE_TIME_TS" value of the hfile generated by the HFileOutputFormat2 class is 0

HBASE-27636 The "CREATE_TIME_TS" value of the hfile generated by the HFileOutputFormat2 class is 0

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileContextBuilder.java
hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java

Revert "HBASE-29654 IndexBlockEncoding is missing in HFileContextBuilder copy…"

---

hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionServerListTmpl.jamon

Backport HBASE-27615 to branch-2.

HBASE-27615 Add group of regionServer on Master webUI

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/throttle/PressureAwareCompactionThroughputController.java

HBASE-27807 PressureAwareCompactionThroughputController#tune log the opposite of the actual scenario
Correct the condition of the if statement

HBASE-27807 PressureAwareCompactionThroughputController#tune log the opposite of the actual scenario

---

hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFuzzyRowFilterEndToEndLarge.java

From 50^3 to 30^3, 125000 -> 27000

HBASE-27864 Reduce the Cardinality for TestFuzzyRowFilterEndToEndLarge

---

pom.xml

See: [HBASE-27634](https://issues.apache.org/jira/browse/HBASE-27634)

HBASE-27634: Builds emit errors related to SBOM parsing

---

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java

HBASE-27899 Beautify the output information of the getStats method in ReplicationSource

HBASE-27899 Beautify the output information of the getStats method in ReplicationSource

---

hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReader.java
hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java
hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestMetaRegionReplicaReplicationEndpoint.java

The base code for the original change is quite different between branch-2 and branch-2.5, mostly due to HBASE-27321, so cherry-picking the original branch-2 PR didn't work.

HBASE-27871 Meta replication stuck forever if wal it's still reading gets rolled and deleted

---

hbase-server/src/main/java/org/apache/hadoop/hbase/procedure2/store/region/RegionProcedureStore.java

HBASE-28051 The javadoc about RegionProcedureStore.delete is incorrect

---

src/main/asciidoc/_chapters/zookeeper.adoc

HBASE-28063. Added docs for ZooKeeper TLS connection

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java

the source of OLDEST_TIMESTAMP is different in the master branch and that has been missed during the rebase.

 HBASE-28055 Addendum. Fixing the compilation failure

---

hbase-common/src/main/resources/hbase-default.xml
hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java

Authored-by: Rahul Kumar <rahul.kumar@rahulku-ltmdgmc.internal.salesforce.com>

Backport "HBASE-28068 Add hbase.normalizer.merge.merge_request_max_number_of_regions property … (#5403)" to branch-3

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
hbase-client/src/main/java/org/apache/hadoop/hbase/client/ShortCircuitMasterConnection.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
hbase-protocol-shaded/src/main/protobuf/Master.proto
hbase-protocol-shaded/src/main/protobuf/MasterProcedure.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/AbstractStateMachineRegionProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableProcedureInterface.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableQueue.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TruncateRegionProcedure.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAdmin1.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionAdminApi2.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestTruncateRegionProcedure.java
hbase-shell/src/main/ruby/hbase/admin.rb
hbase-shell/src/main/ruby/shell.rb
hbase-shell/src/main/ruby/shell/commands/truncate_region.rb
hbase-shell/src/test/ruby/hbase/admin_test.rb
hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java

Cherry-picked commit from master and fixed merge conflicts.

HBASE-28064:Implement truncate_region command

---

hbase-server/src/main/resources/hbase-webapps/master/table.jsp

master branch PR : #5508 
branch-2 PR  #5510 
branch-2.5 PR  #5512

HBASE-28191 Meta browser can happen NPE when the server or target server of region is null

---

bin/hbase

Singed-off-by: Nick Dimiduk <ndimiduk@apache.org>
(cherry picked from commit 82e47cde27c1db91a685cff38c44a5572194f988)

HBASE-25058 Export necessary modules when running under JDK11 (#4337)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestLogRolling.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncLogRolling.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLog.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestLogRolling.java

Detail: HBASE-28190 and backport for branch-2.

HBASE-28190 Add slow sync log rolling test in TestAsyncLogRolling.

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegistryEndpointsRefresher.java
hbase-client/src/main/java/org/apache/hadoop/hbase/security/SecurityInfo.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/security/HBasePolicyProvider.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestBootstrapNodeUpdate.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestSecurityInfoAndHBasePolicyProviderMatch.java

Signed-off-by: Bryan Beaudreault <bbeaudreault@apache.org>
(cherry picked from commit c001ed3ba3c25a0d1a684c393092756b7ad9ee25)

HBASE-28316 Add BootstrapNodeService handlers (#5637)

---

dev-support/Jenkinsfile

Use downloads.a.o instead of a.o/dist

HBASE-28326 All nightly jobs are failing

---

hbase-client/src/main/java/org/apache/hadoop/hbase/Abortable.java
hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java
hbase-examples/src/main/java/org/apache/hadoop/hbase/coprocessor/example/ZooKeeperScanPolicyObserver.java
hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/AbstractProcedureScheduler.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/replication/AbstractPeerProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/AbstractMemStore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/AbstractMultiFileWriter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractProtobufWALReader.java

Change Logs
Modify some spelling errors or non-standard spelling comments pointed out by Typo
Impact
Theoretically no impact
Risk level (write none, low medium or high below)
none

HBASE-28255 Correcting spelling errors or annotations with non-standard spelling

---

.asf.yaml

Revert "HBASE-28325 Enable infra automation to comment on a Jira when a new PR is posted"

---

hbase-common/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKConfig.java
hbase-common/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKConfig.java

HBASE-28340 Add trust/key store type to ZK TLS settings handled by HBase (branch-2.4)

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/DecommissionedHostRejectedException.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerReportForDuty.java

Signed-off by: Nick Dimiduk <ndimiduk@apache.org>

Backport "HBASE-28342 Decommissioned hosts should be rejected by the HMaster (#5681)" to branch-3

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/DecommissionedHostRejectedException.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerReportForDuty.java

Signed-off by: Nick Dimiduk <ndimiduk@apache.org>

Backport "HBASE-28342 Decommissioned hosts should be rejected by the HMaster (#5681)" to branch-2.6

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/RegionSizeCalculator.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestRegionSizeCalculator.java

When a region is in transition, it may briefly have a null ServerName in meta. The RegionSizeCalculator calls RegionLocator.getAllRegionLocations() and does not handle the possibility that a RegionLocation.getServerName() could be null. The ServerName is eventually passed into an Admin call, which results in an NPE.
This has come up in other contexts. For example, taking a look at getAllRegionLocations() impl, we have checks to ensure that we don't call null server names. We need to similarly handle the possibility of nulls in RegionSizeCalculator.

Backport "HBASE-28354 RegionSizeCalculator throws NPE when regions are in transition (#5699)" to branch-2

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/RegionSizeCalculator.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestRegionSizeCalculator.java

When a region is in transition, it may briefly have a null ServerName in meta. The RegionSizeCalculator calls RegionLocator.getAllRegionLocations() and does not handle the possibility that a RegionLocation.getServerName() could be null. The ServerName is eventually passed into an Admin call, which results in an NPE.
This has come up in other contexts. For example, taking a look at getAllRegionLocations() impl, we have checks to ensure that we don't call null server names. We need to similarly handle the possibility of nulls in RegionSizeCalculator.

Backport "HBASE-28354 RegionSizeCalculator throws NPE when regions are in transition (#5699)" to branch-2.6

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java

HBASE-28424 Set correct Result to RegionActionResult for successful Put/Delete mutations

---

hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/AsyncFSOutputHelper.java
hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputHelper.java
hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestFanOutOneBlockAsyncDFSOutput.java
hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestFanOutOneBlockAsyncDFSOutputHang.java
hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestLocalAsyncOutput.java
hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestSaslFanOutOneBlockAsyncDFSOutput.java
hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractProtobufLogWriter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncProtobufLogWriter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogWriter.java

Contributed-by: Charles Connell <charles@connells.org>
FYI @charlesconnell, I had to fix some merge conflicts here so doing it as a PR to let the whole test suite run

HBASE-28260: Add NO_WRITE_LOCAL flag to WAL file creation

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/MutableRegionInfo.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CreateTableProcedure.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestCreateTableProcedure.java

Details see: [HBASE-28481](https://issues.apache.org/jira/browse/HBASE-28481)

HBASE-28481 Prompting table already exists after failing to create table with many region replications

---

hbase-common/src/main/java/org/apache/hadoop/hbase/io/compress/Compression.java
hbase-compression/hbase-compression-xz/src/main/java/org/apache/hadoop/hbase/io/compress/xz/LzmaCodec.java

Refer to https://lists.apache.org/thread/on62z40rwotrcc8w1l5n55rd4zldho5g .

HBASE-28507 Deprecate hbase-compression-xz

---

RELEASENOTES.md

The changes as per spotless:apply are added as part of this PR to fix the error.

HBASE-28498 fix spotless:check errors

---

hbase-client/src/main/java/org/apache/hadoop/hbase/security/EncryptionUtil.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableSnapshotInputFormatImpl.java
hbase-protocol-shaded/pom.xml
hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/FixedFileTrailer.java
pom.xml

Signed-off-by: Bryan Beaudreault <bbeaudreault@apache.org>
(cherry picked from commit 3539581268f2063184044e96518267a9b19b642e)

HBASE-28511 Update hbase-thirdparty to 4.1.7 (#5818)

---

pom.xml

Build has passed
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache HBase 4.0.0-alpha-1-SNAPSHOT:
[INFO] 
[INFO] Apache HBase ....................................... SUCCESS [  5.089 s]
[INFO] Apache HBase - Checkstyle .......................... SUCCESS [  0.927 s]
[INFO] Apache HBase - Annotations ......................... SUCCESS [  0.486 s]
[INFO] Apache HBase - Build Configuration ................. SUCCESS [  0.128 s]
[INFO] Apache HBase - Logging ............................. SUCCESS [  0.653 s]
[INFO] Apache HBase - Shaded Protocol ..................... SUCCESS [ 52.927 s]
[INFO] Apache HBase - Common .............................. SUCCESS [ 10.432 s]
[INFO] Apache HBase - Metrics API ......................... …
```

HBASE-28552 Bump up bouncycastle dependency from 1.76 to 1.78

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java

HBASE-28586 Backport HBASE-24791 Improve HFileOutputFormat2 to avoid always call getTableRelativePath method

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/SequenceIdAccounting.java
hbase-server/src/main/java/org/apache/hadoop/hbase/wal/DisabledWALProvider.java
hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WAL.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestPerColumnFamilyFlush.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestWalAndCompactingMemStoreFlush.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestFSWAL.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLog.java

https://issues.apache.org/jira/browse/HBASE-28588

HBASE-28588 Remove deprecated methods in WAL

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java

Details see: [HBASE-28619](https://issues.apache.org/jira/browse/HBASE-28619)

HBASE-28619 Fix the inaccurate message when snapshot doesn't exist

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/SyncTable.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/CopyTableTestBase.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestCopyTable.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestCopyTableToPeerCluster.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestSyncTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/mob/MobTestUtil.java

Signed-off-by: Xin Sun <sunxin@apache.org>
(cherry picked from commit a94b78666f529f6731cc79c09b628fd099d177ad)

HBASE-28636 Add UTs for testing copy/sync table between clusters (#5963)

---

pom.xml
src/site/resources/css/site.css
src/site/site.xml
src/site/xdoc/index.xml

Also change ™ to ® on the index page as HBase is a registered trademark

HBASE-28617 Add trademark statement in footer on our website

---

hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java
hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestCanaryTool.java

[HBASE-28663](https://issues.apache.org/jira/browse/HBASE-28663)

HBASE-28663 Graceful shutdown of CanaryTool timeouts

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLog.java

HBASE-28665 fixes WALs not marked closed when there are errors in closing WALs

---

hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputHelper.java
hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputSaslHelper.java
hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/ProtobufDecoder.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFlushFromClient.java
pom.xml

(cherry picked from commit df47eddf520976c4006044fac05f01602e9cdfb5)

HBASE-28714 Hadoop check for hadoop 3.4.0 is failing

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestCopyTable.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshot.java
hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/RestoreSnapshotHelper.java
hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestRestoreSnapshotHelper.java

Jira: [HBASE-28704](https://issues.apache.org/jira/browse/HBASE-28704)
Master branch PR: #6047

HBASE-28704 The expired snapshot can be read by CopyTable or ExportSnapshot (branch-2)

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java
hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestReadOnlyZKClient.java

Jira: HBASE-28745
HBASE-28428 addendum

HBASE-28745 : Default Zookeeper ConnectionRegistry APIs timeout should be less

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupDriver.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupInfo.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRequest.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRestoreConstants.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupCommands.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManager.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/FullTableBackupClient.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/TableBackupClient.java
hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupBase.java
hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupMerge.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java

https://issues.apache.org/jira/browse/HBASE-28702

HBASE-28702 TestBackupMerge fails 100% of times on flaky dashboard 

---

src/main/asciidoc/_chapters/backup_restore.adoc

https://issues.apache.org/jira/browse/HBASE-28744

HBASE-28744 Add a new command-line option for table backup in our ref guide

---

hbase-shell/src/main/ruby/shell/commands/snapshot.rb

https://issues.apache.org/jira/browse/HBASE-28734

HBASE-28734 Improve HBase shell snapshot command Doc with TTL option

---

hbase-protocol-shaded/src/main/protobuf/MasterProcedure.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/AbstractCloseTableRegionsProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CloseExcessRegionReplicasProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CloseTableRegionsProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/DisableTableProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestRaceBetweenSCPAndDTP.java

(cherry picked from commit 0fe7f01dab0a20ad17b618c127bd640d5ae7a541)

HBASE-28522 UNASSIGN proc indefinitely stuck on dead rs

---

pom.xml

HBASE-28758 Remove the aarch64 profile

HBASE-28758 Remove the aarch64 profile

---

bin/hbase

Backports https://github.com/apache/hbase/pull/6162

Backport "HBASE-28786 Fix classname for command: copyreppeers in bin/hbase" to branch-3

---

hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestFSUtils.java

Cherrypick the commit from master to branch-3.

HBASE-27746 Check if the file system supports storage policy before invoking setStoragePolicy()

---

hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestsDriver.java
hbase-protocol-shaded/pom.xml
hbase-server/src/main/java/org/apache/hadoop/hbase/util/compaction/MajorCompactor.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestSpaceQuotasWithSnapshots.java
pom.xml

Cherry pick from https://github.com/apache/hbase/pull/6166

HBASE-28793 Update hbase-thirdparty to 4.1.8

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/MergeTableRegionsProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/SplitTableRegionProcedure.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSplitOrMergeAtTableLevel.java

Backport "HBASE-27903 Skip submitting Split/Merge procedure when split/merge is disabled at table level" to branch-3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java

Backports #6187 
CC: @1458451310

Backport "HBASE-28807 Remove some useless code and add some logs for CanaryTool" to branch-3

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableSplit.java

https://issues.apache.org/jira/browse/HBASE-28823

HBASE-28823 Change the LOG field in TableSplit to private

---

hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionServerObserver.java

https://issues.apache.org/jira/browse/HBASE-28824

HBASE-28824 Add deprecation cycle for methods in RegionServerObserver

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java

https://issues.apache.org/jira/browse/HBASE-28826

HBASE-28826 Remove the deprecated annotation in RegionCoprocessorHost

---

hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/TokenUtil.java

https://issues.apache.org/jira/browse/HBASE-28825

HBASE-28825 Add deprecation cycle for methods in TokenUtil

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java

During the persistence of bucket-cache backing map to a file, the backing map is divided into multiple smaller chunks and persisted to the file. This chunking avoids the high memory utilisation of during persistence, since only a small subset of backing map entries need to persisted in one chunk.
However, during the retrieval of the backing map during the server startup, we accumulate all these chunks into a list and then process each chunk to recreate the in-memory backing map. Since, all the chunks are fetched from the persistence file and then processed, the memory requirement is higher.
With this change, the retrieval of bucket-cache from persistence file is optimised to enable the processing of one chunk at a time to avoid high memory utilisation.
Change-Id: …

HBASE-28840: Optimise memory utilization bucketcache retrieval from persistence.

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java

Backport "HBASE-28868 Add missing permission check for updateRSGroupConfig in branch-2" to branch-2.6

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsBase.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsWithACL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java

- Backports #6276 to branch-2.6

HBASE-28867 Backport "HBASE-20653 Add missing observer hooks for region server group to MasterObserver" to branch-2

---

hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminEndpoint.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsBase.java
hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsWithACL.java
hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java

- Backports #6276 to branch-2.5

HBASE-28867 Backport "HBASE-20653 Add missing observer hooks for region server group to MasterObserver" to branch-2 

---

bin/replication/copy_tables_desc.rb

Backport "HBASE-28585 copy_tables_desc.rb script should handle scenarios where the namespace does not exist in the target cluster" to branch-3

---

hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobStoreCompaction.java

HBASE-28564 [addendum] Refactor direct interactions of Reference file creations to SFT interface

---

hbase-server/src/main/java/org/apache/hadoop/hbase/util/MoveWithAck.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestRegionMover2.java

(cherry picked from commit 344bf78b8fc1c7b4f1b07f4ba846a6b56f955c79)

HBASE-28948 RegionMover tool fails when table is deleted (#6423)

---

hbase-rest/pom.xml
hbase-server/pom.xml
hbase-thrift/pom.xml

HBASE-28921 Avoid bundling hbase-webapps folder in default jars

---

dev-support/Jenkinsfile

HBASE-28946 Update nightlies to run with HADOOP2_VERSION = 2.10.2

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableOutputFormat.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableOutputFormat.java

original pr: #6436 
cherry-pick from commit: [5c99925](https://github.com/apache/hbase/commit/5c99925c830b373430f04179a3c791af850f313e)

HBASE-28268 Provide option to skip wal while using TableOutputFormat

---

hbase-server/src/main/java/org/apache/hadoop/hbase/mob/RSMobFileCleanerChore.java
hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestRSMobFileCleanerChore.java

Jira: [HBASE-28956](https://issues.apache.org/jira/browse/HBASE-28956)
Master PR:  #6439

HBASE-28956 RSMobFileCleanerChore may close the StoreFileReader object which is being used by Compaction thread (branch-2)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/namespace/NamespaceStateManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestSplitMergeQuotaTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestSplitMergeSystemTables.java

Backport "HBASE-29005 Cannot split hbase:quota table when quota enforcement is enabled (#6501)" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/namespace/NamespaceStateManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestSplitMergeQuotaTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestSplitMergeSystemTables.java

Backport "HBASE-29005 Cannot split hbase:quota table when quota enforcement is enabled (#6501)" to branch-2.6

---

hbase-server/src/main/java/org/apache/hadoop/hbase/namespace/NamespaceStateManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestSplitMergeQuotaTable.java
hbase-server/src/test/java/org/apache/hadoop/hbase/TestSplitMergeSystemTables.java

Backport "HBASE-29005 Cannot split hbase:quota table when quota enforcement is enabled (#6501)" to branch-2.5

---

hbase-client/src/main/java/org/apache/hadoop/hbase/slowlog/SlowLogTableAccessor.java
hbase-server/src/main/resources/hbase-webapps/regionserver/rsOperationDetails.jsp

HBASE-28959 Output fsreadtime in SlowLogPayLoad to hbase:slowlog.

---

hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputSaslHelper.java

HBASE-28970 Get asyncfs working with custom SASL mechanisms (#6507)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/HBaseServerBase.java

HBASE-29046 Log message is not correct when the Master bind address configured wrongly

---

dev-support/Jenkinsfile

Run all jobs every 3 days, master and branch-3 on first day, branch-2 on second day, and other branches on third day

HBASE-29067 Stagger the nightly tests on jenkins

---

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java

Backport "HBASE-29068 Report percentFilesLocalPrimaryRegions metric (#6596)" to branch-3

---

hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java

Had to do a slight merge conflict resolution in MetricsRegionServerWrapperImpl, but should be alright. Feel free to double check @charlesconnell

Backport "HBASE-29068 Report percentFilesLocalPrimaryRegions metric (#6596)" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/executor/ExecutorService.java

Added logging exception handler from Threads class for ExecutorService

 HBASE-29041 Set UncaughtException Handler for RegionServer ExecutorService

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplica.java

Backport "HBASE-29072 StochasticLoadBalancer#areReplicasColocated ignores rack …" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java

This PR updates block cache loads to not calculate `BlockCacheKey.toString()`—which has been observed causing higher allocation pressure than expected on busy region servers—if tracing isn't enabled. 
I used the Span.isRecordingEnabled API ([OpenTelemetry Docs](https://opentelemetry.io/docs/specs/otel/trace/api/#isrecording)). Based on the following docsnippet, I believe that this will work if OpenTelemetry isn't enabled for HBase:
> This flag SHOULD be used to avoid expensive computations of a Span attributes or events in case when a Span is definitely not recorded. Note that any child span’s recording is determined independently from the value of this flag (typically based on the sampled flag of a TraceFlags on [SpanContext](https://opentelemetry.io/docs/specs/otel/trace/api/#spancontext …

HBASE-29099 Avoid expensive BlockCacheKey.toString() calls when tracing is disabled

---

hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java

…artup because of uninitialized sumMultiplier (#6641)

Backport "HBASE-29073 StochasticLoadBalancer will always run the balancer on st…" to branch-3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java

…artup because of uninitialized sumMultiplier (#6641)

Backport "HBASE-29073 StochasticLoadBalancer will always run the balancer on st…" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java

…artup because of uninitialized sumMultiplier (#6641)

Backport "HBASE-29073 StochasticLoadBalancer will always run the balancer on st…" branch-2.6

---

hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotInfo.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotStats.java

Jira: [HBASE-29088](https://issues.apache.org/jira/browse/HBASE-29088)
Master PR: #6617

HBASE-29088 The denominator cannot be 0 when calculating percentages in SnapshotStats (branch-2)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/executor/ExecutorService.java

- Backports #6612 (Raised on behalf of @DishaVaidh)

HBASE-29041 Set UncaughtException Handler for RegionServer ExecutorService

---

hbase-http/src/main/java/org/apache/hadoop/hbase/http/ProfileServlet.java

HBASE-29045 Support new async-profiler > 2.9 version

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/RestoreJob.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/mapreduce/MapReduceRestoreToOriginalSplitsJob.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/RestoreTool.java
hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java

Backport "HBASE-29114 Restoring to original splits fails if backups are on sepa…" to branch-2

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/RestoreJob.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/mapreduce/MapReduceRestoreToOriginalSplitsJob.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/RestoreTool.java
hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java

Backport "HBASE-29114 Restoring to original splits fails if backups are on sepa…" to branch-2.6

---

hbase-client/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java

Backport of https://github.com/apache/hbase/commit/5edcb41a7ab709bd5a2dc6ac7383929243b18c28

HBASE-29097 Add error logging when put creation fails

---

hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/AssignRegionAction.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalanceAction.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CacheAwareLoadBalancer.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFunction.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasConditional.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/MoveBatchAction.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/MoveRegionAction.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionPlanConditional.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionPlanConditionalCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/SlopFixingCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/SwapRegionsAction.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/replicas/ReplicaKey.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/replicas/ReplicaKeyCache.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasTestConditional.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBalancerConditionals.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingConditionalReplicaDistribution.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionalsTestUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestReplicaDistributionBalancerConditional.java

Backport "HBASE-28513 The StochasticLoadBalancer should support discrete evalua…" to branch-3

---

hbase-shell/src/main/ruby/hbase/table.rb
hbase-shell/src/main/ruby/shell/commands/count.rb

The change is transparent to the users, and it passes all existing test cases.

HBASE-29107 shell: Improve 'count' performance

---

hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/MetaTableIsolationCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/MetaTableIsolationConditional.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionPlanConditionalCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/SlopFixingCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/TableIsolationCandidateGenerator.java
hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/TableIsolationConditional.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBalancerConditionals.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingMetaTableIsolation.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingTableIsolationAndReplicaDistribution.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestMetaTableIsolationBalancerConditional.java

Backport "HBASE-29074 Balancer conditionals should support meta table isolation…" to branch-3

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/MutableRegionInfo.java

I've noticed that tracing can add meaningful CPU cycles to each HBase query. This is easy to correct, it turns out. Creating a tracing span is slow because region names are attached to the spans, and calls to `RegionInfo#getRegionNameAsString()` are expensive. This method re-generates the region name string on each call, which is not necessary. In this PR I make it cache this string.

HBASE-29160: Cache region name string in RegionInfo

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasConditional.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/SlopFixingCandidateGenerator.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/SystemTableIsolationCandidateGenerator.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/SystemTableIsolationConditional.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/TableIsolationConditional.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingSystemTableIsolation.java

Backport "HBASE-29075 Balancer conditionals should support system table isolati…" to branch-2

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/Import.java
hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestImportExport.java

HBASE-25839 Bulk Import fails with java.io.IOException: Type mismatch in value from map
1. CellSortImporter emits values wrapped inside MapReduceExtendedCell
2. Converted KV to CellUtil.

HBASE-25839 Bulk Import fails with java.io.IOException: Type mismatch in value from map

---

hbase-client/pom.xml
hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableEnableDisableError.java

(cherry picked from commit d8f71d019d781063c7888f51de18827effb13516) (cherry picked from commit ef44bccb33f0526723330ff938aa2549f56a2433)

HBASE-29189 NPE in RawAsyncTableAdmin.isTableDisabled (#6798)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AuthManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestZKPermissionWatcher.java

https://issues.apache.org/jira/browse/HBASE-28984

HBASE-28984 Refactor cache update logic to use new PermissionCache instances

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RSProcedureDispatcher.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/RSProcDispatcher.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestProcDispatcher.java

HBASE-29180 Apply fail-fast retry limit for UnknownHostException

---

hbase-client/src/main/java/org/apache/hadoop/hbase/security/AbstractHBaseSaslRpcClient.java
hbase-client/src/main/java/org/apache/hadoop/hbase/security/HBaseSaslRpcClient.java
hbase-client/src/main/java/org/apache/hadoop/hbase/security/NettyHBaseSaslRpcClient.java
hbase-client/src/main/java/org/apache/hadoop/hbase/security/NettyHBaseSaslRpcClientHandler.java
hbase-client/src/main/java/org/apache/hadoop/hbase/security/SaslUtil.java
hbase-client/src/test/java/org/apache/hadoop/hbase/security/TestSaslUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerRpcConnection.java
hbase-server/src/main/java/org/apache/hadoop/hbase/security/HBaseSaslRpcServer.java

Signed-off-by: Andor Molnár <andor@apache.org>
(cherry picked from commit 03effb9a26acd74c58c97053a1247df0de279157)

HBASE-29080 Validate Negotiated SASL QoP Against Requested (#6601) (#6782)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileScanner.java

…seeking to next row (#6643)
cc @jbewing

Backport "HBASE-29103 Avoid excessive allocations during reverse scanning when …" to branch-2

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileScanner.java

…seeking to next row (#6643)
cc @jbewing

Backport "HBASE-29103 Avoid excessive allocations during reverse scanning when …" to branch-3

---

hbase-assembly-byo-hadoop/pom.xml
hbase-assembly/pom.xml

HBASE-29192 Provide installation method that supports running hbase-it

---

hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestUnattainableBalancerCostGoal.java

Backport "HBASE-29202 Balancer conditionals make balancer actions more likely t…" to branch-3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFromRegionLoadFunction.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StoreFileTableSkewCostFunction.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStoreFileTableSkewCostFunction.java

Backport "HBASE-29203 There should be a StorefileSize equivalent to the TableSk…" to branch-2

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java

…R bulkload output directory (#6747)

Backport "HBASE-29146 Incremental backups can fail due to not cleaning up the M…" to branch-2

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java

…R bulkload output directory (#6747)

Backport "HBASE-29146 Incremental backups can fail due to not cleaning up the M…" to branch-2.6

---

hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/RpcThrottlingException.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleSettings.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleType.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-protocol-shaded/src/main/protobuf/server/Quota.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/ExceedOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/GlobalQuotaSettingsImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/OperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RpcQuotaManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestAtomicReadQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultAtomicQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestNoopOperationQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaAdmin.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaState.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/ThrottleQuotaTestUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerLeaseCount.java

Backport "HBASE-29229 Throttles should support specific restrictions for atomic…" to branch-3

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/MergeSplitBulkloadInfo.java

Backport "HBASE-29134 Optimize bulkload backup process for incremental backups …" to branch-3

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/MergeSplitBulkloadInfo.java

Backport "HBASE-29134 Optimize bulkload backup process for incremental backups …" to branch-2

---

hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/MergeSplitBulkloadInfo.java

Backport "HBASE-29134 Optimize bulkload backup process for incremental backups …" to branch-2.6

---

hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/RpcThrottlingException.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleSettings.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleType.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-protocol-shaded/src/main/protobuf/Quota.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/ExceedOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/GlobalQuotaSettingsImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/OperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RpcQuotaManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestAtomicReadQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultAtomicQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestNoopOperationQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaAdmin.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaState.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/ThrottleQuotaTestUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerLeaseCount.java

Backport "HBASE-29229 Throttles should support specific restrictions for atomic…" to branch-2

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-common/src/main/java/org/apache/hadoop/hbase/conf/ConfigKey.java
hbase-common/src/test/java/org/apache/hadoop/hbase/conf/TestConfigKey.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/ConstantSizeRegionSplitPolicy.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DefaultStoreEngine.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreEngine.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/CompactionConfiguration.java
hbase-server/src/main/java/org/apache/hadoop/hbase/util/TableDescriptorChecker.java
hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestTableDescriptorChecker.java

#6709 for branch-2 as requested by @Apache9

HBASE-29137 Add basic config type validation (branch-2)

---

hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/RootProcedureState.java

Revert "HBASE-29055 Remove the useless parameter from RootProcedureState"

---

hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java

https://issues.apache.org/jira/browse/HBASE-29238

HBASE-29238 ExportSnapshot support specify storage policy

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/ReadOnlyController.java
hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestReadOnlyController.java

Add hbase read-only property and  ReadOnlyController
(cherry picked from commit 49b678da90288bc645fcbfb8c0bbd27b33281c0f)

HBASE-29083: Add global read-only mode to HBase

---

pom.xml

(cherry picked from commit bd921e0641e03d07ee394bed1962f057291dfe13)

HBASE-29300 Upgrade Tomcat to 9.0.104

---

hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestPrefetchWithBucketCache.java

* Fixing flakeyness in UT added in HBASE-29288

[ADDENDUM] HBASE-29288 Avoid adding new blocks during prefetch if usage is greater than accept factor (#6965)

---

hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRecreateCluster.java

- use StartMiniClusterOption in branch-2
(cherry picked from commit 902067d)

HBASE-29316 Backport HBASE-29292 to branch-2

---

hbase-assembly/src/main/assembly/client.xml
hbase-assembly/src/main/assembly/hadoop-three-compat.xml
hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java
hbase-common/pom.xml
hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableMapReduceUtil.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestAsyncTableScan.java
hbase-shaded/hbase-shaded-client/pom.xml
hbase-shaded/hbase-shaded-testing-util/pom.xml
hbase-shaded/pom.xml
pom.xml

HBASE-29293 Upgrade to latest opentelemetry libraries (#6969)

---

hbase-http/pom.xml
hbase-http/src/main/java/org/apache/hadoop/hbase/http/lib/AuthenticationFilterInitializer.java
hbase-http/src/test/java/org/apache/hadoop/hbase/http/LdapConstants.java
hbase-http/src/test/java/org/apache/hadoop/hbase/http/TestLdapHttpServer.java
hbase-http/src/test/java/org/apache/hadoop/hbase/http/lib/TestAuthenticationFilterInitializer.java
pom.xml

- Backports https://github.com/apache/hbase/pull/5680

HBASE-28368 Backport "HBASE-27693 Support for Hadoop's LDAP Authentication mechanism (Web UI only)"

---

hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaSettingsFactory.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/RpcThrottlingException.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleSettings.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleType.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-protocol-shaded/src/main/protobuf/server/Quota.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/ExceedOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/GlobalQuotaSettingsImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultHandlerUsageQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaState.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestThreadHandlerUsageQuota.java

Backport "HBASE-29231 Throttles should support limits based on handler thread u…" to branch-3

---

hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaSettingsFactory.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/RpcThrottlingException.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleSettings.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleType.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-protocol-shaded/src/main/protobuf/Quota.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/ExceedOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/GlobalQuotaSettingsImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultHandlerUsageQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaState.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestThreadHandlerUsageQuota.java

Backport "HBASE-29231 Throttles should support limits based on handler thread u…" to branch-2

---

hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaSettingsFactory.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/RpcThrottlingException.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleSettings.java
hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleType.java
hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
hbase-protocol-shaded/src/main/protobuf/Quota.proto
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/ExceedOperationQuota.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/GlobalQuotaSettingsImpl.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultHandlerUsageQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaState.java
hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestThreadHandlerUsageQuota.java

Backport "HBASE-29231 Throttles should support limits based on handler thread u…" to branch-2.6

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SnapshotProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableQueue.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestSnapshotProcedureConcurrently.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestSnapshotProcedureRIT.java

Backport "HBASE-29386 SnapshotProcedure and EnableTableProcedure can cause a de…" to branch-3

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SnapshotProcedure.java
hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableQueue.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestSnapshotProcedureConcurrently.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestSnapshotProcedureRIT.java

Backport "HBASE-29386 SnapshotProcedure and EnableTableProcedure can cause a de…" to branch-2.6

---

bin/hbase-common.sh
bin/hbase-daemon.sh

Check proc_$command in the process command line to confirm that the process is the expected one

HBASE-29400 RollingBatchRestartRsAction may fail to start region server

---

hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
hbase-common/src/main/resources/hbase-default.xml
hbase-server/src/main/java/org/apache/hadoop/hbase/io/util/MemorySizeUtil.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HeapMemoryManager.java
hbase-server/src/test/java/org/apache/hadoop/hbase/io/util/TestMemorySizeUtil.java

**Jira** https://issues.apache.org/jira/browse/HBASE-15625
---
Original PR is https://github.com/apache/hbase/pull/7076

HBASE-15625 Make minimum free heap memory percentage configurable on branch-2

---

hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java
hbase-http/src/main/java/org/apache/hadoop/hbase/http/InfoServer.java

HBASE-29481 Make TLS protocols and cipher list configurable for HTTPS InfoServer

---

hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/TakeSnapshotHandler.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSnapshotWithTTLFromClient.java
hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestTakeSnapshotHandler.java

JIRA: [HBASE-29296](https://issues.apache.org/jira/browse/HBASE-29296)
Master PR: [#6970](https://github.com/apache/hbase/pull/6970)

HBASE-29296 Missing critical snapshot expiration checks (branch-2.5)

---

hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java

[HBASE-29532]Fix the potential NPE issue when the specific recover edit path set

---

hbase-shell/src/test/java/org/apache/hadoop/hbase/client/AbstractTestShell.java
hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestAdminShell.java
hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestRSGroupShell.java
hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestShellNoCluster.java

HBASE-29558: Addendum to fix checkstyle warnings

---

hbase-client/src/main/java/org/apache/hadoop/hbase/client/metrics/ServerSideScanMetrics.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/ScannerContext.java
hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestTableScanMetrics.java

JIRA: [HBASE-29494](https://issues.apache.org/jira/browse/HBASE-29494)

HBASE-29494: Capture Scan RPC processing time and queuing time in Scan Metrics

---

hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java

https://issues.apache.org/jira/browse/HBASE-29577

HBASE-29577 Fix NPE from RegionServerRpcQuotaManager when reloading configuration

---

pom.xml

This reverts commit 04d48ee4903ba88145e21a1c2fd203b1cebb0636.

Revert "HBASE-29609 Upgrade checkstyle and Maven checkstyle plugin (#7321)"

---

hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/ThreadLocalServerSideScanMetrics.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionScannerImpl.java

Cherry-pick of: https://github.com/apache/hbase/pull/7348

HBASE-29626: Refactor server side scan metrics for Coproc hooks
