- hbase-common/src/test/java/org/apache/hadoop/hbase/HBaseCommonTestingUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/TestHBaseTestingUtil.java
Put back the ability to pass a Random instance to HBaseTestingUtil.PortAllocator so the test will pass again.
> HBASE-26824 TestHBaseTestingUtil.testResolvePortConflict failing after HBASE-26582

- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobStoreScanner.java
Change the timing of the test but not the objective by storing three large MOB values into the row with three separate puts, each randomizing the data. Increases running time of the testGetMassive case 2x but avoids OOME in the test environment where the OOME was consistently reproducible.
> HBASE-26761 TestMobStoreScanner (testGetMassive) can OOME

- dev-support/Jenkinsfile_GitHub
- dev-support/hbase-personality.sh
- dev-support/jenkins_precommit_github_yetus.sh
Increase the maven build thread to 4, and also increase the surefire fork count from 0.25C to 0.5C.
This could save us a lot of time.
Please see #4211 for the result.
> HBASE-26828 Increase the concurrency when running UTs in pre commit job

- hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java
- hbase-http/src/main/java/org/apache/hadoop/hbase/http/InfoServer.java
- hbase-http/src/main/java/org/apache/hadoop/hbase/http/gson/ByteArraySerializer.java
- hbase-http/src/main/java/org/apache/hadoop/hbase/http/gson/GsonMessageBodyWriter.java
- hbase-http/src/main/java/org/apache/hadoop/hbase/http/jersey/ResponseEntityMapper.java
- hbase-http/src/main/java/org/apache/hadoop/hbase/http/jersey/SupplierFactoryAdapter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/api_v1/ResourceConfigFactory.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/api_v1/cluster_metrics/model/ClusterMetrics.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/api_v1/cluster_metrics/package-info.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/api_v1/cluster_metrics/resource/ClusterMetricsResource.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/gson/GsonFactory.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/gson/GsonSerializationFeature.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/gson/SizeAsBytesSerializer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/gson/package-info.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/jersey/MasterFeature.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestApiV1ClusterMetricsResource.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/gson/GsonFactoryTest.java
Publishes a set of JSON endpoints following a RESTful structure, which expose a subset of the
`o.a.h.h.ClusterMetrics` object tree. The URI structure is as follows
/api/v1/admin/cluster_metrics
/api/v1/admin/cluster_metrics/live_servers
/api/v1/admin/cluster_metrics/dead_servers
> Backport "HBASE-25895 Implement a Cluster Metrics JSON endpoint" to branch-2

- hbase-client/src/main/java/org/apache/hadoop/hbase/filter/RandomRowFilter.java
- hbase-http/src/main/java/org/apache/hadoop/hbase/http/SecurityHeadersFilter.java
In org.apache.hadoop.hbase.http.SecurityHeadersFilter, marked LimitedPrivate(CONFIG), static method getDefaultParameters(Configuration) returning Map<String,String> was removed.
In org.apache.hadoop.hbase.filter.RandomRowFilter, marked Public, the protected field 'random' of type java.util.Random was removed, which might cause NoSuchFieldError exceptions in downstreamers.
> HBASE-26839 Fix compatibility issues in 2.4.11RC0

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractProtobufLogWriter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncProtobufLogWriter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogWriter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/wal/FSHLogProvider.java
Broken writers need to be closed, so that when doing log split, there will be no need to recover lease for those length 0 wals.
> HBASE-26680 Close and do not write trailer for the broken WAL writer

- hbase-http/pom.xml
- hbase-it/pom.xml
- hbase-resource-bundle/src/main/resources/supplemental-models.xml
- hbase-rest/pom.xml
- pom.xml
This is no longer needed since we've transitioned to the shaded Jersey shipped in
hbase-thirdparty.
> HBASE-26813 Remove javax.ws.rs-api dependency

- hbase-http/pom.xml
- hbase-it/pom.xml
- hbase-resource-bundle/src/main/resources/supplemental-models.xml
- hbase-rest/pom.xml
- pom.xml
This is no longer needed since we've transitioned to the shaded Jersey shipped in
hbase-thirdparty. Also drop supplemental models entry.
> Backport "HBASE-26813 Remove javax.ws.rs-api dependency" to branch-2

- hbase-http/pom.xml
- hbase-it/pom.xml
- hbase-resource-bundle/src/main/resources/supplemental-models.xml
- hbase-rest/pom.xml
- pom.xml
This is no longer needed since we've transitioned to the shaded Jersey shipped in
hbase-thirdparty. Also drop supplemental models entry.
> Backport "HBASE-26813 Remove javax.ws.rs-api dependency" to branch-2.5

- hbase-it/src/test/java/org/apache/hadoop/hbase/TestShellExecEndpointCoprocessor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ConnectionRule.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/MiniClusterRule.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestApiV1ClusterMetricsResource.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestMetaBrowser.java
This is needed primarily for branch-2 codelines where there's no easy bridge from AsyncConnection to Connection.
> HBASE-26834 Adapt ConnectionRule for both sync and async connections (branch-2)

- hbase-endpoint/src/test/java/org/apache/hadoop/hbase/coprocessor/TestCoprocessorEndpointTracing.java
Stuck by this again. branch-2 needs this configuration instance to be initialized as an
HBaseConfiguration. Forward-porting this change to master in order to keep the branches as similar as possible.
> HBASE-26531 Trace coprocessor exec endpoints (addendum)

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSTableDescriptors.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestDefaultMemStore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestGetClosestAtOrBefore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestLogRollingNoCluster.java
Set encoding and blooms on meta as default. Also shutdown access to the
initial meta schema creating method; get from TableDescriptors if you
need access to schema or edit it as you would any other table if you
want to edit it.
This is a backport of https://github.com/apache/hbase/pull/1012 for branch-2.
> HBASE-21065 Try ROW_INDEX_V1 encoding on meta table

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionInfo.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAdmin1.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAdmin2.java
[HBASE-26640](https://issues.apache.org/jira/browse/HBASE-26640) introduced two extra paths under master:store table: ".initializing" and ".initialized", in order to control when such store has been completed started for SFT.
Problem is that TestHFileProcedurePrettyPrinter uses RegionInfo.isEncodedRegionName to determine if a given child path in the table dir is a valid region dir. On branch-2 base, implementation for RegionInfo.isEncodedRegionName considers ".initializing" and ".initialized" as valid region encoded names, thus the test ends up picking one of the flag dirs to list hfiles that should had been modified when validating the test outcome.
Further improvements have been made to RegionInfo.isEncodedRegionName in [HBASE-25368](https://issues.apache.org/jira/browse/HBASE-25368) to …
> HBASE-26881 Backport HBASE-25368 to branch-2

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionFactory.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/security/provider/OAuthBearerSaslAuthenticationProvider.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/security/provider/OAuthBearerSaslProviderSelector.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/security/token/OAuthBearerTokenUtil.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/security/token/TestOAuthBearerTokenUtil.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/security/oauthbearer/OAuthBearerUtils.java
Implemented the environment variable based approach for detecting available JWT tokens. `ConnectionFactory` will check for the presence of "HADOOP_JWT" environment variable and adds it to user's credentials. Format of value is 
`<base64_encoded_jwt>,<expiry in DateTimeFormatter.ISO_ZONED_DATE_TIME format>`
Expiry info is optional.
```
export HADOOP_JWT="Tm90aGluZyBpcyB0cnVlOyBldmVyeXRoaW5nIGlzIHBlcm1pdHRlZAo=,2022-01-25T16:59:48.614000+00:00"
```
> HBASE-26667 Integrate user-experience for hbase-client

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionServerCallable.java
Simple change, did not think it worth a dedicated test. The AsyncTable client callers already appropriately use toStringBinary. For example, here: https://github.com/apache/hbase/blob/branch-2/hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncSingleRequestRpcRetryingCaller.java#L85. I checked a few other places I knew of as well.
> HBASE-26876 Use toStringBinary for rowkey in RegionServerCallable error string

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncClientScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncScanSingleRegionRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableResultScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/StartTestingClusterOption.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/LimitedScanResultConsumer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/SimpleScanResultConsumerImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanAll.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanMetrics.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRawAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TracedAdvancedScanResultConsumer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TracedScanResultConsumer.java
- pom.xml
* on `AsyncTable`, both `scan` and `scanAll` methods should result in `SCAN` table operations.
* the span of the `SCAN` table operation should have children representing all the RPC calls
involved in servicing the scan.
* when a user provides custom implementation of `AdvancedScanResultConsumer`, any spans emitted
from the callback methods should also be tied to the span that represents the `SCAN` table
operation. This is easily done because these callbacks are executed on the RPC thread.
* when a user provides a custom implementation of `ScanResultConsumer`, any spans emitted from the
callback methods are tied to the context of user application code. We could `link` them to the
`SCAN` table operation, except that we have no means of passing that span along.
> HBASE-26545 Implement tracing of scan

- hbase-server/src/main/java/org/apache/hadoop/hbase/backup/HFileArchiver.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/backup/TestHFileArchiving.java
[HBASE-26718](https://issues.apache.org/jira/browse/HBASE-26718)
Of particular note:
1. The tests as they exist today are not validating a rename into archive, but instead validating a rename *from* archive into the timestamped backup copy. With this change, the tests are actually validating the proper renames.
2. I add a short-circuit return for the case where the source file does not exist, as there is no reason to delete a file from archive if we don't even have a source file to move.
3. I retained the logic for sidelining the archived file and moving the source file, if they both exist. One could argue that we could ignore the source file instead... I am really hoping this is the "one in a trillion" case that the comment mentions. So I left the logic as-is, in case it is silently …
> HBASE-26718 HFileArchiver can remove referenced StoreFiles from the archive

- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/client/Client.java
- pom.xml
Dependabot auto-generated a dependency upgrade (#4291) but we could not merge that PR as-is because it caused a unit test failure. There is a comment in our POM indicating this is a known issue:
However, staying back on a version of httpclient with CVE listed vulnerabilities just for this isn't a good option.
This change bumps httpclient from 4.5.3 to 4.5.13 to avoid a CVE of medium severity in this dependency.
Newer httpclient versions enable a URI normalization algorithm by default that rewrites URIs in a way that breaks some forms of valid REST gateway interactions, so this change also disables the unwanted behavior when building the httpclient instance in `Client`.
> HBASE-26903 Bump httpclient from 4.5.3 to 4.5.13

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncClientScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncScanSingleRegionRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableResultScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClientAsyncPrefetchScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClientScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ResultScanner.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableTracing.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/StartMiniClusterOption.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/LimitedScanResultConsumer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/SimpleScanResultConsumerImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanAll.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanMetrics.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRawAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestResultScannerTracing.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TracedAdvancedScanResultConsumer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TracedScanResultConsumer.java
- pom.xml
* on `AsyncTable`, both `scan` and `scanAll` methods should result in `SCAN` table operations.
* the span of the `SCAN` table operation should have children representing all the RPC calls
involved in servicing the scan.
* when a user provides custom implementation of `AdvancedScanResultConsumer`, any spans emitted
from the callback methods should also be tied to the span that represents the `SCAN` table
operation. This is easily done because these callbacks are executed on the RPC thread.
* when a user provides a custom implementation of `ScanResultConsumer`, any spans emitted from the
callback methods should be also be tied to the span that represents the `SCAN` table
operation. This accomplished by carefully passing the span instance around after it is created.
Signed-off-by: Andrew …
> Backport "HBASE-26545 Implement tracing of scan" to branch-2.5

- dev-support/hbase-personality.sh
- pom.xml
Upgrade maven-surefire-plugin to 3.0.0-M6 which should have fixed SUREFIRE-1821
> HBASE-26929 Upgrade surefire plugin to 3.0.0-M6

- hbase-shell/src/main/ruby/hbase/table.rb
- hbase-shell/src/test/ruby/hbase/table_test.rb
HBASE-26895
on hbase shell,
'delete' or 'deleteall' for the whole columnFamily is not working properly.
```
hbase(main):026:0* put 'test', 'r1', 'f:1', 'a'
Took 0.0233 seconds
hbase(main):029:0> delete 'test', 'r1', 'f'
Took 0.0070 seconds
hbase(main):030:0> get 'test', 'r1'
COLUMN                                                                  CELL
f:1                                                                    timestamp=1648114865022, value=a
1 row(s)
hbase(main):038:0> deleteall 'test', 'r1', 'f'
Took 0.0059 seconds
hbase(main):039:0> get 'test', 'r1'
COLUMN                                                                  CELL
f:1                                                                    timestamp=1648114865022, value=a
1 row(s) 
```
looking inside of hbase-shell,
all …
> HBASE-26895 on hbase shell, 'delete/deleteall' for a columnfamily is not working

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
Scanner should be closed to avoid leak in case any exception thrown from RegionObserver#postScannerOpen
> HBASE-26944 Possible resource leak while creating new region scanner

- pom.xml
I chose to keep the declaration that has more exclusions. That decision was arbitrary. The difference was `javax.servlet:servlet-api`.
> HBASE-26906 Remove duplicate dependency declaration (branch-2)

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableMapReduceUtil.java
I think this reference to HTrace was simply missed in early changes. It happens to have not been noticed because earlier versions of Hadoop provide an HTrace jar in the dependency set. Our import ban didn't catch this because we don't import the HTrace class, we refer to it via fully qualified class name. The restrict-imports enforcer-rule appears to work only on import statements.
> HBASE-26954 Compilation of master vs hadoop-3.3.2 fails

- hbase-shell/src/main/ruby/hbase/admin.rb
The java_import for MobCompactPartitionPolicy in admin.rb is missed, which cause an error message for creating table.
```
hbase:006:0> create 't2', {NAME => 'f', IS_MOB => true, MOB_THRESHOLD => 1000000, MOB_COMPACT_PARTITION_POLICY => 'weekly'}
ERROR: uninitialized constant Hbase::Admin::MobCompactPartitionPolicy
Did you mean?  Hbase::Admin::MOB_COMPACT_PARTITION_POLICY
For usage try 'help "create"'
Took 0.6897 seconds
hbase:007:0> 
```
> HBASE-26964 Fix java import in admin.rb

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/MetricsConnection.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestMetricsConnection.java
While I was here, I also changed the default scope. Just my opinion, but I feel like the toString representation is not a good default value because it is relatively meaningless. The one good thing it does is ensure uniqueness of the scopes. I changed the default value to be `${clusterId}-${connection.hashCode}`. This should provide the same uniqueness, but using clusterId will help users identify metrics in processes that connect to more than one hbase cluster.
I'm not sure if we'd consider that change to be a compatibility issue. It only affects the `scope=` part of the JMX MBean objectName. If this is a concern, I can revert that part.
Note: once approved I will have to submit a PR for branch-2, since there we have to also account for the blocking client.
> HBASE-26891 Make MetricsConnection scope configurable

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
This method was accidentally dropped when resolving conflicts in this backport [here](https://github.com/apache/hbase/pull/4273/commits/8755447efc72cbe7afc414e62bfe00d681d2b954#diff-7ab88c464bf7557dd7e4ff33ab640c4a8401126c0bbe1c0916c698dcef7f8b3bL747). Adding it back. I took another pass at that PR's diff both in general and with specific focus on the chained methods, and this is the only error I could find.
> HBASE-26807 Addendum: adhere to maxAttempts in RawAsyncTableImpl.batch

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationGlobalSourceSourceImpl.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSinkSource.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSinkSourceImpl.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSource.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsReplicationSourceSourceImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSink.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSource.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSink.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceShipper.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSink.java
Create an explicit metric around source.failedBatches and sink.failedBatches, incremented whenever an exception is encountered
> HBASE-26581 Add metrics for failed replication edits

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileListFile.java
In StoreFileListFile we have:
} catch (EOFException e) {
// this is normal case, so use info and do not log stacktrace
LOG.info("Failed to load track file {}: {}", trackFiles[i], e.toString());
}
except that we see frequent stacktraces at INFO level from StoreFileListFile and this appear to be the culprit.
> HBASE-26979 StoreFileListFile logs frequent stacktraces at INFO level

- src/main/asciidoc/_chapters/inmemory_compaction.adoc
The default value of `hbase.hregion.compacting.memstore.type` was changed from `BASIC` to `DEFAULT` by [HBASE-20539](https://issues.apache.org/jira/browse/HBASE-20539).
We should update its doc `inmemory_compaction.adoc` accordingly.
> HBASE-26978 Update inmemory_compaction.adoc

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/ServerMetricsTmpl.jamon
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/util/MemorySizeUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerAccounting.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java
[https://issues.apache.org/jira/browse/HBASE-26975](https://issues.apache.org/jira/browse/HBASE-26975)
There are `Memstore Size` and `Memstore Limit` info in rs-status page.
The information is a little coarse granularity and confusing:
* `Memstore Size` means memstore data size, but we cannot tell the difference of on heap and off heap memstore data size.
* `Memstore Limit` is off heap memstore limit if off-heap is enabled, otherwise, it is on heap memstore limit. 
We should provide more detailed information.
> HBASE-26975 Add on heap and off heap memstore info in rs web UI

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/SimpleLoadBalancer.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/StochasticBalancerTestBase.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestSimpleLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
- hbase-common/src/main/resources/hbase-default.xml
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBalancerDecision.java
[HBASE-22349](https://issues.apache.org/jira/browse/HBASE-22349)
Slop is a concept used within `SimpleLoadBalancer` but has always been referenced in `StochasticLoadBalancer` without any effect. This change proposes that we start using the concept of slop, as another trigger for a balancer run. This is similar to HBASE-24139, where a server with 0 regions is considered a trigger to run the balancer.
In this way we can guarantee balancer attempts to run in other cases that a balancer run is desirable, such as only 1 region on a server, or 2x or 3x the average region count on a server.
I remove the `normalizeSlop` method for two reasons:
1. A negative value will indicate the slop value should not be used at all
2. Values greater than 1 can still be useful (setting slop to 2 would mean to …
> HBASE-22349 slop in StochasticLoadBalancer

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
[HBASE-26988](https://issues.apache.org/jira/browse/HBASE-26988)
Some tests call `conf.unset(HConstants.HBASE_MASTER_LOADBALANCE_BYTABLE);` but that only works if dynamic reconfiguration will reset the value. Without this fix (or test fixes), the tests only pass if some ordering constraints are guaranteed.
> HBASE-26988 dynamic configuration of loadbalance.bytable

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableQueryMeter.java
- hbase-hadoop-compat/src/test/java/org/apache/hadoop/hbase/test/MetricsAssertHelper.java
- hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableQueryMeterImpl.java
- hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/test/MetricsAssertHelperImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerTableMetrics.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsTableLatencies.java
Note: This was a clean cherry-pick of https://github.com/apache/hbase/commit/8ff17c68e2fb71c818cd16e6d3445d0c2658798b. If there's a better way for a committer to simply cherry-pick that into branch-2.4, be my guest and we can close that. Happy to do whatever's easiest.
> HBASE-26860 Backport "HBASE-25681 Add a switch for server/table queryMeter" to branch-2.4

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionServerTracker.java
https://issues.apache.org/jira/browse/HBASE-26976
> HBASE-26976 Update related comments after HMaster can load the live RS infos from local region

- hbase-compression/hbase-compression-brotli/src/main/java/org/apache/hadoop/hbase/io/compress/brotli/BrotliCompressor.java
Due to a copy and paste error in BrotliCompressor#reinit we can reallocate a direct buffer instead of an on heap buffer. Not a functional problem right now but in all other cases the allocation is a heap buffer so could be a future surprise, and is in any case incorrect.
> HBASE-26992 Brotli compressor has unexpected behavior during reinitialization

- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
[HBASE-26989](https://issues.apache.org/jira/browse/HBASE-26989)
When running the tests locally, I see these runtime improvements:
`testNeedBalance`: from 120 seconds to 11 seconds
`testSloppyTablesLoadBalanceByTable` 27 seconds to <1 second
`testBalanceOfSloppyServers` 67 seconds to <1 second
I ran `testNeedBalance` 100 times locally, and the other two tests I ran 1000 times locally.
So total class `TestStochasticLoadBalancer` runtime reduces from 230 seconds to 31 seconds.
Additionally, we get more deterministic behavior, since tests are more likely to have consistent results with a max number of steps when compared to a max running time.
> HBASE-26989 TestStochasticLoadBalancer fixes for performance and consistency

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncMetaRegionLocator.java
Addendum extends the test case to cover both `RpcConnectionRegistry` and `ZKConnectionRegistry`.
> Forward-port "HBASE-26648 Improve fidelity of RegionLocator spans (addendum)" from branch-2 to master

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/BlockCacheTmpl.jamon
JIRA: HBASE-27000.
Block cache stats (Misses Caching) display error in RS web UI.
> HBASE-27000 Block cache stats (Misses Caching) display error in RS web UI

- src/main/asciidoc/_chapters/compression.adoc
Document the new compression codecs:
- The configuration keys used for setting the codec implementations for the various algorithms
- The provided compression codecs
- Default schema recommendations (LZ4)
- Default WAL value compression recommendations
> HBASE-26330 Document new provided compression codecs

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
JIRA: HBASE-27015.
A space is missing from the ServerManager log.
> HBASE-27015. Fix log format for ServerManager

- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
JIRA: HBASE-27003.
The logs in PerformanceEvaluation look a little confusing to new users, we should optimize the format.
Before:
After:
> HBASE-27003 Optimize log format for PerformanceEvaluation

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreEngine.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/replication/TestBadReplicationPeer.java
JIRA: HBASE-27020.
Fix spotless warn for master branch. We can see the spotless warn at https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4416/1/artifact/yetus-general-check/output/branch-spotless.txt. There are some compile tasks that fail because of this.
> HBASE-27020 Fix spotless warn for master branch

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/util/BlockIOUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/ReaderContext.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestBlockIOUtils.java
introduce a optional flag `hfile.pread.all.bytes.enabled` and default is disabled.
> HBASE-27013 Introduce read all bytes when using pread for prefetch

- hbase-compression/hbase-compression-aircompressor/src/main/java/org/apache/hadoop/hbase/io/compress/aircompressor/HadoopCompressor.java
- hbase-compression/hbase-compression-aircompressor/src/main/java/org/apache/hadoop/hbase/io/compress/aircompressor/HadoopDecompressor.java
- hbase-compression/hbase-compression-brotli/src/main/java/org/apache/hadoop/hbase/io/compress/brotli/BrotliCompressor.java
- hbase-compression/hbase-compression-brotli/src/main/java/org/apache/hadoop/hbase/io/compress/brotli/BrotliDecompressor.java
- hbase-compression/hbase-compression-lz4/src/main/java/org/apache/hadoop/hbase/io/compress/lz4/Lz4Compressor.java
- hbase-compression/hbase-compression-lz4/src/main/java/org/apache/hadoop/hbase/io/compress/lz4/Lz4Decompressor.java
- hbase-compression/hbase-compression-snappy/src/main/java/org/apache/hadoop/hbase/io/compress/xerial/SnappyCompressor.java
- hbase-compression/hbase-compression-snappy/src/main/java/org/apache/hadoop/hbase/io/compress/xerial/SnappyDecompressor.java
- hbase-compression/hbase-compression-xz/src/main/java/org/apache/hadoop/hbase/io/compress/xz/LzmaCompressor.java
- hbase-compression/hbase-compression-xz/src/main/java/org/apache/hadoop/hbase/io/compress/xz/LzmaDecompressor.java
- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdCompressor.java
- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdDecompressor.java
TRACE level logging is expensive enough to warrant removal. They were useful during development but are now just overhead.
Also we unnecessarily create new compressor and decompressor instances in the reset() methods for the Aircompressor and Lz4 codecs. Remove.
> HBASE-27019 Minor compression performance improvements

- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/trace/ProcedureSpanBuilder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestProcedureTracing.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/trace/OpenTelemetryClassRule.java
This one adds a tracing context to the Master's ProcedureV2 execution. This ties all the spans that result from a procedure execution back to a procedure by name.
> HBASE-26986 Trace a one-shot execution of a Master procedure

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/BufferedDataBlockEncoder.java
Created OnheapDecodedCell and OffheapDecodedExtendedCell objects with duplicate copy of ByteBuffer's underlying array instead of original ByteBuffer
> HBASE-26856:BufferedDataBlockEncoder.OnheapDecodedCell value can get corrupted

- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/trace/ProcedureSpanBuilder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestProcedureTracing.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/trace/OpenTelemetryClassRule.java
This one adds a tracing context to the Master's ProcedureV2 execution. This ties all the spans
that result from a procedure execution back to a procedure by name. Maybe in a follow-on issue, we
can serialize span context along with procedures and display procedure start/stop/retry events and
parent-child hierarchy in tracing visualization.
> Backport "HBASE-26986 Trace a one-shot execution of a Master procedure" to branch-2

- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/trace/ProcedureSpanBuilder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestProcedureTracing.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/trace/OpenTelemetryClassRule.java
This one adds a tracing context to the Master's ProcedureV2 execution. This ties all the spans
that result from a procedure execution back to a procedure by name. Maybe in a follow-on issue, we
can serialize span context along with procedures and display procedure start/stop/retry events and
parent-child hierarchy in tracing visualization.
> Backport "HBASE-26986 Trace a one-shot execution of a Master procedure" to branch-2.5

- dev-support/Jenkinsfile
Since the integration tests will eventually run on the large nodes w/k8s, have them start running their now to validate that we can schedule on the nodes.
Did a scan through our other jenkinsfiles and I believe everything except for `dev-support/adhoc_run_tests/Jenkinsfile` is strongly tied to the `hbase` label and thus will stay off of `hbase-large`. I also don't think we have that job configured to run at all, so maybe a follow on should delete it.
> HBASE-27006 Move nightly integration testing to new larger test node class.

- hbase-shell/src/main/ruby/shell.rb
- hbase-shell/src/main/ruby/shell/commands/list_liveservers.rb
JIRA: HBASE-27018.
To make it easier for us to query the living region Servers. We can add a command `list_liveservers`. There are already `list_deadServers` and `list_Decommissioned_regionServers`.
> HBASE-27018 Add a tool command list_liveservers

- pom.xml
Sometimes we want to run a build with a subset of unit tests to be executed over multiple modules, like:
mvn clean install -DskipITs -Dtest=Test*Encode*
which will execute some tests in common, some in server, etc. but not in checkstyle, which fails
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M6:test
(default-test) on project hbase-checkstyle:
No tests matching pattern "Test*Encode*" were executed!
(Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]
We already set `failIfNoTests` to false in the surefire configuration. Apparently `failIfNoSpecifiedTests` is also necessary to support the above. When `failIfNoSpecifiedTests` is specified in the configuration or on the command line, surefire behaves as expected.
This …
> HBASE-27050 Support unit test pattern matching again

- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSource.java
Trivial fix, give the unit more time, for slow or loaded test hosts.
> HBASE-27051 TestReplicationSource.testReplicationSourceInitializingMetric is flaky

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanAll.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRawAsyncTableScan.java
I've looped this test 100+ times and it doesn't reproduce locally for me. This is a patch that I think will make the test resilient to what happened in this stack trace. There are likely other places where this kind up exception unwrapping needs to happen, so there could be others...
> HBASE-27052 TestAsyncTableScanner.testScanWrongColumnFamily is flaky

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanAll.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRawAsyncTableScan.java
> Backport "HBASE-27052 TestAsyncTableScanner.testScanWrongColumnFamily is flaky" to branch-2

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanAll.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRawAsyncTableScan.java
> Backport "HBASE-27052 TestAsyncTableScanner.testScanWrongColumnFamily is flaky" to branch-2.5

- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaLargeCluster.java
[HBASE-27054](https://issues.apache.org/jira/browse/HBASE-27054)
Testing locally, I was able to see 100% pass rate with 15 second `maxRunningTime` after making these changes. So I changed to inherit from `StochasticBalancerTestBase` instead of `StochasticBalancerTestBase2`. The major difference in `StochasticBalancerTestBase2` for the purposes of this test is a 180 seconds `maxRunningTime` for the balancer, which should now be wasteful for this test. We can use the default 30 seconds, which we will inherit by using `StochasticBalancerTestBase`.
> HBASE-27054 testRegionReplicasOnLargeCluster flake fix

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/master/MetricsMasterSource.java
JIRA: HBASE-27047.
Fix typo for metric drainingRegionServers. `draininigRegionServers` -> `drainingRegionServers`.
> HBASE-27047 Fix typo for metric drainingRegionServers

- bin/draining_servers.rb
HBASE-21812 replaced a for-loop with an each block. Each block introduces a new scope, so a local variable defined inside it cannot be accessed afterwards.
```
NameError: undefined local variable or method `admin' for main:Object
getServerNames at /opt/khp/hbase/bin/draining_servers.rb:81
addServers at /opt/khp/hbase/bin/draining_servers.rb:88
<main> at /opt/khp/hbase/bin/draining_servers.rb:146
```
This commit defines the admin local variable in the current scope beforehand, so that we can still access it after the block.
> HBASE-27030 Fix undefined local variable error in draining_servers.rb

- hbase-http/src/main/java/org/apache/hadoop/hbase/http/HttpServer.java
- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RESTServer.java
- hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftServer.java
https://issues.apache.org/jira/browse/HBASE-27027
> HBASE-27027 Use jetty SslContextFactory.Server instead of deprecated SslContextFactory

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/CleanerChore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/DirScanPool.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/backup/TestHFileArchiving.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/backup/example/TestZooKeeperTableArchiveClient.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestCleanerChore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestHFileCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestHFileLinkCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestLogsCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/MasterRegionTestBase.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/TestMasterRegionCompaction.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/TestMasterRegionWALCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotManager.java
This avoids starvation when the archive directory is large and takes a long time
to iterate through.
Signed-off-by: Anoop Sam John <anoopsamjohn@apache.org>
Signed-off-by: Pankaj <pankajkumar@apache.org>
> Backport to branch-2, HBASE-26320 Implement a separate thread pool for the LogCleaner (#3712)

- conf/hbase-env.sh
tested locally and now standalone with these configuration `export HBASE_TRACE_OPTS="-Dotel.traces.exporter=jaegar -Dotel.metrics.exporter=none"` in `conf/hbase-env.sh` no longer failed
before the change, it's always using the default and create Otlp metrics exporter but it cannot be done.
```
[opentelemetry.auto.trace 2022-05-19 17:09:13:587 -0700] [grpc-default-executor-3] WARN io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.Status.asRuntimeException(Status.java:534)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.jav …
```
> HBASE-27055 Add additional comments when using HBASE_TRACE_OPTS with standalone mode

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
o reproduce the bug I've used hbase with hbase root dir pointing to s3 bucket and WAL dir pointing to HDFS. 2 phase bulkload was used:
Phase1 (Completed successfully):
hbase org.apache.hadoop.hbase.mapreduce.ImportTsv -Dimporttsv.separator=',' -Dimporttsv.bulk.output=output -Dimporttsv.columns=HBASE_ROW_KEY,name,department employees /tmp/test.csv
Phase2 (Failed with IllegalArgumentException on the RS side):
hbase org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles output employees
With the provided changes Phase2 was completed successfully.
> HBASE-27061 two phase bulkload is broken when SFT is in use.

- hbase-shell/src/main/ruby/jar-bootstrap.rb
Simple changes to jar-bootstrap.rb are required after switching the logger to Log4J v2.
Refer to https://stackoverflow.com/questions/23434252/programmatically-change-log-level-in-log4j2
> HBASE-26854 Shell startup logs a bunch of noise

- pom.xml
When building against Hadoop 3.3.3 and any future version of Hadoop incorporating reload4j the new Enforcer rule we have active in branch-2.5 and up to exclude other logging frameworks besides log4j2 will trigger. We need to add exclusions to prevent that from happening so the build will succeed.
Also exclude leveldbjni-all to avoid a LICENSE file generation error. hadoop-hdfs and hadoop-mapreduce are messy and export this among findbugs and other clutter. Anyway, better to exclude something we do not require than add an unnecessary supplemental model.
> HBASE-27065 Build against Hadoop 3.3.3

- pom.xml
When building against Hadoop 3.3.3 and any future version of Hadoop incorporating reload4j the new Enforcer rule we have active in branch-2.5 and up to exclude other logging frameworks besides log4j2 will trigger. We need to add exclusions to prevent that from happening so the build will succeed.
Also exclude leveldbjni-all to avoid a LICENSE file generation error. hadoop-hdfs and hadoop-mapreduce are messy and export this among findbugs and other clutter. Anyway, better to exclude something we do not require than add an unnecessary supplemental model.
> HBASE-27065 [branch-2] Build against Hadoop 3.3.3

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionVisualizerTmpl.jamon
The `Region Visualizer` display failed. Because the active master hostname is `localhost`.
Before the change:
After the change:
> HBASE-27066 The Region Visualizer display failed

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorkQueue.java
[ERROR] org.apache.hadoop.hbase.master.normalizer.TestRegionNormalizerWorkQueue.testTake  Time elapsed: 0.065 s  <<< 
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
at org.apache.hadoop.hbase.master.normalizer.TestRegionNormalizerWorkQueue.testTake(TestRegionNormalizerWorkQueue.java:211)
Caused by: java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
at org.apache.hadoop.hbase.master.normalizer.RegionNormalizerWorkQueue.take(RegionNormalizerWorkQueue.java:192) …
> HBASE-27064 CME in TestRegionNormalizerWorkQueue

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/BackupMasterStatusTmpl.jamon
JIRA: HBASE-27068.
When the active master has not yet been elected. We access the master web UI, a NPE will be thrown out. Assertion is now added, but assertion in production is disabled by default. We can use `Preconditions` instead.
> HBASE-27068 NPE occurs when the active master has not yet been elected

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReader.java
Reduce the log level of some logs in ReplicationSourceWALReader for the most frequent messages, related to adding entries, especially empty ones (in addEntryToBatch) and filtering (in filterEntry).
> HBASE-27079 Lower some DEBUG level logs in ReplicationSourceWALReader to TRACE

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionServerListTmpl.jamon
JIRA: HBASE-27037.
Display the region server state on the Web UI.
> HBASE-27037 Display the region server state on the Web UI

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegion.java
https://issues.apache.org/jira/browse/HBASE-27039
> HBASE-27039 Some methods of MasterRegion should be annotated for testing only

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractProtobufLogWriter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncProtobufLogWriter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/ProtobufLogWriter.java
Address the source compatibility problem caused by adding method to the LimitedPrivate(CONFIG) abstract class.
> HBASE-26680 Close and do not write trailer for the broken WAL writer(addendum)

- hbase-server/src/main/resources/hbase-webapps/regionserver/region.jsp
Add MOB info in web UI.
The web UI are as follows:
> HBASE-26962: Add mob info in web UI

- hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotManifest.java
force the use of default SFT when snapshotting mob regions
> HBASE-27017: MOB snapshot is broken when FileBased SFT is used

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/RegionServerListTmpl.jamon
> HBASE-27092 Regionserver table on Master UI is broken

- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/ChoreService.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/HBaseServerBase.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/MetaRegionLocationCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMasterCommandLine.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionServerTracker.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServerCommandLine.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/TestServerInternalsTracing.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerInternalsTracing.java
- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MasterAddressTracker.java
- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java
- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
As of this patch, now every span that's emitted in my unit test has a meaningful parent span, tied back to either a server activity or the ZKWatcher handler pool. PTAL.
> HBASE-26366 Provide meaningful parent spans to ZK interactions

- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/ChoreService.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/MetaRegionLocationCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMasterCommandLine.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionServerTracker.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServerCommandLine.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/TestServerInternalsTracing.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerInternalsTracing.java
- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MasterAddressTracker.java
- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java
- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
A backport of #4459 to branch-2.
> Backport "HBASE-26366 Provide meaningful parent spans to ZK interactions" to branch-2

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegion.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegionFlusherAndCompactor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestMasterObserver.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/TestMasterRegionFlush.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java
- hbase-shell/src/main/ruby/hbase/admin.rb
- hbase-shell/src/main/ruby/shell.rb
- hbase-shell/src/main/ruby/shell/commands/flush_master_store.rb
- hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
https://issues.apache.org/jira/browse/HBASE-27028
> HBASE-27028 Add a shell command for flushing master local region

- pom.xml
- update asciidoctor maven plugin to latest
- update the asciidoctor pdf dependency to latest
- allow the plugin to use its own version of jruby
tested with a local build via the jenkins script for site build.
> HBASE-27106 update asciidoctor site building.

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerAccounting.java
JIRA: HBASE-27117.
After [HBASE-15787](https://issues.apache.org/jira/browse/HBASE-15787), the return value type of RegionServerAccounting#isAboveHighWaterMark and RegionServerAccounting#isAboveLowWaterMark are no longer boolean.
> HBASE-27117 Update the method comments for RegionServerAccounting

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
This is a relatively simple change -- We were already fetching ClusterMetrics. This change adds `Option.TABLE_TO_REGIONS_COUNT` to that and then uses `clusterMetrics.getTableRegionStatesCount()` instead of MetaTableAccessor.
I couldn't think of any new tests to add here. There are substantial tests in TestClusterScopeQuotaThrottle, TestQuotaThrottle, and TestQuotaAdmin. I did some messing with the logic to prove that existing tests would have failed if there were a bug here. This is just a different implementation for an existing functionality, rather than a net new functionality to test.
> HBASE-26945 Quotas causes too much load on meta for large clusters

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/CleanerChore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SecureBulkLoadManager.java
In the deleteAction method of CleanerChore class, the delete variable cannot be printed out
`LOG.trace("Finish deleting {} under {}, deleted=", type, dir, deleted); `
> HBASE-27001 The deleted variable cannot be printed out

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
This was a straight-forward cherry-pick which I would typically just push directly. But I was for some reason having trouble running TestQuotaThrottle locally, so pushing this so that I can make use of the pre-commit hooks to verify that it's safe for this branch.
> HBASE-26945 Quotas causes too much load on meta for large clusters (branch-2 backport)

- hbase-common/src/main/java/org/apache/hadoop/hbase/util/ReflectionUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/HeapByteBufAllocator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/SimpleByteBufAllocator.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestNettyRpcServer.java
Support site configuration of the bytebuf allocator that Netty will use for `NettyRpcServer` channels. We do not allow the site operator to fine tune this but could. It would be particularly useful to allow preference of heap buffers where direct memory may be limited or utilized for other purposes. 
New property name is `hbase.netty.rpcserver.allocator`. Default is no value, which is equivalent to "pooled", which is our current default. Valid values are:
- `pooled`: use PooledByteBufAllocator
- `unpooled`: use UnpooledByteBufAllocator
- `heap`: use HeapByteBufAllocator, which is a PooledByteBufAllocator that preferentially allocates buffers on heap wherever possible
- `<class>`: If the value is none of the recognized labels, treat it as a class name implementing …
> HBASE-27111 Make Netty channel bytebuf allocator configurable.

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableRegionLocatorImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/HRegionLocator.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncNonMetaRegionLocator.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRegionLocationCaching.java
Backport required a separate impl for blocking client. Change is simple, but pushing PR to let test suite run
> HBASE-26790 getAllRegionLocations can cache locations with null hostname (branch-2 backport)

- hbase-endpoint/src/main/java/org/apache/hadoop/hbase/client/coprocessor/AggregationClient.java
- hbase-endpoint/src/test/java/org/apache/hadoop/hbase/client/coprocessor/TestAggregationClient.java
This simple PR introduces 2 new constructors. One allows for sharing a Connection as the issue describes, and the other allows for a totally connection-less instance. 
There weren't any tests for this class, so I added a very basic one that simply verifies the connection lifecycle is working as expected for the different constructors.
> HBASE-27060 Allow sharing connections between AggregationClient instances

- hbase-endpoint/src/test/java/org/apache/hadoop/hbase/client/coprocessor/TestAggregationClient.java
This should have been a relatively simple backport, but ran into some issues:
- in the original backport, i tested the change using `mvn clean verify -pl hbase-server -am`. I forgot that AggregationClient had moved to hbase-endpoint, so this erroneously made it seem like the backport was good (since it just didn't compile hbase-endpoint at all). But actually HBaseTastingUtil doesn't exist in branch-2*. 
- I fixed that with an addendum, but somehow my editor messed up the import grouping, so now it's failing due to spotless. 
Lesson learned: make sure to test the right modules if not doing a PR (i tried, but will be more careful next time), and make sure to run spotless:apply any time i make a non-cherrypick change.
Submitting this as a PR so i can run the full pre-commit checks and be …
> HBASE-27060 Addendum spotless fix

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/ByteBuffAllocator.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/nio/ByteBuff.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/nio/RefCnt.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/TestByteBuffAllocator.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/TestByteBuffAllocatorLeakDetection.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlockUnpack.java
First commit fixes the leak and adds a test.
Second commit adds ResourceLeakDetector to RefCnt. It's already added at the netty layer, and is expected to be low overhead. One can disable it (along with at the netty layer) by setting `-Dorg.apache.hbase.thirdparty.io.netty.leakDetection.level=DISABLED`. I don't really have time to do any specific perf tests right now. I could wrap it in a special `hbase.server.allocator.leakDetection.enabled` config, at the cost of a few extra factory methods in ByteBuff.java and RefCnt.java. Or otherwise I could revert that commit and we can handle it in a different jira.
> HBASE-27170 ByteBuffAllocator leak when decompressing blocks near minSizeForReservoirUse

- hbase-assembly/pom.xml
- pom.xml
- the agent jar dropped the `-all` classifier after 1.8.0
> HBASE-27172 Upgrade OpenTelemetry dependency to 1.15.0

- hbase-assembly/pom.xml
- pom.xml
- the agent jar dropped the `-all` classifier after 1.8.0
> Backport "HBASE-27172 Upgrade OpenTelemetry dependency to 1.15.0" to branch-2

- hbase-assembly/pom.xml
- pom.xml
- the agent jar dropped the `-all` classifier after 1.8.0
> Backport "HBASE-27172 Upgrade OpenTelemetry dependency to 1.15.0" to branch-2.5

- hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
- hbase-testing-util/pom.xml
- pom.xml
Signed-off-by: Xin Sun <ddupgs@gmail.com>
(cherry picked from commit 41972cb46017f84d39ce85c76121074e0f4b8bbb)
> HBASE-27148 Move minimum hadoop 3 support version to 3.2.3 (#4561)

- bin/hbase
- conf/hbase-env.sh
* Take advantage of the fact that OpenTelemetry can read its configuration from environment
variables and make use of this where possible, only falling back to passing properties into the
process launch configuration when it's necessary. DRY up tracing configuration and make it
easier to manage in a container environment.
* Replace `HBASE_TRACE_OPTS`, which used to act as both a feature flag and a baseline for
configuration shared across processes. Instead, use `HBASE_OTEL_TRACING_ENABLED` as a feature
flag, and let configuration reuse be handled via the environment variables that otel supports
naively.
* Add further explanation for how to write your configuration for our different deployment
modes (standalone, pseudo-distributed, fully distributed) and in different environments.
> HBASE-27182 Rework tracing configuration

- src/main/asciidoc/_chapters/ops_mgt.adoc
[Aliyun Object Storage Service](https://www.aliyun.com/product/oss)(Aliyun OSS) is widely used, particularly popular among China’s cloud users, and it provides cloud object storage for a variety of use cases. [Hadoop file system](http://hadoop.apache.org/docs/current/hadoop-aliyun/tools/hadoop-aliyun/index.html) supports OSS since version 2.9.1. Now, we can export and import snapshots using Aliyun object storage service(OSS).
Jira: https://issues.apache.org/jira/browse/HBASE-27190
> HBASE-27190 Add some docs about exporting and importing snapshots using Aliyun object storage service(OSS)

- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/BufferChain.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleRpcServerResponder.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleServerCall.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleServerRpcConnection.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestBufferChain.java
Replace `BufferChain#write(channel,int)` with a simpler `#write(channel)` implementation that does not attempt to "chunk" data to be written. This method was used exclusively by `SimpleRpcServer`. The code was unnecessarily complex and caused short writes when values were large, which were exposed by MAC verification failures when SASL is enabled, so was corrected and simplified. Any difference in performance from this change will be limited to `SimpleRpcServer`. Testing under load confirms the fix and does not show significant regression.
`SimpleRpcServer` and its related code is now also marked as `@Deprecated`.
> HBASE-27097 SimpleRpcServer is broken

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMultiRespectsLimits.java
TestMultiRespectLimits submits a put with an empty value. This appears to not be what was intended.
> HBASE-27161 Improve TestMultiRespectsLimits

- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestNettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSecureNettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSecureSimpleRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSimpleRpcServer.java
Add test coverage for `SimpleRpcServer`.
Improve the way we test both `SimpleRpcServer` and `NettyRpcServer`: Use `LoadTestKVGenerator` to generate random values with varying sizes between 1000 bytes and 1M bytes, and also to verify them when reading the values back.
Add secure test coverage for both `SimpleRpcServer` and `NettyRpcServer.`
> HBASE-27194 Add test coverage for SimpleRpcServer

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestChecksum.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlock.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlockUnpack.java
Tests a different fix for HBASE-27053, based on analysis I posted in the issue.
> HBASE-27053 IOException during caching of uncompressed block to the block cache

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
I wasn't sure if an addendum was the way to go here, so let me know if a new jira would be better
> HBASE-27205 Fix tests that rely on EnvironmentEdgeManager in branch-2.4 (addendum)

- hbase-client/src/main/java/org/apache/hadoop/hbase/filter/RegexStringComparator.java
Changing the encoding of JoniRegexEngine to NonStrictUTF8Encoding in RegexStringComparator.
https://issues.apache.org/jira/browse/HBASE-27219
> HBASE-27219 Change JONI encoding in RegexStringComparator

- hbase-client/src/main/java/org/apache/hadoop/hbase/security/HBaseSaslRpcClient.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/security/TestHBaseSaslRpcClient.java
Revert "HBASE-24579: Failed SASL authentication does not result in an exception on client side (#1921)"
This reverts commit bd79c4065ccb13a5e217d844376b3e7b9489d2fe.
When Kerberos authentication succeeds, on the server side, after receiving the final SASL token from the client, we simply wait for the client to continue by sending the connection header. After HBASE-24579, on the client side, an additional `readStatus()` was added, which mistakenly assumes that after negotiation has completed a status code will be sent. However when authentication has succeeded the server will not send one. As a result the client will hang and only throw an exception when the configured read timeout is reached, which is 20 seconds by default.
We cannot unilaterally send the expected additional status code …
> HBASE-27204 BlockingRpcClient will hang for 20 seconds when SASL is enabled after finishing negotiation

- pom.xml
This pull request changes some Java flags to fix test issues with OpenJDK 17.
An missing export is added, and the option  --illegal-access=permit is removed since
it is ignored in OpenJDK 17
OpenJDK 17 is the current version with long time support, so it is a better option than version 16 or 18 for current projects. 
There are still some failures in org.apache.hadoop.hbase.http.TestProxyUserSpnegoHttpServer, but these ones are unrelated to this pull request or OpenJDK 17.
> HBASE-27179 Fix build under OpenJDK 17

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketAllocator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCache.java
Example output (with log4j log formatting prefixes removed for clarity):
```
Bucket allocator statistics follow:
Free bytes=5325249536; used bytes=35391673344; total bytes=40716922880; waisted bytes=355258368; completelyFreeBuckets=843
Object size 33792; used=195000; free=114; total=195114; waisted bytes=10741760; full buckets=1048
Object size 66560; used=275656; free=46; total=275702; waisted bytes=114128896; full buckets=2932
Object size 99328; used=76785; free=12; total=76797; waisted bytes=46185472; full buckets=1218
Object size 132096; used=6090; free=20; total=6110; waisted bytes=11315200; full buckets=129
Object size 525312; used=3303; free=8; total=3311; waisted bytes=155653120; full buckets=300
Object size 787456; used=152; free=2; total=154; waisted bytes=17233920; full …
```
> HBASE-27225 Add BucketAllocator bucket size statistic logging

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCacheRefCnt.java
This change mirrors how it works in LruBlockCache and the other implementations. A `evictedByEvictionProcess` boolean is added to doEvictBlock and blockEvicted, which wraps the `cacheStats.evicted` calls. Then, all calls to those methods are set to pass in `false` except the calls originating from the `freeSpace(String why)` method.
There are various edge cases which can result in a cache eviction. It's hard to test all of those, but I added a test which covers the 3 main cases.
> HBASE-27229 BucketCache statistics should not count evictions by hfile

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/BlockCacheTmpl.jamon
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCacheUtil.java
I kept around the old warning, but moved it to near the "View as Json" links, since that's where it makes sense now.
Here's how it looks on one of my prod regionservers:
> HBASE-27257 Remove unnecessary usage of CachedBlocksByFile from RS UI

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheConfig.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BufferedBucketCache.java
https://issues.apache.org/jira/browse/HBASE-26681
> HBASE-26681 Introduce a little RAMBuffer for bucketcache to reduce gc and improve throughput

- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/hfile/trace/HFileContextAttributesBuilderConsumer.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/util/BlockIOUtils.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchExecutor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestBlockIOUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetch.java
Take another pass through tracing of the read path, make adjustments accordingly. One of the major concerns raised previously is that we create a span for every block access. Start by simplifying this to trace events and see what else comes up.
Block-level and stream-level interactions are represented as span events with attached attributes (that's otel terminology for "structured logs", attached to the spans). I made an effort to surface information that an operator might be interested in while diagnosing slow read performance, and details that the previous generation of dev had already seen fit to surface via trace-level logging. We no longer emit spans for `HFileReaderImpl.readBlock`. I hope this is a good compromise between visibility and performance.
Also added a span context for …
> HBASE-27153 Improvements to read-path tracing

- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/hfile/trace/HFileContextAttributesBuilderConsumer.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/util/BlockIOUtils.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchExecutor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestBlockIOUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetch.java
> Backport "HBASE-27153 Improvements to read-path tracing" to branch-2

- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/AttributesMatchers.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/hfile/trace/HFileContextAttributesBuilderConsumer.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/util/BlockIOUtils.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchExecutor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestBlockIOUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetch.java
> Backport "HBASE-27153 Improvements to read-path tracing" to branch-2.5

- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStatus.java
https://issues.apache.org/jira/browse/HBASE-27269
> HBASE-27269 The implementation of TestReplicationStatus.waitOnMetricsReport is incorrect

- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcClient.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcConnection.java
- hbase-common/pom.xml
- hbase-common/src/main/java/org/apache/hadoop/hbase/exceptions/KeyManagerException.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/exceptions/SSLContextException.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/exceptions/TrustManagerException.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/exceptions/X509Exception.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/KeyStoreFileType.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/BaseX509ParameterizedTestCase.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestX509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509KeyType.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContext.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestHelpers.java
- hbase-server/pom.xml
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestNettyIPCSsl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestNettyIPCSslFailure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestTlsIPC.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestTlsWithKerberos.java
- pom.xml
Based on @Apache9 's suggestions and the previous PR #4125 the following changes have been incorporated:
- `flush()` call handling is fixed in `BufferCallBeforeInitHandler`, so it will not block the SSL handshake,
- `SSLContext` and `SSLEngine` are now based on Netty's `SslContextBuilder` class. In order to fully take advantage of that I had to add ByteBufAllocator config to the client side like we already have in the server,
- `SSLContext` is cached in `X509Util` for client and server. This is because I'd like to add FileWatchers for keystore/truststore in order to easily renew certificates in a running cluster.
cc @bbeaudreault @meszibalu @joshelser
> HBASE-26666 Add native TLS encryption support to RPC server/client

- bin/hbase
- bin/hbase.cmd
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileListFile.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileListFilePrettyPrinter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/storefiletracker/TestStoreFileListFilePrinter.java
This is the tool to read the content of StoreFileTrackerFile in plain english.
The tool can be run by giving direct path to the storefiletrackerfile, by specifying -f option
OR
by providing information like region name(-r option), table name (-t option) and column family (-cf option)
> HBASE-27265 : Tool to read StoreFileTrackerFile

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableSourceImpl.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregate.java
- hbase-hadoop-compat/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperStub.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BloomFilterMetrics.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CompoundBloomFilter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CompoundBloomFilterWriter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStoreFile.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregateImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Store.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreEngine.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/BloomFilterFactory.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsTableAggregate.java
- Add static index/bloom sizes
- Add metrics for bloom requests and negative results
Combined these together are very useful for determining whether you should add bloom filters (if eligible requests is high) and whether they are worth the cost (compare bloom size to bloom request/negative result count)
I added a test in TestHStore because I mostly wanted to verify that these new request/negative/eligible counts make it through the entire stack end-to-end, since it involves plumbing into a few classes.
> HBASE-27241 Add metrics for evaluating cost and effectiveness of bloom filters

- hbase-shaded/pom.xml
https://issues.apache.org/jira/browse/HBASE-27292
```
$ mvn clean install -DskipTests -Phadoop-3.0 -Dhadoop-three.version=3.3.4
...
[ERROR] Found artifact with unexpected contents: '/home/rocky/srcs/hbase/hbase-shaded/hbase-shaded-mapreduce/target/hbase-shaded-mapreduce-3.0.0-alpha-4-SNAPSHOT.jar'
Please check the following and either correct the build or update
the allowed list with reasoning.
okhttp3/
okhttp3/Request$Builder.class
...
kotlin/
kotlin/collections/
kotlin/collections/ArraysUtilJVM.class
...
```
> HBASE-27292. Fix build failure against Hadoop 3.3.4 due to added dependency on okhttp.

- hbase-common/src/main/java/org/apache/hadoop/hbase/PrivateCellUtil.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/TableName.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePrettyPrinter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/mob/DefaultMobStoreCompactor.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/mob/DefaultMobStoreFlusher.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/mob/MobFileCleanerChore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/mob/MobUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HMobStore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStoreFile.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileWriter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/FaultyMobStoreCompactor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobCompactionOptMode.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobCompactionOptRegionBatchMode.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobCompactionRegularRegionBatchMode.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobCompactionWithDefaults.java
* Reorganize MOB compaction tests for more reuse.
* Add tests for mob compaction after snapshot clone operations
* note the original table used to write a given mob hfile and use that to find it later.
Signed-off-by: Esteban Gutierrez <esteban@apache.org>
---
Ported to branch-2 for [HBASE-27154](https://issues.apache.org/jira/browse/HBASE-27154)
Co-authored-by: Andrew Purtell <apurtell@apache.org>
> HBASE-23723 Ensure MOB compaction works in optimized mode after snapshot clone

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCompressedSizePredicator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileWriterImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PreviousBlockCompressionRatePredicator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/UncompressedBlockSizePredicator.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStoreFile.java
Here we propose two additional properties,"hbase.block.size.limit.compressed" and  "hbase.block.size.max.compressed" that would allow for consider the compressed size (if compression is in use) for delimiting blocks during hfile writing. When compression is enabled, certain datasets can have very high compression efficiency, so that the default 64KB block size and 10GB max file size can lead to hfiles with very large number of blocks. 
In this proposal, "hbase.block.size.limit.compressed" is a boolean flag that switches to compressed size for delimiting blocks, and "hbase.block.size.max.compressed" is an int with the limit, in bytes for the compressed block size, in order to avoid very large uncompressed blocks (defaulting to 320KB).
> HBASE-27264 Add options to consider compressed size when delimiting blocks during hfile writes

- hbase-server/src/main/java/org/apache/hadoop/hbase/mob/DefaultMobStoreCompactor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/FaultyMobStoreCompactor.java
> Backport "HBASE-24163 MOB compactor implementations should use format specifiers when calling String.format" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/mob/DefaultMobStoreCompactor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/FaultyMobStoreCompactor.java
> Backport "HBASE-24163 MOB compactor implementations should use format specifiers when calling String.format" to branch-2.5

- hbase-shell/src/main/ruby/hbase/admin.rb
https://issues.apache.org/jira/browse/HBASE-27295
> HBASE-27295 Correct the comment of list_deadservers method in admin.rb

- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
HBASE-27268 In trace log mode, the client does not print callId/startTime and the server does not print receiveTime, so fix it.
> HBASE-27268 In trace log mode, the client does not print callId/startTime and the server does not print receiveTime

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/aes/CommonsCryptoAES.java
Add “commons.crypto.stream.buffer.size” configuration  in hbase when doing encryption through commonsCryptoAES.
> HBASE-27089 Add “commons.crypto.stream.buffer.size” configuration

- hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java
https://issues.apache.org/jira/browse/HBASE-27246
> HBASE-27246 RSGroupMappingScript#getRSGroup has thread safety problem

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/TableDescriptorChecker.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestAssignmentManagerMetrics.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestOpenRegionFailedMemoryLeak.java
Signed-off-by: Bryan Beaudreault <bbeaudreault@apache.org>
Conflicts:
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
> HBASE-25922 - Disabled sanity checks ignored on snapshot restore (#4533)

- RELEASENOTES.md
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/CompactSplit.java
> Backport 'HBASE-27152 Under compaction mark may leak (#4725)' to branch-2.5

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
https://issues.apache.org/jira/browse/HBASE-27335
> HBASE-27335 HBase shell hang for a minute when quiting

- bin/hbase
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcClient.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestX509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContext.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContextProvider.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestHelpers.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/AbstractTestTlsRejectPlainText.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestNettyTlsIPC.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestSaslTlsIPC.java
cc @bbeaudreault @Apache9 @apurtell
> HBASE-27342 Use Hadoop Credentials API to retrieve passwords of TLS key/trust stores

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBatchRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncScanSingleRegionRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/MetricsConnection.java
Enable metric reporting on backoff time when a server is overloaded.
> HBASE-26809: Report client backoff time for server overloaded

- bin/hbase
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcClient.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestX509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContext.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContextProvider.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestHelpers.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/AbstractTestTlsRejectPlainText.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestNettyTlsIPC.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestSaslTlsIPC.java
Signed-off-by: Balazs Meszaros <meszibalu@apache.org>
> HBASE-27342 Use Hadoop Credentials API to retrieve passwords of TLS key/trust stores (#4747)

- src/site/site.xml
The content is in the website git repo but there's no menu on our homepage.
> HBASE-25563 Add "2.4 Documentation" to the website

- hbase-asyncfs/pom.xml
- hbase-endpoint/pom.xml
- hbase-examples/pom.xml
- hbase-hadoop2-compat/pom.xml
- hbase-http/pom.xml
- hbase-mapreduce/pom.xml
- hbase-rest/pom.xml
- hbase-server/pom.xml
- hbase-shaded/hbase-shaded-testing-util/pom.xml
- pom.xml
Make it so our published poms carry the minimum needed to run
an hbase; the published pom has no profiles -- the profiles
specified at build time are resolved, their dependencies inlined,
and then they are stripped -- and no build-time, or plugins
dependencies or properties, etc. Resultant poms have explicit
hadoop lib versions baked in -- no more being able to choose
hbase with hadoop2 or haddop3 at downstream build time by setting
a '-Dhadoop.profile=X.0'.
Pattern is to add profiles when none in sub-modules when
the flatten plugin complains it can't resolve an hadoop
dependency's 'version' (e.g. hadoop-common, hadoop-hdfs).
Adding the hadoop-2.0 and hadoop-3.0 profiles in the sub-module
make it so the flatten plugin can figure 'hadoop.version'
definitively.
Another spin on the above …
> HBASE-27340 Artifacts with resolved profiles

- hbase-asyncfs/pom.xml
- hbase-balancer/pom.xml
- hbase-endpoint/pom.xml
- hbase-examples/pom.xml
- hbase-hadoop-compat/pom.xml
- hbase-http/pom.xml
- hbase-mapreduce/pom.xml
- hbase-procedure/pom.xml
- hbase-rest/pom.xml
- hbase-server/pom.xml
- hbase-shaded/hbase-shaded-testing-util/pom.xml
- pom.xml
(Forward port from branch-2; simplified by the fact that there
is no hadoop-2.0 profile on master branch)
Make it so our published poms carry the minimum needed to run
an hbase; the published pom has no profiles -- the profiles
specified at build time are resolved, their dependencies inlined,
and then they are stripped -- and no build-time, or plugins
dependencies or properties, etc. Resultant poms have explicit
hadoop lib versions baked in -- no more being able to choose
hbase with hadoop2 or haddop3 at downstream build time by setting
a '-Dhadoop.profile=X.0'.
Pattern is to add profiles when none in sub-modules when
the flatten plugin complains it can't resolve an hadoop
dependency's 'version' (e.g. hadoop-common, hadoop-hdfs).
Adding the profile in the sub-module make it so the flatten …
> HBASE-27340 Artifacts with resolved profiles (#4740)

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePrettyPrinter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFilePrettyPrinter.java
Wraps the existing codahale Histogram in a KeyValueStats object. This object tracks the global min and max sizes for the statistic, since Histogram's is subject to sampling. Additionally adds a new `-d` argument which enables printing of detailed size range counts. This can be useful for further visualizing the distribution of sizes. 
Below is an example form a real HFile. Prior to this patch, the max value shown was only 25k due to the sampling done by Histogram. Additionally, the new buckets (printed when `-d` is passed) make it easy to see that there are actually a few doze quite large rows in this file.
```
Stats:
Key length:
min = 43
max = 137
mean = 104.97
stddev = 25.93
median = 105.00
75% <= 137.00
95% <= 137.00
98% <= 137.00
99% <= 137.00
99.9% <= 137.00
count = 852277
0 <= 10 …
```
> HBASE-27224 HFile tool statistic sampling produces misleading results

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/BCFKSFileLoader.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/FileKeyStoreLoader.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/FileKeyStoreLoaderBuilderProvider.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/JKSFileLoader.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/KeyStoreLoader.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/PEMFileLoader.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/PKCS12FileLoader.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/PemReader.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/StandardTypeFileKeyStoreLoader.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/AbstractTestX509Parameterized.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestBCFKSFileLoader.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestFileKeyStoreLoaderBuilderProvider.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestJKSFileLoader.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestKeyStoreFileType.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestPEMFileLoader.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestPKCS12FileLoader.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestX509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContext.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContextProvider.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestHelpers.java
Another backport from the ZooKeeper project which adds autodetection of keystore/truststore file types as well as BCFKS format support.
Lots of changes on the testing side unfortunately. I had to refactor the ported classed to take advantage of @Apache9 's x509 test context provider.
cc @bbeaudreault @Apache9 @meszibalu
> HBASE-27346 Autodetect key/truststore file type from file extension

- hbase-client/src/main/java/org/apache/hadoop/hbase/HColumnDescriptor.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ColumnFamilyDescriptor.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ColumnFamilyDescriptorBuilder.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestColumnFamilyDescriptorBuilder.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/IndexBlockEncoding.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileContext.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileContextBuilder.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockIndexChunk.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlockIndex.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileIndexBlockEncoder.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileIndexBlockEncoderImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileInfo.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileWriterImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/NoOpIndexBlockEncoder.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileTrackerBase.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlockIndex.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileWriterV3.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileWriterV3WithDataEncoders.java
> HBASE-27314 Make index block be customized and configured

- hbase-protocol-shaded/src/main/protobuf/PrefetchPersistence.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCacheKey.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheConfig.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchExecutor.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchProtoUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetchRSClose.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestPrefetchPersistence.java
Jira link: https://issues.apache.org/jira/browse/HBASE-27313 
Summary:
Persist list of Hfiles names for which prefetch is completed when persist for in-memory bucket cache mapping state is enabled
We need to persist the Set, which contains a list of all the HFiles for which the prefetch has completed along with the In-memory state of the bucket cache so that when we restart and if any prefetch is scheduled again for the same HFile and we already have the in-memory state retrieved, we can skip the prefetch for it.
> HBASE-27313: Persist list of Hfiles names for which prefetch is done

- src/main/asciidoc/_chapters/security.adoc
TLS docs.
cc @Apache9 @bbeaudreault @meszibalu @petersomogyi @joshelser
> HBASE-27226 Document native TLS support in Netty RPC

- bin/hbase
It is due to the fact that [read -r -a CMD_ARGS <<< "$@" ](https://github.com/apache/hbase/blob/master/bin/hbase#L878) in the hbase script would split command line args after expansion of `$@` array (i.e. `"$@"`) . Instead a straightforward array copy can be used.
> HBASE-27352 - Quoted string argument with spaces passed from command line are propagated wrongly to the underlying java class

- bin/hbase
…line are propagated wrongly to the underlying java class (#4754)
> Backport "HBASE-27352 - Quoted string argument with spaces passed from command …" to branch-2

- bin/hbase
…line are propagated wrongly to the underlying java class (#4754)
> Backport "HBASE-27352 - Quoted string argument with spaces passed from command …" to branch-2.5

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileListFilePrettyPrinter.java
This is to rectify the columnfamily argument from optional to mandatory. In the sysout message it is wrongly put as optional parameter but it is actually a mandatory parameter. Also better way to declare as a string and reusing in multiple places.
> HBASE-27317 : Storefiletracking : Rectifying the option for columnfamily as mandatory

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/HBaseServerBase.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/RegionMover.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterUseIp.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerUseIp.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestRegionMoverUseIp.java
https://issues.apache.org/jira/browse/HBASE-27304
> HBASE-27304 Support using IP to expose master/rs servers for some special scenarios

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/HBaseHostnameVerifier.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/HBaseTrustManager.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestHBaseHostnameVerifier.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestHBaseTrustManager.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestX509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContext.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestHelpers.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/AbstractTestMutualTls.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestMutualTlsClientSide.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestMutualTlsServerSide.java
Recreating https://github.com/apache/hbase/pull/4724 due to build issues
cc @Apache9
> HBASE-27280 Add mutual authentication support to TLS

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorkQueue.java
Concurrent modification in RegionNormalizerWorkQueue
> HBASE-27384 Backport HBASE-27064 in 2.4

- hbase-http/src/main/java/org/apache/hadoop/hbase/http/prometheus/PrometheusHadoopServlet.java
- hbase-http/src/test/java/org/apache/hadoop/hbase/http/prometheus/TestPrometheusServlet.java
You can access metrics description while using '/prometheus' endpoint via "description=true" URL parameter.
Example: `http://HOSTNAME:16010/prometheus?description=true`
Apache JIRA: https://issues.apache.org/jira/browse/HBASE-27395
> HBASE-27395 Adding description to Prometheus metrics

- pom.xml
Jettison versions <= 1.5.0 are subject to CVE-2022-40149 and CVE-2022-40150.
Move jettison.version to 1.5.1.
> HBASE-27424 Upgrade Jettison for CVE-2022-40149/40150

- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/BlockingRpcConnection.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcConnection.java
Include the remote server name in the logged exception message when the connection setup fails in BlockingRpcConnection.
Add an equivalent log line in NettyRpcConnection.
> HBASE-27339 Improve sasl connection failure log message to include server

- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MiniZooKeeperCluster.java
Link to JIRA: https://issues.apache.org/jira/browse/HBASE-27420
Add a provision to allow zk to listen for client connections on non-loopback IP.
> HBASE-27420 Allow non-loopback for zk standalone server in minizkcluster

- hbase-replication/src/main/java/org/apache/hadoop/hbase/replication/ReplicationQueueStorage.java
- hbase-replication/src/main/java/org/apache/hadoop/hbase/replication/TableReplicationQueueStorage.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/master/ReplicationLogCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/master/TestReplicationLogCleaner.java
https://issues.apache.org/jira/browse/HBASE-27405
> HBASE-27405 Fix the replication hfile/log cleaner report that the replication table does not exist

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java
[HBASE-27159](https://issues.apache.org/jira/browse/HBASE-27159)
> HBASE-27159 Emit source metrics for BlockCacheExpressHitPercent

- hbase-rest/src/main/resources/hbase-webapps/rest/rest.jsp
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/RSStatusTmpl.jamon
- hbase-server/src/main/resources/hbase-webapps/master/header.jsp
- hbase-server/src/main/resources/hbase-webapps/regionserver/header.jsp
- hbase-thrift/src/main/resources/hbase-webapps/thrift/thrift.jsp
Before this change, Prometheus metrics were only accessible via the '/prometheus' endpoint.
I made changes in the UI, so instead of _Metrics Dump_ there's a dropdown menu called _Metrics_ with the JMX and Prometheus metrics.
I also included the metrics description, so there are four endpoints available from there:
- JMX
- JMX with description 
- Prometheus
- Prometheus with description
**Apache JIRA:** https://issues.apache.org/jira/browse/HBASE-27406
> HBASE-27406 Make "/prometheus" endpoint accessible from HBase UI

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheConfig.java
Apache Jira:  https://issues.apache.org/jira/browse/HBASE-27363
Summary:
1. Change the config key for PREFETCH_PERSISTENCE_PATH_KEY to hbase.prefetch.file.list.path 
2. Fix the spotbugs issue mentioned in https://issues.apache.org/jira/browse/HBASE-27313
> HBASE-27363: Fix the config key PREFETCH_PERSISTENCE_PATH_KEY and spotbugs

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/metrics2/lib/DynamicMetricsRegistry.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsTableMetricsMap.java
the method removeHistogramMetrics will cause the metricsMap leak!
because the put op in the map is the baseName but the remove is not , the origin code add the histogramSuffixe follow the baseName when remove.
> HBASE-27440 fix table HistogramMetrics leak in table metrics map

- hbase-compression/hbase-compression-aircompressor/pom.xml
- hbase-compression/hbase-compression-brotli/pom.xml
The brotli4j and aircompressor dependencies don't have s390x arch support yet. Even though aircompressor is pure java, it only supports little-endian right now. 
This PR adds profiles to automatically set skipTests for `hbase-compression-aircompressor` and `hbase-compression-brotli` on s390x so builds can complete successfully.
> HBASE-27167 s390x: Skip tests on unsupported compression libs

- dev-support/create-release/hbase-rm/Dockerfile
- dev-support/create-release/prepend_changes.py
- dev-support/create-release/release-build.sh
- dev-support/create-release/release-util.sh
Also upgrade our Dockerfile for release scripts to use ubuntu 22.04, maven 3.8.6 and yetus 0.14.1.
Use python3 as much as possible.
> HBASE-27449 Use xmllint to parse version and revision in release scripts

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestListTablesByState.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java
- hbase-shell/src/main/ruby/hbase/admin.rb
- hbase-shell/src/main/ruby/shell.rb
- hbase-shell/src/main/ruby/shell/commands/list_disabled_tables.rb
- hbase-shell/src/main/ruby/shell/commands/list_enabled_tables.rb
- hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestListTablesShell.java
- hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestShell.java
- hbase-shell/src/test/ruby/shell/list_tables_test.rb
- hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
https://issues.apache.org/jira/browse/HBASE-27444
> HBASE-27444 Add tool commands list_enabled_tables and list_disabled_tables

- dev-support/create-release/README.txt
- dev-support/create-release/do-release-docker.sh
- dev-support/create-release/mac-sshd-gpg-agent/Dockerfile
- dev-support/create-release/release-util.sh
This is... a solution. It's probably fine for running on hardware you own with a source repository you trust. I'm not sure it's wise when running on a remote build machine...
> HBASE-27312 Update create-release to work with maven-gpg-plugin-3.0.1 and gnupg >= 2.1.x

- dev-support/hbase-vote.sh
With a small change, the hbase-vote.sh script can be used to verify release candidates produced from the hbase-thirdparty repository. Probably more could be done that is specific to this project's release artifacts, but this minor change enables the basics.
> HBASE-27477 Tweak hbase-vote.sh to support hbase-thirdparty

- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcClient.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/FileChangeWatcher.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/TestFileChangeWatcher.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContext.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestNettyTLSIPCFileWatcher.java
This patch is the port of ZooKeeper's FileWatcher's functionality which we can take advantage to detect changes in truststore / keystore files for TLS. Cert / key renewal processes don't need HBase services to be restarted with this patch.
cc @bbeaudreault @Apache9
> HBASE-27347 Port FileWatcher from ZK to autodetect keystore/truststore changes in TLS connections

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/DumpReplicationQueues.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AbstractFSWALProvider.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestDumpReplicationQueues.java
https://issues.apache.org/jira/browse/HBASE-27217
> HBASE-27217 Revisit the DumpReplicationQueues tool

- hbase-server/pom.xml
- hbase-server/src/test/java/org/apache/hadoop/hbase/monitoring/TestTaskMonitor.java
- pom.xml
`testClone` is detected as flaky by [NonDex](https://github.com/TestingResearchIllinois/NonDex) since the origin task monitor and the cloned one are represented as JSON objects, which are in a non-deterministic order. Therefore, I used JSONAssert to check if they are equal instead.
> HBASE-27479 fix flaky test testClone in TestTaskMonitor

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
This is just a very simple logging change to ensure that we always print as much info as we have available.
The biggest actual affect is that the `HFile:` section will now always be printed. The other components are optional and in my experience only available in HFileWriter _not_ HFileReader. So I think they'd only show up if cacheOnWrite is enabled and fails to allocate a block while writing blocks to a storefile. In my experience I've never seen them show up, because we don't have cacheOnWrite enabled.
The [original implementation](https://github.com/apache/hbase/pull/3840/files?diff=split&w=0#diff-b75abcdb76c582e16144df3a9bf2ddbc8fd0814c06190c33503a2c1cb365273cL1012) had a similar fallback which was lost in the most recent cleanup.
> HBASE-27408 Improve BucketAllocatorException log to always include HFile name

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/MergeNormalizationPlan.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/NormalizationPlan.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/RegionNormalizerWorker.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SplitNormalizationPlan.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestRegionNormalizerWorker.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
This PR adds the new setting `hbase.normalizer.plans_size_limit.mb`. This setting limit the number of plans processed by RegionNormalizerWorker, by forcing it to stop processing plans once the cumulative region size limits are exceeded.
> HBASE-27496 Optionally limit the cumulative size of normalization plans produced by SimpleRegionNormalizer

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/CleanerChore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleaner/DirScanPool.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/backup/TestHFileArchiving.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/backup/example/TestZooKeeperTableArchiveClient.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestCleanerChore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestHFileCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestHFileLinkCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestLogsCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/MasterRegionTestBase.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/TestMasterRegionCompaction.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/TestMasterRegionWALCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotManager.java
This avoids starvation when the archive directory is large and takes a long time to iterate through.
Signed-off-by: Anoop Sam John <anoopsamjohn@apache.org>
Signed-off-by: Pankaj <pankajkumar@apache.org>
> HBASE-26320 Implement a separate thread pool for the LogCleaner

- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcClient.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/FileChangeWatcher.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/TestFileChangeWatcher.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContext.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestNettyTLSIPCFileWatcher.java
Backport of https://github.com/apache/hbase/commit/047f4e22e0271ab0dfbf6e7843ae37c008c57c69
> HBASE-27347 Port FileWatcher from ZK to autodetect keystore/truststore changes in TLS connections (branch-2)

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRequestFutureImpl.java
In this one instance, the meta cache dropping exception metric is not tracked. 
cc: @bbeaudreault
> HBASE-27494: Fix missing meta cache dropping exception metrics

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/MetricsConnection.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestMetricsConnection.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/ClientPushbackTestBase.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestClientOperationTimeout.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMetaCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMultiActionMetricsFromClient.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestReplicasClient.java
Signed-off-by: David Manning <67607031+d-c-manning@users.noreply.github.com>
> HBASE-27466: Making metrics instance containing one or more connections. (#4874)

- dev-support/Jenkinsfile_GitHub
- dev-support/jenkins_precommit_github_yetus.sh
1. Added changerequest() condition to create builds for PRs
2. Removed the current shell script clause that skips non-PR builds
> HBASE-22924 GitHUB PR job should use when clause to filter to just PRs

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRequestFutureImpl.java
Batch requests submitted via AsyncProcess can fail if the pool is too small or backing region servers are overloaded. Currently, this will result in a meta cache clear which can further exacerbate the problem. Here we special case the exception to no clear the cache. 
cc: @bbeaudreault
> HBASE-27491: do not clear cache on RejectedExecutionException

- hbase-http/src/main/java/org/apache/hadoop/hbase/http/prometheus/PrometheusHadoopServlet.java
- hbase-http/src/test/java/org/apache/hadoop/hbase/http/prometheus/TestPrometheusServlet.java
In this change I implemented the query feature for the Prometheus metrics
**Apache JIRA:** https://issues.apache.org/jira/browse/HBASE-27435
> HBASE-27435 Make Prometheus metrics queryable

- hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutput.java
- hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/util/RecoverLeaseFSUtils.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
I am new to hbase and I'm trying to fix some comment sytax errors while reading the source code.
> HBASE-27530 Fix comment syntax errors

- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/MonitoredRPCHandlerImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/MonitoredTaskImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/TaskMonitor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestCallRunner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestFifoRpcScheduler.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestSimpleRpcScheduler.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/monitoring/TestTaskMonitor.java
~Simple null check to prevent the following spam when a task does not have a status.~ 
Simple changes to prevent NPE spam in hmaster logs 
- Initialize the status and description when new MonitoredTasks are created 
- Do not allow null statuses or descriptions to be set
```
[RpcServer.default.FPBQ.Fifo.handler=29,queue=2,port=60000] ERROR org.apache.hadoop.hbase.ipc.RpcServer: Unexpected throwable object  
java.lang.NullPointerException    
at org.apache.hadoop.hbase.shaded.protobuf.generated.ClusterStatusProtos$ServerTask$Builder.setStatus(ClusterStatusProtos.java:14352)    
at org.apache.hadoop.hbase.shaded.protobuf.ProtobufUtil.toServerTask(ProtobufUtil.java:3565)    
at org.apache.hadoop.hbase.ClusterMetricsBuilder.lambda$toClusterStatus$4(ClusterMetricsBuilder.java:80)    
at …
```
> HBASE-27390: prevent NPE when task status is null

- src/main/asciidoc/_chapters/security.adoc
Please verify language.
cc @bbeaudreault
> HBASE-27538 Document auto cert file reloading HBASE-27347

- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
This PR solves [HBASE-27253](https://issues.apache.org/jira/browse/HBASE-27253) by making the following RpcServer class' configurations dynamic:
* `hbase.regionserver.slowlog.buffer.enabled`
* `hbase.ipc.warn.response.time`
* `hbase.ipc.warn.response.size`
As the Jira suggests, it will be useful to toggle this feature and change thresholds on-demand when diagnosing problematic traffic.
> HBASE-27253 Make slowlog configurations dynamic

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
https://issues.apache.org/jira/browse/HBASE-27489
> HBASE-27489 Fix several problems after HBASE-27304

- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java
Clamp the boundaries of the selected sublist according to the input list size.
> HBASE-27563 ChaosMonkey sometimes generates invalid boundaries for random item selection

- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/monkies/PolicyBasedChaosMonkey.java
> Backport "HBASE-27563 ChaosMonkey sometimes generates invalid boundaries for random item selection" to branch-2.4

- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionServerObserver.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerCoprocessorHost.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/ReplicationSinkServiceImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSink.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationWithWALExtendedAttributes.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSink.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntrySinkFilter.java
HBase provides coproc ability to enhance WALKey attributes (a.k.a. WAL annotations) in order for the replication sink cluster to build required metadata with the mutations. The endpoint is preWALAppend(). This ability was provided by HBASE-22622. The map of extended attributes is optional and hence not directly used by hbase internally. 
For any hbase downstreamers to build CDC (Change Data Capture) like functionality, it might required additional metadata in addition to the ones being used by hbase already (replication scope, list of cluster ids, seq id, table name, region id etc). For instance, Phoenix uses many additional attributes like tenant id, schema name, table type etc.
We already have this extended map of attributes available in WAL protobuf, to provide us the capability to …
> HBASE-27529 Provide RS coproc ability to attach WAL extended attributes to mutations at replication sink

- hbase-it/src/test/java/org/apache/hadoop/hbase/ClusterManager.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/DistributedHBaseCluster.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/Action.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActionBaseAction.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartRandomJournalNodeAction.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerAndDependenciesKillingMonkeyFactory.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseClusterInterface.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/SingleProcessHBaseCluster.java
> HBASE-27568 ChaosMonkey add support for JournalNodes

- hbase-it/src/test/java/org/apache/hadoop/hbase/ClusterManager.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/DistributedHBaseCluster.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/Action.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartActionBaseAction.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/RestartRandomJournalNodeAction.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/factories/ServerAndDependenciesKillingMonkeyFactory.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseCluster.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/MiniHBaseCluster.java
> Backport "HBASE-27568 ChaosMonkey add support for JournalNodes" to branch-2.4

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/MasterRegistry.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMasterRegistry.java
Setting of hbase.master.port is ignored in default processing of hbase.masters.
For example,
hbase.masters=localhost
hbase.master.port=8100
"Server at localhost:16000" is in the failed servers list"
but:
hbase.masters=localhost:8100
hbase.master.port=8100
and all is well. This is confusing and a minor configuration handling bug.
> HBASE-27561 hbase.master.port is ignored in processing of hbase.masters

- hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestAccessController.java
allow namespace admins to clone snapshots created by them
> HBASE-27493: Allow namespace admins to clone snapshots created by them

- pom.xml
This PR aims to publish SBOM artifacts along with the other Apache projects.
- https://cwiki.apache.org/confluence/display/COMDEV/SBOM
Here is an article to give some context.
- https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/
Software Bill of Materials (SBOM) are additional artifacts containing the aggregate of all direct and transitive dependencies of a project. The US Government (based on NIST recommendations) currently accepts only the three most popular SBOM standards as valid, namely: [CycloneDX](https://cyclonedx.org/), [Software Identification (SWID) tag](https://csrc.nist.gov/projects/Software-Identification-SWID), [Software Package Data Exchange® (SPDX)](https://spdx.dev/).
We can use one of the Maven plugin, [CycloneDX maven …
> HBASE-27562 Publish SBOM artifacts

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
[HBASE-27528](https://issues.apache.org/jira/browse/HBASE-27528) MasterRpcServices record audit log in privileged operations **(grant, revoke)**.
```java
public RevokeResponse revoke(RpcController controller, RevokeRequest request)
throws ServiceException {
try {
......
server.cpHost.preRevoke(userPermission); // has audit log in AccessChecker
...... // removeUserPermission
User caller = RpcServer.getRequestUser().orElse(null);
if (AUDITLOG.isTraceEnabled()) {
String remoteAddress = RpcServer.getRemoteAddress().map(InetAddress::toString).orElse("");
AUDITLOG.trace("User {} (remote address: {}) revoked permission {}", caller,
remoteAddress, userPermission); // duplicate auditlog
}
......
}
```
but I found a path from `server.cpHost.preRevoke(userPermission);` to `AccessChecker audit log` …
> HBASE-27528 log duplication issues in MasterRpcServices.

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/janitor/CatalogJanitor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/janitor/TestCatalogJanitor.java
There already existed a robust reference check method for cleaning splits, `checkDaughterInFs`. I cleaned that up a little bit and re-use it in cleanMergeRegion. This way both cleaning splits and merges use the same reference checking logic. This should be easier to maintain going forward.
I added tests in TestCatalogJanitor -- there were none for merges, so i added a base case and a failure mode case.
I decided not to modify HRegionFileSystem.openRegionFromFileSystem -- even if I modified that to throw FileNotFoundException, from a defensive coding perspective I'd rather not assume that exception refers to the region dir specifically. This code is highly destructive, so we rely on an explicit `exists` call and only delete if that successfully returns false within our method.
> HBASE-27579 CatalogJanitor can cause data loss due to errors during cleanMergeRegion

- pom.xml
Correct version for 2.10.2 pulled from https://github.com/apache/hadoop/blob/rel/release-2.10.2/hadoop-project/pom.xml#L721
> HBASE-27592 Update hadoop netty version for hadoop-2.0 profile

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/HalfStoreFileReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileScanner.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/KeyValueHeap.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/KeyValueScanner.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/NonLazyKeyValueScanner.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionScannerImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/ScannerContext.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SegmentScanner.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileScanner.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileReaderImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/DelegatingKeyValueScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerBlockSizeLimits.java
I've deployed this on a test cluster and verified that it helps to reduce excess retained blocks due to heavily filtered scans. It is nice to have a upper limit on the cost of a scan, whether filtered or unfiltered and equally applying to both.
> HBASE-27558 Scan quotas and limits should account for total block IO

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/BufferedDataBlockEncoder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestTags.java
We missed resetting `uncompressTags` state when rewinding. This is important, otherwise the first call to `decodeTags()` will not actually decode anything and this ends up corrupting the expected buffer state. See comment for some details.
> HBASE-27580 Reverse scan over rows with tags throw exceptions when using DataBlockEncoding

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMultiRespectsLimits.java
There are two benefits to this change:
1. The old model totally ignores blocks retained by filtered cells. Filtered blocks are still retained, so should be counted.
2. The old model required covering all request types with addSize calls, and missed checkAndMutate/append/increment. The new model simplifies and unifies accounting between Multiget/Scan and makes it possible to consistently report accurate block IO in metrics (future PR).
However, there is one important functional change here. Previously we kept track of `lastBlock` in order to try not to overcount blocks when submitting multigets for individual cells of the same row or multiple contiguous rows in the same block. For example:
- Block A contains rows 1, 2, 3
- Submit `table.get(List.of(1, 2, 3))`
- Existing code would only …
> HBASE-27570 Unify tracking of block IO across all read request types

- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestTooLargeLog.java
I can't reproduce the nightly build crash locally, so I'm hoping this will give some idea of if the fix helps.
I noticed a responseTooLarge log in the test output at the exact same millisecond as the crash (according to corresponding core dump log). The responseTooLarge is coming from the `loadTable` call, which does a giant mutate. The changes here attempt to avoid triggering a responseTooLarge for that request.
> HBASE-27534 Addendum fix test crash

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotFileCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotHFileCleaner.java
> HBASE-27627 Improve efficiency of SnapshotHFileCleaner

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/ActiveMasterManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/TaskGroup.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/TaskMonitor.java
- hbase-server/src/main/resources/hbase-webapps/master/header.jsp
- hbase-server/src/main/resources/hbase-webapps/master/startupProgress.jsp
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/AlwaysStandByHMaster.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestActiveMasterManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/monitoring/TestTaskMonitor.java
A new PR after https://github.com/apache/hbase/pull/3667, according to the comments there, 
1. reuses the monitor codes;
2. shows bounded recently (default 30) journals/phases of a monitored task, to avoid the page to be too large;
3. shows the startup progress task group state;
4. shows all the group tasks state and phase statuses, as well as the eslaped time;
5. refactors the monitored tasks in startup, uses one task after master initialized;
> HBASE-21521 Expose master startup status via web UI

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/ActiveMasterManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/TakeSnapshotHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/TaskGroup.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/TaskMonitor.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java
- hbase-server/src/main/resources/hbase-webapps/master/header.jsp
- hbase-server/src/main/resources/hbase-webapps/master/startupProgress.jsp
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/AlwaysStandByHMaster.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestActiveMasterManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/monitoring/TestTaskMonitor.java
Signed-off-by: Bryan Beaudreault <bbeaudreault@apache.org>
> backport HBASE-21521, Expose master startup status via web UI (#4788)

- hbase-common/src/main/java/org/apache/hadoop/hbase/types/CopyOnWriteArrayMap.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/types/TestCopyOnWriteMaps.java
See javadoc of putIfAbsent:
> `@return` the previous value associated with the specified key, or null if there was no mapping for the key. (A null return can also indicate that the map previously associated null with the key, if the implementation supports null values.)
New test verifies putIfAbsent semantics on both CopyOnWriteArrayMap and ConcurrentSkipListMap so we can see that other ConcurrentMap implementations follow this contract. I've also read the code of a few others.
> HBASE-27648 CopyOnWriteArrayMap does not honor contract of ConcurrentMap.putIfAbsent

- hbase-backup/pom.xml
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManager.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/BackupUtils.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/RestoreTool.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupBase.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/ExtendedCellSerialization.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/WALPlayer.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestWALPlayer.java
This seems simple enough from a compatibility perspective. I'm adding a new `io.serializations`, but it should not matter for HFileOutputFormat2 whose output is actually written by StoreFileWriter. It'll only be used in the intermediate output, so is safe to change between deploys.
I chose to create a new ExtendedCellSerialization because it seemed the cleanest way to encapsulate, since others may have used CellSerialization in other contexts. The alternative would be to make CellSerialization implement Configurable, and use that to inject some new configuration which defaults to false. It felt better to skip needing to add a new configuration.
EDIT: I decided to wrap this in a conditional so its exposed to WALPlayer only for now. I realized that someone could have a job which reads Cells …
> HBASE-27649 WALPlayer does not properly dedupe overridden cell versions

- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/RemoteProcedureDispatcher.java
- hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/executor/ExecutorService.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/RegionsRecoveryChore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStates.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/FileArchiverNotifierFactoryImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/throttle/StoreHotnessProtector.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestBalancer.java
> Backport "HBASE-23102: Improper Usage of Map putIfAbsent (#828)" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSource.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/ReplicationSourceDummy.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceManager.java
https://issues.apache.org/jira/browse/HBASE-24781
Since https://github.com/apache/hbase/pull/778, `refreshSources` stopped calling `metrics.clear()`.
However, some of the tasks in `clear()`, including decrementing `sizeOfLogQueue`, still have to be performed by `refreshSources`.
> HBASE-24781 Clean up peer metrics when disabling peer

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStates.java
Depends on backport of HBASE-23102 / #5048 ; will rebase once that one is merged.
FYI @mwkang
> Backport "HBASE-23561 Look up of Region in Master by encoded region name is O(n)" and addendum to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java
JIRAID:HBASE-27670 Improve FSUtils to directly obtain FSDataOutputStream
jira: https://issues.apache.org/jira/browse/HBASE-27670
> HBASE-27670 Improve FSUtils to directly obtain FSDataOutputStream

- hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFilesTool.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestBulkLoadHFiles.java
JIRA:[HBASE-27688](https://issues.apache.org/jira/browse/HBASE-27688)
If HFile splitting occurs during bulkload, the CREATE_TIME_TS of hfileinfo =0,When HFile is copied after splitting, CREATE_TIME_TS of the original file is not copied。
> HBASE-27688 HFile splitting occurs during bulkload, the CREATE_TIME_TS of hfileinfo is 0

- src/main/asciidoc/_chapters/compression.adoc
Fix a misspelling of the ZstdCodec in compression documentation. See also https://issues.apache.org/jira/browse/HBASE-27701.
> HBASE-27701 Fix a misspelling of the ZstdCodec

- hbase-common/src/main/java/org/apache/hadoop/hbase/security/User.java
Implementation follows that of those who came before -- nothing fancy, no locking or memory barriers.
Having the UGI as a protected, non-final property on an abstract class is a nightmare.
> HBASE-27708 CPU hot-spot resolving User subject

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheConfig.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchExecutor.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCachePersister.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetchRSClose.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCachePersister.java
https://issues.apache.org/jira/browse/HBASE-27686
> HBASE-27686: Recovery of BucketCache and Prefetched data after RS Crash

- hbase-common/src/main/java/org/apache/hadoop/hbase/nio/ByteBuff.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/nio/RefCnt.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/TestByteBuffAllocator.java
- hbase-server/pom.xml
This felt like the cleanest way to solve this case, but open to other opinions. Whether we need to checkRefCount is directly tied to whether we use NONE recycler.
A couple other options I considered:
- Create a new inheritance hierarchy, i.e. OnHeapSingleByteBuff, etc. This felt like it'd only complicate an already complex system.
- Update the SingleByteBuff and MultiByteBuff constructors to take a new `boolean onHeap` or `boolean shouldCheckRefCount`. This felt more error prone because it's too easy for someone to forget to pass the correct boolean value for the corresponding recycler.
I added a basic test to validate that we only call checkRefCount for non-NONE recyclers. Beyond that, I think our existing ample coverage should suffice? Let me know if you'd like to see a particular test.
> HBASE-27710 ByteBuff ref counting is too expensive for on-heap buffers

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileListFile.java
JIRA: https://issues.apache.org/jira/browse/HBASE-27729.
> HBASE-27729. Missed one parameter when logging exception in StoreFileListFile.

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/FSDataInputStreamWrapper.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/FileLink.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/ReaderContextBuilder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetch.java
Using isolate stream reader for prefetching in pread reader, to speed up the prefetching progress.
The blocks cached when prefetching will be released after the pread reader is closed.
> HBASE-27646 Should not use pread when prefetching in HFilePreadReader

- bin/hbase-daemon.sh
Introduce separate `trap`s for SIGHUP vs. the rest. Treat `SIGINT`, `SIGKILL`, and `EXIT` identically, as before. Use the signal name without `SIG` prefix for increased portability, as per the POSIX man page for `trap`.
`SIGTERM` handler will now honor `HBASE_STOP_TIMEOUT` as described in the file header.
> Backport "HBASE-27651 hbase-daemon.sh foreground_start should propagate SIGHUP and SIGTERM" to branch-2

- bin/hbase-daemon.sh
Introduce separate `trap`s for SIGHUP vs. the rest. Treat `SIGINT`, `SIGKILL`, and `EXIT` identically, as before. Use the signal name without `SIG` prefix for increased portability, as per the POSIX man page for `trap`.
`SIGTERM` handler will now honor `HBASE_STOP_TIMEOUT` as described in the file header.
> Backport "HBASE-27651 hbase-daemon.sh foreground_start should propagate SIGHUP and SIGTERM" to branch-2.5

- hbase-server/src/main/java/org/apache/hadoop/hbase/fs/HFileSystem.java
HFileSystem::getLocalFs useless，and can be remove
> HBASE-27736 HFileSystem.getLocalFs is not used

- hbase-build-configuration/pom.xml
Old protobuf-2.5 doesn't know about Apple Silicon. Fall back to the x86 binary and hope that rosetta continues to work.
https://cwiki.apache.org/confluence/display/HADOOP/Develop+on+Apple+Silicon+%28M1%29+macOS
> HBASE-27741 Fall back to protoc osx-x86_64 on Apple Silicon

- hbase-build-configuration/pom.xml
Old protobuf-2.5 doesn't know about Apple Silicon. Fall back to the x86 binary and hope that rosetta continues to work.
https://cwiki.apache.org/confluence/display/HADOOP/Develop+on+Apple+Silicon+%28M1%29+macOS
> Backport "HBASE-27741 Fall back to protoc osx-x86_64 on Apple Silicon" to branch-2.5

- hbase-build-configuration/pom.xml
Old protobuf-2.5 doesn't know about Apple Silicon. Fall back to the x86 binary and hope that rosetta continues to work.
https://cwiki.apache.org/confluence/display/HADOOP/Develop+on+Apple+Silicon+%28M1%29+macOS
> Backport "HBASE-27741 Fall back to protoc osx-x86_64 on Apple Silicon" to branch-2.4

- hbase-resource-bundle/src/main/resources/supplemental-models.xml
- pom.xml
Update compression codec dependencies:
- aircompressor 0.21 -> 0.24
- brotli4j 1.8.0 -> 1.11.0
- snappy 1.1.8.4 -> 1.1.9.1
- zstd-jni 1.5.0-4 -> 1.5.4-2
and add a new supplemental model for new brotli4j dependency.
> HBASE-27744 Update compression dependencies

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetchRSClose.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCachePersister.java
Currently, we maintain a list of Hfiles on disk for which prefetch is complete and avoid prefetching those files after a restart. But we don't handle cases where blocks are evicted from the cache. This ticket is for updating the list of prefetched files upon simple block eviction.
Jira: https://issues.apache.org/jira/browse/HBASE-27750
> HBASE-27750: Update the list of prefetched Hfiles upon block eviction

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/metrics/ServerSideScanMetrics.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserSource.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserSourceImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcCallContext.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerCall.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregate.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregateFactory.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserAggregateImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/metrics/MetricsTableRequests.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestNamedQueueRecorder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/procedure2/store/region/TestRegionProcedureStore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsTableRequests.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsUserAggregate.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerBlockSizeLimits.java
- Adds `countofBlockBytesScanned` to ScanMetrics, and incorporates that into TestScannerBlockSizeLimits assertions.
- Renames server side RpcCall's counter from `responseBlockBytes` to `blockBytesScanned`. This seems more straightforward in the context of a request.
- Adds histograms for each of get, scan, increment, append, checkAndMutate, as well as an overall `blockBytesScannedCount` to Regionserver and TableLatencies metrics
- Adds blockBytesScannedCount to user aggregate metric. This would be useful for tuning quotas for users.
This is mostly boilerplate. Since blockBytesScanned increments globally for a request, we have to treat it similarly to time when calling the various per-request update methods -- subtract `after - before` for multi's to get the per-action value.
> HBASE-27532 Add block bytes scanned metrics

- hbase-shell/src/main/ruby/irb/hirb.rb
This PR is with respect to handling of SyntaxError exception in case we pass non-ascii characters in ruby shell.
The error scenario is explained in the below example :
hbase:002:0> create 't2', 'cf'
2023-03-14 04:54:50,061 INFO  [main] client.HBaseAdmin: Operation: CREATE, Table Name: default:t2, procId: 2140 completed
Created table t2
Took 1.1503 seconds
=> Hbase::Table - t2
hbase:003:0> alter 't2', NAME ⇒ 'cf', VERSIONS ⇒ 5
SyntaxError: (hbase):3: syntax error, unexpected tIDENTIFIER
alter 't2', NAME ⇒ 'cf', VERSIONS ⇒ 5
                 ^~~
                      eval at org/jruby/RubyKernel.java:1091
                  evaluate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/workspace.rb:85
                  evaluate at …
> HBASE-27726 Handling of ruby shell SyntaxError exceptions

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/FixedIntervalRateLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RateLimiter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestRateLimiter.java
Removes limits in `refill` which did not allow to go negative. 
FixedIntervalRateLimiter also needed some changes in getWaitInterval to properly match with how refilling really works.
Updated the tests to revive the original intended logic for quotas, where we really test for overconsumption.
> HBASE-27704 Quotas can drastically overflow configured limit

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsUserSourceImpl.java
Spotbugs complains because, for example, the assignment of `appendHisto` is synchronized but the actual usage in `updateAppend` is not. The first thought might be to synchronize all of the methods, but that would be detrimental to performance and unnecessary since these metrics are already thread safe.
The synchronization of register/deregister was added as part of the LossyCounting stuff for user metrics. So its possible under extreme conditions for the LossyCounting thread to deregister a user source which is currently being registered. So it's important to synchronize the actual metric creation/removal, more than anything else.
There is only one caller of `register/deregister`, here in  [MetricsUserAggregateSourceImpl](https://github.com/apache/hbase/blob/master/hbase-hadoop-compat/src/ …
> HBASE-27758 Inconsistent synchronization in MetricsUserSourceImpl

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSyncUp.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSyncUpTool.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSyncUpToolBase.java
https://issues.apache.org/jira/browse/HBASE-27623
> HBASE-27623 Start a new ReplicationSyncUp after the previous failed

- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestClusterRestartFailover.java
This test has been flakey. When it is rerun by surefire, the underlying minicluster isn't completely cleaned. specifically, the metics system isn't reset. The result is an otherwise successful re-run is failed because there's 8 or 12 SCPcounts instead of the 4 that a single run of the test would otherwise produce. Thus, assert of a multiple of 4.
> HBASE-27720 TestClusterRestartFailover is flakey due to metrics assertion

- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/BlockingRpcConnection.java
The basic idea here is we should usually have two threads: the main thread and a reader thread. Writes come through the main thread, which also handles calling setupIOStreams if the connection is not yet made. The reader thread is continually polling for work, calling `readResponse()` when calls are found. The writer methods are all synchronized, while the reader thread is not. The reader thread uses a `waitForWork()` poll method, which is itself synchronized.
If an exception occurs while writing a request, `closeConn` will be called. This interrupts and nulls out the reader `thread`, along with the socket and streams, and fails all calls that were pending read. The next write to come in will go through `setupIOStreams()`, which will create new sockets/streams and start a new reader …
> HBASE-27768 Race conditions in BlockingRpcConnection

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/SystemTableWALEntryFilter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationWALEntryFilters.java
Jira: https://issues.apache.org/jira/browse/HBASE-27422
> HBASE-27422: Support replication for hbase:acl

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/OnlineLogRecord.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/SlowLogParams.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestOnlineLogRecord.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-protocol-shaded/src/main/protobuf/server/region/TooSlowLog.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/impl/SlowLogQueueService.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestNamedQueueRecorder.java
[HBASE-27536](https://issues.apache.org/jira/browse/HBASE-27536)
Currently slow logs only includes a barebones text format of the underlying protobuf Message fields. Gets and Puts are relatively straightforward from a query cost perspective, but the configuration of Scans can have very significant performance implications.
With that in mind, we think it would be valuable to include the JSON representation of a given Scan to the slow log that it may produce.
cc @bbeaudreault @virajjasani
> HBASE-27536: Include more request information in slowlog for Scans

- hbase-external-blockcache/pom.xml
- hbase-external-blockcache/src/main/java/org/apache/hadoop/hbase/io/hfile/MemcachedBlockCache.java
- hbase-external-blockcache/src/test/java/org/apache/hadoop/hbase/io/hfile/TestMemcachedBlockCache.java
Changes:
- Track and log better stats.
- Fix use of memcached API such that we are not accidentally immediately expiring keys. 
- Use a default retention period of 30 days, the max per memcached spec. 
- Use set instead of add to store keys.
- Gracefully handle failures to cache and read timeouts. 
- Add unit tests using jmemcached as a test dependency.
Testing performed:
- New unit tests pass
- Stats logging of hit rate matches memcached side stats
- After manually killing the memcached server reads continue to be served, the load client LTT reports no errors, and there are no errors logged in the regionserver logs except for memcached client, as expected. Memcached client errors stop once memcached is restarted.
The stats logging looks liks
2023-04-14 14:15:06,767 INFO …
> HBASE-27796 Improve MemcachedBlockCache

- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestHBaseFsckReplication.java
https://issues.apache.org/jira/browse/HBASE-27274
> HBASE-27274 Re-enable the disabled tests when implementing HBASE-27212

- conf/log4j2.properties
- hbase-logging/src/test/resources/log4j2.properties
Make use of `%notEmpty` pattern with MDC logging. Will function as expected once we upgrade to Log4J 2.21.0+.
> HBASE-27762 Include EventType and ProcedureV2 pid in logging via MDC (addendum)

- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
Check if the executor has already been shut down before submitting new job.
I'm not sure if catching `RejectedExecutionException` would be a better approach here. I'm open for suggestions.
Find more details in the Jira ticket.
> HBASE-27810 HBCK throws RejectedExecutionException when closing ZooKeeper resources

- hbase-logging/src/test/resources/log4j2.properties
- hbase-server/src/main/java/org/apache/hadoop/hbase/executor/EventHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/AssignRegionHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/RSProcedureHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/UnassignRegionHandler.java
Includes revert of change to `conf/log4j2.properties`.
> Backport "HBASE-27762 Include EventType and ProcedureV2 pid in logging via MDC (#5145)" to branch-2.5

- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
> HBASE-27810 HBCK throws RejectedExecutionException when closing ZooKeeper resources (branch-2.4)

- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/RpcThrottlingException.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/quotas/TestRpcThrottlingException.java
`StringUtils#formatTime` will round down millis which can produce misleading error messages on RpcThrottlingExceptions with wait intervals between 0 and 1 second. This PR simply adds support expressing sub-second wait intervals 
@bbeaudreault
> HBASE-27799: RpcThrottlingException wait interval message is misleading between 0-1s

- pom.xml
Release notes for the underlying zstd 1.5.5 library: https://github.com/facebook/zstd/releases/tag/v1.5.5
This version includes a fix that prevented zstd-jni from running on s390x on common linux distros.
> HBASE-27838 Update zstd-jni from version 1.5.4-2 -> 1.5.5-2

- src/main/asciidoc/_chapters/ops_mgt.adoc
https://issues.apache.org/jira/browse/HBASE-27516
> HBASE-27516 Document the table based replication queue storage in ref guide

- hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFilesTool.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/tool/TestBulkLoadHFiles.java
hfile split occurs during bulkload, the new HFile file does not specify favored nodes
> HBASE-27733 hfile split occurs during bulkload, the new HFile file does not specify favored nodes

- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestListTablesByState.java
Surefire version 3.0.0-M6 has a bug where tests end up being removed from the test results if they fail with a long exception message. See:
https://issues.apache.org/jira/browse/SUREFIRE-2079
TestListTablesByState is currently failing due to an error. However, it is being missed because of the surefire bug. I found this while testing the final surfire 3.0.0 version which fixes the bug and the test then shows up as failing.
> HBASE-27851 Fix TestListTablesByState which is silently failing due to a surefire bug

- hbase-common/src/test/java/org/apache/hadoop/hbase/HBaseClassTestRule.java
HBaseClassTestRule applies a timeout and a system exit rule to tests. The timeout rule throws an exception if it hits the timeout threshold. Since the timeout rule is applied after the system exit rule, the system exit rule does not see the exception and does not re-enable the system exit behavior which can cause maven to hang on some tests.
This change applies the timeout rule before the system exit rule so that normal system exit can be restored before the surefire forked node is shutdown.
> HBASE-27857 Fix timeout exception handling in HBaseClassTestRule

- hbase-shaded/pom.xml
Fix build failure mentioned in  [HBASE-27860](https://issues.apache.org/jira/browse/HBASE-27860)
> HBASE-27860: Fix build error against Hadoop 3.3.5

- pom.xml
Surefire version updated from 3.0.0-M6 -> 3.1.0.
SurefireForkNodeFactory is a new strategy to control how the forked nodes communicate with the main maven process. It uses a tcp channel instead of pipes and fixes some corrupted messages seen in the s390x build.
> HBASE-27858 Update surefire version to 3.1.0 and use SurefireForkNodeFactory

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/ImportTsv.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestImportTsv.java
Fix issue: [HBASE-27848](https://issues.apache.org/jira/browse/HBASE-27848)
It is better to  fast-fail before MR is submitted if we specify a error column family when using ImportTsv Tool
> HBASE-27848:Should fast-fail if unmatched column family exists when using ImportTsv

- pom.xml
See details: [HBASE-27876](https://issues.apache.org/jira/browse/HBASE-27876)
I tested following commands.
```
$ mvn clean install -DskipTests
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
$ ls target/
hbase-3.0.0-alpha-4-SNAPSHOT-site.xml  maven-shared-archive-resources
```
```
$ mvn clean install -DskipTests -Prelease
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
$ ls target/
bom.json  bom.xml  hbase-3.0.0-alpha-4-SNAPSHOT-site.xml  maven-shared-archive-resources  rat.txt
```
> HBASE-27876: Only generate SBOM when releasing

- hbase-server/src/main/java/org/apache/hadoop/hbase/backup/HFileArchiver.java
When HFiles are placed on a filesystem other than HDFS a rename operation can be a non-atomic file copy operation. It can take a long time to copy a large hfile and if interrupted there may be a partially copied file present at the destination. If we fail to “rename” the files into the archive we will continue to fail indefinitely. Before larger changes are considered, perhaps to StoreFileTracker, we should mitigate this problem.
> HBASE-27843 If moveAndClose fails HFileArchiver should delete any incomplete archive side changes

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/LruBlockCache.java
When we evict a block from L1 and move it to L2 there is a brief window of time where we have removed the block from the L1 map and yet the victim handler has not completed execution. Some read-your-write use cases can be significantly impacted even though the window is small. Victim handling can be made atomic with respect to the unmapping operation. The upside is there will be no L1+L2 misses during the transition. The downside is if the victim handler takes a long time to execute – currently they are all very fast, so only a theoretical risk – then other removals or insertions in L1 can block until it completes.
> HBASE-27867 Close the L1 victim handler race

- hbase-compression/hbase-compression-snappy/src/main/java/org/apache/hadoop/hbase/io/compress/xerial/SnappyCodec.java
- hbase-compression/hbase-compression-snappy/src/test/java/org/apache/hadoop/hbase/io/compress/xerial/TestHFileCompressionSnappy.java
- hbase-compression/hbase-compression-snappy/src/test/java/org/apache/hadoop/hbase/io/compress/xerial/TestSnappyCodec.java
- hbase-compression/hbase-compression-snappy/src/test/java/org/apache/hadoop/hbase/io/compress/xerial/TestWALCompressionSnappy.java
We need to add a native library load check with a helpful error message if xerial snappy fails to initialize due to a too old glibc or similar reason, and disable the unit test if the native library fails to load.
> HBASE-27872 xerial's snappy-java requires GLIBC >= 2.32

- src/site/xdoc/downloads.xml
The actual stable version was changed in HBASE-27849, but this link was forgotten.
> HBASE-27933 Update stable version to 2.5.x

- dev-support/create-release/release-util.sh
Use the github webui to retrieve the project pom from the build branch instead of gitbox.
Tested with a dry run of create-release/do-release.sh.
> HBASE-27894 create-release is broken by recent gitbox changes

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
When not enable trace log, we also could record the slow read block message
> HBASE-27888 Record readBlock message in log when it takes too long time

- src/main/asciidoc/_chapters/getting_started.adoc
Fix typo of quck start doc HBASE-27937
> HBASE-27937 Update getting_started to fix typo

- hbase-server/src/main/java/org/apache/hadoop/hbase/client/ClientSideRegionScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestClientSideRegionScanner.java
[Jira](https://issues.apache.org/jira/browse/HBASE-27950)
> HBASE-27950 ClientSideRegionScanner does not adhere to RegionScanner.nextRaw contract

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
It seems not correct to have the MasterRpcServices methods for direct regionserver<->master communication   (regionServerStartup, regionServerReport, and reportFatalRSError) contending with normal priority requests. They should be made ADMIN_QOS priority to avoid potential operational deadlocks.
> HBASE-27951 Use ADMIN_QOS in MasterRpcServices for regionserver operational dependencies

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsHeapMemoryManagerSource.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsHeapMemoryManagerSourceImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HeapMemoryManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsHeapMemoryManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerAccounting.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsHeapMemoryManager.java
> HBASE-27948 Report memstore on-heap and off-heap size as jmx metrics in sub=Memory bean

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBatchRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncScanSingleRegionRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionUtils.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/backoff/HBaseServerExceptionPauseManager.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/backoff/TestHBaseServerExceptionPauseManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncClientPauseForRpcThrottling.java
The RpcThrottlingException tells the client how much to back off, but right now the recommendation is ignored. This PR introduces logic that respects said back off recommendation.
This feature was added to branch-2 via https://github.com/apache/hbase/pull/5226
@bbeaudreault
> HBASE-27798: Client side should back off based on wait interval in RpcThrottlingException

- hbase-common/src/main/resources/hbase-default.xml
Details see: [HBASE-27942](https://issues.apache.org/jira/browse/HBASE-27942)
> HBASE-27942:The description about hbase.hstore.comactionThreshold is not accurate

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
Details see: [HBASE-27920](https://issues.apache.org/jira/browse/HBASE-27920)
> HBASE-27920:Skipping compact for this region if the table disable compaction

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
Details see : [HBASE-27859](https://issues.apache.org/jira/browse/HBASE-27859)
> HBASE-27859:HMaster.getCompactionState can happen NPE when region state is closed

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBatchRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncScanSingleRegionRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionUtils.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/backoff/HBaseServerExceptionPauseManager.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/backoff/TestHBaseServerExceptionPauseManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncClientPauseForRpcThrottling.java
Backport of https://github.com/apache/hbase/pull/5275
@bbeaudreault
> [branch-2] HBASE-27798: Client side should back off based on wait interval in RpcThrottlingException

- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/shaded/protobuf/TestProtobufUtil.java
Per conversation in [HBASE-27553](https://issues.apache.org/jira/browse/HBASE-27553), we could provide the related row in the params blob for mutation slow logs. This should be useful information for the debugger reading the logs.
cc @bbeaudreault @hgromer @saijmo @eab148 @bozzkar
> HBASE-27553: add row param to mutation slow logs

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileInfo.java
I left the option in place, but just changed the default. If desired, I could just remove the option as well. I can't think of a case where it would be good to enable, am just trying to preserve compatibility if anyone has set it.
> HBASE-27896 Disable hdfs readahead for pread reads

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/LruBlockCache.java
Details see: [HBASE-28011](https://issues.apache.org/jira/browse/HBASE-28011)
Apply this commit, LruBlockCache.logStats would print info,as follow:  
```
INFO  [LruBlockCacheStatsExecutor] hfile.LruBlockCache: totalSize=3.20 GB, usedSize=2.41 MB, freeSize=3.20 GB, max=3.20 GB, blockCount=4, accesses=13, hits=9, hitRatio=69.23%, , cachingAccesses=13, cachingHits=9, cachingHitsRatio=69.23%, evictions=29, evicted=0, evictedPerRun=0.0
```
> HBASE-28011 : The logStats about LruBlockCache is not accurate

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/BufferedDataBlockEncoder.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteBufferUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/encoding/TestDataBlockEncoders.java
This PR updates BufferedEncodedSeeker#seekToKeyInBlock (used extensively in the reverse scan path) to avoid calling `CellUtil.cloneRow` for off-heap Cell seek targets.
For `private` "findCommonPrefix*" methods, I used an invariant that the "right" cell is always a `keyOnlyKv` and therefore on-heap.
For the `public` "compareCommonPrefix*" methods, I added extra paths to them to account for either the left or right cell to be on or off-heap to keep the behavior optimized for any external callers. In practice, I believe these methods are internal to `BufferedEncodedSeeker` except for a few unit tests so I'd be open to reducing the branching to just optimize for the left cell being able to be on/off-heap. I'd love some feedback on this approach as it adds a fair amount of extra code that …
> HBASE-28012 Avoid CellUtil.cloneRow in BufferedEncodedSeeker

- hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteBufferUtils.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/util/Bytes.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestByteBufferUtils.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestBytes.java
This PR updates `ByteBufferUtils#findCommonPrefix` and `Bytes#findCommonPrefix` to compare 8 bytes from the input buffers/arrays if `Unsafe` access is available. On platforms where Unsafe is unavailable, we use the current implementations. This is a similar optimization as to what is already done with `ByteBufferUtils#compareToUnsafe`.
There was a `Bytes#findCommonPrefix` method and a `ByteBufferUtils#findCommonPrefix` method that both accepted `byte[]` args. I've updated the `ByteBufferUtils#findCommonPrefix` method to delegate to `Bytes#findCommonPrefix` and applied the optimization for 8 byte at a time comparison to the `Bytes` class. 
Overall, the implementation draws a ton of inspiration from `ByteBufferUtils#compareToUnsafe`. The only large change that I made is for how we handle …
> HBASE-28025 Enhance ByteBufferUtils.findCommonPrefix to compare 8 bytes each time

- hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestBytes.java
Remove the "@Test" annotation from the "TestBytes" class due to its reliance on "TestCase" from JUnit 3.
> HBASE-28025 Enhance ByteBufferUtils.findCommonPrefix to compare 8 bytes each time [addendum]

- hbase-protocol-shaded/src/main/protobuf/server/io/BucketCacheEntry.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheConfig.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchExecutor.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketEntry.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketProtoUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/FileIOEngine.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/PersistentIOEngine.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestBlockEvictionOnRegionMovement.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetchRSClose.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetchWithBucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCachePersister.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestByteBufferIOEngine.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestPrefetchPersistence.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestRAMCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
[HBASE-27686](https://issues.apache.org/jira/browse/HBASE-27686) added a background thread for periodically saving the cache index map, together with a list of completed cached files so that we can recover the cache state in case of crash or restart. Problem is that the cache index can become few GB large (a sample case with 1.6TB of used bucket cache would map to between 8GB to 10GB indexes), and these writes take few seconds to complete, causing any RS crash very likely to leave a corrupt index file that can't be recovered when the RS starts again. Worse, since we store the list of cached files on a separate file, this also leads to cache inconsistencies, with files in the list of cached files never cached once the RS is restarted, even though we have no cache index for those and every …
> HBASE-28004 Persistent cache map can get corrupt if crash happens midway through the write

- hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotDescriptionUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestSnapshotScannerHDFSAclController.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestSnapshotDescriptionUtils.java
`Co-authored-by: Ujjawal <ujjawal4046@gmail.com>`
Jira: HBASE-28042
> HBASE-28042 Snapshot corruptions due to non-atomic rename within same filesystem

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/MetricsIO.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFile.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsJvm.java
Backports https://github.com/apache/hbase/pull/5323
> HBASE-27966 HBase Master/RS JVM metrics populated incorrectly

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKConfig.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKConfig.java
Looks like HBase has 2 different prefixes for ZooKeeper properties:
`hbase.zookeeper.property.`
`hbase.client.zookeeper.property.`
and we also have these:
`hbase.zookeeper.quorum`
`hbase.client.zookeeper.quorum`
Unfortunately I couldn't decrypt the meaning of each of every one of them, but we'd like to set system properties here which will be effective for all ZooKeeper clients in the same java process. Hence I only added the following properties which will be set in both client and server modes.
```
hbase.zookeeper.property.client.secure
hbase.zookeeper.property.clientCnxnSocket
hbase.zookeeper.property.ssl.keyStore.location
hbase.zookeeper.property.ssl.keyStore.password
hbase.zookeeper.property.ssl.keyStore.passwordPath
hbase.zookeeper.property.ssl.trustStore.location …
```
> HBASE-28038 Add TLS settings to ZooKeeper client

- hbase-client/src/main/java/org/apache/hadoop/hbase/RegionLoad.java
Correctly extract megabytes from a Size object. This bug only affects 2.x versions, so targeting branch-2.5.
> HBASE-28059 Use correct units in RegionLoad#getStoreUncompressedSizeMB()

- hbase-examples/src/main/java/org/apache/hadoop/hbase/client/example/MultiThreadedClientExample.java
- hbase-examples/src/test/java/org/apache/hadoop/hbase/client/example/TestMultiThreadedClientExample.java
This PR is now open for review. The details os stack trace is captured in https://issues.apache.org/jira/projects/HBASE/issues/HBASE-27991 
ForkJoinPool and ThreadPoolExecutor are both implemented classes of the ExecutorService interface from the java.util.concurrent package, which provides a framework for asynchronously executing tasks in Java.
```
ExecutorService created using Executors.newFixedThreadPool(10), that gives you a ThreadPoolExecutor, can not be cast to ForkJoinPool in hbase-examples/src/main/java/org/apache/hadoop/hbase/client/example/MultiThreadedClientExample.java 
```
> HBASE-27991 fixing ClassCastException in multithread client run

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
This change is trivial, and I'm not sure how to unit test it given it requires tcnative to be on the classpath and on a supported architecture. I tested this in my environment with and without tcnative on the classpath.
> HBASE-28008 Add support for netty tcnative

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBatchRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncScanSingleRegionRpcRetryingCaller.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionUtils.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/MetricsConnection.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionServerCallable.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/DelegatingHBaseRpcController.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/HBaseRpcController.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/HBaseRpcControllerImpl.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestMetricsConnection.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestClientTableMetrics.java
Detail: [HBASE-27853](https://issues.apache.org/jira/browse/HBASE-27853) and backport for branch-2.
> HBASE-27853 Add client side table metrics for rpc calls and request latency.

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/OnlineLogRecord.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestOnlineLogRecord.java
- hbase-protocol-shaded/src/main/protobuf/server/region/TooSlowLog.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/RpcLogDetails.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/impl/SlowLogQueueService.java
- hbase-server/src/main/resources/hbase-webapps/regionserver/rsOperationDetails.jsp
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestNamedQueueRecorder.java
In [HBASE-27657](https://issues.apache.org/jira/browse/HBASE-27657) we added support for request and connection attributes. By pushing this metadata to the slow log we can provide more flexible and meaningful visibility for those debugging via the slow log.
cc @bbeaudreault @hgromer @eab148 @bozzkar
> HBASE-27981 Add connection and request attributes to slow log

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/OnlineLogRecord.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestOnlineLogRecord.java
- hbase-protocol-shaded/src/main/protobuf/TooSlowLog.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/RpcLogDetails.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/impl/SlowLogQueueService.java
- hbase-server/src/main/resources/hbase-webapps/regionserver/rsOperationDetails.jsp
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestNamedQueueRecorder.java
Master PR: https://github.com/apache/hbase/pull/5335
In [HBASE-27657](https://issues.apache.org/jira/browse/HBASE-27657) we added support for request and connection attributes. By pushing this metadata to the slow log we can provide more flexible and meaningful visibility for those debugging via the slow log.
cc @bbeaudreault
> [branch-2 ] HBASE-27981 Add connection and request attributes to slow log (#5335)

- hbase-asyncfs/pom.xml
- hbase-common/pom.xml
- hbase-endpoint/pom.xml
- hbase-examples/pom.xml
- hbase-http/pom.xml
- hbase-mapreduce/pom.xml
- hbase-resource-bundle/src/main/resources/supplemental-models.xml
- hbase-rest/pom.xml
- hbase-server/pom.xml
- pom.xml
- Upgrades to v1.76, i.e. the latest version
- Replaces bcprov-jdk15on with bcprov-jdk18on and bcpkix-jdk15on with bcpkix-jdk18on 
- Excludes bcprov-jdk15on from everywhere else, to avoid conflicts with bcprov-jdk18on
> HBASE-28089 Upgrade BouncyCastle to fix CVE-2023-33201

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClientAsyncPrefetchScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClientScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClientSimpleScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionConfiguration.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ReversedClientScanner.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ScannerCallableWithReplicas.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestClientScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestClientScannerTimeouts.java
Adds a new `hbase.client.use.scanner.timeout.for.next.calls` config, defaulting to false. When true, ClientScanner (for HTable) will use the scanner timeout for next() calls like AsyncTable does. As with AsyncTable, other calls (openScanner, closeScanner, renewLease) continue to use readRpcTimeout.
Adds a new test in TestClientScannerTimeouts to verify old and new behavior.
I wonder if we should enable this by default in branch-2, and disable by default in 2.5.x. Open to opinions.
> HBASE-28085 Configurably use scanner timeout as rpc timeout for scanner next calls

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestChecksum.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlockHeaderCorruption.java
> Forward-port "HBASE-28065 Corrupt HFile data is mishandled in several cases" to master

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestChecksum.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlockHeaderCorruption.java
* when no block size is provided and there's not a preread headerBuf, treat the value with caution.
* verify HBase checksums before making use of the block header.
* inline verifyOnDiskSizeMatchesHeader to keep throw/return logic in the method body.
* whenever a read is determined to be corrupt and fallback to HDFS checksum is necessary, also invalidate the cached value of headerBuf.
* built out a test suite covering various forms of block header corruption, for blocks in first and second positions.
> HBASE-28065 Corrupt HFile data is mishandled in several cases (branch-2.5)

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestChecksum.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlockHeaderCorruption.java
* when no block size is provided and there's not a preread headerBuf, treat the value with caution.
* verify HBase checksums before making use of the block header.
* inline verifyOnDiskSizeMatchesHeader to keep throw/return logic in the method body.
* separate validation of onDiskSizeWithHeader as input parameter from as read from block header
* simplify branching around fetching and populating onDiskSizeWithHeader.
* inline retrieving nextOnDiskBlockSize ; add basic validation.
* whenever a read is determined to be corrupt and fallback to HDFS checksum is necessary, also invalidate the cached value of headerBuf.
* build out a test suite covering various forms of block header corruption, for blocks in first and second positions.
> Backport "HBASE-28065 Corrupt HFile data is mishandled in several cases" to branch-2.4

- hbase-common/src/main/resources/hbase-default.xml
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/normalizer/SimpleRegionNormalizer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
…gions property … (#5403)  
Authored-by: Rahul Kumar <rahul.kumar@rahulku-ltmdgmc.internal.salesforce.com>
Signed-off-by: Nick Dimiduk <ndimiduk@apache.org> @rahulLiving
> HBASE-28068 Add hbase.normalizer.merge.merge_request_max_number_of_re… 

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
https://issues.apache.org/jira/browse/HBASE-28105
Avoid NPE by making sure the table exists in the latest metadata.
> HBASE-28105 NPE in QuotaCache if Table is dropped from cluster

- hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizer.java
The default config was updated to 100 but update of the test was missed.
> HBASE-28126 Update MaxNumberOfRegionsCount in TestSimpleRegionNormalizer

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/BackupUtils.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupUtils.java
Make the hostname parsing in BackupUtils#parseHostFromOldLog more lenient by not making any assumptions about the name of the file other than that it starts with a org.apache.hadoop.hbase.ServerName.
> HBASE-28082 oldWALs naming can be incompatible with HBase backup

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
There's a chance for rs to be NULL when starting up the HMaster. Then we ran into NPE exception
```
2023-09-18 14:17:40,452 ERROR [master/hmaster:16000:becomeActiveMaster] master.HMaster: Failed to become active master
java.lang.NullPointerException
at org.apache.hadoop.hbase.master.HMaster.isRegionOnline(HMaster.java:1229)
at org.apache.hadoop.hbase.master.HMaster.waitForMetaOnline(HMaster.java:1218)
at org.apache.hadoop.hbase.master.HMaster.finishActiveMasterInitialization(HMaster.java:968)
at org.apache.hadoop.hbase.master.HMaster.startActiveMasterManager(HMaster.java:2193)
at org.apache.hadoop.hbase.master.HMaster.lambda$run$0(HMaster.java:528)
at java.lang.Thread.run(Thread.java:750)
```
This PR add a simple check and make HMaster keep waiting instead of directly shutting down.
> HBASE-28109 NPE for the region state: Failed to become active master (HMaster)

- pom.xml
Change-Id: I45a17ac34b12aa00a04341413ac01dc70e5f328b
> HBASE-28135 Specify -Xms for tests

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStateNode.java
To prevent threads from being blocked by the lock of RegionStateNode, modify the way of acquiring the RegionStateNode lock in checkOnlineRegionsReport to tryLock.
> HBASE-28113  Modify the way of acquiring the RegionStateNode lock in checkOnlineRegionsReport to tryLock

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
On 2.x [the ServerManager registers admins in a HashMap](https://github.com/apache/hbase/blob/branch-2/hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java). This can result in thread safety issues — we recently observed an exception which caused a region to be indefinitely stuck in transition until we could manually intervene. We saw the following exception in the HMaster logs:
```
2023-10-11 02:20:05.213 [RSProcedureDispatcher-pool-325] ERROR org.apache.hadoop.hbase.master.procedure.RSProcedureDispatcher: Unexpected error caught, this may cause the procedure to hang forever
java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of …
```
> HBASE-28146: Make ServerManager rsAdmins map thread safe

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
- hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto
- hbase-protocol-shaded/src/main/protobuf/server/master/MasterProcedure.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/AbstractStateMachineRegionProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableProcedureInterface.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TruncateRegionProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncRegionAdminApi2.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestTruncateRegionProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java
- hbase-shell/src/main/ruby/hbase/admin.rb
- hbase-shell/src/main/ruby/shell.rb
- hbase-shell/src/main/ruby/shell/commands/truncate_region.rb
- hbase-shell/src/test/ruby/hbase/admin_test.rb
- hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
HBASE-28064:Implement truncate_region command to truncate region directly from FS
Implemented truncate_region command and added unit/system tests.
> HBASE-28064:Implement truncate_region command

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCachePersister.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/FileIOEngine.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetchWithBucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestRecoveryPersistentBucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
On restarts, once we read the backing map from the persisted file, we compare the last modification time of the cache recorded there against the last modification time of the cache. If those differ, it means the cache has been updated after the backing map has been persisted, so the backing map might not be accurate. We then iterate though the backing map entires and compare the entries cached time against the related block in the cache, and if those differ, we remove the entry from the map.
Currently this validation is made at RS initialisation time, but with caches as large as 1.6TB/30M+ blocks, it can last to an hour, meaning the RS is useless over that time. This PR changes this validation to be performed in the background, whilst direct accesses to a block in the cache would also …
> HBASE-28170 Put the cached time at the beginning of the block; run cache validation in the background when retrieving the persistent cache

- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcDuplexHandler.java
https://issues.apache.org/jira/browse/HBASE-28017
These new calls have equivalents in BlockingRpcConnection's read/write methods. This will ensure that request/response size metrics are available to those using the netty client.
cc @bbeaudreault @hgromer @eab148 @bozzkar
> HBASE-28017: set request and response sizes in NettyRpcDuplexHandler

- hbase-shell/src/main/ruby/hbase/admin.rb
…a table in HBase shell, the log prompt will report an error.
> HBASE-28145 When specifying the wrong BoolFilter type while creating a table in HBase shell, an error will occur.

- hbase-client/src/main/java/org/apache/hadoop/hbase/security/AbstractHBaseSaslRpcClient.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/security/NettyHBaseSaslRpcClientHandler.java
- hbase-examples/src/main/java/org/apache/hadoop/hbase/security/provider/example/ShadeSaslClientAuthenticationProvider.java
- hbase-examples/src/main/java/org/apache/hadoop/hbase/security/provider/example/ShadeSaslServerAuthenticationProvider.java
- hbase-examples/src/test/java/org/apache/hadoop/hbase/security/provider/example/TestShadeSaslAuthenticationProvider.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyHBaseSaslRpcServerHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/SimpleServerRpcConnection.java
- Backport HBASE-23881 "Netty SASL implementation does not wait for challenge response"
- Backport HBASE-24263 "TestDelegationToken is broken"
- Fix assertion to check for InvalidToken.class.getName() to ensure bug is fixed
> HBASE-24179 Backport fix for "Netty SASL implementation does not wait for challenge response" to branch-2.x

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/hbck/HbckChore.java
- hbase-server/src/main/resources/hbase-webapps/master/hbck.jsp
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestHbckChore.java
Ensure that hbck will report as inconsistent regions where previously a location was reported but now the region location is null, if it is not expected to be offline.
> HBASE-28157. hbck should report previously reported regions with null region location

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-protocol-shaded/src/main/protobuf/server/region/Admin.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CombinedBlockCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetchRSClose.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetchWithBucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockRegionServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java
- hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
Jira: https://issues.apache.org/jira/browse/HBASE-27794
> HBASE-27794: Tooling for parsing/reading the prefetch files list file

- hbase-it/pom.xml
- hbase-server/pom.xml
- hbase-zookeeper/pom.xml
- pom.xml
Backport of #5475
(cherry picked from commit 0d04a6053a05525e0ba8fd6525c3af7f3412c9de)
> HBASE-28153 Upgrade zookeeper to a newer version (#5484)

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java
master branch PR: https://github.com/apache/hbase/pull/5503
branch-2 PR: https://github.com/apache/hbase/pull/5504
branch-2.5 PR: https://github.com/apache/hbase/pull/5505
> HBASE-28184 Tailing the WAL is very slow if there are multiple peers

- hbase-server/src/main/resources/hbase-webapps/master/table.jsp
Deatils see : [HBASE-28191](https://issues.apache.org/jira/browse/HBASE-28191)
> HBASE-28191 : Meta browser can happen NPE when the server or target server of region is null

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestX509Util.java
When using OpenSSL/BoringSSL, put these cipher suites at the top of our preference list always. When using the JDK cipher support, only put these on the list if on JDK 11+.
> HBASE-28122: Support TLSv1.3 cipher suites

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptor.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
- hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto
- hbase-protocol-shaded/src/main/protobuf/server/master/MasterProcedure.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ModifyTableProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestModifyTableProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java
- hbase-shell/src/main/ruby/hbase/admin.rb
- hbase-shell/src/main/ruby/hbase_constants.rb
- hbase-shell/src/main/ruby/shell/commands/alter.rb
- hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
- pom.xml
Provide an optional lazy_mode for the alter command to modify the TableDescriptor without the region entering the RIT. The modification will take effect when the region is reopened.
> HBASE-25549 Provide a switch that allows avoiding reopening all regions when modifying a table to prevent RIT storms.

- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStoreFile.java
This PR attempts to optimize the StoreFileScanner.seekToPreviousRow (& related reverse scan methods) to reduce the number of seeks from the beginning of the block by introducing a variable "previousRow"
~I still have some work to do to ensure that `StoreFileScanner` obeys it's interface/contract in lieu of the new changes as the introduction of state in previousRow greatly alters reverse seek behavior~ Finished with this, the only method that doesn't necessarily obey the contract is `next()` as it doesn't clear the `previousRow` state if the caller were to keep calling `next` past a row boundary. That is, if the caller were to perform `seekToPreviousRow` calls, call `next()` past a row boundary, and then call `seekToPreviousRow`, the result is that you'd seek back to before the row that …
> HBASE-28043 Reduce seeks from beginning of block in StoreFileScanner.seekToPreviousRow

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/SlowLogParams.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/RpcLogDetails.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestRpcLogDetails.java
The RpcLogDetails class represents a slow (or large) log event which will later be consumed by the SlowLogQueueService.
Right now the RpcLogDetails' param field points to the slow call's Message, and this Message is backed by a CodedInputStream which may be overwritten before the given log is consumed. This overwriting of the Message may result in slow query payloads for which the metadata derived post-consumption is inaccurate.
To solve this bug we need to deep copy the Message in the RpcLogDetails constructor. I have this bug reproduced in a QA environment and have confirmed that this resolves the issue.
cc @bbeaudreault @hgromer @eab148 @bozzkar
> HBASE-28175: Deep copy RpcLogDetails' param field

- hbase-server/src/main/resources/hbase-webapps/master/table.jsp
master branch PR : #5508 
branch-2 PR #5510 
branch-2.4 PR  #5511
> HBASE-28191 Meta browser can happen NPE when the server or target server of region is null

- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/Constants.java
- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/MultiRowResource.java
- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RowResource.java
- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RowSpec.java
- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/TableResource.java
- hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/RowResourceBase.java
- hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestDeleteRow.java
- hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestGetAndPutResource.java
- hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestMultiRowResource.java
- src/main/asciidoc/_chapters/external_apis.adoc
See https://issues.apache.org/jira/browse/HBASE-28174
Very much a draft. I'm yet to test this. Testing checklist (hopefully I've caught everything here):
> HBASE-28174

- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/BlockingRpcConnection.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcConnection.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/RpcConnection.java
Back-port of https://github.com/apache/hbase/pull/2716 to the 2.4 release line.
Follow-up of https://github.com/apache/hbase/pull/5515.
(cherry picked from commit f813479)
Co-authored-by: Duo Zhang <zhangduo@apache.org>
> HBASE-25336 [branch-2.4] Use Address instead of InetSocketAddress in RpcClient implementation

- hbase-protocol-shaded/src/main/protobuf/PrefetchPersistence.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchProtoUtils.java
…… (#5339)
Reviewew-by: Kota-SH <shanmukhaharipriya@gmail.com>
(cherry picked from commit 364fcea01c45921b806edea80c8a01e08608dd8d)
> HBASE-28186 Rebase CacheAwareBalance related commits

- hbase-shell/src/test/ruby/shell/list_locks_test.rb
We added a new field in Procedure so the json output is also changed thus we need to change the assertion
> HBASE-28212 Addendum fix TestShell

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
- hbase-protocol-shaded/src/main/protobuf/Master.proto
- hbase-protocol-shaded/src/main/protobuf/MasterProcedure.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ModifyTableProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestModifyTableProcedure.java
- hbase-shell/src/main/ruby/hbase/admin.rb
- hbase-shell/src/main/ruby/hbase_constants.rb
- hbase-shell/src/main/ruby/shell/commands/alter.rb
- hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
* This is to prevent RIT storms.
* The changes have been made in both alter and alter sync commands.
The related changes have already been merged in the master branch from https://github.com/apache/hbase/pull/2924. This change cherry-picks that, and makes few additional changes on top of that.
> HBASE-25549 Provide a switch that allows avoiding reopening all regions when modifying a table to prevent RIT storms

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ModifyTableProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ReopenTableRegionsProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestReopenTableRegionsProcedureBatchBackoff.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestReopenTableRegionsProcedureBatching.java
https://issues.apache.org/jira/browse/HBASE-28215
The mass reopening of regions caused by a table descriptor modification can be quite disruptive. For latency/error sensitive workloads, like our user facing traffic, we need to be very careful about when we modify table descriptors, and it can be virtually impossible to do it painlessly for busy tables.
This PR introduces two new configurations:
1. hbase.table.regions.reopen.batch.size
* This is an integer which represents the number of reopen procedures to create in a single batch. This defaults to Integer.MAX_VALUE, so it should be a no-op for any table with fewer than billions of regions 
3. hbase.table.regions.reopen.batch.backoff.ms
* This is a long which represents the millis to be waited between reopen batches. Hyperbolically, you …
> HBASE-28215: region reopen procedure batching/throttling

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionServerAggregate.java
We routinely see JVM crashes originating from our RegionServerMetricsWrapperRunnable in jdk17 on aarch64. Since that method is so large, it's hard to know exactly where or what the problem is. There is an [issue submitted](https://github.com/adoptium/adoptium-support/issues/951), but no indication of whether or when a fix will come.
The core dump indicates its a problem with On Stack Replacement (OSR). Reading up on that, it can kick in when long methods are suddenly deemed hot and attempt to be optimized in place. Taking a stab in the dark based on that, I saw two potential issues in RegionServerMetricsWrapperRunnable:
1. The method is exceptionally long, especially when considering the loops
2. There are over 50 volatile variables updated in the parent class
This PR attempts to solve …
> HBASE-28206 [JDK17] JVM crashes intermittently on aarch64

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestLogRolling.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncLogRolling.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestLogRolling.java
Detail: https://issues.apache.org/jira/browse/HBASE-28190
> HBASE-28190 Add slow sync log rolling test in TestAsyncLogRolling.

- bin/hbase
- bin/hbase-config.sh
Change-Id: I0ade930b2f92a0dfd015697a9c4de20e7de65ba5
> HBASE-28252 Add sun.net.dns and sun.net.util to the JDK11+ module exports in the hbase script

- hbase-shell/src/test/ruby/hbase/table_test.rb
Add some delay (1/1000s) between HBase shell commands in Ruby to avoid two commands ending up with the same version.
Please backport until `branch-2.4`
> HBASE-28254 Flaky test: TestTableShell

- bin/draining_servers.rb
- bin/get-active-master.rb
- bin/replication/copy_tables_desc.rb
- bin/shutdown_regionserver.rb
- hbase-logging/src/main/java/org/apache/hadoop/hbase/logging/InternalLog4jUtils.java
- hbase-logging/src/main/java/org/apache/hadoop/hbase/logging/Log4jUtils.java
- hbase-shell/src/main/ruby/jar-bootstrap.rb
- hbase-shell/src/test/ruby/no_cluster_tests_runner.rb
- hbase-shell/src/test/ruby/tests_runner.rb
* Removed redundant imports and replaced unsupported methods with alternates
* Removed usage of `org.apache.logging.log4j` and `org.apache.log4j.Logger` from ruby scripts
* Added new methods in `Log4jUtils.java` and `InternalLog4jUtils.java` to be used as alternative in scripts
* Disabled info/debug logging of existing ruby scripts to clean up noisy output
> HBASE-28269 Fix broken ruby scripts and clean up logging

- hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/io/asyncfs/TestFanOutOneBlockAsyncDFSOutput.java
This is not included in Flaky Test reports, but happens quite frequently for me locally. `testRecover()` passes the expected failure and throws error:
```
java.lang.AssertionError: flush should fail
at org.junit.Assert.fail(Assert.java:89)
at org.apache.hadoop.hbase.io.asyncfs.TestFanOutOneBlockAsyncDFSOutput.testRecover(TestFanOutOneBlockAsyncDFSOutput.java:154)
```
Looks like it happens only if the other test `testConnectToDatanodeFailed()` precedes it. They do similar thing: restart one of the DataNodes to generate failure in FS connection. I've tried the following things to fix it:
- changed the ID of DataNode to be restarted to be unique in the 2 tests,
- added `CLUSTER.waitDatanodeFullyStarted()` at the end of testConnectToDatanodeFailed.
None of them helped unfortunately, so I …
> HBASE-28274 Flaky test: TestFanOutOneBlockAsyncDFSOutput (Part 2)

- hbase-server/src/main/java/org/apache/hadoop/hbase/client/ClientSideRegionScanner.java
This PR updates ClientSideRegionScanner to close its instances of the MobFileCache and the BlockCache. In normal region server operation, the shutdown of these resources is typically handled by RegionServerServices which isn't present in the ClientSideRegionScanner. Since the ClientSideRegionScanner instantiates these resources, it should handling shutting them down as well to avoid resource leaks.
I've verified that this works locally with some debug breakpoints. I'd love to write some automated test behavior for this, but unsure how to proceed there. Would appreciate any pointers.
[HBASE-28224](https://issues.apache.org/jira/browse/HBASE-28224)
> HBASE-28224 ClientSideRegionScanner appears not to shutdown MobFileCache

- hbase-server/src/main/java/org/apache/hadoop/hbase/HBaseServerBase.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionServerObserver.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerCoprocessorHost.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestMasterObserver.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestAccessController.java
Provide coprocessor hooks for updateConfiguration and clearRegionBlockCache. Also, use these new hooks in AccessController to gate access to these operations. This closes a minor security hole.
> HBASE-26268: Provide coprocessor hooks for updateConfiguration and clearRegionBlockCache

- hbase-server/src/main/resources/hbase-webapps/master/table.jsp
Currently, HBase Web UI can only see the uncompressed StoreFile size of each Region on the Region Server page, but sometimes we also hope to see this information on the table details page, which can help analyze the data distribution of each table.
> HBASE-28305 Add "Uncompressed StoreFileSize" column to the table.jsp

- hbase-assembly/pom.xml
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-extensions/hbase-openssl/pom.xml
- hbase-extensions/pom.xml
- pom.xml
EDIT: I've updated the title and description to account for the new direction. The new direction makes it easier for people to include tcnative in their own projects as well as in our release binaries.
Introduces the following module hierarchy:
```
hbase
-\ hbase-assembly
-\ hbase-client
-\ etc...
-\ hbase-extensions
-\ hbase-openssl
```
`hbase-openssl` includes runtime dependency on hbase-shaded-netty-tcnative.  `hbase-assembly` has been updated to depend on `hbase-openssl` instead. I've verified that the binaries still include the right jar:
```
❯ tar -ztvf hbase-assembly/target/hbase-4.0.0-alpha-1-SNAPSHOT-client-bin.tar.gz | grep tcnative
-rw-r--r--  0 root   root  5437808 Jan 22  2020 hbase-4.0.0-alpha-1-SNAPSHOT-client/lib/hbase-shaded-netty-tcnative-4.1.5.jar
❯ tar -ztvf …
```
> HBASE-28307 Add hbase-openssl module and include in release binaries

- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionServerObserver.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerCoprocessorHost.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/AccessController.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestMasterObserver.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestAccessController.java
This backport is a bit messy because on branch-2 we don't have `HBaseServerBase`. Instead, an `HMaster` extends `HRegionServer`. So, this backport drops the pre/postUpdate**Master** variants.
`TestAccessController` fails locally for me at mini-cluster started up with the message "Master passed us a different hostname to use". This may be something weird with my local (WSL2) environment, so trying on Jenkins.
FYI @charlesconnell
> Backport "HBASE-26268 Provide coprocessor hooks for updateConfiguration and clearRegionBlockCache (#5593)" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/locking/LockManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/TakeSnapshotHandler.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestSnapshotProcedureWithLockTimeout.java
> HBASE-28271 Infinite waiting on lock acquisition by snapshot can result in unresponsive master

- hbase-metrics-api/src/main/java/org/apache/hadoop/hbase/metrics/MetricRegistry.java
- hbase-metrics/src/main/java/org/apache/hadoop/hbase/metrics/impl/MetricRegistryImpl.java
- hbase-metrics/src/test/java/org/apache/hadoop/hbase/metrics/impl/TestMetricRegistryImpl.java
JIRA: https://issues.apache.org/jira/browse/HBASE-28327
This will help us clean up metrics safely. We will remove a `Metric` with the specified `name` from the metric registry if and only if the provided `metric` matches the object in the registry.
> HBASE-28327 Add `remove(String name, Metric metric)` method to MetricRegistry

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
Details see: [HBASE-28332](https://issues.apache.org/jira/browse/HBASE-28332)
> HBASE-28332 Type conversion is no need in method CompactionChecker.chore()

- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcCallContext.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerCall.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerRpcConnection.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestNamedQueueRecorder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestRpcLogDetails.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/procedure2/store/region/TestRegionProcedureStore.java
At my employer we plan on using a coprocessor to log information about some requests to HBase. For this to be useful to us, we need to know who each request is coming from. We use HBase's TLS support with mutual authentication to authenticate clients. I'd like a way to expose the client certificate used on a request to coprocessors. For setups using Kerberos authentication, RpcCall exposes the Kerberos principal shortname via `getRequestUser()`, so this would be the TLS equivalent to that. I've tested this patch applied to 2.5.x in my company's infrastructure.
I found that in order for this patch to be useful to me, I also need netty to fix a related bug which I reported as https://github.com/netty/netty/issues/13796. This doesn't need to block this PR.
> HBASE-28317: Expose client TLS certificate on RpcCallContext

- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestNettyRpcServer.java
Fixes a bug introduced in https://github.com/apache/hbase/pull/5644
> HBASE-28336: Correctly cast array of Certificates to array of X509Certificates

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableDescriptorBuilder.java
Resolving : https://issues.apache.org/jira/projects/HBASE/issues/HBASE-28334
> HBASE-28334: Remove unnecessary null DEFAULT_VALUE

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/FSDataInputStreamWrapper.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/TestFSDataInputStreamWrapper.java
This also simplifies the code quite a bit, since we no longer need reflection for old unsupported versions. Updated the test to account for the new logic and cover this case.
> HBASE-28338 Bounded leak of FSDataInputStream buffers from checksum switching

- hbase-client/src/main/java/org/apache/hadoop/hbase/HTableDescriptor.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptor.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestTableDescriptorBuilder.java
- hbase-protocol-shaded/src/main/protobuf/MasterProcedure.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/fs/ErasureCodingUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CloneSnapshotProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CreateTableProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ModifyTableProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RestoreSnapshotProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/CompactedHFilesDischarger.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/TableDescriptorChecker.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestManageTableErasureCodingPolicy.java
- hbase-shell/src/main/ruby/hbase/admin.rb
- hbase-shell/src/test/java/org/apache/hadoop/hbase/client/AbstractTestShell.java
- hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestAdminShell.java
- hbase-shell/src/test/ruby/hbase/admin_test.rb
- hbase-shell/src/test/ruby/test_helper.rb
This is a draft because I expect it to fail for hadoop2. I want to take a stab at making it work on branch-2, but will need to iterate on some reflection stuff. Will convert to real once I'm ready.
> HBASE-28216 HDFS erasure coding support for table data dirs

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultQuota.java
If you're managing HBase for many users, then managing effective user quotas can be a difficult operational burden. At my day job we have thousands of web services, workers, and recurring jobs — each of which we consider a distinct user via [request attributes](https://github.com/apache/hbase/pull/5326) and [quota user overrides](https://github.com/apache/hbase/pull/5424). A common reliability issue is that some single system runs awry, for whatever reason, and generates a pathologic amount of traffic at the HBase level; this can cause pain for any other systems dependent on the given HBase cluster.
The above situation could potentially be solved by maintaining our own automated user quota management, but even better would be the ability to specify default user quotas at the HBase level. …
> HBASE-27800: Add support for default user quotas

- hbase-client/src/main/java/org/apache/hadoop/hbase/security/NettyHBaseSaslRpcClientHandler.java
- hbase-examples/src/test/java/org/apache/hadoop/hbase/security/provider/example/TestShadeSaslAuthenticationProvider.java
- Fix the unit test by creating new connection in the context of token user
- Add back tryComplete() to `NettyHBaseSaslRpcClientHandler` otherwise PLAIN mech authentication timeouts.
cc @joshelser
> HBASE-28337 Positive connection test in TestShadeSaslAuthenticationProvider runs with Kerberos instead of Shade authentication

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/OperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestAtomicReadQuota.java
Right now atomic operations are just treated as a single write from the quota perspective. Since an atomic operation also encompasses a read, it would make sense to increment readNum and readSize counts appropriately.
cc @bbeaudreault @hgromer @eab148 @bozzkar
> HBASE-28349 Count atomic operations against read quotas

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/OperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestAtomicReadQuota.java
Backport https://github.com/apache/hbase/pull/5668 to branch-2
Right now atomic operations are just treated as a single write from the quota perspective. Since an atomic operation also encompasses a read, it would make sense to increment readNum and readSize counts appropriately.
> Backport "HBASE-28349 Count atomic operations against read quotas" to branch-2

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncRequestFutureImpl.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncProcess.java
- hbase-server/pom.xml
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestClientOperationTimeout.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestAtomicReadQuota.java
edit: Tests have been added, ready for review
> HBASE-28352 HTable batch does not honor RpcThrottlingException waitInterval

- hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java
> HBASE-28204 : Region Canary can take lot more time If any region (except the first region) starts with delete markers

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/MoveWithAck.java
> HBASE-28357 MoveWithAck#isSuccessfulScan for Region movement should use Region End Key for limiting scan to one region only

- hbase-common/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKConfig.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKConfig.java
POC for turning all `hbase.zookeeper.property.*` prefixed properties into system properties.
cc @Apache9
> HBASE-28340 Add trust/key store type to ZK TLS settings handled by HBase

- hbase-common/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKConfig.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/zookeeper/TestZKConfig.java
> HBASE-28340 Add trust/key store type to ZK TLS settings handled by HBase (branch-2)

- hbase-server/src/main/java/org/apache/hadoop/hbase/HBaseRpcServicesBase.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRSQosFunction.java
The updateConfiguration operation called by admin should be considered a higher priority operation and given to the priority queue, but is currently considered to have the same priority as read and write requests. If the handle is occupied, the configuration cannot be updated. In fact, in our scenario, some abnormal phoenix sql is killed by controlling the amount of data that scan can filter with dynamic parameters. Abnormal sql often results in a full handle. In this case, the configuration cannot be dynamically modified to implement emergency traffic limiting.
> HBASE-28238 rpcservice should perform some important admin operation to priority ADMIN_QOS

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/ThrottleQuotaTestUtil.java
In https://github.com/apache/hbase/pull/5666 we introduced default user quotas, but I accidentally called UserQuotaState's default constructor rather than passing in the current timestamp. The consequence is that we're constantly refreshing these default user quotas, and this can be a bottleneck for horizontal cluster scalability.
We have deployed this to a cluster with thousands of unique quota users and verified that the refresh workload was significantly reduced.
@bbeaudreault @hgromer @eab148 @bozzkar
> HBASE-28370 Set `updateTs` on default UserQuotaState

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/DecommissionedHostRejectedException.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HostIsConsideredDecommissionedException.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerReportForDuty.java
Fixes: [HBASE-28342](https://issues.apache.org/jira/browse/HBASE-28342).
This PR adds support to specifying a new configuration value in `hbase-site.xml` which is: `"hbase.master.reject.decommissioned.hosts"`.
When the value is set to `true` the Master will reject RegionServers reporting for duty if and only if their hostnames match any of the servers currently present in the list of decommissioned servers (in the draining servers list). Default value for the configuration is `false`. This configuration is also implemented as live-loadable, the `ServerManager` class now implements the `ConfigurationObserver` interface and listens to changes to this value.
This small patch allows operators to prevent faulty hosts from rejoining the cluster by specifying that configuration property to …
> HBASE-28342 Decommissioned hosts should be rejected by the HMaster

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/DecommissionedHostRejectedException.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerReportForDuty.java
Signed-off by: Nick Dimiduk <ndimiduk@apache.org>
> Backport "HBASE-28342 Decommissioned hosts should be rejected by the HMaster (#5681)" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StorefileRefresherChore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreFileRefresherChore.java
According to semantics, when StoreFile Refresher is turned on, only the area with replicas should be refreshed. **Tables with read-only attributes will not be refreshed.**
There are the following scenarios: Assume that some tables in the database have replica enabled, while others do not. If a table that does not have replica enabled needs to perform migration tasks - first enable readonly and then export the snapshot, StorefileRefresherChore will always refresh the table that does not have replica enabled but performs migration tasks. This is obviously illogical.
Therefore, StorefileRefresherChore needs to determine whether the region has a read-only copy, and refresh it if it has a read-only copy. And tables with read-only properties are not refreshed.
> HBASE-28313 StorefileRefresherChore should not refresh readonly table

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/RegionSizeCalculator.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestRegionSizeCalculator.java
Fixes [HBASE-28354](https://issues.apache.org/jira/browse/HBASE-28354).
This PR filters out the regions with `null` ServerName instances from the regions size calculations.
> HBASE-28354 RegionSizeCalculator throws NPE when regions are in transition

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/RegionSizeCalculator.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestRegionSizeCalculator.java
When a region is in transition, it may briefly have a null ServerName in meta. The RegionSizeCalculator calls RegionLocator.getAllRegionLocations() and does not handle the possibility that a RegionLocation.getServerName() could be null. The ServerName is eventually passed into an Admin call, which results in an NPE.
This has come up in other contexts. For example, taking a look at getAllRegionLocations() impl, we have checks to ensure that we don't call null server names. We need to similarly handle the possibility of nulls in RegionSizeCalculator.
> Backport "HBASE-28354 RegionSizeCalculator throws NPE when regions are in transition (#5699)" to branch-3

- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/AbstractProcedureScheduler.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/LockAndQueue.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/LockStatus.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/SimpleProcedureScheduler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/GlobalQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureScheduler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MetaQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/PeerQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/Queue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SchemaLocking.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableQueue.java
We see unit test failures in Jenkins that look like this:
```
java.lang.IllegalArgumentException: run queue not empty
at org.apache.hbase.thirdparty.com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.load(ProcedureExecutor.java:332)
at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.init(ProcedureExecutor.java:665)
at org.apache.hadoop.hbase.procedure2.ProcedureTestingUtility.restart(ProcedureTestingUtility.java:132)
at org.apache.hadoop.hbase.procedure2.ProcedureTestingUtility.restart(ProcedureTestingUtility.java:100)
at org.apache.hadoop.hbase.master.procedure.MasterProcedureTestingUtility.restartMasterProcedureExecutor(MasterProcedureTestingUtility.java:85)
at …
```
> Backport "HBASE-28403 Improve debugging for failures in procedure tests (#5709)" to branch-3

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/RegionSizeCalculator.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestRegionSizeCalculator.java
When a region is in transition, it may briefly have a null ServerName in meta. The RegionSizeCalculator calls RegionLocator.getAllRegionLocations() and does not handle the possibility that a RegionLocation.getServerName() could be null. The ServerName is eventually passed into an Admin call, which results in an NPE.
This has come up in other contexts. For example, taking a look at getAllRegionLocations() impl, we have checks to ensure that we don't call null server names. We need to similarly handle the possibility of nulls in RegionSizeCalculator.
> Backport "HBASE-28354 RegionSizeCalculator throws NPE when regions are in transition (#5699)" to branch-2.5

- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/AbstractProcedureScheduler.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/LockAndQueue.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/LockStatus.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/SimpleProcedureScheduler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RandomCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureScheduler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MetaQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/PeerQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/Queue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SchemaLocking.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableQueue.java
We see unit test failures in Jenkins that look like this:
```
java.lang.IllegalArgumentException: run queue not empty
at org.apache.hbase.thirdparty.com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.load(ProcedureExecutor.java:332)
at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.init(ProcedureExecutor.java:665)
at org.apache.hadoop.hbase.procedure2.ProcedureTestingUtility.restart(ProcedureTestingUtility.java:132)
at org.apache.hadoop.hbase.procedure2.ProcedureTestingUtility.restart(ProcedureTestingUtility.java:100)
at org.apache.hadoop.hbase.master.procedure.MasterProcedureTestingUtility.restartMasterProcedureExecutor(MasterProcedureTestingUtility.java:85)
at …
```
> Backport "HBASE-28403 Improve debugging for failures in procedure tests (#5709)" to branch-2

- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/AbstractProcedureScheduler.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/LockAndQueue.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/LockStatus.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/SimpleProcedureScheduler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RandomCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureScheduler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MetaQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/PeerQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/Queue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SchemaLocking.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableQueue.java
We see unit test failures in Jenkins that look like this:
```
java.lang.IllegalArgumentException: run queue not empty
at org.apache.hbase.thirdparty.com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.load(ProcedureExecutor.java:332)
at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.init(ProcedureExecutor.java:665)
at org.apache.hadoop.hbase.procedure2.ProcedureTestingUtility.restart(ProcedureTestingUtility.java:132)
at org.apache.hadoop.hbase.procedure2.ProcedureTestingUtility.restart(ProcedureTestingUtility.java:100)
at org.apache.hadoop.hbase.master.procedure.MasterProcedureTestingUtility.restartMasterProcedureExecutor(MasterProcedureTestingUtility.java:85)
at …
```
> Backport "HBASE-28403 Improve debugging for failures in procedure tests (#5709)" to branch-2.6

- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/AbstractProcedureScheduler.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/LockAndQueue.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/LockStatus.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/SimpleProcedureScheduler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RandomCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureScheduler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MetaQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/PeerQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/Queue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SchemaLocking.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerQueue.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TableQueue.java
We see unit test failures in Jenkins that look like this:
```
java.lang.IllegalArgumentException: run queue not empty
at org.apache.hbase.thirdparty.com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.load(ProcedureExecutor.java:332)
at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.init(ProcedureExecutor.java:665)
at org.apache.hadoop.hbase.procedure2.ProcedureTestingUtility.restart(ProcedureTestingUtility.java:132)
at org.apache.hadoop.hbase.procedure2.ProcedureTestingUtility.restart(ProcedureTestingUtility.java:100)
at org.apache.hadoop.hbase.master.procedure.MasterProcedureTestingUtility.restartMasterProcedureExecutor(MasterProcedureTestingUtility.java:85)
at …
```
> Backport "HBASE-28403 Improve debugging for failures in procedure tests (#5709)" to branch-2.5

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/RestoreTablesClient.java
Assume a user has a series of backups: Full1, Inc2, Inc3, where a table has not changed between Full1 and Inc3, but has changed after Inc3.
When restoring that table to Inc3, a log warning was outputted mentioning there was no need for a restore. This message in fact means there is no need for the incremental restore portion of the restore process.
> HBASE-28408 Rephrase confusing log message

- hbase-examples/pom.xml
- hbase-protocol-shaded/pom.xml
- hbase-shaded/pom.xml
- pom.xml
Initial PR is pinned to SNAPSHOT built from https://github.com/apache/hbase-thirdparty/pull/112 .
> HBASE-28379 Upgrade thirdparty dep to 4.1.6

- hbase-protocol-shaded/pom.xml
- hbase-shaded/pom.xml
- pom.xml
Trying out #5693 vs. branch-2.6. In particular, I'm hoping that the unit test suite will be more reliable here. Looks like hbase-examples handled shaded-protobuf slightly differently on this branch.
> Backport "HBASE-28379 Upgrade thirdparty dep to 4.1.6 (#5693)" to branch-2.6

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/OperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RateLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestBlockBytesScannedQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestRateLimiter.java
We've been experiencing RpcThrottlingException with 0ms waitInterval. This seems odd and wasteful, since the client side will immediately retry without backoff. I think the problem is related to the synchronization of RateLimiter.
The TimeBasedLimiter checkQuota method does the following:
```
if (!reqSizeLimiter.canExecute(estimateWriteSize + estimateReadSize)) {
RpcThrottlingException.throwRequestSizeExceeded(
reqSizeLimiter.waitInterval(estimateWriteSize + estimateReadSize));
} 
```
Both canExecute and waitInterval are synchronized, but we're calling them independently. So it's possible under high concurrency for canExecute to return false, but then waitInterval returns 0 (would have been true).
This simplifies the API by having canExecute return the waitInterval, it being greater than …
> HBASE-28359 Improve quota RateLimiter synchronization

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/WALSyncTimeoutIOException.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/WALUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AsyncFSWALProvider.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WAL.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestWarmupRegion.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestWALSyncTimeoutException.java
Porting of change for HBASE-27230 to branch-2. (#4641)
Change-Id: I4a413143681376235a250d164fec36ff9eb377b4
> HBASE-27230 RegionServer should be aborted when WAL.sync throws Timeout.

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java
Our objective is to remove ZooKeeper from our public interface, remaking it as an internal concern. Connecting to a cluster via ZooKeeper quorum will be considered deprecated starting in 2.6. Our default connection mechanism will switch to via RPC in 3.0 And finally we intend to remove the ZooKeeper connection mechanism from client-facing APIs in 4.0.
> HBASE-23324 Deprecate clients that connect to Zookeeper

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java
Our objective is to remove ZooKeeper from our public interface, remaking it as an internal concern. Connecting to a cluster via ZooKeeper quorum will be considered deprecated starting in 2.6. Our default connection mechanism will switch to via RPC in 3.0 And finally we intend to remove the ZooKeeper connection mechanism from client-facing APIs in 4.0.
> Backport "HBASE-23324 Deprecate clients that connect to Zookeeper (#5745)" to branch-3

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java
Our objective is to remove ZooKeeper from our public interface, remaking it as an internal concern. Connecting to a cluster via ZooKeeper quorum will be considered deprecated starting in 2.6. Our default connection mechanism will switch to via RPC in 3.0 And finally we intend to remove the ZooKeeper connection mechanism from client-facing APIs in 4.0.
> Backport "HBASE-23324 Deprecate clients that connect to Zookeeper (#5745)" to branch-2

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java
Our objective is to remove ZooKeeper from our public interface, remaking it as an internal concern. Connecting to a cluster via ZooKeeper quorum will be considered deprecated starting in 2.6. Our default connection mechanism will switch to via RPC in 3.0 And finally we intend to remove the ZooKeeper connection mechanism from client-facing APIs in 4.0.
> Backport "HBASE-23324 Deprecate clients that connect to Zookeeper (#5745)" to branch-2.6

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/HBaseFsck.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/hbck/ReplicationChecker.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestHBaseFsckWithoutTableHbaseReplication.java
Details see: [HBASE-28395](https://issues.apache.org/jira/browse/HBASE-28395)
> HBASE-28395 TableNotFoundException when executing 'hbase hbck'

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/ExceedOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/OperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RateLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestBlockBytesScannedQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/ThrottleQuotaTestUtil.java
https://issues.apache.org/jira/browse/HBASE-28385
Let's say you're running a table scan with a throttle of 100MB/sec per RegionServer. Ideally your scans are going to pull down large results, often containing hundreds or thousands of blocks.
You will estimate each scan as costing a single block of read capacity, and if your quota is already exhausted then the server will evaluate the backoff required for your estimated consumption (1 block) to be available. This will often be ~1ms, causing your retries to basically be immediate.
Obviously it will routinely take much longer than 1ms for 100MB of IO to become available in the given configuration, so your retries will be destined to fail. At worst this can cause a saturation of your server's RPC layer, and at best this causes erroneous …
> HBASE-28385 make Scan estimates more realistic

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegionFlusherAndCompactor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
Details see: [HBASE-28427](https://issues.apache.org/jira/browse/HBASE-28427)
> HBASE-28427 FNFE related to 'master:store' when moving archived hfiles to global archived dir

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/FixedIntervalRateLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RateLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestRateLimiter.java
See https://issues.apache.org/jira/browse/HBASE-28453
The AverageIntervalRateLimiter causes tiny wait intervals which can result in DDOS at worst, or poor UX at best. See below where we implemented a 10k request/second/machine quota at 10:43 and saw requests fall into immediate retry loops and inundate the cluster:
The FixedIntervalRateLimiter causes large wait intervals which make it difficult to fully utilize a quota. See below where we were stuck only utilizing ~20% of our quota consistently. After restarting the cluster to use a FIRL with a 100ms refill interval we were able to achieve much better utilization:
As suggested above, this PR introduces support for a refill interval that is <= the TimeUnit of a FixedIntervalRateLimiter. This means that you can define a quota in a …
> HBASE-28453 FixedIntervalRateLimiter support for a shorter refill interval

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupSystemTable.java
For details see: [HBASE-28449 ](https://issues.apache.org/jira/browse/HBASE-28449)
> HBASE-28449 - fix backupSystemTable prefix scans

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
https://issues.apache.org/jira/browse/HBASE-27990
This PR adds a precheck for `hbase.blockcache.minblocksize` such that it must be positive.
(1) set hbase.blockcache.minblocksize=0
(2) run org.apache.hadoop.hbase.io.hfile.TestCacheConfig#testBucketCacheConfigL1L2Setup
The test throws a IllegalArgumentException rather than a division by zero error.
> HBASE-27990. BucketCache causes ArithmeticException due to improper blockSize value checking

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/ByteBuffAllocator.java
https://issues.apache.org/jira/browse/HBASE-27989
This PR prohibits setting `hbase.server.allocator.buffer.size` to 0 or negative. A warning is also added if the minimum size for reservoir use is set to zero.
1. set `hbase.server.allocator.buffer.size=0`
2. run `org.apache.hadoop.hbase.io.hfile.bucket.TestBucketCacheRefCnt#testInBucketCache`
The test now throws an `IllegalArgumentException` with detailed message.
> HBASE-27989. ByteBuffAllocator causes ArithmeticException due to improper poolBufSize value checking

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/ServerManager.java
> HBASE-28366 Mis-order of SCP and regionServerReport results into region inconsistencies

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestPrefetchPersistence.java
While backporting original PR to branch-2, I still got some failures for TestBucketCachePersister.testPrefetchBlockEvictionWhilePrefetchRunning. I believe I was using the wrong offset in BucketCache.notifyFileCachingCompleted, so if the eviction happens while in the loop of notifyFileCachingCompleted, we fail to acknowledge the eviction and still consider the file fully cached.
> [ADDENDUM] HBASE-28458 BucketCache.notifyFileCachingCompleted may incorrectly consider a file fully cached (#5777)

- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckEmptyRegionInfo.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckInconsistentRegions.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckOrphanRegionsOnFS.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckOrphanRegionsOnRS.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckOverlapRegions.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckRegionDetails.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckRegionHoles.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckServerName.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/HbckUnknownServers.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/hbck/HbckConfigFactory.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/hbck/model/HbckMetrics.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/hbck/resource/HbckMetricsResource.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/http/TestHbckMetricsResource.java
`/hbck/hbck-metrics/` will provide entire HBCK Report in JSON Format. Also each inconsistency can be requested separately using their endpoints.
Endpoint list for each inconsistencies :
Orphan Region on FS : `/hbck/hbck-metrics/orphan-regions-on-fs`
Orphan Region on RS : `/hbck/hbck-metrics/orphan-egions-on-rs`
Inconsistent Regions : `/hbck/hbck-metrics/inconsistent-regions`
Region Holes : `/hbck/hbck-metrics/region-holes`
Region Overlaps : `/hbck/hbck-metrics/region-overlaps`
Unknown Servers : `/hbck/hbck-metrics/unknown-servers`
Empty Region Info : `/hbck/hbck-metrics/empty-regioninfo`
> HBASE-26192 Master UI hbck should provide a JSON formatted output option

- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdCompressor.java
- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdDecompressor.java
The zstd documentation recommends re-using context objects when possible, because their creation has some expense. They can be more cheaply reset than re-created. In this PR, create one `Zstd(De)compressCtx` for the lifetime of a `Compressor` or `Decompressor` object.
> HBASE-28485: Re-use ZstdDecompressCtx/ZstdCompressCtx for performance

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/CompressionTest.java
CompressionTest should close the FileSystem object otherwise some resources may not be released, which caused an Ozone output stream user thread to hang.
Deployed on a cluster, ran the same command `hbase org.apache.hadoop.hbase.util.CompressionTest ofs://ozone/vol1/bucket1/test_file.txt snappy` to verify it no longer hangs on an Ozone path.
> HBASE-28448 CompressionTest hangs when run over a Ozone ofs path

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFile.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/PrefetchExecutor.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/PrefetchExecutorNotifier.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetch.java
Make the prefetch delay configurable. The prefetch delay is associated to hbase.hfile.prefetch.delay configuration. There are some cases where configuring hbase.hfile.prefetch.delay would help in achieving better throughput.
> HBASE-28292 Make Delay prefetch property to be dynamically configured

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
The java method comment contains a typo. 
The comment incorrectly states "Region name to assign" instead of "Region name to unassign".
> HBASE-28470 Fix typo in Java method comment

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheConfig.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStore.java
Make following properties dynamically configured, 
hbase.rs.evictblocksonclose
hbase.rs.cacheblocksonwrite
hbase.block.data.cacheonread
for use case scenarios where configuring them dynamically would help in achieving better throughput.
> HBASE-28517 Make properties dynamically configured

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DataTieringManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetch.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestDataTieringManager.java
As a part of cache blocks eviction when the cache is full,
the data-tiering logic is integrated into the freeSpace code path
to identify the cold data files and evict the blocks associated with
those files.
The list of files is traversed to identify the cold files based
on the hot-data-age configuration and also the max timestamp associated
with the files.
The blocks associated with those cold files are evicted first and then
the existing logic of LFU blocks is executed to further evict the blocks.
> HBASE-28468: Integrate the data-tiering logic into cache evictions.

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DataTieringManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestDataTieringManager.java
Data-tiering feature should not be enabled by default, since this feature has specific use-cases. Hence, introduce a system-wide configuration to enable the feature.
Avoid the code data-tiering code paths when this system-wide configuration is not enabled.
Change-Id: I308119884c42173cfef3b23c360a842c7f516977
> HBASE-28535: Add a region-server wide key to enable data-tiering.

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/TakeSnapshotHandler.java
Details see: [HBASE-28575](https://issues.apache.org/jira/browse/HBASE-28575)
> HBASE-28575 Always printing error log when snapshot table

- hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKMainServer.java
[HBASE-28563](https://issues.apache.org/jira/browse/HBASE-28563)
- Add `close` to HACK_UNTIL_ZOOKEEPER_1897_ZooKeeperMain
- Close the ZooKeeper when a timeout occurs
> HBASE-28563 Closing ZooKeeper in ZKMainServer

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/CompressionTest.java
This bug was found via HDDS-10564.
(cherry picked from commit adc79a0a9c2b579915a902f611a66edfddf3149c)
> HBASE-28448 CompressionTest hangs when run over a Ozone ofs path (#5771)

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HFileOutputFormat2.java
> HBASE-28586 Backport HBASE-24791 Improve HFileOutputFormat2 to avoid always call getTableRelativePath method

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/TableDescriptorBuilder.java
https://issues.apache.org/jira/browse/HBASE-28581
> HBASE-28581 Remove deprecated methods in TableDescriotorBuilder

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/HBackupFileSystem.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManifest.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/RestoreTablesClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/TableBackupClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/BackupUtils.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestFullBackup.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java
In older versions of HBase's backup mechanism, a manifest was written per table being backed up. This was since refactored to one manifest per backup, but the manifest code was not updated. A concrete issue with the old code was that the manifest for full backups did not correctly list the tables included in the backup.
> HBASE-28502 Cleanup old backup manifest logic

- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/TestPerformanceEvaluation.java
Enable PE to load any custom implementation of tests at runtime
> HBASE-27938 - PE load any custom implementation of tests at runtime

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/HBackupFileSystem.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManifest.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/RestoreTablesClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/TableBackupClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/BackupUtils.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestFullBackup.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java
In older versions of HBase's backup mechanism, a manifest was written per table being backed up. This was since refactored to one manifest per backup, but the manifest code was not updated. A concrete issue with the old code was that the manifest for full backups did not correctly list the tables included in the backup.
> Backport "HBASE-28502 Cleanup old backup manifest logic (#5871)" to branch-3

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/HBackupFileSystem.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManifest.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/RestoreTablesClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/TableBackupClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/BackupUtils.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestFullBackup.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java
In older versions of HBase's backup mechanism, a manifest was written per table being backed up. This was since refactored to one manifest per backup, but the manifest code was not updated. A concrete issue with the old code was that the manifest for full backups did not correctly list the tables included in the backup.
> Backport "HBASE-28502 Cleanup old backup manifest logic (#5871)" to branch-2

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/HBackupFileSystem.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManifest.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/RestoreTablesClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/TableBackupClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/BackupUtils.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestFullBackup.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java
In older versions of HBase's backup mechanism, a manifest was written per table being backed up. This was since refactored to one manifest per backup, but the manifest code was not updated. A concrete issue with the old code was that the manifest for full backups did not correctly list the tables included in the backup.
> HBASE-28502 Cleanup old backup manifest logic (#5871)

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupDelete.java
The incremental backup set is the set of tables included when an incremental backup is created, it is managed per backup root dir and contains all tables that are present in at least one backup (in that root dir).
The incremental backup set can only shrink when backups are deleted. However, the implementation was incorrect, causing this set to never be able to shrink.
> HBASE-28568 Fix incremental backup set shrinking

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupDelete.java
Import the correct shaded Guava and run spotless:apply.
> HBASE-28568 Incremental backup set does not correctly shrink (addendum)

- src/site/xdoc/downloads.xml
I checked all the links here and they seem good.
One thing I noticed is that my CHANGES.md file still says `## Release 2.6.0 - Unreleased (as of 2024-04-29)`. I'm not sure if I missed a step, or if I should just manually commit another change to the file which updates that line
> HBASE-28236 Add 2.6.0 to downloads page

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupDelete.java
The incremental backup set is the set of tables included when an incremental backup is created, it is managed per backup root dir and contains all tables that are present in at least one backup (in that root dir).
The incremental backup set can only shrink when backups are deleted. However, the implementation was incorrect, causing this set to never be able to shrink.
> Backport "HBASE-28568 Incremental backup set does not correctly shrink (#5876)" to branch-3

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupDelete.java
The incremental backup set is the set of tables included when an incremental backup is created, it is managed per backup root dir and contains all tables that are present in at least one backup (in that root dir).
The incremental backup set can only shrink when backups are deleted. However, the implementation was incorrect, causing this set to never be able to shrink.
> Backport "HBASE-28568 Incremental backup set does not correctly shrink (#5876)" to branch-2.6

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
Issue Link: https://issues.apache.org/jira/browse/HBASE-28599 ( reported by @robiee17 )
Below is written by @robiee17
```
Issue:
`RowTooBigException` is thrown when a duplicate increment RPC call is attempted.
Expected Behavior:
1. The initial RPC increment call should time out for some reason.
2. The duplicate RPC call should be converted to a GET request and fetch the result that I am trying to increment.
3. The result should contain only the qualifier that I am attempting to increment.
Actual Behavior:
1. The initial RPC increment call timed out, which is expected.
2. The duplicate RPC call is converted to a GET request but fails to clone the qualifier into the GET request.
3. Hence, the GET request attempts to retrieve all qualifiers for the given row and columnfamily, resulting in a …
```
> HBASE-28599 RowTooBigException is thrown when duplicate increment RPC call is attempted

- pom.xml
> HBASE-28605 Add ErrorProne ban on Hadoop shaded thirdparty jars

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCacheKey.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CombinedBlockCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFile.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileWriterImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DataTieringManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionFileSystem.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileWriter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/TimeRangeTracker.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestDataTieringManager.java
This PR introduces time-based priority caching for the `hbase.rs.cachecompactedblocksonwrite` configuration. This feature enhances block caching efficiency by prioritizing blocks based on their time stamps during the writing of compacted files.
> HBASE-28469: Integration of time-based priority caching into compaction paths

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheConfig.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestDataTieringManager.java
Whenever the blocks of the file are read from the file system, they are cached into the block-cache if cache-on-read configuration is enabled. This configuration is enabled by default. However, with the time-based priority caching, we may not want to cache the blocks of the cold file.
In this PR, we add checks to avoid the caching of cold data files and cache the blocks of hot data files.
Change-Id: Ia07d791a841640e468c3ba33acebba81dbecbbc2
> HBASE-28467: Add time-based priority caching checks for cacheOnRead code paths.

- pom.xml
> Backport "HBASE-28605 Add ErrorProne ban on Hadoop shaded thirdparty jars (#5918)" to branch-3

- pom.xml
> Backport "HBASE-28605 Add ErrorProne ban on Hadoop shaded thirdparty jars (#5918)" to branch-2

- pom.xml
> Backport "HBASE-28605 Add ErrorProne ban on Hadoop shaded thirdparty jars (#5918)" to branch-2.6

- pom.xml
> Backport "HBASE-28605 Add ErrorProne ban on Hadoop shaded thirdparty jars (#5918)" to branch-2.5

- src/main/asciidoc/_chapters/performance.adoc
- src/main/asciidoc/_chapters/schema_design.adoc
fix the explanation for the configuration of hbase.ipc.sserver.callqueue.read.ratio
> HBASE-28630 fix the explanation for the configuration of hbase.ipc.sserver.callqueue.read.ratio

- hbase-server/src/main/resources/hbase-webapps/master/snapshot.jsp
- hbase-server/src/main/resources/hbase-webapps/master/snapshotsStats.jsp
- hbase-server/src/main/resources/hbase-webapps/master/userSnapshots.jsp
- hbase-shell/src/main/ruby/shell/commands/list_snapshots.rb
Details see: [HBASE-28614](https://issues.apache.org/jira/browse/HBASE-28614)
After applying this commit.
On HBase UI:  
On hbase shell:  
```
hbase:027:0> list_snapshots
SNAPSHOT                                    TABLE + CREATION TIME + TTL(Sec)
expired_snap01                             t01 (2024-05-26 14:18:16 +0800) 10 (Expired)
snap01                                     t01 (2024-05-25 22:28:13 +0800) FOREVER
snap02                                     t01 (2024-05-25 22:28:37 +0800) 100000
3 row(s)
Took 0.0209 seconds
=> ["expired_snap01", "snap01", "snap02"]
```
> HBASE-28614 Introduce a field to display whether the snapshot is expired

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java
https://issues.apache.org/jira/browse/HBASE-28625
> HBASE-28625 ExportSnapshot should verify checksums for the source file and the target file

- dev-support/hbase_docker/m1/Dockerfile
Tested hadolint <Dockerfile> and verified that it doesn't throw any error.
> HBASE-28618: Fixed hadolint check in nightly build.

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/mapreduce/MapReduceBackupMergeJob.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupMerge.java
HBASE-28539 Fix merging of incremental backups when the backup filesystem is not the same as the one underpinning HBase itself.
> HBASE-28539 Merge of incremental backups fails if backups are on a separate FileSystem

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/mapreduce/MapReduceBackupMergeJob.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupMerge.java
When the backups are stored on a location that is not the DistributedFilesystem underpinning HBase itself merging of incremental backups fails. Detected with backups stored on S3A, but can be reproduced with any other (like LocalFilesystem).
> Backport "HBASE-28539 Merge of incremental backups fails if backups are on a separate FileSystem (#5867)" to branch-3

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/mapreduce/MapReduceBackupMergeJob.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupMerge.java
When the backups are stored on a location that is not the DistributedFilesystem underpinning HBase itself merging of incremental backups fails. Detected with backups stored on S3A, but can be reproduced with any other (like LocalFilesystem).
> Backport "HBASE-28539 Merge of incremental backups fails if backups are on a separate FileSystem (#5867)" to branch-2

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/mapreduce/MapReduceBackupMergeJob.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupMerge.java
When the backups are stored on a location that is not the DistributedFilesystem underpinning HBase itself merging of incremental backups fails. Detected with backups stored on S3A, but can be reproduced with any other (like LocalFilesystem).
> Backport "HBASE-28539 Merge of incremental backups fails if backups are on a separate FileSystem (#5867)" to branch-2.6

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RSProcedureDispatcher.java
Added request log to RSProcedureDispatcher during retries
Jira: HBASE-28049
> HBASE-28049 RSProcedureDispatcher to log the request details during retries

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java
Do lease recovery as a last resort if async wal fails to close WAL file.
This issue will make WAL on Ozone more resilient because Ozone does not support renaming open files (which happens due to WAL log archiving).
> HBASE-28637 asyncwal should attempt to recover lease if close fails

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/WALEntryStream.java
There was one code path within a `if (reader != null) {}` block that did not return and end the method early, thus allowing a subsequent line to re-create the `reader`. This was not the intention of the author. This PR closes this loophole.
> HBASE-28666: In WALEntryStream, always use current WALTailingReader if one exists

- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/client/Client.java
also expose HttpClientConnectionManager
> HBASE-28671 Add close method to REST client

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/master/BackupLogCleaner.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/master/TestBackupLogCleaner.java
See https://issues.apache.org/jira/browse/HBASE-28680
We have been trying to setup daily incremental backups for hundreds of clusters at my day job. Recently we discovered that old WALs were piling up across many clusters inline with when we began running incremental backups.
This led to the realization that [the BackupLogCleaner will always skip **archived** HMaster WALs](https://github.com/HubSpot/hbase/blob/3a170578b04d5947c655319f1b8d8475ccb6bb4e/hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/util/BackupUtils.java#L364-L367). This is a problem because, if a cleaner is skipping a given file, then [the CleanerChore will never delete it](https://github.com/apache/hbase/blob/fb988373c1cd0184400fe17c4323fbf0de07c951/hbase-server/src/main/java/org/apache/hadoop/hbase/master/cleane …
> HBASE-28680 BackupLogCleaner should clean up archived HMaster logs

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/master/BackupLogCleaner.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/master/TestBackupLogCleaner.java
We have been trying to setup daily incremental backups for hundreds of clusters at my day job. Recently we discovered that old WALs were piling up across many clusters inline with when we began running incremental backups.
This led to the realization that the BackupLogCleaner will always skip archived HMaster WALs. This is a problem because, if a cleaner is skipping a given file, then the CleanerChore will never delete it.
This seems like a misunderstanding of what it means to "skip" a WAL in a BaseLogCleanerDelegate, and, instead, we should always return these HMaster WALs as deletable from the perspective of the BackupLogCleaner. We could subject them to the same scrutiny as RegionServer WALs: are they older than the most recent successful backup? But, if I understand correctly, HMaster …
> Backport "HBASE-28680 BackupLogCleaner causes HMaster WALs to pile up indefinitely (#6006)" to branch-3

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/master/BackupLogCleaner.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/master/TestBackupLogCleaner.java
We have been trying to setup daily incremental backups for hundreds of clusters at my day job. Recently we discovered that old WALs were piling up across many clusters inline with when we began running incremental backups.
This led to the realization that the BackupLogCleaner will always skip archived HMaster WALs. This is a problem because, if a cleaner is skipping a given file, then the CleanerChore will never delete it.
This seems like a misunderstanding of what it means to "skip" a WAL in a BaseLogCleanerDelegate, and, instead, we should always return these HMaster WALs as deletable from the perspective of the BackupLogCleaner. We could subject them to the same scrutiny as RegionServer WALs: are they older than the most recent successful backup? But, if I understand correctly, HMaster …
> Backport "HBASE-28680 BackupLogCleaner causes HMaster WALs to pile up indefinitely (#6006)" to branch-2

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/master/BackupLogCleaner.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/master/TestBackupLogCleaner.java
We have been trying to setup daily incremental backups for hundreds of clusters at my day job. Recently we discovered that old WALs were piling up across many clusters inline with when we began running incremental backups.
This led to the realization that the BackupLogCleaner will always skip archived HMaster WALs. This is a problem because, if a cleaner is skipping a given file, then the CleanerChore will never delete it.
This seems like a misunderstanding of what it means to "skip" a WAL in a BaseLogCleanerDelegate, and, instead, we should always return these HMaster WALs as deletable from the perspective of the BackupLogCleaner. We could subject them to the same scrutiny as RegionServer WALs: are they older than the most recent successful backup? But, if I understand correctly, HMaster …
> Backport "HBASE-28680 BackupLogCleaner causes HMaster WALs to pile up indefinitely (#6006)" to branch-2.6

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshot.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshotAdjunct.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshotV1NoCluster.java
https://issues.apache.org/jira/browse/HBASE-28656
> HBASE-28656 Optimize the verifyCopyResult logic in ExportSnapshot

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/SnapshotWithAclTestBase.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSnapshotWithAcl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSnapshotWithAclAsyncAdmin.java
Details see: [HBASE-28658](https://issues.apache.org/jira/browse/HBASE-28658)
> HBASE-28658 The failsafe snapshot should be deleted after rollback successfully

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/SnapshotWithAclTestBase.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSnapshotWithAcl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSnapshotWithAclAsyncAdmin.java
Jira issue: [HBASE-28658](https://issues.apache.org/jira/browse/HBASE-28658)
master branch PR: #5984
> HBASE-28658 The failsafe snapshot should be deleted after rollback successfully (for branch-2)

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupBase.java
See https://issues.apache.org/jira/browse/HBASE-28687
If the backup system tables become disabled, then we enter a state which the backup client will not recover from. Without manual intervention, every subsequent backup attempt will fail on [BackupSystemTable's calls to waitForSystemTable](https://github.com/apache/hbase/blob/3a3dd66e21da3f85c72d75605857713716d579fb/hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java#L214-L215).
This checkSystemTable method already ensures that the tables exist — it should also ensure that the tables are enabled before we await that condition.
Alternatively, we could fast-fail if the tables are disabled rather than awaiting an enabled state that will never occur.
cc @ndimiduk @charlesconnell @hgromer
> HBASE-28687 BackupSystemTable#checkSystemTable should ensure system tables are enabled

- hbase-server/src/main/java/org/apache/hadoop/hbase/wal/OutputSink.java
> HBASE-28703 Data race in RecoveredEditsOutputSink while closing writers

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
https://issues.apache.org/jira/browse/HBASE-28672
At my day job we are trying to implement [default quotas](https://issues.apache.org/jira/browse/HBASE-27800) for a variety of access patterns. We began by introducing a default read IO limit per-user, per-machine — this has been very successful in reducing hotspots, even on clusters with thousands of distinct users.
While implementing a default writes/second throttle, I realized that doing so would put us in a precarious situation where large enough batches may never succeed. If your batch size is greater than your TimeLimiter's max throughput, then you will always fail in the quota estimation stage; this will stick the client in a backoff-and-retry loop until it times out. Meanwhile [IO estimates are more …
> HBASE-28672 Ensure large batches are not indefinitely blocked by quotas

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CombinedBlockCache.java
Remove log Warn: Cache key had block type null, but was found in L1
> [HBASE-28364] Warn: Cache key had block type null, but was found in L1

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
(cherry picked from commit 0e8cfdb507723729a2cade50ea364149eec3466c) (cherry picked from commit b88129617ca1bb06948bd07a972c8a4f2121c02c)
Conflicts:
hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
Change-Id: Ia704c1b36b99be345d11a70ac2452dea094e9575
> HBASE-28637 asyncwal should attempt to recover lease if close fails (#5962)

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLog.java
> HBASE-28665 WALs not marked closed when there are errors in closing WALs

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestCopyTable.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshot.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/RestoreSnapshotHelper.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestRestoreSnapshotHelper.java
Details see: [HBASE-28704](https://issues.apache.org/jira/browse/HBASE-28704)
> HBASE-28704 The expired snapshot can be read by CopyTable or ExportSnapshot

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/IncreasingToUpperBoundRegionSplitPolicy.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionSplitPolicy.java
Details see: [HBASE-28727](https://issues.apache.org/jira/browse/HBASE-28727)
> HBASE-28727 SteppingSplitPolicy may not work when table enables region replication

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/mapreduce/MapReduceBackupCopyJob.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/mapreduce/TestMapReduceBackupCopyJob.java
The MapReduceBackupCopyJob class provides no means for updating DistCp job options. This means that you're stuck with defaults, which isn't always desirable. For example, my workplace would like the freedom to deviate from at least two DistCp defaults:
`distcp.direct.write` — we would like to set this to true, because writing and renaming tmp files is expensive in S3 (where we store our backups).
we would also like control over the number of mappers that DistCp will run
It is not the prettiest solution, but I'm proposing that we support DistCp customizations via the given backup client configuration like [this.](https://github.com/HubSpot/hbase/compare/hubspot-2.6...HubSpot:hbase:backup-distcp-options) It's necessary to do this conf -> arg conversion because we still want to use [DistCp's …
> HBASE-28686 MapReduceBackupCopyJob should support custom DistCp options

- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaRetriever.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaObserverChore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/SnapshotQuotaObserverChore.java
- hbase-server/src/main/resources/hbase-webapps/master/quotas.jsp
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/SpaceQuotaHelperForTests.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestMasterQuotasObserver.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaAdmin.java
Every call to `HBaseAdmin#getQuota()` opens a new `Connection`, and then closes it. As far as I can tell, this is pointless, since it could use the existing `Connection` object held by the `HBaseAdmin`. Change this and other uses of QuotaRetriever to use existing Connections.
> HBASE-28716: Users of QuotaRetriever should pass an existing connection (master)

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupDriver.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupInfo.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRequest.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRestoreConstants.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupCommands.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManager.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/FullTableBackupClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/TableBackupClient.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupBase.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupMerge.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java
https://issues.apache.org/jira/browse/HBASE-28702
> HBASE-28702 TestBackupMerge fails 100% of times on flaky dashboard

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ZKConnectionRegistry.java
- hbase-zookeeper/src/test/java/org/apache/hadoop/hbase/zookeeper/TestReadOnlyZKClient.java
> HBASE-28745 :  Default Zookeeper ConnectionRegistry APIs timeout should be less

- hbase-server/src/main/java/org/apache/hadoop/hbase/client/TableSnapshotScanner.java
Disable the mslab altogether (via hbase.hregion.memstore.mslab.enabled set to false) within snapshot based mapper
> HBASE-28743 Fixes NPE for TableSnapshotScanner by disabling mslab

- hbase-compression/hbase-compression-aircompressor/src/main/java/org/apache/hadoop/hbase/io/compress/aircompressor/ZstdCodec.java
- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdCodec.java
HADOOP-18810 added io.compression.codec.zstd.buffersize in core-default.xml with default value as 0, so default value of hbase.io.compress.zstd.buffersize will become 0 instead of ZSTD_BUFFER_SIZE_DEFAULT (256 * 1024) when not configured in hbase-site.xml.
> HBASE-28655 IllegalArgumentException: Illegal bufferSize thrown when hbase.io.compress.zstd.buffersize is not configured

- hbase-compression/hbase-compression-aircompressor/src/main/java/org/apache/hadoop/hbase/io/compress/aircompressor/ZstdCodec.java
- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdCodec.java
HADOOP-18810 added io.compression.codec.zstd.buffersize in core-default.xml with default value as 0, so default value of hbase.io.compress.zstd.buffersize will become 0 instead of ZSTD_BUFFER_SIZE_DEFAULT (256 * 1024) when not configured in hbase-site.xml.
(cherry picked from commit 73f2710e47557218dcf92cc3e7b1788dfbb57fd2)
> HBASE-28655 IllegalArgumentException: Illegal bufferSize thrown when hbase.io.compress.zstd.buffersize is not configured 

- hbase-server/src/main/resources/hbase-webapps/regionserver/region.jsp
Details see: [HBASE-28753](https://issues.apache.org/jira/browse/HBASE-28753)
> HBASE-28753 FNFE may occur when accessing the region.jsp of the replica region

- hbase-server/src/main/resources/hbase-webapps/regionserver/region.jsp
master PR: #6117
Jira: [HBASE-28753](https://issues.apache.org/jira/browse/HBASE-28753)
> HBASE-28753 FNFE may occur when accessing the region.jsp of the replica region (branch-2)

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/regionserver/CompactionTool.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactionToolNpeFix.java
Fixes NPE issue with initialization of ChunkCreator by disabling the mslab
> HBASE-28742 Fixes NPE for CompactionTool when mslab enabled

- hbase-server/src/main/resources/hbase-webapps/regionserver/region.jsp
Jira: [HBASE-28753](https://issues.apache.org/jira/browse/HBASE-28753)
master PR: #6117 
branch-2 PR: #6118
> HBASE-28753 FNFE may occur when accessing the region.jsp of the replica region (branch-2.5) 

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/RestoreDriver.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupCommands.java
https://issues.apache.org/jira/browse/HBASE-28389
> HBASE-28389 HBase backup yarn queue parameter ignored

- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/RegionObserver.java
https://issues.apache.org/jira/browse/HBASE-28648
> HBASE-28648 Change the deprecation cycle for RegionObserver.postInstantiateDeleteTracker

- pom.xml
Backports https://github.com/apache/hbase/pull/6157
> Backport "HBASE-28784 Exclude samples and release-documentation zip of jaxws-ri from output tarball" to branch-2.6

- pom.xml
Backports https://github.com/apache/hbase/pull/6157
> Backport "HBASE-28784 Exclude samples and release-documentation zip of jaxws-ri from output tarball" to branch-2.5

- bin/hbase
Backports https://github.com/apache/hbase/pull/6162
> Backport "HBASE-28786 Fix classname for command: copyreppeers in bin/hbase" to branch-2

- bin/hbase
Backports https://github.com/apache/hbase/pull/6162
> Backport "HBASE-28786 Fix classname for command: copyreppeers in bin/hbase" to branch-2.6

- hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestFSUtils.java
Simply check and ignore silently if the underlying FS does not support storage policy.
the hasPathCapability() API is Hadoop 3.2 and above. So do not cherrypick this change to HBase 2.x or lower.
> HBASE-27746 Check if the file system supports storage policy before invoking setStoragePolicy()

- dev-support/Jenkinsfile_GitHub
Correct typo in JenkinsFile : `s/Hadoop3/Hadoop2/`
> HBASE-28732 Fix typo in Jenkinsfile_Github for jdk8 hadoop2 check

- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/RemoteProcedureDispatcher.java
- hbase-protocol-shaded/src/main/protobuf/Admin.proto
- hbase-protocol-shaded/src/main/protobuf/RegionServerStatus.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/CloseRegionProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/OpenRegionProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionRemoteProcedureBase.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/FlushRegionProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RSProcedureDispatcher.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SnapshotRegionProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SnapshotVerifyProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SplitWALRemoteProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SwitchRpcThrottleRemoteProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/replication/ClaimReplicationQueueRemoteProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/replication/RefreshPeerProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionServerServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RemoteProcedureResultReporter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SplitRequest.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/AssignRegionHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/CloseRegionHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/OpenRegionHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/RSProcedureHandler.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/UnassignRegionHandler.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/MockNoopMasterServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestServerRemoteProcedure.java
…res (#1)
* HBASE-28690 added masterStartCode as fencing token for remote procedures
* HBASE-28690 comments updated
* HBASE-28690 add masterStartCode for RemoteProcedureRequest
* HBASE-28690 used master active time for fencing and review comments
* HBASE-28690 minor comment addition
* HBASE-28690 spotless apply
* HBASE-28690 reduce log line length for checkstyle
---------
> HBASE-28690 Aborting Active HMaster is not rejecting reportRegionStateTransition if procedure is initialised by next Active master

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/HBaseTrustManager.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/TestHBaseTrustManager.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/crypto/tls/X509TestContext.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/OptionalSslHandlerWithHostPort.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/TestMutualTlsClientSideNonLocalhost.java
- Added our version of `OptionalSslHandler` which carries hostport information
- Removed the (IMHO) unnecessary reverse DNS lookup from `initSSL`
- Unit test to cover plaintext and TLS-only cases
> HBASE-28777 mTLS client hostname verification doesn't work with OptionalSslHandler

- hbase-examples/pom.xml
- hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestsDriver.java
- hbase-protocol-shaded/pom.xml
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/compaction/MajorCompactor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestSpaceQuotasWithSnapshots.java
- pom.xml
Update hbase-thirdparty to 4.1.8.
Added staging repository for compilation and build, will remove it when 4.1.8 is officially released.
> HBASE-28793 Update hbase-thirdparty to 4.1.8

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
https://issues.apache.org/jira/browse/HBASE-28802
> HBASE-28802 Log the IP when hbase.server.useip.enabled is set to true

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupInfo.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
https://issues.apache.org/jira/browse/HBASE-28643
The BackupInfo class has a failedMsg field which is a string of unbounded length. When a DistCp job fails then its failure message contains all of its source paths, and its failure message gets propagated to this failedMsg field on the given BackupInfo.
If a DistCp job has enough source paths, then this will result in backup status updates being rejected:
```
java.lang.IllegalArgumentException: KeyValue size too large
at org.apache.hadoop.hbase.client.ConnectionUtils.validatePut(ConnectionUtils.java:513)
at org.apache.hadoop.hbase.client.HTable.validatePut(HTable.java:1095)
at org.apache.hadoop.hbase.client.HTable.lambda$put$3(HTable.java:564)
at org.apache.hadoop.hbase.trace.TraceUtil.trace(TraceUtil.java:187)
at …
```
> HBASE-28643 An unbounded backup failure message can cause an irrecoverable state for the given backup

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
https://issues.apache.org/jira/browse/HBASE-28697
I've been thinking through the incremental backup order of operations, and I think we delete rows from the bulk loads system table too early and, consequently, make it possible to produce a "successful" incremental backup that is missing bulk loads.
To summarize the steps here, starting in `IncrementalTableBackupCilent#execute`:
1. We take an incremental backup of the WALs generated since the last backup
2. We ensure any bulk loads done since the last backup are appropriately represented in the new backup by going through the system table and copying the appropriate files to the backup directory
3. We delete all of the system table rows which told us about these bulk loads
4. We generate a backup manifest and mark the backup as complete
5. …
> HBASE-28697 Don't clean bulk load system entries until backup is complete

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketProtoUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
The persistent bucket cache implementation feature relies on the persistence of backing map to a persistent file. the protobuf APIs are used to serialise the backing map and its related structures into the file.
An asynchronous thread periodically flushes the contents of backing map to the persistence file.
The protobuf library has a limitation of 2GB on the size of protobuf messages. If the size of backing map increases beyond 2GB, an unexpected exception is reported in the asynchronous thread and stops the persister thread. This causes the persistent file go out of sync with the actual bucket cache. Due to this, the bucket cache shrinks to a smaller size after a cache restart. Checksum errors are also reported.
This Jira tracks the implementation of introducing chunking of the backing …
> HBASE-28805: Chunked persistence of backing map for persistent bucket cache.

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
- hbase-endpoint/src/test/java/org/apache/hadoop/hbase/client/TestAsyncAggregationClientWithCallbackThreadPool.java
To call a coprocessor endpoint asynchronously, you start by calling `AsyncTable#coprocessorService()`, which gives you a `CoprocessorServiceBuilder`, and a few steps later you can talk to your coprocessor over the network. One argument to `AsyncTable#coprocessorService()` is a `CoprocessorCallback` object, which contains several methods that will be called during the lifecycle of a coprocessor endpoint call. `AsyncTableImpl`'s implementation of `AsyncTable#coprocessorService()` wraps your `CoprocessorCallback` with its own that delegates the work to a thread pool. A snippet of this:
```
@Override
public void onRegionComplete(RegionInfo region, R resp) {
pool.execute(context.wrap(() -> callback.onRegionComplete(region, resp)));
}
...
@Override
public void onComplete() { …
```
> HBASE-28792: AsyncTableImpl should call coprocessor callbacks in a defined order

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RecoveredReplicationSource.java
> HBASE-28669: fix leaks a connection to ZooKeeper

- hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/io/asyncfs/FanOutOneBlockAsyncDFSOutputHelper.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
Now,  DatanodeInfo will be output in the print log. When we are troubleshooting and searching for slow datanode nodes, we need to convert IP addresses to hostnames, which is quite cumbersome.
I think the output log should has good readability, so it would be better to output the hostname of the datanode.
> HBASE-28775 Change the output of DatanodeInfo in the log to the hostname of the datanode

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/http/MasterStatusServlet.java
- hbase-server/src/main/resources/hbase-webapps/master/procedures.jsp
- hbase-server/src/main/resources/hbase-webapps/regionserver/region.jsp
Jira:  [HBASE-28778](https://issues.apache.org/jira/browse/HBASE-28778)
Master branch PR:  #6152
> HBASE-28778 NPE may occur when opening master-status or table.jsp or procedure.jsp while Master is initializing (branch-2)

- hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java
Remove some useless code in CanaryTool.sniff.
Add some logs when get null location for table region.
> HBASE-28807 Remove some useless code and add some logs for CanaryTool

- hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java
Backports https://github.com/apache/hbase/pull/6187
CC: @1458451310
> Backport "HBASE-28807 Remove some useless code and add some logs for CanaryTool" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/WALObserver.java
(cherry picked from commit 35c7fc0bab4371fd5e726838ee093b933503cb39)
> HBASE-28580 Revert the deprecation for methods in WALObserver (#6205)

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
When successfully taking an incremental backup, one of our final steps is to delete bulk load metadata from the system table for the bulk loads that needed to be captured in the given backup. This means that we will basically truncate the entire bulk loads system table in a single batch of the deletes after successfully taking an incremental backup. Depending on your usage, one may run tons of bulk loads between backups, so this design is needlessly fragile. We should partition these deletes so that we never erroneously fail a backup due to this; there are a few other cases where we generated unbounded multi requests in the BackupSystemTable that this PR addresses too.
A few questions here:
1. Do we want to make the batch size configurable? Seems like yet another config in hbase that I'd …
> HBASE-28696 Partition BackupSystemTable queries

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/master/BackupLogCleaner.java
https://issues.apache.org/jira/browse/HBASE-28810
While implementing HBase's incremental backups across a few hundred clusters, we continue to step on some rakes. Now and again, we find old WALs piling up due to a poorly cleaned up BackupInfo, or a bug in the BackupLogCleaner, etc.
The BackupLogCleaner is difficult to debug for a couple of reasons:
- It has a lack of useful debug logging
- It has [a misleadingly named method](https://github.com/HubSpot/hbase/blob/2d08fa67dfe9458260bc0be3ebc7bbd769850190/hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/master/BackupLogCleaner.java#L83-L83) (this method returns the newest backup ts, not the oldest)
This small refactor improves the logging and naming
cc @ndimiduk
> HBASE-28810 Improve BackupLogCleaner naming, debug logging

- hbase-assembly/src/main/assembly/client.xml
- hbase-assembly/src/main/assembly/hadoop-three-compat.xml
- hbase-assembly/src/main/assembly/hadoop-two-compat.xml
- hbase-resource-bundle/src/main/resources/supplemental-models.xml
- hbase-rest/pom.xml
- hbase-server/pom.xml
- hbase-shaded/hbase-shaded-mapreduce/pom.xml
- hbase-thrift/pom.xml
- pom.xml
Backport of https://github.com/apache/hbase/pull/5607, please goto original PR for details
> HBASE-28070 Replace javax.servlet.jsp dependency with tomcat-jasper

- hbase-server/src/test/java/org/apache/hadoop/hbase/codec/CodecPerformance.java
HBASE-28822 Change the LOG field in CodecPerformance to private
> HBASE-28822 Change the LOG field in CodecPerformance to private

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CombinedBlockCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFilePreadReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCachePersister.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CacheAwareLoadBalancer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestBlockEvictionOnRegionMovement.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetch.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestBucketWriterThread.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestPrefetchPersistence.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestRecoveryPersistentBucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
[HBASE-28804: Implement asynchronous retrieval of bucket-cache data from persistence
During the retrieval of data from bucket cache persistence file, a transient structure that stores the blocks ordered by filename is constructed from the backing map entries. The  population of this transient structure is done during the server start-up. This process increases the region-server startup time, if the bucketcache has large number of blocks.
This population happens inline with the server restart and blocks the server for several minutes. This makes the server restart inconvenient for the external users. Restarts during upgrade can run into timeout issues due to this delay in the server startup.
Hence, the recommendation in this Jira is to make the cache-retrieval asynchronous to the server …
> Backport HBASE-28804 to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketProtoUtils.java
During the serialisation of backing map of bucketcache persistence, we create a new BackingMapEntry.Builder object for every entry in the bucket map. This can be optimized by creating a single builder object and reusing it for every entry object.
Change-Id: I6f6c05dfa256ce964cd1d66e5050d9424db4be46
> HBASE-28821: Optimise the memory-utilisation during persistence of bucketcache.

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestNoopOperationQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerLeaseCount.java
We've noticed memory issues during intense periods of quota throttling. This happens because new scanners are created prior to the acquisition of the throttle, and aren't cleaned up correctly in the case acquiring the throttle throws an exception. This change creates a new region scanner only if the quota was acquired successfully to avoid scanner leaks.
> HBASE-28396: Quota throttling can cause a leak of scanners

- hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/TokenUtil.java
Co-authored-by: wangxin <wangxin9702@gmail.com>
(cherry picked from commit 4446d297112899dab59c0952489457c4419366d3)
> HBASE-28825 Add deprecation cycle for methods in TokenUtil (#6237)

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
Currently, the default value of the configuration parameter "hbase.bucketcache.persistence.chunksize" is 10 million (10000000). This is the number of block entries that are processed during the persistence of bucket-cache backing map to the persistence file. During the testing, it was found that, this high number of chunksize resulted in high heap utilisation in region servers leading to longer GC pauses which also led to server crashes intermittently.
When the value of this configuration is set to 10K(10000), the cache remains stable. No GC delays are observed. Also no server crashes are observed. The jmap outputs collected against the regionservers showed reduced memory utilisation from 4.5-5GB to 1-1.5GB for the objects related to persistence code.
Change-Id: …
> HBASE-28841: Modify default value of hbase.bucketcache.persistence.chunksize to 10K

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTable.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTableImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/NoopPartialResultCoprocessorCallback.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
- hbase-endpoint/src/main/java/org/apache/hadoop/hbase/client/coprocessor/AggregationClient.java
- hbase-endpoint/src/main/java/org/apache/hadoop/hbase/client/coprocessor/AggregationHelper.java
- hbase-endpoint/src/main/java/org/apache/hadoop/hbase/client/coprocessor/AsyncAggregationClient.java
- hbase-endpoint/src/main/java/org/apache/hadoop/hbase/coprocessor/AggregateImplementation.java
- hbase-endpoint/src/test/java/org/apache/hadoop/hbase/client/MockPartialResultAggregateImplemention.java
- hbase-endpoint/src/test/java/org/apache/hadoop/hbase/client/TestAsyncAggregationClientPartialResult.java
- hbase-protocol-shaded/src/main/protobuf/server/coprocessor/Aggregate.proto
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/DummyAsyncTable.java
Currently there is a gap in the coverage of HBase's quota-based workload throttling. Requests sent by `[Async]AggregationClient` reach `AggregateImplementation`. This then executes Scans in a way that bypasses the quota system. We see issues with this at Hubspot where clusters suffer under this load and we don't have a good way to protect them.
In this PR I'm teaching `AggregateImplementation` to optionally stop scanning when a throttle is violated, and send back just the results it has accumulated so far. In addition, it will send back a row key to `AsyncAggregationClient`. When the client gets a response with a row key, it will sleep in order to satisfy the throttle, and then send a new request with a scan starting at that row key. This will have the effect of continuing the work where …
> HBASE-28770: Support partial results in AggregateImplementation and AsyncAggregationClient

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRequestAttributes.java
The tests in the TestRequestAttributes class pass even when they should fail. Throw an `IOException` in the `AttributesCoprocessor` when the map of expected request attributes does not match the map of given request attributes.
[HBASE-28842](https://issues.apache.org/jira/browse/HBASE-28842)
I discovered this bug when backporting [HBASE-28001](https://issues.apache.org/jira/browse/HBASE-28001) to`branch-2` https://github.com/apache/hbase/pull/6246
> HBASE-28842: Fix TestRequestAttributes test to fail when it should 

- hbase-common/src/main/resources/hbase-default.xml
- src/main/asciidoc/_chapters/hbase-default.adoc
- src/main/asciidoc/_chapters/security.adoc
https://issues.apache.org/jira/browse/HBASE-28816
> HBASE-28816: The description of "hbase.superuser" is confusing

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/MergeTableRegionsProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/SplitTableRegionProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestSplitOrMergeAtTableLevel.java
> Backport "HBASE-27903 Skip submitting Split/Merge procedure when split/merge is disabled at table level" to branch-2

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRequestAttributes.java
@eab148 am I correct that this is the only change introduced by this commit to branch-2 since this bug was discovered in the backport?
> Backport "HBASE-28842 TestRequestAttributes should fail when expected (#6255)" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketProtoUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestVerifyBucketCacheFile.java
During the retrievel of bucket-cache from persistence, it was observed that, if an exception, other than the IOException occurs, the exception is not logged and also the retrieval thread exits leaving the bucket cache in an uninitialised state, leaving it unusable.
This change, enables the retrieval thread to peint all types of exceptions and also reinitialises the bucket cache and makes it reusable.
Unfortunately, the exception was seen due to a parallel execution of eviction during the execution persistence of backing map. Hence, this use-case may not be tested via a unit test.
Change-Id: I81b7f5fe06945702bbc59df96d054f95f03de499
> HBASE-28839: Handle all types of exceptions during retrieval of bucket-cache from persistence.

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/FlushTableProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/procedure/flush/MasterFlushTableProcedureManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFlushFromClient.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFlushFromClientWithDisabledFlushProcedure.java
Details see: [HBASE-28187](https://issues.apache.org/jira/browse/HBASE-28187)
And even worse, although this flush can be terminated by exception or manually，we are still unable to operate this region because of RegionTooBusyException.
> HBASE-28187 NPE when flushing a non-existing column family

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestRequestAttributes.java
The diff is a little weird. Full explanation here: https://github.com/apache/hbase/pull/6268#issuecomment-2360741518
> Backport "HBASE-28842 TestRequestAttributes should fail when expected (#6255)" to branch-2.6

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/master/BackupLogCleaner.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupBase.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/master/TestBackupLogCleaner.java
https://issues.apache.org/jira/projects/HBASE/issues/HBASE-28705
> HBASE-28705 backup log cleaner cleans required walls when using multiple backuproots

- src/main/asciidoc/_chapters/developer.adoc
The Reference Guide (book) link to the mailing lists page is broken.
> HBASE-28887 Fix broken link to mailing lists page in reference guide

- bin/replication/copy_tables_desc.rb
When utilizing the copy_tables_desc.rb script to duplicate tables to a target cluster, if the specified table's namespace is nonexistent in the target cluster, the script fails to execute successfully. It is recommended to incorporate logic within the script for detecting and handling scenarios where the namespace does not exist.
and fix spelling errors.
> fix : HBASE-28585. Add namespace handling method in copy_tables_desc.rb

- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/model/VersionModel.java
- hbase-rest/src/main/protobuf/VersionMessage.proto
- hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/TestVersionResource.java
- hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/model/TestVersionModel.java
https://github.com/apache/hbase/pull/6262
Note: Did not backported the changes to the asciidoc Reference Guide because the REST Endpoints and REST XML and protobuf Schemas sections are not present in this branch.
> Backport "HBASE-28645 Add build information to the REST server version endpoint" to branch-2

- bin/replication/copy_tables_desc.rb
Backports https://github.com/apache/hbase/pull/5884
> Backport "HBASE-28585 copy_tables_desc.rb script should handle scenarios where the namespace does not exist in the target cluster" to branch-2

- hbase-examples/pom.xml
- hbase-protocol-shaded/pom.xml
- pom.xml
> HBASE-28879 Bump hbase-thirdparty to 4.1.9

- hbase-examples/pom.xml
- hbase-protocol-shaded/pom.xml
- pom.xml
> Backport "HBASE-28879 Bump hbase-thirdparty to 4.1.9" to branch-3

- pom.xml
> Backport "HBASE-28879 Bump hbase-thirdparty to 4.1.9" to branch-2

- pom.xml
> Backport "HBASE-28879 Bump hbase-thirdparty to 4.1.9" to branch-2.6

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegion.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/region/TestMasterRegionWALSyncTimeoutIOException.java
This change enhances the ProcedureExecutor to honor new `WALSyncTimeoutIOException` introduced on HBASE-27230 / #4641. This new behavior is to abort the HMaster.
This appears to be the first time we're taking action based on exceptions thrown during procedure execution. I'm not sure if this is the right thing to do or we should be acting similarly for other exceptions.
@petersomogyi @Apache9 @comnetwork please take a look.
> HBASE-28803 HBase Master stuck due to improper handling of WALSyncTimeoutException within UncheckedIOException

- src/site/site.xml
https://github.com/apache/hbase-site/pull/9 will add the 2.6 documentation to the website git repo.
This PR will add the menu items on the homepage.
> HBASE-28733 Add "2.6 Documentation" to the website

- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileBlockIndex.java
> HBASE-28890 RefCnt Leak error when caching index blocks at write time (addendum) for branch-2.5

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/HFileLink.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileInfo.java
This is an easy performance win for the 2.6.x release series, and is safe in master too. See JIRA ticket for more motivation.
> HBASE-28905: Skip excessive evaluations of LINK_NAME_PATTERN and REF_NAME_PATTERN regular expressions

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBufferedMutatorBuilder.java
Add default implementations of the new methods so that a custom implementation of AsyncBufferedMutatorBuilder will not fail to compile after upgrade.
> HBASE-28001: Add request attribute support to BufferedMutator (#6076) (addendum)

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTable.java
This addendum is only for branch-2.6. It is intended to enable binary compatibility for an existing client that implements its own AsyncTable, when upgrading from 2.6.0 to 2.6.1.
> HBASE-28770 Support partial results in AggregateImplementation and AsyncAggregationClient (addendum) for branch-2.6

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncTable.java
This addendum is only for branch-2.6. It is intended to enable binary compatibility for an existing client that implements its own AsyncTable, when upgrading from 2.6.0 to 2.6.1.
> Backport "HBASE-28770 Support partial results in AggregateImplementation and AsyncAggregationClient (addendum)" to branch-2

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/ColumnFamilyMismatchException.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java
> HBASE-28897: Force CF compatibility during incremental backup

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/HFileLink.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileInfo.java
Backport of https://github.com/apache/hbase/pull/6348
> HBASE-28905: Skip excessive evaluations of LINK_NAME_PATTERN and REF_NAME_PATTERN regular expressions (branch-2)

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketAllocator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestRecoveryPersistentBucketCache.java
When an inconsistency is detected during the recovery of bucket cache from persistence, we tend to throw away the complete cache and try to rebuild the cache. Thsi inconsistency can occur when the region server is abruptly terminated.
This can be avoided by skipping the inconsistent backing map entry and continuing with the cache recovery. The inconsistent backing map entry will be discarded during the subsequent bucket cache validation.
Change-Id: I41237bda2189cbd73e22e4eadf4d53d16a3733f6
> HBASE-28900: Avoid resetting the bucket cache during recovery from persistence.

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketAllocator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/bucket/TestRecoveryPersistentBucketCache.java
Backport the fix of HBASE-28900 to branch-2.
> HBASE-28900: Avoid resetting the bucket cache during recovery from persistence. (#6360)

- dev-support/Jenkinsfile
- dev-support/hbase-personality.sh
- dev-support/hbase_nightly_yetus.sh
The nightly tests won't run on this PR.
See https://ci-hbase.apache.org/job/Test%20script%20for%20nightly%20script/job/HBASE-28846/ 
for the hacked-up test PR which tests the contents of this change
> HBASE-28906 Run nightly tests with multiple Hadoop 3 versions

- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestPrefetch.java
This test currently fails intermittently in master branch, as startime is post reader creation 
Elapsed time is sometimes  25074ms and sometimes 24994ms (but delay is 25000ms) since starttime was calculated after reader creation
> HBASE-28924 Create the start time right before creating the reader to calculate elapsedTime in testPrefetchWithDelay

- hbase-rest/pom.xml
- hbase-server/pom.xml
- hbase-thrift/pom.xml
We are bundling all webapp resources in hbase-server, hbase-thrift, hbase-rest and transitively to hbase-shaded-mapreduce jar. This can be an issue, say if any of the Js projects used by hbase are vulnerable, security scan tools like sonatype start flagging the jars too as vulnerable since they contain vulnerable code.
With this JIRA, we want to avoid bundling static webapp resources in our jars.
> HBASE-28921 Skip bundling hbase-webapps folder in jars

- hbase-rest/pom.xml
- hbase-server/pom.xml
- hbase-thrift/pom.xml
Reverts apache/hbase#6368
I see some test failures during debugging some other code. Apparently we use hbase-webapps folder to create an instance hbase local cluster for tests and the folder needs to be present in classpath. I am seeing following since we have removed hbase-webapps from hbase-server jar and hence tests  in other modules can't find it in classpath now:
```
Caused by: java.io.FileNotFoundException: hbase-webapps/master not found in CLASSPATH
at org.apache.hadoop.hbase.http.HttpServer.getWebAppsPath(HttpServer.java:1086)
at org.apache.hadoop.hbase.http.HttpServer.getWebAppsPath(HttpServer.java:1073)
at org.apache.hadoop.hbase.http.HttpServer.<init>(HttpServer.java:589)
at org.apache.hadoop.hbase.http.HttpServer$Builder.build(HttpServer.java:431)
at …
```
> Revert "HBASE-28921 Skip bundling hbase-webapps folder in jars"

- hbase-asyncfs/src/main/java/org/apache/hadoop/hbase/util/RecoverLeaseFSUtils.java
- hbase-asyncfs/src/test/java/org/apache/hadoop/hbase/util/TestRecoverLeaseFSUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestFSUtils.java
* use reflection to access these Hadoop APIs.
* added more UT coverage. Tested a few UTs with Hadoop 3.3.5.
TODO:
* Test with Hadoop 3.3.6, 3.4.0.
* Test with Ozone 2.0.0-SNAPSHOT.
> HBASE-28898. Use reflection to access recoverLease(), setSafeMode() APIs.

- dev-support/Jenkinsfile
- dev-support/hbase-personality.sh
- dev-support/hbase_nightly_pseudo-distributed-test.sh
- dev-support/hbase_nightly_yetus.sh
includes HBASE-28929 Set hadoop-three.version in Hadoop 3 backwards compatibility tests 
includes addendum: workaround for MAPREDUCE-7492
(cherry picked from commit 4be7e39e5a7953853ef79652c65160021dfa0105)
> HBASE-28906 Run nightly tests with multiple Hadoop 3 versions (#6356)

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/ColumnFamilyMismatchException.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
> Backport "HBASE-28917 ColumnFamilyMismatchException mixes IA public and private" to branch-3

- hbase-external-blockcache/pom.xml
- hbase-external-blockcache/src/main/java/org/apache/hadoop/hbase/io/hfile/MemcachedBlockCache.java
- hbase-external-blockcache/src/test/java/org/apache/hadoop/hbase/io/hfile/TestMemcachedBlockCache.java
- pom.xml
(cherry picked from commit a2d508a8fb21815444354ea2a95bee86a6b6f64a)
> HBASE-28942 Purge all netty 3 dependencies by default (#6406)

- hbase-shaded/hbase-shaded-client-byo-hadoop/pom.xml
- hbase-shaded/hbase-shaded-mapreduce/pom.xml
- hbase-shaded/hbase-shaded-testing-util-tester/pom.xml
- hbase-shaded/hbase-shaded-testing-util/pom.xml
> HBASE-28943 Remove all jackson 1.x dependencies for hadoop-3 profile, since all jackson 1.x versions have vulnerabilities

- hbase-rest/pom.xml
- hbase-server/pom.xml
- hbase-thrift/pom.xml
- pom.xml
We are bundling all webapp resources in hbase-server, hbase-thrift, hbase-rest and transitively to hbase-shaded-mapreduce jar. This can be an issue, say if any of the Js projects used by hbase are vulnerable, security scan tools like sonatype start flagging the jars too as vulnerable since they contain vulnerable code.
With this JIRA, we want to avoid bundling static webapp resources in our default jars as these are available during runtime via hbase-webapps directory bundled in our assembly.
But, we still need this for our minicluster based tests which expects it to be present in test classpath. Hence, we are copying hbase-webapps to hbase-server tests jar, which contains class SingleProcessHBaseCluster responsible for hbase minicluster creation. This class eventually needs hbase-webapps …
> HBASE-28921 Avoid bundling hbase-webapps folder in default jars

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/MoveWithAck.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestRegionMover2.java
(cherry picked from commit 344bf78b8fc1c7b4f1b07f4ba846a6b56f955c79)
> HBASE-28948 RegionMover tool fails when table is deleted (#6423)

- hbase-server/src/main/java/org/apache/hadoop/hbase/mob/RSMobFileCleanerChore.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestRSMobFileCleanerChore.java
Details see: [HBASE-28956](https://issues.apache.org/jira/browse/HBASE-28956)
> HBASE-28956 RSMobFileCleanerChore may close the StoreFileReader object which is being used by Compaction thread

- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/UserQuotaState.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaUserOverride.java
https://issues.apache.org/jira/browse/HBASE-28963
My company is running Quotas across a few hundred clusters of varied size. One cluster has hundreds of servers, tens of thousands of regions, and tens of thousands of unique users — for all of whom we build default user quotas to manage resource usage OOTB. 
We noticed that the HMaster was quite busy for this cluster, and after some investigation we realized that RegionServers were hammering the HMaster's ClusterMetrics endpoint to facilitate the refreshing of table machine quota factors. We were also hotspotting the RegionServer hosting the quotas system table.
```
2024-11-05T21:22:21,024 [regionserver:60020.Chore.1 {}] INFO org.apache.hadoop.hbase.client.HBaseAdmin: getClusterMetrics call stack: …
```
> HBASE-28963 Updating Quota Factors is too expensive

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableOutputFormat.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableOutputFormat.java
Jira: HBASE-28268
If we have replication setup between clusters A <-> B, If we use CopyTable job to copy the data from cluster B to cluster A during production issues. It doesn't make sense to write to WALs on A using TableOutputFormat (since the mutations being copied already exist on B). 
So, added config which helps to skip writing to the WALs while using the TableOutputFormat, if we want to skip writing to WAL then Durability of the mutation is set to SKIP_WAL, or else default value will be used.
> HBASE-28268 Provide option to skip wal while using TableOutputFormat

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionConfiguration.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionConfiguration.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncConnectionConfiguration.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestConnectionConfiguration.java
https://issues.apache.org/jira/browse/HBASE-28608
> HBASE-28608 More sensible client meta operation timeout default

- hbase-client/src/main/java/org/apache/hadoop/hbase/filter/FuzzyRowFilter.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/filter/PrefixFilter.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/PrivateCellUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFuzzyRowFilter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFuzzyRowFilterEndToEnd.java
This is the backport of https://github.com/apache/hbase/pull/6457 to `branch-2`
Changes:
- Reproduced the issue with a mini cluster test.
- Corrected reverse unit tests in `TestFuzzyRowFilter` as some expectations were not correct.
- Fixed hint returned by `FuzzyRowFilter.getNextForFuzzyRule()` in the reverse case:
- Before we only trimmed the trailing zeros from the hint in the forward scan case. From now on we also do this in the reverse case.
- Also extracted `PrefixFilter.increaseLastNonMaxByte()` method to `PrivateCellUtil` so that it can be reused in `FuzzyRowFilter`.
- When the hint should contain a `0xFF`. As a start, when we have a reverse scan, we not only need trailing `0xff`'s instead of trailing `0x00`'s, but it seems we always need `0xff`'s instead of the `0x00`'s.
- Made …
> HBASE-28634 Fix FuzzyRowFilter may not return data on reverse scans

- hbase-mapreduce/pom.xml
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/RowCounter.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestRowCounter.java
A flag is introduced, which, when enabled, allows RowCounter to count the various types of Delete Markers - DELETE_COLUMN, DELETE_FAMILY, DELETE_FAMILY_VERSION. It will also calculate the number of rows having a delete marker.
To enable this the scan object was modified -> if flag is set, raw scan is performed without FirstKeyOnlyFilter.
Note: Commits are cherry-picked from https://github.com/apache/hbase/pull/6435
> HBASE-28328 Add an option to count different types of Delete Markers in RowCounter

- src/main/asciidoc/_chapters/architecture.adoc
- src/main/asciidoc/_chapters/upgrading.adoc
- Renamed the anchor ID under "Changes of Note!" section.
- Added a link from this section to the other "Upgrading Coprocessors to 2.0" section.
- Fixed the anchor ID of "BucketCache Deploy Modes". This way a broken link is now fixed.
> HBASE-20663 Make sure coprocessor upgrade anchor ID is not duplicated in HBase book

- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/TableResource.java
- hbase-rest/src/main/resources/org/apache/hadoop/hbase/rest/XMLSchema.xsd
- src/main/asciidoc/_chapters/external_apis.adoc
Added the following to the REST API documentation:
- Table exists endpoint (`GET /table/exists`)
- Stateless Scanner endpoint (the documentation for this was based on the patch of https://issues.apache.org/jira/browse/HBASE-10346)
- `filter` and `filter_b64` parameters for multiget endpoint
- "suffixGlobbing" endpoints (`GET /table/row_prefix*/column`)
- append operation
- increment operation
- `includeStartRow` and `includeStopRow` stateless scanner parameters
Other changes:
- Updated REST XML Schema and REST Protobufs Schema in documentation
- Updated XMLSchema.xsd with the latest changes
Do you maybe see some other REST endpoints not documented?
> HBASE-28525 Extended REST Documentation: Stateless Scanner, table exists, multiget with filter

- hbase-server/src/main/java/org/apache/hadoop/hbase/backup/HFileArchiver.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/DeleteTableProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionFileSystem.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/backup/TestHFileArchiving.java
> HBASE-28836 Parallize the file archival to improve the split times 

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-common/src/main/resources/hbase-default.xml
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/util/MemorySizeUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HeapMemoryManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestCacheConfig.java
Introduce a new configuration, `hfile.block.cache.memory.size`, which allows setting the block cache size with an exact byte value or a human-readable storage size.
> HBASE-28600 Introduce hfile.block.cache.memory.size configuration

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/FileChangeWatcher.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/tls/X509Util.java
- hbase-common/src/test/java/org/apache/hadoop/hbase/io/TestFileChangeWatcher.java
At my company we have an issue with our HBase servers not reloading TLS certificate files after they change on disk. We run our HMasters inside Kubernetes Pods, and define our certificate contents as Kubernetes Secrets. Then, the Secrets are projected into the HMaster containers as files. When the value of a Secret changes, the file changes automatically. However, Kubernetes does some complicated indirection, and does not change the files directly. It swaps a new directory in with new files in it.
HBase sets up a `WatchService` on the directory containing the TLS cert. For example, at my company, the cert is at `/etc/hadoop/conf/ssl/cert/server-chain.pem`. Then, events from that `WatchService` are delivered to a [handler method](https://github.com/apache/hbase/blob/836630422df2776287a860ef …
> HBASE-28931: Poll SSL cert file for changes

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupHFileCleaner.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupObserver.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManager.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BulkLoad.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackupWithBulkLoad.java
No functional changes.
Currently split into 2 commits as to help the reviewer with seeing what was changed. This can be squashed when merging.
> HBASE-28767 Simplify backup bulk-loading code

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileWriterImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/TestCacheEviction.java
…d for a region immediately after it is flushed with cacheOnWrite turned on
> HBASE-29035: Amount of region cached in the region metrics not updated for a region immediately after it is flushed with cacheOnWrite turned on

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileListFile.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/storefiletracker/TestStoreFileListFile.java
When using FileBasedStoreFileTracker, there is an issue where StoreFileListFile is not recognized after upgrading from HBase 2.5 to 2.6. 
In HBase 2.5, the names of StoreFileListFiles are f1 or f2, but starting from 2.6, a timestamp is added to the filenames, as introduced in [HBASE-29021](https://issues.apache.org/jira/browse/HBASE-29021). 
However, this change was not backported to 2.5. 
To resolve this issue, a patch was applied to add the timestamp when it is missing in the StoreFileListFile name.
> HBASE-29021 When StoreFileTracker is FILE, unable to recognize StoreFileListFile after upgrade from 2.5 to 2.6

- hbase-diagnostics/src/main/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
- hbase-diagnostics/src/test/java/org/apache/hadoop/hbase/TestPerformanceEvaluation.java
Use 8-byte long integers in the code to prevent integer overflows.
Commands that fail without the patch:
bin/hbase pe --nomapred --presplit=21 --compress=LZ4 --rows=10737418240 randomWrite 1
bin/hbase pe --nomapred --compress=LZ4 --rows=1073741824 randomWrite 20
> HBASE-29013 Make PerformanceEvaluation support larger data sets

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/RSStatusTmpl.jamon
- hbase-server/src/main/resources/hbase-webapps/master/table.jsp
Cherry-picked the following patches which were missing on `branch-2` branch. Most of these applied as a clean cherry-pick (without conflicts). Unfortunately there were some which had conflicts and I manually resolved them.
Each commit message contains from which commit it was cherry-picked from.
- HBASE-24624 Optimize table.jsp code (#1963) - :warning: This did not apply cleanly - had to resolve conflicts manually
- HBASE-25402 Sorting order by start key or end key is not considering empty start key/end key (#2955)
- HBASE-28778 NPE may occur when opening master-status or table.jsp or procedure.jsp while Master is initializing (#6152)
- HBASE-20452 Master UI: Table merge button should validate required fields before submit
> HBASE-29037 Backport missing UI patches to branch-2

- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/TestPerformanceEvaluation.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestCellBasedHFileOutputFormat2.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestHFileOutputFormat2.java
Cherry-picked 6ebd48e477 and replaced `Random#nextLong(bound)` which is not available on JDK 8 with `ThreadLocalRandom#nextLong(bound)` (e140ae762d).
Not being able to provide a seed doesn't matter in this context, so this should be good enough.
> HBASE-29013 Make PerformanceEvaluation support larger data sets (branch-2)

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/MasterProcedureEnv.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RSProcedureDispatcher.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestAssignmentManagerBase.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/RSProcDispatcher.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestProcDispatcher.java
Jira: HBASE-28638
Master initiated remote procedures are scheduled by RSProcedureDispatcher. If it encounters specific errors on first retry (e.g. CallQueueTooBigException or SaslException), it is guaranteed that the remote call has not reached the regionserver, therefore the remote call is marked failed prompting the parent procedure to select different target regionserver to resume the operation.
If the first attempt is successful, RSProcedureDispatcher continues with infinite retries. We can encounter valid case (e.g. ConnectionClosedException) which is halting the remote operation. Without manual intervention, it can cause significant delay upto several minutes or hours to the region-in-transition.
The purpose of this Jira is to impose retry limit for specific error types such that if …
> HBASE-28638 Fail-fast retry limit for specific errors to recover from remote procedure failure using server crash

- hbase-server/src/test/java/org/apache/hadoop/hbase/http/TestInfoServersACL.java
There were some changes in the Bootstrap upgrade which caused the test to fail because the test expected certain text to appear on the UI page.
> HBASE-28832 Fixed TestInfoServersACL test

- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/RSStatusTmpl.jamon
- hbase-server/src/main/resources/hbase-webapps/master/table.jsp
- hbase-thrift/src/main/resources/hbase-webapps/thrift/footer.jsp
- hbase-thrift/src/main/resources/hbase-webapps/thrift/header.jsp
- hbase-thrift/src/main/resources/hbase-webapps/thrift/thrift.jsp
Cherry-picked the following patches which were missing on `branch-2.6` branch. Most of these applied as a clean cherry-pick (without conflicts). Unfortunately there were some which had conflicts and I manually resolved them.
Each commit message contains from which commit it was cherry-picked from.
- HBASE-18382 add transport type info into Thrift UI (#880)
- HBASE-20693 Refactor thrift jsp's and extract header and footer (#5732)
- HBASE-24624 Optimize table.jsp code (#1963) - :warning: This did not apply cleanly - had to resolve conflicts manually
- HBASE-25402 Sorting order by start key or end key is not considering empty start key/end key (#2955)
- HBASE-28778 NPE may occur when opening master-status or table.jsp or procedure.jsp while Master is initializing (#6152)
> HBASE-29036 Backport missing UI patches to branch-2.6

- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RESTDumpServlet.java
- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/RESTServer.java
- hbase-rest/src/main/resources/hbase-webapps/rest/footer.jsp
- hbase-rest/src/main/resources/hbase-webapps/rest/header.jsp
- hbase-rest/src/main/resources/hbase-webapps/rest/processRest.jsp
- hbase-rest/src/main/resources/hbase-webapps/rest/rest.jsp
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/RSStatusTmpl.jamon
- hbase-server/src/main/resources/hbase-webapps/master/header.jsp
- hbase-server/src/main/resources/hbase-webapps/master/table.jsp
- hbase-server/src/main/resources/hbase-webapps/regionserver/header.jsp
- hbase-thrift/src/main/resources/hbase-webapps/thrift/footer.jsp
- hbase-thrift/src/main/resources/hbase-webapps/thrift/header.jsp
- hbase-thrift/src/main/resources/hbase-webapps/thrift/thrift.jsp
Cherry-picked the following patches which were missing on branch-2.5 branch. Most of these applied as a clean cherry-pick (without conflicts). Unfortunately there were some which had conflicts and I manually resolved them.
Each commit message contains from which commit it was cherry-picked from.
- HBASE-27406 Make /prometheus endpoint accessible from HBase UI (#4833)
- HBASE-27814 Add support for dump and process metrics servlet in REST InfoServer (#5215)
- HBASE-18382 add transport type info into Thrift UI (#880)
- HBASE-20693 Refactor thrift jsp's and extract header and footer (#5732)
- HBASE-24624 Optimize table.jsp code (#1963) - :warning: This did not apply cleanly - had to resolve conflicts manually
- HBASE-25402 Sorting order by start key or end key is not considering empty start …
> HBASE-29028 Backport missing UI patches to branch-2.5

- hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/model/ScannerModel.java
- hbase-rest/src/test/java/org/apache/hadoop/hbase/rest/model/TestScannerModel.java
HBASE-28627 REST ScannerModel doesn't support includeStartRow/includeStopRow(addendum)
> HBASE-28627 REST ScannerModel doesn't support includeStartRow/includeStopRow(addendum)

- pom.xml
* Backports https://github.com/apache/hbase/pull/6560
> HBASE-28968 Bump jruby to 9.4.9.0 to fix rexml CVE (#6560)

- hbase-diagnostics/src/main/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
The option applies to all tests since HBASE-10788.
> HBASE-29040 Fix description of "sampleRate" of PerformanceEvaluation

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFunction.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerTestBase.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/StochasticBalancerTestBase.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerBalanceCluster.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerLargeCluster.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerMidCluster.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplica.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaHighReplication.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaLargeCluster.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaMidCluster.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaReplicationGreaterThanNumNodes.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaSameHosts.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaWithRacks.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerSmallCluster.java
[Jira](https://issues.apache.org/jira/browse/HBASE-29070)
On top of actually making the balancer better, this PR reduces the runtime of the balancer test suite on my machine from about 30min to about 8min
cc @charlesconnell @hgromer @krconv @ksravista
> HBASE-29070 Balancer cost function epsilon is imprecise

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/StorageSize.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/StorageUnit.java
- hbase-common/src/main/resources/hbase-default.xml
- hbase-common/src/test/java/org/apache/hadoop/hbase/TestStorageSize.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/util/MemorySizeUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HeapMemoryManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestCacheConfig.java
Tested same result and logs in this [comment](https://issues.apache.org/jira/browse/HBASE-28600?focusedCommentId=17903856&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17903856)
I introduced the [StorageSize](https://github.com/apache/hadoop/blob/branch-3.1.0/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/StorageSize.java) and [StorageUnit](https://github.com/apache/hadoop/blob/branch-3.1.0/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/StorageUnit.java) classes from Hadoop 3.x in https://github.com/apache/hbase/commit/b20c42cb5bcc2ba0dd0bd00909691c6ead23dfab
Another approach could have been implementing similar methods in our [Size](https://github.com/apache/hbase/blob/branch-2/hbase-client/src/main/java …
> Backport "HBASE-28600 Enable setting blockcache on-heap sizes in bytes (#6422)" to branch-2

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/StorageSize.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/StorageUnit.java
- hbase-common/src/main/resources/hbase-default.xml
- hbase-common/src/test/java/org/apache/hadoop/hbase/TestStorageSize.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/util/MemorySizeUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HeapMemoryManager.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestCacheConfig.java
Tested same result and logs in this [comment](https://issues.apache.org/jira/browse/HBASE-28600?focusedCommentId=17903856&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17903856)
I introduced the [StorageSize](https://github.com/apache/hadoop/blob/branch-3.1.0/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/StorageSize.java) and [StorageUnit](https://github.com/apache/hadoop/blob/branch-3.1.0/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/StorageUnit.java) classes from Hadoop 3.x in https://github.com/apache/hbase/commit/82eeb505cfff637a44fe18fc813c6622c8be0f5b
Another approach could have been implementing similar methods in our [Size](https://github.com/apache/hbase/blob/branch-2/hbase-client/src/main/java …
> Backport" HBASE-28600 Enable setting blockcache on-heap sizes in bytes (#6422)" to branch-2.6

- pom.xml
- Backports #6579 (to let CI run through the change once on branch-2)
> HBASE-29056 Bump commons-io:commons-io from 2.14.0 to 2.18.0

- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
- hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java
If you are running a table with region replicas, the secondary replicas usually cannot achieve 100% locality. Currently a RegionServer reports two locality metrics:
* `percentFilesLocal`
* `percentFilesLocalSecondaryRegions`
Both of these will be less than 100% if region replicas are enabled. The best we can do is get 100% locality for the primary replicas, but there is currently no way to see if we've achieved it.
I propose introducing the new metric `percentFilesLocalPrimaryRegions`, which will close this gap.
> HBASE-29068: Report percentFilesLocalPrimaryRegions metric

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Get.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/Scan.java
> HBASE-29004 Optimize unnecessary type castings in Scan and Get setter methods

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CacheAwareLoadBalancer.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFunction.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/LocalityBasedCostFunction.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionCountSkewCostFunction.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaGroupingCostFunction.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerBalanceCluster.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaWithRacks.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/LoadOnlyFavoredStochasticBalancer.java
This just makes the candidate generators nicer to work with. This is part of https://github.com/apache/hbase/pull/6593 that I'm breaking off into an atomic piece
Existing test coverage provides great guardrails to ensure that we haven't broken anything
> HBASE-29071 StochasticLoadBalancer candidate generators should use a Map, rather than ordinal based indexing

- dev-support/hbase-vote.sh
Uses the long-form of arguments, hopefully, to improve readability. The new `execute` line is what fixes the issue.
> HBASE-29092 hbase-vote.sh is stymied by the new robots.txt on dist.apache.org

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CacheAwareLoadBalancer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFunction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/LocalityBasedCostFunction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionCountSkewCostFunction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionReplicaGroupingCostFunction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/LoadOnlyFavoredStochasticBalancer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerBalanceCluster.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplicaWithRacks.java
…Map, rather than ordinal based indexing (#6598)
> Backport "HBASE-29071 StochasticLoadBalancer candidate generators should use a …" to branch-2

- pom.xml
(cherry picked from commit 1b882533679c0ce62704748900455e89e1551a3e)
> HBASE-29086 Bump hbase-thirdparty to 4.1.10

- hbase-common/src/main/java/org/apache/hadoop/hbase/util/Strings.java
- hbase-diagnostics/src/main/java/org/apache/hadoop/hbase/ScanPerformanceEvaluation.java
- hbase-diagnostics/src/main/java/org/apache/hadoop/hbase/util/MultiThreadedAction.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/PutSortReducer.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableInputFormatBase.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TextSortReducer.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlockIndex.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/MetricsWAL.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotInfo.java
- hbase-server/src/main/resources/hbase-webapps/master/procedures.jsp
- hbase-server/src/main/resources/hbase-webapps/master/quotas.jsp
- hbase-server/src/main/resources/hbase-webapps/master/rsgroup.jsp
- hbase-server/src/main/resources/hbase-webapps/master/snapshot.jsp
- hbase-server/src/main/resources/hbase-webapps/master/snapshotsStats.jsp
- hbase-server/src/main/resources/hbase-webapps/master/table.jsp
- hbase-server/src/main/resources/hbase-webapps/master/tablesDetailed.jsp
- hbase-server/src/main/resources/hbase-webapps/regionserver/region.jsp
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionReplayEvents.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/MockStoreFileGenerator.java
- Replaced the following deprecated methods:
- java.net.URLEncoder.encode(String) -> java.net.URLEncoder.encode(String, Charset)
- org.apache.hadoop.util.StringUtils.humanReadableInt(long) -> org.apache.hadoop.util.StringUtils.TraditionalBinaryPrefix.long2String(long, "", 1): For this a new static util method is introduced: org.apache.hadoop.hbase.util.Strings.humanReadableInt
- org.apache.hadoop.fs.FileSystem.getLength(Path) -> getFileStatus(Path).getLen()
- org.apache.hadoop.hbase.ServerName.getStartcode() -> org.apache.hadoop.hbase.ServerName.getStartCode()
- Also removed unused imports in the touched JSP files.
> HBASE-29026 Replace some deprecated calls

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplica.java
This is yet another bite of https://github.com/apache/hbase/pull/6593
In https://github.com/apache/hbase/pull/3729 we removed consideration replicas' rack distribution. This was, in my opinion, a mistake — if we want to be flexible for environments that have too few racks, then we should just do so by skipping this check when the rack count is < the max replica count
> HBASE-29072 StochasticLoadBalancer#areReplicasColocated ignores rack colocation

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplica.java
> Backport "HBASE-29072 StochasticLoadBalancer#areReplicasColocated ignores rack …" to branch-3

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
The sumMultiplier field is used in the needsBalance method, but it is not initialized until calling balanceTable. This is silly and can cause weird behavior on an HMaster's initial balancer run, because the statement:
```java
boolean balanced = (total / sumMultiplier < minCostNeedBalance);
```
will always result to false, given that `total / sumMultiplier` == NaN, so it is not comparable to the min balance cost.
This isn't a huge issue, but I noticed this in my recent work on the balancer and it's worth fixing imo.
The needsBalance method already iterates through all cost functions ahead of using the sumMultiplier field, so we might as well just ensure that we've updated the sumMultiplier field here as well.
> HBASE-29073 StochasticLoadBalancer will always run the balancer on startup because of uninitialized sumMultiplier

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerRegionReplica.java
> Backport "HBASE-29072 StochasticLoadBalancer#areReplicasColocated ignores rack …" to branch-2.6

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
> Backport "HBASE-29099 Avoid expensive BlockCacheKey.toString() calls when traci…" to branch-3

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
> Backport "HBASE-29099 Avoid expensive BlockCacheKey.toString() calls when traci…" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
> Backport "HBASE-29099 Avoid expensive BlockCacheKey.toString() calls when traci…" to branch-2.6

- hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotInfo.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotStats.java
Details see: [HBASE-29088](https://issues.apache.org/jira/browse/HBASE-29088)
> HBASE-29088 The denominator cannot be 0 when calculating percentages in SnapshotStats

- hbase-http/src/main/java/org/apache/hadoop/hbase/http/ProfileServlet.java
Use the asprof script as default in order to support new async-profiler version.
> HBASE-29045 Support new async-profiler > 2.9 version

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBufferedMutator.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBufferedMutatorBuilder.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBufferedMutatorBuilderImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncBufferedMutatorImpl.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionConfiguration.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/BufferedMutator.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/BufferedMutatorParams.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionConfiguration.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionOverAsyncConnection.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestBufferedMutatorParams.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncBufferMutator.java
At my company I've been experimenting with enabling `hbase.rpc.rows.size.threshold.reject` on our RegionServers as a protective measure, to prevent Java OOMs caused by large Multi requests. This has caused issues for some clients using `BufferedMutator`s, which send large batches of mutations, sometimes all to a single RegionServer. It the `BufferedMutator` had a way to flush before hitting the RegionServer's `hbase.rpc.rows.warning.threshold`, then it could gets its mutations done successfully. This is easy to add.
> HBASE-29148: BufferedMutator should be able to flush after buffering a certain number of mutations

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/compress/BlockDecompressorHelper.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/compress/ByteBuffDecompressionCodec.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/compress/ByteBuffDecompressor.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/compress/CodecPool.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/compress/Compression.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/HFileBlockDefaultDecodingContext.java
- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdByteBuffDecompressor.java
- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdCodec.java
- hbase-compression/hbase-compression-zstd/src/test/java/org/apache/hadoop/hbase/io/compress/zstd/TestHFileCompressionZstd.java
- hbase-compression/hbase-compression-zstd/src/test/java/org/apache/hadoop/hbase/io/compress/zstd/TestZstdByteBuffDecompressor.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/CompressionContext.java
Each time a block is decoded in `HFileBlockDefaultDecodingContext`, a new `DecompressorStream` is allocated and used. This is a lot of allocation, and the use of the streaming pattern requires copying every byte to be decompressed more times than necessary. Each byte is copied from a `ByteBuff` into a `byte[]`, then decompressed, then copied back to a `ByteBuff`. For decompressors like `org.apache.hadoop.hbase.io.compress.zstd.ZstdDecompressor` that only operate on direct memory, two additional copies are introduced to move from a `byte[]` to a direct NIO `ByteBuffer`, then back to a `byte[]`.
Aside from the copies inherent in the decompression algorithm, and the necessity of copying from an compressed buffer to an uncompressed buffer, all of these other copies can be avoided without …
> HBASE-29135: ZStandard decompression can operate directly on ByteBuffs

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasCandidateGenerator.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/MetaTableIsolationCandidateGenerator.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/MetaTableIsolationConditional.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionPlanConditionalCandidateGenerator.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/SlopFixingCandidateGenerator.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/TableIsolationCandidateGenerator.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/TableIsolationConditional.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/replicas/ReplicaKey.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBalancerConditionals.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingConditionalReplicaDistribution.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingMetaTableIsolation.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingTableIsolationAndReplicaDistribution.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestMetaTableIsolationBalancerConditional.java
In [HBASE-28513](https://issues.apache.org/jira/browse/HBASE-28513) we added support for balancer conditionals which will the balancer discrete rules to follow when generating plans. This PR adds support for meta table isolation that works in a  more flexible, lightweight, and cost effective way compared to RegionServer groups.
In a subsequent PR I'll solve [HBASE-29075](https://issues.apache.org/jira/browse/HBASE-29075) by extending this framework to support generic system table isolation as well. The triad of 28513, 29074, and 29075 will complete my team's initial vision for balancer conditionals, unlocking support for system table isolation, meta table isolation, and improved secondary replica distribution.
> HBASE-29074 Balancer conditionals should support meta table isolation

- src/site/site.xml
According to https://whimsy.apache.org/site/project/hbase the website should link to the Apache Privacy Policy (https://privacy.apache.org/policies/privacy-policy-public.html).
> HBASE-29153 Added Privacy Policy link to website

- hbase-server/src/main/resources/hbase-webapps/static/js/tab.js
Before HBase UI always tried to load `userSnapshots.jsp` with an AJAX request on all UI pages - **NOK**.
This happened even on RegionServer UI or REST UI where this call always failed with HTTP 500.
From now on HBase UI only loads `userSnapshots.jsp` when the Snapshots tab (div with `tab_userSnapshots` ID) exists on the page.
Also did a minor improvement to `tab.js`: use `const` instead of `var` as `var` has so many problems:
> With block-level scope, no hoisting, and the ability to declare constants, let and const make code more predictable, maintainable, and less error-prone. By using let and const instead of var, developers can avoid common pitfalls and write more declarative code.
Also fixed a whitespace.
> HBASE-29093 Load userSnapshots.jsp only on master status page

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionStateNode.java
- hbase-server/src/main/resources/hbase-webapps/master/rits.jsp
With the patch, the location of the unassigned regions are shown as "null". I added a method to RegionStateNode for the null-check, but if you prefer to do without it, I can change the expressions in the jsp file instead.
> HBASE-29066 Fix NPE in rits.jsp when regions are not open

- pom.xml
Skip generating ref guide when running 'mvn site' on branch other than master
> HBASE-28986 Port HBASE-26932 to branch-3

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/AssignRegionAction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalanceAction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BaseLoadBalancer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CacheAwareLoadBalancer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFunction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasConditional.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/FavoredStochasticBalancer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/MoveBatchAction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/MoveRegionAction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionPlanConditional.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionPlanConditionalCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/SlopFixingCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/SwapRegionsAction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/replicas/ReplicaKey.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/replicas/ReplicaKeyCache.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionalsTestUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasTestConditional.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBalancerConditionals.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingConditionalReplicaDistribution.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestReplicaDistributionBalancerConditional.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancerHeterogeneousCost.java
> Backport "HBASE-28513 The StochasticLoadBalancer should support discrete evalua…" to branch-2

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupDriver.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupInfo.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRequest.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRestoreConstants.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupAdminImpl.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupCommands.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupManager.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/FullTableBackupClient.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/TableBackupClient.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestContinuousBackup.java
- hbase-protocol-shaded/src/main/protobuf/Backup.proto
This PR introduces a new parameter/option `-cb` (`--continuous-backup-enabled`) for full backups. When specified, it enables continuous backup for the selected tables along with the full backup.
Continuous backup leverages the HBase replication framework and uses `org.apache.hadoop.hbase.backup.replication.ContinuousBackupReplicationEndpoint` (by default) to continuously stream WAL entries to the backup WAL directory defined by `hbase.backup.continuous.wal.dir`.
> HBASE-29025: Enhance the full backup command to support Continuous Backup

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/MetaTableIsolationCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/MetaTableIsolationConditional.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionPlanConditionalCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/SlopFixingCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/TableIsolationCandidateGenerator.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/TableIsolationConditional.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestBalancerConditionals.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingMetaTableIsolation.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingTableIsolationAndReplicaDistribution.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestMetaTableIsolationBalancerConditional.java
> Backport "HBASE-29074 Balancer conditionals should support meta table isolation…" to branch-2

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/DistributeReplicasConditional.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/SlopFixingCandidateGenerator.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/SystemTableIsolationCandidateGenerator.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/SystemTableIsolationConditional.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/TableIsolationConditional.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestLargeClusterBalancingSystemTableIsolation.java
In [HBASE-28513](https://issues.apache.org/jira/browse/HBASE-28513) we are adding support for "balancer conditionals", and in [HBASE-29074](https://issues.apache.org/jira/browse/HBASE-29074) we added support for isolating each meta replica on its own server.
This takes that work a step further, and provides the ability to isolate all system tables (excluding meta, if meta has its own isolation configured) to particular servers when the cluster is balanced. You can turn this on by setting `hbase.master.balancer.stochastic.conditionals.isolateSystemTables` to true.
This change can help to isolate any problematic system table workloads from user-facing tables, or vice versa
> HBASE-29075 Balancer conditionals should support system table isolation

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionConfiguration.java
- hbase-common/src/main/resources/hbase-default.xml
Addendum to [prior PR](https://github.com/apache/hbase/pull/6718) based on [this suggestion](https://issues.apache.org/jira/browse/HBASE-29148?focusedCommentId=17931208&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17931208).
> HBASE-29179: Fall back to hbase.rpc.rows.warning.threshold if hbase.client.write.buffer.maxmutations is not set

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/TableName.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/TestMetaTableForReplica.java
Add support for custom meta table name and ability to start cluster on the same storage location. 
New config setting:
hbase.meta.table.suffix default ""  Adds a suffix to the meta table name: value=’test’ -> ‘hbase:meta_test’
> HBASE-29082: Support for custom meta table name suffix

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/Import.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestImportExport.java
1. CellSortImporter emits values wrapped inside MapReduceExtendedCell
2. Converted KV to CellUtil.
> HBASE-25839 Bulk Import fails with java.io.IOException: Type mismatch in value from map

- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdByteBuffDecompressor.java
- hbase-compression/hbase-compression-zstd/src/test/java/org/apache/hadoop/hbase/io/compress/zstd/TestZstdByteBuffDecompressor.java
My recent contribution in HBASE-29135 has a bug. `ZstdByteBuffDecompressor` doesn't update the position of the input `ByteBuffer` after reading from it. When there are multiple "chunks" in the input buffer, this causes failure to read chunks after the first one.
This PR fixes the bug and adjusts an existing test to verify the fix.
> HBASE-29172: Fix to bug in ZstdByteBuffDecompressor

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionConfiguration.java
- hbase-common/src/main/resources/hbase-default.xml
Addendum to [prior PR](https://github.com/apache/hbase/pull/6718) based on [this suggestion](https://issues.apache.org/jira/browse/HBASE-29148?focusedCommentId=17931208&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17931208).
> HBASE-29179: Fall back to hbase.rpc.rows.warning.threshold if hbase.client.write.buffer.maxmutations is not set (branch-2)

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/RegionPlanConditional.java
The value of this lookup can be null, and we can't pass a null value to Arrays#stream:
```
java.lang.NullPointerException: Cannot read the array length because "array" is null
at java.util.Arrays.stream(Arrays.java:5559) ~[?:?]
at org.apache.hadoop.hbase.master.balancer.RegionPlanConditional.isViolating(RegionPlanConditional.java:103) ~[hbase-server-2.6-hubspot-SNAPSHOT.jar:2.6-hubspot-SNAPSHOT]
```
> HBASE-29186 RegionPlanConditionals can produce a null pointer

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestUnattainableBalancerCostGoal.java
Because we'll accept any moves that improve conditional violations, this bug can cause us to erroneously approve balancer actions.
> HBASE-29202 Balancer conditionals make balancer actions more likely to be approved

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFromRegionLoadFunction.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StoreFileTableSkewCostFunction.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStoreFileTableSkewCostFunction.java
I deployed this to a QA cluster at my company and enabled:
1. System table isolation (balancer conditional)
2. Replica distribution (balancer conditional)
3. and primarily balanced based on StoreFileSizeTableSkew and StoreFileSizeCost
We ended up with multiple tables, balanced virtually perfectly in every regard (the empty column is the host assigned to serving system tables):
I'm still thinking about how to unit test this. It is implicitly tested by our existing test suite since it has a default cost >0, but there is not much precedent for testing these cost functions individually and it would be non-trivial to meaningfully test it in isolation
> HBASE-29203 There should be a StorefileSize equivalent to the TableSkewCost

- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerClusterState.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/CostFromRegionLoadFunction.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.java
- hbase-balancer/src/main/java/org/apache/hadoop/hbase/master/balancer/StoreFileTableSkewCostFunction.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStochasticLoadBalancer.java
- hbase-balancer/src/test/java/org/apache/hadoop/hbase/master/balancer/TestStoreFileTableSkewCostFunction.java
> Backport "HBASE-29203 There should be a StorefileSize equivalent to the TableSk…" to branch-3

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/balancer/BalancerConditionals.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/CandidateGeneratorTestUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/balancer/TestUnattainableBalancerCostGoal.java
> Backport "HBASE-29202 Balancer conditionals make balancer actions more likely t…" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileScanner.java
…seeking to next row (#6643)
cc @rmdmattingly
> Backport "HBASE-29103 Avoid excessive allocations during reverse scanning when …" to branch 2.6

- hbase-client/src/main/java/org/apache/hadoop/hbase/security/EncryptionUtil.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-http/src/test/java/org/apache/hadoop/hbase/http/TestHtmlQuoting.java
- hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestsDriver.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableSnapshotInputFormatImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/FixedFileTrailer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/compaction/MajorCompactor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestSpaceQuotasWithSnapshots.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegionInfo.java
- hbase-shaded/pom.xml
- hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThriftHBaseServiceHandler.java
- pom.xml
We can either squash these into a single commit, or backport the five patches one-by-one (reordered, and with the right commit message).
Which one do you prefer ?
> HBASE-29205 Bump hbase-thirdparty to 4.1.10 in branch-2.5

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java
> HBASE-29146: Incremental backups can fail due to not cleaning up the MR bulkload output directory

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestIncrementalBackup.java
…R bulkload output directory (#6747)
> Backport "HBASE-29146 Incremental backups can fail due to not cleaning up the M…" to branch-3

- hbase-shell/src/main/ruby/hbase/admin.rb
- hbase-shell/src/test/ruby/hbase/admin_test.rb
- hbase-shell/src/test/ruby/shell/commands_test.rb
Sometimes, users may inadvertently attempt to use compaction_switch; therefore, it is advisable to implement a verification step for the first argument passed to this function, ensuring that incorrect inputs do not accidentally disable compaction.
> HBASE-28754 verify the first argument passed to compaction_switch

- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
- hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/RootProcedureState.java
Details see: [HBASE-29055](https://issues.apache.org/jira/browse/HBASE-29055)
> HBASE-29055 Remove the useless parameter from RootProcedureState

- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/RpcThrottlingException.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleSettings.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleType.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-protocol-shaded/src/main/protobuf/server/Quota.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/ExceedOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/GlobalQuotaSettingsImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/OperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RpcQuotaManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestAtomicReadQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultAtomicQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestNoopOperationQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaAdmin.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaState.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/ThrottleQuotaTestUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerLeaseCount.java
Pretty straightforward, and well tested here imo: atomic requests can be uniquely expensive, and it would be nice to throttle them in isolation.
cc @ndimiduk @hgromer
> HBASE-29229 Throttles should support specific restrictions for atomic workloads

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
…we don't cleanup the MR directory (#6876)
> Backport "HBASE-29239: Subsequent runs of re-splitting HFiles can fail because …" to branch-3

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
…we don't cleanup the MR directory (#6876)
> Backport "HBASE-29239: Subsequent runs of re-splitting HFiles can fail because …" to branch-2.6

- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/RpcThrottlingException.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleSettings.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/ThrottleType.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
- hbase-protocol-shaded/src/main/protobuf/Quota.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/DefaultOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/ExceedOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/GlobalQuotaSettingsImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopOperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/NoopQuotaLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/OperationQuota.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/QuotaUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RegionServerRpcQuotaManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/RpcQuotaManager.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/quotas/TimeBasedLimiter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionCoprocessorHost.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestAtomicReadQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultAtomicQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestDefaultOperationQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestNoopOperationQuota.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaAdmin.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaState.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/ThrottleQuotaTestUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerLeaseCount.java
> Backport "HBASE-29229 Throttles should support specific restrictions for atomic…" to branch-2.6

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupDriver.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRestoreConstants.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupCommands.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupDelete.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupDeleteWithContinuousBackupAndPITR.java
This PR introduces validation to prevent the deletion of backups that are essential for Point-In-Time Recovery (PITR). If a backup is the only remaining full backup enabling PITR for certain tables, deletion will be blocked unless the force option is explicitly specified.
> HBASE-29210: Introduce Validation for PITR-Critical Backup Deletion

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdminRequestRetryingCaller.java
We do not implement complicated relocating logic for admin operations, so when region is moved, we just fail the operations immediately, like compacting table, etc.
> HBASE-29232 give up retrying earlier for some admin operations

- hbase-compression/hbase-compression-zstd/src/main/java/org/apache/hadoop/hbase/io/compress/zstd/ZstdByteBuffDecompressor.java
- hbase-compression/hbase-compression-zstd/src/test/java/org/apache/hadoop/hbase/io/compress/zstd/TestZstdByteBuffDecompressor.java
- pom.xml
At present, `ZstdByteBuffDecompressor` is limited to decompressing from a direct ByteBuffer to another direct ByteBuffer, or from a heap ByteBuffer to another heap ByteBuffer. Following a [change](https://github.com/luben/zstd-jni/pull/351) I contributed to the zstd-jni project, this limitation can be removed.
> HBASE-29193: Allow ZstdByteBuffDecompressor to take direct ByteBuffer as input and heap ByteBuffer as output, or vice versa

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
I've looked at a lot of allocation profiles of RegionServers doing a read-heavy workload. Some allocations that dominate the chart can be easily avoided. The method `StoreScanner#read()` contains this code
```
heap.recordBlockSize(blockSize -> {
if (rpcCall.isPresent()) {
rpcCall.get().incrementBlockBytesScanned(blockSize);
}
scannerContext.incrementBlockProgress(blockSize);
});
```
that runs for every iteration of its main loop. A closure can be created before the loop and re-used instead.
> HBASE-29253: Avoid allocating a new closure on every row processed by StoreScanner

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/region/MasterRegion.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterRegionMutation1.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterRegionMutation2.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestMasterRegionMutation.java
> HBASE-29251 Procedure gets stuck if the procedure state cannot be persisted

- hbase-client/src/main/java/org/apache/hadoop/hbase/security/provider/SaslClientAuthenticationProviders.java
- pom.xml
When the `ServiceLoader::load` method is invoked with a single argument, it uses the context `ClassLoader` of current thread(by calling `Thread.currentThread.getContextClassLoader()`). (For definition, see [here](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html#load-java.lang.Class-).)
Under normal circumstances, this does not cause issues. But there is a problem if you try to:
- load a class at runtime from a jar file (e.g. call `URLClassLoader::loadClass`)
- (the jar file has a dependency with `hbase-client`)
- from the parent Application.
In my case, I encountered this problem while developing JDBC wrapper for hbase-shell.
If you load the class from the jar file, the `ClassLoader` of current thread is normally the class loader used to load the parent application. …
> HBASE-25338 Use ClassLoader of current class instead of thread context ClassLoader

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/BufferedMutatorParams.java
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestBufferedMutatorParams.java
As title, a small mistake was introduced in [HBASE-28001](https://issues.apache.org/jira/browse/HBASE-28001).
> HBASE-29204: BufferedMutatorParams#clone() should copy the requestAttributes field

- hbase-common/src/main/java/org/apache/hadoop/hbase/ByteBufferKeyOnlyKeyValue.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/io/encoding/RowIndexSeekerV1.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestRowIndexV1RoundTrip.java
I've looked at a lot of allocation profiles of RegionServers doing a read-heavy workload. Some allocations that dominate the chart can be easily avoided.
The following code in the main decode method
```
currentBuffer.asSubByteBuffer(currentBuffer.position(), current.keyLength, tmpPair);
ByteBuffer key = tmpPair.getFirst().duplicate();
key.position(tmpPair.getSecond()).limit(tmpPair.getSecond() + current.keyLength);
current.keyBuffer = key; 
```
results in a new ByteBuffer for every cell. The reason to have this duplicate ByteBuffer is to hold the result of tmpPair.getSecond() as its position state. But this is just an integer that can be more cheaply stored in a different way. We can introduce a current.keyOffset variable and do this instead:
``` …
```
> HBASE-29252: Reduce allocations in RowIndexSeekerV1

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRestoreConstants.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/snapshot/ClientSnapshotDescriptionUtils.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/NamespaceDescriptor.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/TableName.java
> Backport "HBASE-29207 The backup system table should be considered a system tab…" to branch-3

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupRestoreConstants.java
- hbase-client/src/main/java/org/apache/hadoop/hbase/snapshot/ClientSnapshotDescriptionUtils.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/NamespaceDescriptor.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/TableName.java
> Backport "HBASE-29207 The backup system table should be considered a system tab…" to branch-2

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/TakeSnapshotHandler.java
Since the process stage of TakeSnapshotHandler starts [async](https://github.com/apache/hbase/blob/branch-2.5/hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotManager.java#L578), sometimes it takes too much time to downgrade from EXCLUSIVE to SHARED lock blocking ASSIGN child procedures of SCP.
> HBASE-29109 Downgrade to shared lock at the time of prepare snapshot itself

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStore.java
[HBASE-29254](https://issues.apache.org/jira/browse/HBASE-29254)
> HBASE-29254 StoreScanner returns incorrect row after flush due to topChanged behavior

- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaSettingsFactory.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaThrottle.java
While rolling out atomic throttles at my day job, I realized that we're unable to fetch our atomic throttle settings. This is because, in https://issues.apache.org/jira/browse/HBASE-29229, I forgot to wire up atomic throttles in the QuotaSettingsFactory.
I've also added a test that will make it much harder to make this same mistake down the road
> HBASE-29281 Atomic request throttles are missing QuotaSettingsFactory support

- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaSettingsFactory.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaThrottle.java
> Backport "HBASE-29281 Atomic request throttles are missing QuotaSettingsFactory…" to branch-3

- hbase-client/src/main/java/org/apache/hadoop/hbase/quotas/QuotaSettingsFactory.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/quotas/TestQuotaThrottle.java
> Backport "HBASE-29281 Atomic request throttles are missing QuotaSettingsFactory…" to branch-2

- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestRecreateCluster.java
TestRecreateCluster has a logic error and and would cleanup the master region in the root directory, this is not the right case we would like to support in the cloud storage that we expect the hbase cluster to shutdown gracefully and master region to be flushed to permanent storage as HFiles.
> HBASE-29292 Revise TestRecreateCluster

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/TableDescriptorChecker.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestTableDescriptorChecker.java
HBASE-29137 was backported to branch-2 in #6799, but @guluo2016 pointed out that it doesn't perform verification of the column-familiy level configuration.
* See https://github.com/apache/hbase/pull/6799#discussion_r2084374632
This was due to the change of the alter command of HBase shell in #1959 in master branch which decided to use `setValue` instead of `setConfiguration`. So in branch-2, we need to check the values in the `configuration`, instead of `values`. But in this patch, I updated the code to check both.
The unit test was unable to detect this because it was using `setValue` instead of `setConfiguration`.
@Apache9 Do you think we also need this in master branch? Could you explain the difference between "values" and "configuration"? Are we phasing out the latter?
> HBASE-29314 TableDescriptorChecker should verify CF configuration set via setConfiguration (branch-2)

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncTableImpl.java
I noticed a bug that I introduced in [HBASE-28770](https://issues.apache.org/jira/browse/HBASE-28770). I introduced the ability for coprocessor endpoints to send partial responses. When this happens, the client needs to send a new request to fetch remaining results, and may sleep before doing so. The logic for sleeping looks like:
```
if (waitInterval.isZero()) {
  AsyncConnectionImpl.RETRY_TIMER.newTimeout(
    (timeout) -> coprocessorServiceUntilComplete(stubMaker, updatedCallable, callback,
      locateFinished, unfinishedRequest, region, span),
    waitInterval.toMillis(), TimeUnit.MILLISECONDS);
} else {
  coprocessorServiceUntilComplete(stubMaker, updatedCallable, callback, locateFinished,
    unfinishedRequest, region, span);
}  
```
which has backwards logic. The first line should …
> HBASE-29280: Fix bug in RawAsyncTableImpl#coprocessorServiceUntilComplete retry logic

- bin/hbase-daemon.sh
See https://issues.apache.org/jira/browse/HBASE-29307
```
$ ./bin/hbase-daemon.sh status master
master is not running
$ echo $?
1
$ ./bin/hbase-daemon.sh status regionserver
regionserver is running as PID 45560
$ echo $?
0
```
> HBASE-29307 Add status command to hbase-daemon.sh for process state checking

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterAnnotationReadingPriorityFunction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterQosFunction.java
These reports are critical for completing region movements and ensuring availability. Any delay in reporting can directly impact system availability.
> HBASE-29323 Use Priority Handler for all RegionServerStatus rpc at Master

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupCommands.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupDeleteWithContinuousBackupAndPITR.java
The current approach incorrectly checks whether a full backup is the only valid base for all PITR target points, which is not a valid criterion. A full backup should not be required to support all PITR points to be considered necessary. Instead, each full backup only contributes to a specific PITR time range, depending on when the backup was taken and the availability of continuous backups afterward.
This ticket proposes a more accurate and conservative approach:
- Determine the PITR range each full backup can support.
- Identify if another full backup exists that fully covers the same range.
- If such a backup exists, the original one can be considered safe for deletion.
> HBASE-29261: Investigate flaw in backup deletion validation of PITR-critical backups and propose correct approach

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterAnnotationReadingPriorityFunction.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterQosFunction.java
HBASE-29323 Use Priority Handler for all RegionServerStatus rpc at Master(#6994)
> HBASE-29323 Use Priority Handler for all RegionServerStatus rpc at Master(#6994)

- hbase-endpoint/pom.xml
- hbase-endpoint/src/main/java/org/apache/hadoop/hbase/coprocessor/AggregateImplementation.java
- hbase-endpoint/src/test/java/org/apache/hadoop/hbase/coprocessor/TestAggregateImplementation.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionScannerImpl.java
My contribution in [HBASE-28770](https://issues.apache.org/jira/browse/HBASE-28770) contains a bug that is exposed under certain conditions. When using `AsyncAggregationClient` (not `AggregationClient`), the client signals that it can accept partial results. On the server side, this triggers `AggregateImplementation` to check quotas prior to each cell that it scans, and return as soon as a throttle is violated, even if the result is not complete. The client will sleep and then make a request for the next chunk of results.
However, when `AggregateImplementation` violates a throttle before finding any results at all, it returns a result to the client that says the results are empty and complete, so the client should not request any more. Under high load, this can happen and lead to the …
> HBASE-29301: Fix AggregrateImplementation pagination logic

- pom.xml
* This change is required for being able to handle recent Java bytecodes
* Move to latest version which works with maven-shade-plugin 3.6.0
> HBASE-29327 Dependency manage byte-buddy and bump it to 1.15.11

- hbase-rest/src/main/resources/hbase-webapps/rest/footer.jsp
- hbase-server/pom.xml
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/regionserver/RSStatusTmpl.jamon
- hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/tool/CanaryStatusTmpl.jamon
- hbase-server/src/main/resources/hbase-webapps/master/scripts.jsp
- hbase-server/src/main/resources/hbase-webapps/regionserver/footer.jsp
- hbase-thrift/src/main/resources/hbase-webapps/thrift/footer.jsp
Popovers ("Metrics" menu) were not working on the UI and the following JS error was logged to browser console:
```
Uncaught TypeError: i.createPopper is not a function
```
This is because popper.js was not available on the page for Bootstrap.
Solution: We use bootstrap.bundle.min.js instead which includes both popper.js and Bootstrap.
> HBASE-27802 Manage static javascript resources programatically (addendum: Fix not working popovers on UI)

- hbase-common/src/main/java/org/apache/hadoop/hbase/io/util/BlockIOUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
This PR updates expensive tracing calls if tracing is disabled. In particular, the expensive tracing calls as determined by a flamegraph are in BlockIOUtils & HFileBlock. I've audited for other places where tracing is used to eliminate any other expensive calls as well (but couldn't find any outside of BlockIOUtils & HFileBlock). 
This generally just follows the pattern of refactoring to use empty Attributes if we can determine that the Span isn't going to be persisted/saved anywhere via Span.isRecordingEnabled e.g. the same approach taken in https://github.com/apache/hbase/pull/6642 / [HBASE-29099](https://issues.apache.org/jira/browse/HBASE-29099)
I used the Span.isRecordingEnabled API ([OpenTelemetry Docs](https://opentelemetry.io/docs/specs/otel/trace/api/#isrecording)). Based on the …
> HBASE-29222 Avoid expensive tracing calls if tracing is disabled

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/MergeTableRegionsProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/SplitTableRegionProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/AbstractStateMachineTableProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/RegionServerHostingReplicaSlowOpenCoprocessor.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestMergeTableRegionsProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestSplitTableRegionProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestTruncateRegionProcedure.java
When adding new replicas, ModifyTableProcedure roughly does the following:
1. Edits the table descriptor
1. Closes and opens all existing regions
1. Creates replication peer to support the new replica regions
1. Opens new replica regions
When closing a region in step 2, the act of closing it can trigger a split. When the HMaster runs the SplitTableRegionProcedure, it roughly does:
1. Close the region to be split
1. Split the store files
1. Open the new daughter regions (including replicas)
When a split is done as part of a ModifyTableProcedure that adds replicas, we get the following combination of behavior:
1. Edit the table descriptor
1. Close and open all existing regions, adding a SplitTableRegionProcedure to the HMaster's queue
1. To begin the SplitTableRegionProcedure, close region …
> HBASE-29315: Cancel Split/MergeTableRegionProcedure if table modification is in progress

- hbase-assembly/src/main/assembly/client.xml
- hbase-assembly/src/main/assembly/hadoop-three-compat.xml
- hbase-assembly/src/main/assembly/hadoop-two-compat.xml
- hbase-client/src/test/java/org/apache/hadoop/hbase/client/trace/hamcrest/SpanDataMatchers.java
- hbase-common/pom.xml
- hbase-common/src/main/java/org/apache/hadoop/hbase/trace/HBaseSemanticAttributes.java
- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableMapReduceUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/AbstractTestAsyncTableScan.java
- hbase-shaded/hbase-shaded-client/pom.xml
- hbase-shaded/hbase-shaded-testing-util/pom.xml
- hbase-shaded/pom.xml
- pom.xml
* Move from `io.opentelemetry:opentelemetry-semconv` to relocated groupid `io.opentelemetry.semconv:opentelemetry-semconv` and change imports accordingly.
* Refactoring to keep all semantic attributes inside `HBaseSemanticAttributes`
* Add appropriate excludes and includes for renamed groupid `io.opentelemetry.semconv:opentelemetry-semconv` from `io.opentelemetry:opentelemetry-semconv`
Signed-off-by: Istvan Toth <stoty@apache.org>
(cherry picked from commit 82a2ddf789d161877b3920decab9565f56e6aa4b)
> HBASE-29293 Upgrade to latest opentelemetry libraries (#6969)

- pom.xml
* This change is required for being able to handle recent Java bytecodes
* Move to latest version which works with maven-shade-plugin 3.6.0
Signed-off-by: Istvan Toth <stoty@apache.org>
(cherry picked from commit 279398254459f296adfee5f1c87a50d4fba5e593)
> HBASE-29327 Dependency manage byte-buddy and bump it to 1.15.11 (#7003)

- pom.xml
Bump JRuby to version 9.3.15.0 — the final release in the 9.3 series (June 2024) — to incorporate the latest bug fixes.
* https://github.com/jruby/jruby/releases/tag/9.3.14.0
* https://github.com/jruby/jruby/releases/tag/9.3.15.0
joni and jcodings are already up-to-date.
* https://github.com/apache/hbase/blob/337a5303e3c669f6fb3e1030215cc6af8f9d595a/pom.xml#L626-L627
* https://github.com/jruby/jruby/blob/9.3.15.0/core/pom.rb#L54-L55
/cc @NihalJain
> HBASE-29360 Bump JRuby to version 9.3.15.0 in branch-2.6

- pom.xml
- Drops moderate jruby-openssl CVE: CVE-2025-46551 and GHSA-72qj-48g4-5xgx  from our classpath.
- Also fixes performance problem in IRB where pasting clipboard content is extremely slow.
> HBASE-29318 Bump jruby to 9.4.12.1 to fix jruby-openssl CVEs

- pom.xml
- Drops moderate jruby-openssl CVE: CVE-2025-46551 and GHSA-72qj-48g4-5xgx  from our classpath.
- Also fixes performance problem in IRB where pasting clipboard content is extremely slow.
> HBASE-29318 Bump jruby to 9.4.12.1 to fix jruby-openssl CVEs (#6997)

- hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/CoprocessorHost.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/security/access/ReadOnlyController.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestCanStartHBaseInReadOnlyMode.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestReadOnlyController.java
- src/main/asciidoc/_chapters/configuration.adoc
https://issues.apache.org/jira/browse/HBASE-29236
This pull request adds support for Dynamic Configuration at the coprocessor level and makes the `hbase.global.readonly.enabled` config variable dynamically configurable.  This variable is used with the ReadOnlyController coprocessor.  In order to make this class dynamically configurable, we have it implement the ConfigurationObserver interface.  We also need to register this observer with the ConfigurationManager, so the ReadOnlyController is registered to HMaster's, HRegionServer's, and HRegion's ConfigurationManager.  Also, since the ReadOnlyController is a coprocessor, we need to use the CoprocessorHost in order to get the coprocessor and register it with the ConfigurationManager.
`hbase.global.readonly.enabled` can be configured …
> HBASE-29236: Add Support for Dynamic Configuration at the Coprocessor Level

- hbase-diagnostics/src/main/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
See https://issues.apache.org/jira/browse/HBASE-29357 for details.
```sh
bin/hbase pe --nomapred --size=2 --presplit=30 sequentialWrite 1
bin/hbase pe --nomapred --size=2 --presplit=30 --sampleRate=0.1 sequentialRead 1
bin/hbase shell -n <<< "split 'TestTable'"
bin/hbase pe --nomapred --size=2 --presplit=30 --sampleRate=0.1 sequentialRead 1
bin/hbase pe --nomapred --size=2 --presplit=30 --replicas=2 --sampleRate=0.1 sequentialRead 1
bin/hbase pe --nomapred --size=2 --presplit=30 --replicas=2 --splitPolicy=org.apache.hadoop.hbase.regionserver.DisabledRegionSplitPolicy --sampleRate=0.1 sequentialRead 1
bin/hbase pe --nomapred --size=2 --presplit=30 --replicas=2 --splitPolicy=org.apache.hadoop.hbase.regionserver.DisabledRegionSplitPolicy --families=2 --sampleRate=0.1 sequentialRead 1
```
> HBASE-29357 PerformanceEvaluation: Read tests should not drop existing table

- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
Backport HBASE-29357 to branch-2 as requested by @taklwu.
Tested manually from branch-2.
```sh
bin/hbase pe --nomapred --size=2 --presplit=40 sequentialWrite 1
bin/hbase pe --nomapred --size=2 --presplit=20 sequentialWrite 1
bin/hbase pe --nomapred --size=2 --presplit=30 --replicas=2 --splitPolicy=org.apache.hadoop.hbase.regionserver.DisabledRegionSplitPolicy sequentialRead 1
bin/hbase pe --nomapred --size=2 --presplit=30 --replicas=2 --splitPolicy=org.apache.hadoop.hbase.regionserver.DisabledRegionSplitPolicy --families=2 sequentialRead 1
```
> Backport "HBASE-29357 PerformanceEvaluation: Read tests should not drop existing table" to branch-2

- hbase-diagnostics/src/main/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
Backport [HBASE-29357](https://issues.apache.org/jira/browse/HBASE-29357) to branch-3 as requested by @taklwu.
Same test result as https://github.com/apache/hbase/pull/7049.
> Backport "HBASE-29357 PerformanceEvaluation: Read tests should not drop existing table" to branch-3

- hbase-build-configuration/pom.xml
- hbase-examples/pom.xml
- hbase-shaded/hbase-shaded-check-invariants/src/test/resources/ensure-jars-have-correct-contents.sh
- hbase-shaded/hbase-shaded-with-hadoop-check-invariants/src/test/resources/ensure-jars-have-correct-contents.sh
- hbase-shaded/pom.xml
- pom.xml
* Update allowed_expr to allow `org/jspecify/annotation/*.class` which is coming from guava due to https://github.com/google/guava/commit/2cc8c5eddb587db3ac12dacdd5563e79a4681ec4
* Bump maven-shade-plugin to 3.6.0 as we see failure `META-INF/versions/22/com/fasterxml/jackson/core/internal/shaded/fdp/v2_19_0/FastDoubleSwar.class: java.lang.IllegalArgumentException: Unsupported class file major version 66` due to https://github.com/FasterXML/jackson-core/commit/7d8dc09bb772ffb0981e3dcf8e9d95b2273bd756
* Add `--should-stop=ifError=FLOW` as `compilerArgs`. This is required by error prone >= 2.36.0, otherwise compile fails. See https://github.com/google/error-prone/commit/e71db1f369a9367f6f2db34c4fbd006b6d6238fd for details!
> HBASE-29317 Bump hbase-thirdparty to 4.1.11

- hbase-build-configuration/pom.xml
- hbase-shaded/hbase-shaded-check-invariants/src/test/resources/ensure-jars-have-correct-contents.sh
- hbase-shaded/hbase-shaded-with-hadoop-check-invariants/src/test/resources/ensure-jars-have-correct-contents.sh
- hbase-shaded/pom.xml
- pom.xml
* Update allowed_expr to allow `org/jspecify/annotation/*.class` which is coming from guava due to https://github.com/google/guava/commit/2cc8c5eddb587db3ac12dacdd5563e79a4681ec4
* Bump maven-shade-plugin to 3.6.0 as we see failure `META-INF/versions/22/com/fasterxml/jackson/core/internal/shaded/fdp/v2_19_0/FastDoubleSwar.class: java.lang.IllegalArgumentException: Unsupported class file major version 66` due to https://github.com/FasterXML/jackson-core/commit/7d8dc09bb772ffb0981e3dcf8e9d95b2273bd756
* Add `--should-stop=ifError=FLOW` as `compilerArgs`. This is required by error prone >= 2.36.0, otherwise compile fails. See https://github.com/google/error-prone/commit/e71db1f369a9367f6f2db34c4fbd006b6d6238fd for details! But since we do not upgrade to 2.36.0 on branch-2.x we have kept this …
> HBASE-29317 Bump hbase-thirdparty to 4.1.11 (#6993)

- hbase-build-configuration/pom.xml
- hbase-shaded/hbase-shaded-check-invariants/src/test/resources/ensure-jars-have-correct-contents.sh
- hbase-shaded/hbase-shaded-with-hadoop-check-invariants/src/test/resources/ensure-jars-have-correct-contents.sh
- hbase-shaded/pom.xml
- pom.xml
* Update allowed_expr to allow `org/jspecify/annotation/*.class` which is coming from guava due to https://github.com/google/guava/commit/2cc8c5eddb587db3ac12dacdd5563e79a4681ec4
* Bump maven-shade-plugin to 3.6.0 as we see failure `META-INF/versions/22/com/fasterxml/jackson/core/internal/shaded/fdp/v2_19_0/FastDoubleSwar.class: java.lang.IllegalArgumentException: Unsupported class file major version 66` due to https://github.com/FasterXML/jackson-core/commit/7d8dc09bb772ffb0981e3dcf8e9d95b2273bd756
* Add `--should-stop=ifError=FLOW` as `compilerArgs`. This is required by error prone >= 2.36.0, otherwise compile fails. See https://github.com/google/error-prone/commit/e71db1f369a9367f6f2db34c4fbd006b6d6238fd for details! But since we do not upgrade to 2.36.0 on branch-2.x we have kept this …
> HBASE-29317 Bump hbase-thirdparty to 4.1.11 (#6993) 

- hbase-diagnostics/src/main/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
- hbase-diagnostics/src/test/java/org/apache/hadoop/hbase/TestPerformanceEvaluation.java
https://issues.apache.org/jira/browse/HBASE-29365
> HBASE-29365 Improve option parser of PerformanceEvaluation

- hbase-client/src/main/java/org/apache/hadoop/hbase/ActiveClusterSuffix.java
- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-protocol-shaded/src/main/protobuf/server/ActiveClusterSuffix.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterFileSystem.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestActiveClusterSuffix.java
Using HBase Active and Read Replica Clusters, there could be potential problem scenarios where multiple clusters started in the active mode. This change set prevents starting multiple clusters in active mode.
> HBASE-29228 Add support to prevent running multiple active clusters

- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMultiParallel.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestTimestampsFilter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFileDataBlockEncoder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestDeadServer.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerWithBulkload.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestLogRolling.java
Details see: [HBASE-29273](https://issues.apache.org/jira/browse/HBASE-29273)
> HBASE-29273 Remove deprecated boxed primitive constructors in some test classes

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ModifyTableProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ReopenTableRegionsProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestReopenTableRegionsProcedureBatching.java
See https://issues.apache.org/jira/browse/HBASE-29279
```ruby
alter 't', { NAME => 'd', COMPRESSION => 'GZ' }
alter 't', { NAME => 'd', COMPRESSION => 'GZ' },
{
CONFIGURATION => {
'hbase.reopen.table.regions.progressive.batch.size.max' => 32,
'hbase.reopen.table.regions.progressive.batch.backoff.ms' => 500
}
}
alter 't', { NAME => 'd', COMPRESSION => 'GZ' }
```
> HBASE-29279 Allow throttling alter operation via table configuration

- hbase-backup/pom.xml
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupHFileCleaner.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupHFileCleaner.java
https://issues.apache.org/jira/browse/HBASE-29029
> HBASE-29029 Refactor BackupHFileCleaner + fix test

- pom.xml
Details see: [HBASE-29388](https://issues.apache.org/jira/browse/HBASE-29388)
Before applying this change. 
Afet executing `mvn spotless:apply` on Windows
```bash
git diff
warning: LF will be replaced by CRLF in CHANGES.txt.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in LICENSE.txt.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in NOTICE.txt.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in conf/hbase-policy.xml.
The file will have its original line endings in your working directory …
```
> HBASE-29388 mvn spotless:apply changes line endings (CRLF to LF) on Windows

- hbase-backup/pom.xml
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupHFileCleaner.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupHFileCleaner.java
The TestBackupHFileCleaner test was broken, as it used a different API to register bulk loads than the API that is actually used to register bulk loads during backups. The test also incorrectly closed the FS of the HBaseTestingUtil, causing this test to block for about 5 minutes during shutdown.
Both the test and BackupHFileCleaner itself were overly convoluted and are cleaned up. Methods in BackupSystemTable that could lead to incorrect use have been removed or deprecated (to fix their use case in HBASE-28715).
> Backport "HBASE-29029 Refactor BackupHFileCleaner + fix test (#6533)" to branch-2

- hbase-backup/pom.xml
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/BackupHFileCleaner.java
- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupHFileCleaner.java
The TestBackupHFileCleaner test was broken, as it used a different API to register bulk loads than the API that is actually used to register bulk loads during backups. The test also incorrectly closed the FS of the HBaseTestingUtil, causing this test to block for about 5 minutes during shutdown.
Both the test and BackupHFileCleaner itself were overly convoluted and are cleaned up. Methods in BackupSystemTable that could lead to incorrect use have been removed or deprecated (to fix their use case in HBASE-28715).
> Backport "HBASE-29029 Refactor BackupHFileCleaner + fix test (#6533)" to branch-2.6

- conf/hadoop-metrics2-hbase.properties
https://issues.apache.org/jira/browse/HBASE-29399
> HBASE-29399 Update hadoop-metrics2-hbase.properties template

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
Fixes a URISyntaxException during incremental backup creation for tables that have a (non-default) namespace.
> HBASE-29423 Incremental backups broken for non-default namespaces

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
Fixes a URISyntaxException during incremental backup creation for tables that have a (non-default) namespace.
> Backport "HBASE-29423 Incremental backups broken for non-default namespaces (#7130)" to branch-3

- hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/IncrementalTableBackupClient.java
Fixes a URISyntaxException during incremental backup creation for tables that have a (non-default) namespace.
> Backport "HBASE-29423 Incremental backups broken for non-default namespaces (#7130)" to branch-2.6

- hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/snapshot/ExportSnapshot.java
- hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/snapshot/TestExportSnapshotHelpers.java
I propose to make ExposeSnapshot accept two plugins: a CustomFileGrouper and a FileLocationResolver. Here's what they will look like:
```
public interface CustomFileGrouper {
Collection<Collection<Pair<SnapshotFileInfo, Long>>>
getGroupedInputFiles(final Collection<Pair<SnapshotFileInfo, Long>> snapshotFiles);
}
public interface FileLocationResolver {
Set<String> getLocationsForInputFiles(final Collection<Pair<SnapshotFileInfo, Long>> files);
}
```
Users can optionally provide implementations of these interfaces on their classpath, and tell ExportSnapshot to use them via new options. By default, there will be no change in behavior. If users choose to implement these plugins, they can influence ExportSnapshot to be topology-aware in a very flexible way. I plan to write my own plugins …
> HBASE-29432: Provide mechanism to plug in rack or host locality logic into ExportSnapshot

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/BucketCache.java
The merge of HBASE-28596 on branch-2.6 has broken HBASE-29243. This addendum commit fixes this issue.
> [ADDENDUM] HBASE-28596 Optimise BucketCache usage upon regions splits/merges.

- hbase-client/src/main/java/org/apache/hadoop/hbase/client/metrics/ServerSideScanMetrics.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/BlockCacheUtil.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CompoundBloomFilter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/FixedFileTrailer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlock.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileBlockIndex.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileReaderImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/LruBlockCache.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/NoOpIndexBlockEncoder.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/ThreadLocalServerSideScanMetrics.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionScannerImpl.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SegmentScanner.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileReader.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileWriter.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/handler/ParallelSeekHandler.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestBytesReadFromFs.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBytesReadServerSideScanMetrics.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestDefaultMemStore.java
Cherry-pick of https://github.com/apache/hbase/pull/7158.
- Conflicts in some import statements.
- In BlockCacheUtil#getBlockForCaching() the `NextBlockOnDiskSize` is set to -1. This seems to be miss as this will lead to some extra seeks just to get onDiskSize of block when reading next block of the current block. This was fixed in 2.7 as a side item as part of [HBASE-29288](https://issues.apache.org/jira/browse/HBASE-29288). In 2.6 fixing this gap as a side item via this PR.
> HBASE-29398: Server side scan metrics for bytes read from FS vs Block cache vs memstore

- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerCall.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/ipc/TestServerCall.java
ServerCall.setResponse() method currently swallows IOException when creating response, 
leaving client without any indication of server-side failure. This violates the RPC 
protocol requirement that server should always send a response (either success or error).
This issue has existed since HBASE-14598 and continues to affect the latest branches 
(3.0 and 2.6).
The original fix for HBASE-14598 attempted to prevent OOM errors by checking array size 
before allocation and throwing DoNotRetryIOException to stop client retries. However, 
the DoNotRetryIOException never reaches the client due to a flaw in ServerCall.setResponse().
When IOException occurs during response creation (e.g., during cell block building):
1. The exception is caught in ServerCall.setResponse()
2. Only a warning is …
> HBASE-28589 ServerCall.setResponse swallows IOException and leaves client without response

- hbase-server/src/main/java/org/apache/hadoop/hbase/util/RegionSplitter.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestRegionSplitter.java
https://issues.apache.org/jira/browse/HBASE-29474
The first commit breaks the test, and the second commit fixes it.
EDIT: The third commit revives the sorting logic that was mistakenly removed in https://github.com/apache/hbase/commit/5e91b45b166cd5a68457234f0a62ca1c2b5d9211.
> HBASE-29474 RegionSplitter.rollingSplit is broken

- hbase-backup/src/test/java/org/apache/hadoop/hbase/backup/TestBackupRestoreExpiry.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestSnapshotProcedureEarlyExpiration.java
[ADDENDUM] Fix broken branch-2/branch-2.6 builds
The recent changes in #6970 have caused build failures on the branch-2/branch-2.6, the details see: https://github.com/apache/hbase/pull/6970#issuecomment-3149151194
The root cause was a class name mismatch due to my oversight: the code was using `HBaseTestingUtil` instead of the correct class name `HBaseTestingUtility`.
> [ADDENDUM] HBASE-29296 Missing critical snapshot expiration checks

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
- hbase-protocol-shaded/src/main/protobuf/server/master/MasterProcedure.proto
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/DeleteTableProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ModifyTableProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/RecoverySnapshotUtils.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TruncateRegionProcedure.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TruncateTableProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestDeleteTableProcedureWithRecovery.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestModifyTableProcedureWithRecovery.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestRecoverySnapshotUtils.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestTruncateRegionProcedureWithRecovery.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestTruncateTableProcedureWithRecovery.java
Although HFiles are copied to the archive in a destructive schema change, recovery scenarios are not automatic and involve some operator labor to reconstruct the table and re-import the archived data. We can easily prevent the deletion of the HFiles of a deleted table or column family by taking a snapshot of the table immediately prior to any destructive schema actions. We also set a TTL on the snapshot so housekeeping of unwanted HFiles remains no touch. Because we take a table snapshot all table structure and metadata is also captured and saved so fast recovery is possible, as either a restore from snapshot, or a clone from snapshot to a new table.
Existing site configuration property prerequisites:
* `hbase.snapshot.enabled` = `true` ( default is `true` )
New site configuration …
> HBASE-28919 Soft drop for destructive table actions

- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionFileSystem.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreEngine.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/MigrationStoreFileTracker.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileTracker.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/storefiletracker/StoreFileTrackerBase.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompactionArchiveConcurrentClose.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHStore.java
Post [HBASE-28564](https://issues.apache.org/jira/browse/HBASE-28564), HStoreFile creation is SFT aware and Reference file creations are moved to SFT.
To enable virtual links from [HBASE-27826](https://issues.apache.org/jira/browse/HBASE-27826), HFileArchival should be routed via SFT instead of HRegionFileSystem, to identify and archive only physical files and skip virtual links
> HBASE-29458 SFT removeStoreFiles api to only archive physical files and ignore virtual links

- hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestBackupRestore.java
https://issues.apache.org/jira/browse/HBASE-29503
Currently, IntegrationTestBackupRestore is creating a separate thread to run the full/incremental backup and restore processes.  With this implementation, if an exception occurs in this thread, then an error will be logged but the integration test will still pass.  I initially noticed this while working on [HBASE-29411](https://issues.apache.org/jira/browse/HBASE-29411).  I also observed this behavior when I did not have changes from PR #7151 in my branch.
This pull request turns the backup/restore thread into an actual class that implements Runnable.  Within this class, there is an instance variable that starts as `null` and records any exceptions that occur.  The main thread checks this instance variable when it joins the thread.  If …
> HBASE-29503: IntegrationTestBackupRestore is passing even if an exception occurs in the thread(s) it creates

- hbase-server/src/main/java/org/apache/hadoop/hbase/wal/AbstractRecoveredEditsOutputSink.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitUtil.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplit.java
Solution Document - https://docs.google.com/document/d/1CX9ysa5thq0vajXR2zapcMkfwTwV9VsW6xGXuxdN97M/edit?tab=t.0#heading=h.74kik1edg70t
> HBASE-28951 Handle simultaneous WAL splitting to recovered edits by multiple worker

- hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestBackupRestore.java
https://issues.apache.org/jira/browse/HBASE-29507
This pull request reduces the value for `DEFAULT_ROWS_IN_ITERATION` in IntegrationTestBackupRestore.java from 500,000 to 10,000.  The change prevents an OutOfMemoryError from occurring when running IntegrationTestBackupRestore locally. The error was discovered while testing the fix for PR #7203.  If we still want to use 500,000 rows for an actual integration test on a distributed cluster, then the row count can be overridden via the command line by using the `rows_in_iteration` arg (see `ROWS_PER_ITERATION_KEY` on [this line](https://github.com/apache/hbase/blob/master/hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestBackupRestore.java#L429-L431)).
> HBASE-29507: IntegrationTestBackupRestore is failing because it cannot restore from backup directory

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SnapshotProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestSnapshotProcedure.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/procedure/TestSnapshotProcedureForSnapshotType.java
Jira: [HBASE-29184](https://issues.apache.org/jira/browse/HBASE-29184)
master pr: https://github.com/apache/hbase/pull/6790
> HBASE-29184 The snapshot type for disabled table is incorrect when snapshot procedure is enabled (branch-2)

- hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestBackupRestore.java
https://issues.apache.org/jira/browse/HBASE-29544
This is a cherry-pick from PR #7243.
`IntegrationTestBackupRestore` runs the backup and restore processes in a separate thread (or threads).  PR #7203 ([HBASE-29503](https://issues.apache.org/jira/browse/HBASE-29503)) fixed an issue where the test would still pass even if an exception occurred in one of the threads.  However, that fix only handles exceptions.  It does not handle other throwables, such as `AssertionError`.  This pull request extends the functionality implemented in PR #7203 to handle all throwables instead of just exceptions.
I added a `RuntimeException` to `BackupAndRestoreThread.run()` to test exception handling:
```
public void run() {
try {
throw new RuntimeException("Do we see this?");
} catch (Throwable t) { …
```
> HBASE-29544: Assertion errors in BackupAndRestoreThread are not causing IntegrationTestBackupRestore to fail

- hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
This PR addresses the issue described in [HBASE-28881](https://issues.apache.org/jira/browse/HBASE-28881) Setting hbase.oldwals.cleaner.thread.size to a negative value can break HMaster and produce hard-to-diagnose logs.
Problem: When setting 'hbase.master.procedure.threads' to a negative value, the HMaster starts normally, but the clients cannot connect to the server. Additionally, there are no related error messages in the HMaster logs, making it difficult for users to diagnose the root cause of the issue.
Solution: Defining the default value of _numThreads_; Changing the declaration of _numThreads_ to local; Adding a value check: when _numThreads_ <= 0, it will be reset to the default value and outputs log info. 
We appreciate your review and feedback! 
Thanks @Apache9
> HBASE-28881: Adding check and diagnose log for "hbase.master.procedure.threads" when set to non-positive value

- hbase-server/src/main/java/org/apache/hadoop/hbase/replication/master/ReplicationLogCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/master/cleaner/TestLogsCleaner.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/replication/master/TestReplicationLogCleaner.java
Details see: HBASE-29376
Setting `hbase.master.cleaner.interval` to `10000ms`, and when stopping the HMaster service, we can observe the following logs.
```
2025-06-05T07:30:03,108 INFO  [RS:0;localhost:16020] regionserver.HRegionServer: Closing user regions
2025-06-05T07:30:08,773 WARN  [master/localhost:16000.Chore.1] master.ReplicationLogCleaner: Rpc client has been stopped.
2025-06-05T07:30:09,124 INFO  [RS:0;localhost:16020] regionserver.HRegionServer: ***** STOPPING region server 'localhost,16020,1749079746517' *****
```
> HBASE-29376 ReplicationLogCleaner.preClean/getDeletableFiles should return early when asyncClusterConnection closes during HMaster stopping

- hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
Jira: [HBASE-29621](https://issues.apache.org/jira/browse/HBASE-29621)
> HBASE-29621: Remove the leading whitespace in the active.cluster.suffix.id filename

- hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFile.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcCall.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/ServerCall.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/monitoring/ThreadLocalServerSideScanMetrics.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RSRpcServices.java
- hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/RegionScannerImpl.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestNamedQueueRecorder.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/namequeues/TestRpcLogDetails.java
- hbase-server/src/test/java/org/apache/hadoop/hbase/procedure2/store/region/TestRegionProcedureStore.java
JIRA: [HBASE-29626](https://issues.apache.org/jira/browse/HBASE-29626)
> HBASE-29626: Refactor server side scan metrics for Coproc hooks
